#!/usr/bin/env python3
"""
CFE BATCH 4
Q201-225: Casos Reais de Fraude Corporativa
Dominio: Financial Transactions & Fraud Schemes
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"No caso Enron, o principal esquema fraudulento consistiu em:","tag":"Caso Enron","options":["A. Desvio sistemático de recursos das operações de caixa","B. Uso de entidades fora do balanço e transações fictícias para ocultar dívidas","C. Apropriação indébita de estoques e ativos físicos","D. Manipulação de dados na folha de pagamento"],"correct":1,"justification_correct":"A Enron utilizou entidades de propósito específico (SPEs) e contabilidade enganosa para inflar lucros e manter bilhões em dívidas fora do balanço consolidado. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Desvio de caixa, estoque e folha de pagamento são categorias distintas; o esquema central da Enron foi a manipulação de demonstrações via entidades off-balance sheet."},
    {"num":2,"text":"Qual sinal de alerta era mais evidente nas demonstrações financeiras da Enron?","tag":"Red Flags Enron","options":["A. Controles internos robustos e bem documentados","B. Estruturas contábeis excessivamente complexas e pouco transparentes","C. Relatórios financeiros claros e de fácil compreensão","D. Uso limitado e conservador de instrumentos derivativos"],"correct":1,"justification_correct":"A complexidade deliberada das estruturas contábeis e a falta de transparência sobre as SPEs obscureciam a real posição financeira da Enron. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Controles robustos, transparência e uso conservador de derivativos seriam indicadores positivos, não red flags."},
    {"num":3,"text":"A fraude contábil da WorldCom foi perpetrada principalmente por meio de:","tag":"Caso WorldCom","options":["A. Esquemas de fraude na folha de pagamento","B. Capitalização indevida de despesas operacionais para inflar resultados","C. Pagamento de propinas a fornecedores estratégicos","D. Desvio físico de ativos de estoque"],"correct":1,"justification_correct":"A WorldCom capitalizou bilhões em despesas operacionais que deveriam ter sido reconhecidas no resultado, inflando artificialmente os lucros e os ativos reportados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Folha de pagamento, propinas e estoque são categorias distintas; a capitalização indevida foi o mecanismo central da fraude WorldCom."},
    {"num":4,"text":"Qual foi uma das principais consequências regulatórias do escândalo da WorldCom?","tag":"Impacto Regulatório","options":["A. Ausência de mudanças regulatórias significativas","B. Aprovação da Lei Sarbanes-Oxley, fortalecendo governança e auditoria","C. Aumento na ocorrência de desvios de ativos físicos","D. Redução do escrutínio sobre os trabalhos de auditoria externa"],"correct":1,"justification_correct":"O escândalo WorldCom, juntamente com o caso Enron, foi determinante para a aprovação da Lei Sarbanes-Oxley (SOX) em 2002, que estabeleceu padrões mais rigorosos de governança e auditoria. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O escândalo gerou endurecimento regulatório significativo, não ausência de mudanças ou relaxamento de controles."},
    {"num":5,"text":"Qual característica é comum nos principais casos de fraude corporativa documentados?","tag":"Padrões de Fraude","options":["A. Envolvimento restrito a colaboradores de nível operacional","B. Conluio entre gestores e anulação deliberada de controles","C. Detecção imediata pelos mecanismos de auditoria vigentes","D. Ausência de incentivos financeiros para os perpetradores"],"correct":1,"justification_correct":"Os grandes casos de fraude corporativa tipicamente envolvem conluio entre executivos e a supressão deliberada de controles internos que deveriam detectar as irregularidades. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Grandes fraudes raramente são restritas ao nível operacional, raramente são detectadas imediatamente e quase sempre envolvem incentivos financeiros."},
    {"num":6,"text":"No escândalo da Tyco International, os executivos envolvidos foram responsáveis por:","tag":"Caso Tyco","options":["A. Desvio de recebimentos antes do registro contábil (skimming)","B. Concessão de empréstimos não autorizados e uso indevido de recursos corporativos","C. Esquemas de fraude com fornecedores e terceiros","D. Manipulação de dados e pagamentos na folha de pagamento"],"correct":1,"justification_correct":"Os executivos da Tyco utilizaram recursos da empresa para despesas pessoais suntuosas e concederam empréstimos não autorizados a si próprios, ocultando tudo por meio de manipulação contábil. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas descrevem esquemas distintos; o caso Tyco foi marcado pelo uso indevido direto de recursos corporativos pelos próprios executivos."},
    {"num":7,"text":"Qual falha de controle interno foi determinante para a ocorrência da fraude na Tyco International?","tag":"Controles Tyco","options":["A. Comitê de auditoria independente e atuante","B. Governança corporativa deficiente e ausência de supervisão independente","C. Processos de auditoria interna eficazes e bem estruturados","D. Relatórios financeiros transparentes e acessíveis"],"correct":1,"justification_correct":"A ausência de supervisão independente efetiva pelo conselho e pelo comitê de auditoria permitiu que os executivos praticassem o uso indevido de recursos por anos sem detecção. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Comitê de auditoria atuante, auditoria interna eficaz e transparência são controles que teriam impedido ou detectado o esquema."},
    {"num":8,"text":"O esquema Ponzi operado por Bernie Madoff se baseou fundamentalmente em:","tag":"Caso Madoff","options":["A. Superestimação de estoques e ativos físicos","B. Divulgação de retornos de investimento fictícios para atrair novos investidores","C. Manipulação sistemática de dados na folha de pagamento","D. Pagamento de propinas para obtenção de contratos financeiros"],"correct":1,"justification_correct":"Madoff fabricou demonstrações de rentabilidade consistentemente positivas, utilizando recursos de novos investidores para pagar os retornos prometidos aos anteriores — estrutura clássica do esquema Ponzi. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Estoque, folha de pagamento e propinas são categorias distintas; o esquema de Madoff foi puramente baseado em retornos fictícios."},
    {"num":9,"text":"Qual sinal de alerta, se devidamente investigado, poderia ter exposto o esquema de Madoff mais cedo?","tag":"Red Flags Madoff","options":["A. Retornos extraordinariamente consistentes independentemente das condições de mercado","B. Alta rotatividade de funcionários na empresa","C. Complexidade excessiva nas estratégias de estoque","D. Existência de segregação de funções nos processos"],"correct":0,"justification_correct":"Retornos consistentemente positivos, mesmo em períodos de queda de mercado, são estatisticamente implausíveis e deveriam ter suscitado questionamentos aprofundados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Rotatividade de funcionários, complexidade de estoque e segregação de funções não são os principais red flags do esquema Madoff."},
    {"num":10,"text":"O caso Bernie Madoff evidencia, acima de tudo, que:","tag":"Lições Madoff","options":["A. Auditorias externas independentes são suficientes para prevenir fraudes dessa magnitude","B. A confiança baseada em reputação pode ser explorada na ausência de verificação independente","C. Fraudes de pequena escala causam impactos proporcionalmente maiores","D. O skimming é o mecanismo primário em esquemas de investimento fraudulentos"],"correct":1,"justification_correct":"A reputação de Madoff e sua posição de prestígio no mercado financeiro suprimiram o ceticismo dos investidores, permitindo que o esquema operasse por décadas sem verificação adequada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditorias externas falharam no caso Madoff; o esquema era de enorme escala; skimming não foi o mecanismo utilizado."},
    {"num":11,"text":"O escândalo da Satyam Computer Services envolveu a prática de:","tag":"Caso Satyam","options":["A. Esquemas de fraude na folha de pagamento com funcionários fictícios","B. Superestimação fictícia de saldos de caixa e receitas inexistentes","C. Desvio físico de estoques e ativos tecnológicos","D. Pagamento de subornos a fornecedores de serviços"],"correct":1,"justification_correct":"O fundador da Satyam fabricou saldos de caixa, receitas e lucros por anos, resultando em uma das maiores fraudes corporativas da história da Índia. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Folha de pagamento, estoque e subornos a fornecedores são categorias distintas; a Satyam falsificou ativos e receitas nas demonstrações financeiras."},
    {"num":12,"text":"Qual deficiência de controle interno foi fator crítico para a perpetuação da fraude na Satyam?","tag":"Controles Satyam","options":["A. Processos de auditoria externa rigorosos e independentes","B. Ausência de supervisão independente efetiva pelo comitê de auditoria","C. Relatórios financeiros transparentes e amplamente divulgados","D. Realização de conciliações bancárias frequentes e sistemáticas"],"correct":1,"justification_correct":"A supervisão insuficiente pelo comitê de auditoria e pelo conselho permitiu que a gestão manipulasse as demonstrações financeiras por anos sem detecção adequada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditoria externa rigorosa, transparência e conciliações frequentes são controles que teriam limitado ou detectado a fraude."},
    {"num":13,"text":"A fraude contábil da HealthSouth Corporation foi perpetrada principalmente por meio de:","tag":"Caso HealthSouth","options":["A. Desvios de caixa e furto de recebimentos","B. Superestimação sistemática de receitas e ativos para atender expectativas do mercado","C. Pagamento de propinas a fornecedores da área de saúde","D. Suborno de funcionários e agentes governamentais"],"correct":1,"justification_correct":"Os executivos da HealthSouth falsificaram resultados financeiros para cumprir as previsões de lucro de Wall Street, inflando receitas e ativos de forma sistemática. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Desvios de caixa, propinas e suborno a governo são categorias distintas do esquema central da HealthSouth."},
    {"num":14,"text":"Qual padrão nos resultados financeiros era um red flag evidente no caso da HealthSouth?","tag":"Red Flags HealthSouth","options":["A. Lucros consistentemente abaixo das expectativas do mercado","B. Progressão de resultados excessivamente regular e sem oscilações naturais","C. Alta rotatividade nos cargos de liderança","D. Existência de controles internos rigorosos e auditados"],"correct":1,"justification_correct":"A progressão inusualmnte regular dos lucros, sem as oscilações naturais esperadas em qualquer negócio, deveria ter sinalizado a manipulação dos resultados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Lucros abaixo do esperado, rotatividade de liderança e controles rigorosos não são os principais sinais de alerta do caso HealthSouth."},
    {"num":15,"text":"Qual método de detecção foi determinante para expor a fraude na HealthSouth?","tag":"Detecção HealthSouth","options":["A. Denúncias de investidores externos insatisfeitos","B. Denunciantes internos combinados com revisões forenses de auditoria","C. Inspeções físicas de instalações e equipamentos","D. Revisão de registros regulatórios públicos"],"correct":1,"justification_correct":"Denúncias de colaboradores internos desencadearam investigações forenses que revelaram a extensão da manipulação dos resultados na HealthSouth. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Investidores externos, inspeções físicas e registros regulatórios foram canais menos determinantes na detecção da fraude HealthSouth."},
    {"num":16,"text":"A fraude praticada pela Olympus Corporation consistiu em:","tag":"Caso Olympus","options":["A. Desvio sistemático de itens de estoque e componentes ópticos","B. Ocultação de perdas de investimentos por meio de aquisições irregulares superfaturadas","C. Manipulação de dados na folha de pagamento de executivos","D. Pagamento de propinas a fornecedores e distribuidores"],"correct":1,"justification_correct":"A Olympus ocultou perdas bilionárias de investimentos em derivativos realizando aquisições superfaturadas, onde os valores excedentes serviam para absorver as perdas ocultas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Estoque, folha de pagamento e propinas a fornecedores são categorias distintas; o esquema da Olympus foi de ocultação de perdas via aquisições."},
    {"num":17,"text":"Qual fator principal permitiu que a fraude na Olympus Corporation se perpetuasse por mais de uma década?","tag":"Perpetuação Olympus","options":["A. Existência de controles internos rigorosos e bem aplicados","B. Conluio entre executivos seniores para suprimir a descoberta","C. Transparência nos relatórios financeiros divulgados","D. Realização de auditorias internas e externas frequentes"],"correct":1,"justification_correct":"O conluio entre executivos de alto escalão foi determinante para suprimir as investigações internas e atrasar a detecção do esquema por mais de dez anos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Controles rigorosos, transparência e auditorias frequentes teriam impedido ou detectado o esquema da Olympus."},
    {"num":18,"text":"A Toshiba Corporation foi responsável por falsificar:","tag":"Caso Toshiba","options":["A. Saldos de disponibilidades e caixa restrito","B. Resultados financeiros ao longo de múltiplos exercícios consecutivos","C. Dados e valores registrados na folha de pagamento","D. Registros de estoque e volumes de produção"],"correct":1,"justification_correct":"A Toshiba inflou seus lucros por mais de seis anos mediante a subestimação sistemática de custos e a superestimação de receitas em múltiplas divisões. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Caixa, folha de pagamento e estoque foram alvos periféricos; a falsificação dos resultados consolidados foi o esquema central da Toshiba."},
    {"num":19,"text":"Qual deficiência de governança foi fator determinante para a fraude da Toshiba?","tag":"Governança Toshiba","options":["A. Existência de supervisão independente efetiva do conselho","B. Ausência de governança corporativa eficaz e cultura de pressão por resultados","C. Comitê de auditoria estruturado e independente","D. Políticas contábeis transparentes e conservadoras"],"correct":1,"justification_correct":"A cultura de pressão por resultados aliada à governança ineficaz criou o ambiente propício para que gestores manipulassem os números sem supervisão adequada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Supervisão independente, comitê de auditoria estruturado e políticas conservadoras são controles que teriam prevenido a fraude."},
    {"num":20,"text":"O escândalo de corrupção da Siemens AG envolveu principalmente:","tag":"Caso Siemens","options":["A. Esquemas de fraude na folha de pagamento em múltiplos países","B. Pagamento sistemático de subornos para obtenção de contratos governamentais internacionais","C. Desvio de estoques e componentes industriais","D. Declaração incorreta de receitas em demonstrações consolidadas"],"correct":1,"justification_correct":"A Siemens operou um sistema global de pagamento de subornos a funcionários públicos de diversos países para garantir contratos, resultando em multas bilionárias nos EUA e na Alemanha. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Folha de pagamento, estoque e demonstrações financeiras foram impactados perifericamente; o núcleo do escândalo foi o esquema de suborno para contratos."},
    {"num":21,"text":"Qual controle teria sido mais eficaz para prevenir o escândalo de corrupção da Siemens?","tag":"Prevenção Siemens","options":["A. Políticas anticorrupção robustas com monitoramento efetivo","B. Auditorias periódicas de folha de pagamento","C. Conciliações bancárias mais frequentes","D. Segregação de funções nos processos de gestão de estoque"],"correct":0,"justification_correct":"Políticas anticorrupção claras combinadas com monitoramento de pagamentos e due diligence de terceiros são os controles mais eficazes contra esquemas de suborno internacionais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditorias de folha, conciliações e segregação de funções de estoque são controles relevantes para outros tipos de fraude, não para o esquema de suborno da Siemens."},
    {"num":22,"text":"No escândalo do Wells Fargo, o esquema fraudulento consistiu em:","tag":"Caso Wells Fargo","options":["A. Desvio de recebimentos antes do registro contábil","B. Abertura não autorizada de contas em nome de clientes sem seu consentimento","C. Criação de esquemas de investimento fictícios","D. Declaração incorreta de estoques e ativos financeiros"],"correct":1,"justification_correct":"Funcionários do Wells Fargo abriram milhões de contas bancárias e de crédito não autorizadas em nome de clientes existentes para cumprir metas agressivas de vendas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Skimming, investimentos fictícios e declaração de estoque são esquemas distintos; o Wells Fargo foi um caso de fraude vinculada a incentivos de desempenho."},
    {"num":23,"text":"Qual sinal de alerta era mais evidente nas operações do Wells Fargo?","tag":"Red Flags Wells Fargo","options":["A. Conformidade consistente com regulações do setor financeiro","B. Volume de abertura de contas por funcionário excepcionalmente acima da média","C. Programas de incentivo de vendas transparentes e equilibrados","D. Resposta eficaz e ágil a reclamações de denunciantes"],"correct":1,"justification_correct":"A abertura de contas por funcionário muito acima da média de mercado deveria ter sinalizado práticas irregulares motivadas por metas de desempenho não sustentáveis. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Conformidade, incentivos transparentes e resposta eficaz a denunciantes seriam indicadores positivos de integridade, não red flags."},
    {"num":24,"text":"A detecção precoce da fraude no Wells Fargo poderia ter sido aprimorada principalmente por meio de:","tag":"Detecção Wells Fargo","options":["A. Auditorias internas e monitoramento contínuo das práticas de vendas","B. Eliminação completa de todos os programas de incentivo de desempenho","C. Desconsideração de reclamações de menor relevância","D. Inspeções físicas das agências e instalações"],"correct":0,"justification_correct":"Auditorias internas sistemáticas e monitoramento analítico das métricas de vendas por colaborador teriam identificado os padrões atípicos de abertura de contas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Eliminar incentivos, ignorar reclamações e inspeções físicas são respostas inadequadas ou insuficientes para detectar esse tipo de fraude."},
    {"num":25,"text":"A principal lição comum extraída dos grandes casos de fraude corporativa é que:","tag":"Lições Aprendidas","options":["A. Apenas organizações de pequeno porte são vulneráveis a esquemas fraudulentos","B. Prevenção proativa, detecção eficaz e governança robusta são essenciais em qualquer organização","C. Fraudes corporativas de grande escala são impossíveis de detectar","D. Auditores externos independentes são suficientes para prevenir qualquer esquema"],"correct":1,"justification_correct":"Os casos Enron, WorldCom, Madoff e outros demonstram que controles internos abrangentes, cultura ética, supervisão independente e detecção proativa são indispensáveis em organizações de qualquer porte. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Grandes organizações são igualmente vulneráveis; fraudes podem ser detectadas; auditores externos isoladamente não são suficientes."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/cfe/financial_transactions")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "cfe",
    "domain_id": "financial_transactions",
    "quiz_num": num1,
    "domain_name": "Financial Transactions & Fraud Schemes",
    "cert_name": "CFE / ACFE",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (Casos Reais) salvas em {path1}")
