#!/usr/bin/env python3
"""
ISO 27001 LEAD IMPLEMENTER - BATCH 1
30 questoes de nivel senior
Dominio: planning_implementation (clausulas, controles, auditorias)
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"O gestor do SGSI identifica que as políticas são adequadas, mas os colaboradores são inconsistentes na adesão aos requisitos. Qual é a medida mais eficaz para resolver esse problema?","tag":"Conscientização e Treinamento","options":["A. Revisar as políticas para simplificar os requisitos de conformidade","B. Realizar sessões de treinamento direcionadas para melhorar a compreensão e adesão","C. Aumentar a frequência das auditorias para detectar não conformidades","D. Introduzir medidas disciplinares mais rigorosas para garantir a conformidade"],"correct":1,"justification_correct":"Quando as políticas são adequadas e o problema é comportamental, a causa raiz é falta de competência ou conscientização. O treinamento direcionado ataca a causa raiz, transformando a cultura passiva em cultura de segurança ativa — alinhado à Cláusula 7.3 (Conscientização) da ISO 27001. (ISO/IEC 27001:2022)","justification_wrong":"Revisar políticas adequadas é desnecessário; aumentar auditorias é reativo; medidas disciplinares isoladas não resolvem a causa raiz do problema comportamental."},
    {"num":2,"text":"Uma empresa de e-commerce usando IaaS identifica que misconfigurations em servidores virtuais podem causar violações de dados. Qual é a forma MAIS eficaz de gerenciar esse risco em conformidade com a ISO/IEC 27001?","tag":"Gestão de Configuração","options":["A. Monitorar e auditar regularmente a infraestrutura do provedor de IaaS em busca de falhas","B. Implementar política de gestão de configuração e realizar análises internas regulares das configurações","C. Confiar nas ferramentas automatizadas do provedor para detectar e corrigir falhas","D. Utilizar abordagem híbrida combinando IaaS com servidores locais para reduzir o risco"],"correct":1,"justification_correct":"A ISO 27001 exige controles documentados e verificáveis. A política de gestão de configuração estabelece o padrão de hardening, e as análises internas verificam a conformidade operacional — demonstrando que a organização assumiu a propriedade do risco. (ISO/IEC 27001:2022, Controle A.8.9)","justification_wrong":"Monitorar apenas o provedor é insuficiente; ferramentas automatizadas sem política interna não demonstram conformidade; abordagem híbrida não resolve o problema de configuração."},
    {"num":3,"text":"Durante a implementação do SGSI, a organização enfrenta dificuldades para garantir que novos colaboradores compreendam as políticas de segurança. Qual abordagem é mais eficaz para transferir o conhecimento organizacional?","tag":"Integração de Novos Colaboradores","options":["A. Distribuir manual completo sobre políticas de segurança durante o onboarding","B. Desenvolver programa de integração estruturado com treinamento prático, mentoria e repositório centralizado","C. Exigir que novos funcionários participem de um workshop de conscientização de um dia","D. Fornecer acesso ao registro de riscos para familiarizar com riscos e controles identificados"],"correct":1,"justification_correct":"A eficácia (Cláusula 9.1) é medida pelo resultado. A opção B aborda conhecimento tácito via mentoria e prático, além de garantir repositório centralizado conforme Cláusula 7.5 (Informação Documentada), retendo capital intelectual. (ISO/IEC 27001:2022)","justification_wrong":"Manual sem prática não garante compreensão; workshop único é insuficiente; acesso ao registro de riscos é complementar, não substituto do programa de integração."},
    {"num":4,"text":"O CISO de uma plataforma de e-commerce expressa preocupação sobre a proteção de um ambiente de Big Data dinâmico com múltiplos formatos. Qual característica do Big Data deve ser priorizada para alinhar com a ISO/IEC 27001?","tag":"Big Data e Segurança","options":["A. Focar na variedade de formatos para garantir proteção uniforme de todos os tipos","B. Abordar o volume de dados para garantir capacidade de armazenamento e backups suficientes","C. Priorizar a velocidade de geração para garantir monitoramento em tempo real e detecção rápida de ameaças","D. Concentrar-se em um único formato de dados para simplificar a gestão de segurança"],"correct":2,"justification_correct":"A velocidade alinha-se ao controle A.8.16 (Monitoramento de Eventos) da ISO/IEC 27002:2022 e à base para gestão de incidentes (Cláusula 10.1 e controles A.5.24-A.5.28). Disponibilidade e integridade dependem de detecção e resposta oportunas. (ISO/IEC 27001:2022)","justification_wrong":"Variedade e volume são importantes mas secundários; focar em um único formato compromete a abrangência exigida pelo SGSI."},
    {"num":5,"text":"Durante a fase de planejamento do SGSI, objetivos de segurança mal definidos e não alinhados com os negócios são identificados. Qual é o método mais eficaz para estabelecer objetivos significativos?","tag":"Objetivos de Segurança","options":["A. Revisar missão e visão organizacional e definir objetivos conforme essas declarações","B. Usar resultados da avaliação de riscos para formular objetivos diretamente ligados aos riscos","C. Consultar a alta direção para identificar objetivos de negócio e alinhar objetivos de segurança para apoiá-los","D. Comparar objetivos com os de organizações do mesmo setor para estabelecer metas realistas"],"correct":2,"justification_correct":"Consultar a alta direção (Cláusula 5.1 — Liderança e Comprometimento) garante alinhamento dos objetivos de segurança com os objetivos estratégicos do negócio, fornecendo direção e apoio necessários. (ISO/IEC 27001:2022, Cláusula 6.2)","justification_wrong":"Missão e visão são abstratas demais; riscos isolados podem ignorar o contexto estratégico; benchmarking setorial não considera as necessidades específicas da organização."},
    {"num":6,"text":"Uma empresa de tecnologia implementando ISO/IEC 27001 precisa garantir que documentos confidenciais de projeto permaneçam não divulgados. Qual controle é mais eficaz?","tag":"Controles de Confidencialidade","options":["A. Implementar criptografia para todos os documentos durante armazenamento e transmissão","B. Exigir que funcionários assinem NDAs antes de acessar os documentos","C. Realizar auditorias internas regulares para verificar a segurança dos documentos","D. Restringir o acesso aos documentos aos funcionários que trabalham no projeto específico"],"correct":0,"justification_correct":"A criptografia garante tecnicamente a confidencialidade durante armazenamento e transmissão, impedindo divulgação não autorizada mesmo em caso de acesso indevido ao meio. Alinha-se ao controle A.8.24 (Uso de criptografia) da ISO/IEC 27002:2022. (ISO/IEC 27001:2022)","justification_wrong":"NDAs criam obrigações legais mas não proteção técnica; auditorias identificam problemas mas não protegem; restrição de acesso não protege durante transmissão."},
    {"num":7,"text":"Um prestador de serviços de saúde precisa proteger EHRs contra alteração ou exclusão por indivíduos não autorizados. Qual controle é mais apropriado?","tag":"Integridade de Dados","options":["A. Configurar controles de acesso baseados em função (RBAC) para restringir privilégios de modificação","B. Realizar treinamentos semestrais de conscientização para funcionários que lidam com EHRs","C. Criptografar os EHRs usando AES-256 para garantir confidencialidade","D. Implementar plano de recuperação de desastres para restaurar EHRs em caso de perda"],"correct":0,"justification_correct":"O RBAC garante que apenas indivíduos com funções autorizadas possam modificar ou excluir EHRs, protegendo a integridade. Alinha-se ao controle A.5.15 (Controle de acesso) da ISO/IEC 27002:2022. (ISO/IEC 27001:2022)","justification_wrong":"Treinamento reduz erros humanos mas não impõe restrições técnicas; criptografia protege confidencialidade, não integridade; DRP trata perda de dados, não alterações não autorizadas."},
    {"num":8,"text":"Uma organização multinacional identificou não conformidades em auditoria interna. Qual ação melhor demonstra conformidade com a ISO/IEC 27001 no acompanhamento e resolução de não conformidades?","tag":"Ações Corretivas","options":["A. Realizar análise de causa raiz para cada não conformidade e atualizar o relatório de auditoria","B. Designar responsável pela ação corretiva e garantir que a data de conclusão seja registrada","C. Escalar todas as não conformidades para a equipe de gestão para resolução imediata","D. Priorizar não conformidades por gravidade e documentar as ações corretivas tomadas"],"correct":1,"justification_correct":"A ISO/IEC 27001 (Cláusula 10.1) exige designação de responsabilidade e registro de datas de conclusão das ações corretivas, promovendo responsabilização e resolução oportuna. A combinação de responsável + prazo é o requisito estrutural da norma. (ISO/IEC 27001:2022)","justification_wrong":"Análise de causa raiz é necessária mas insuficiente sozinha; escalar tudo à gestão é impraticável; priorização sem acompanhamento não atende aos requisitos da cláusula 10.1."},
    {"num":9,"text":"Durante auditoria de Estágio 1, o auditor levanta preocupações sobre o escopo documentado do SGSI. O que esse cenário ilustra sobre a diferença entre auditorias de Estágio 1 e Estágio 2?","tag":"Auditorias de Certificação","options":["A. Estágio 1 valida eficácia operacional; Estágio 2 avalia o escopo do SGSI","B. Estágio 1 garante que o escopo esteja claramente definido; Estágio 2 avalia sua implementação dentro do escopo","C. Estágio 1 verifica alinhamento com requisitos legais; Estágio 2 verifica completude da documentação","D. Estágio 1 identifica problemas na documentação; Estágio 2 trata lacunas documentais não resolvidas"],"correct":1,"justification_correct":"A auditoria de Estágio 1 foca na adequação do escopo e da documentação do SGSI, enquanto o Estágio 2 avalia a implementação e eficácia operacional dentro do escopo definido. (PECB ISO/IEC 27001 Lead Auditor Guide)","justification_wrong":"A eficácia operacional é foco do Estágio 2; o Estágio 1 não se limita a requisitos legais; o Estágio 2 não trata especificamente lacunas documentais não resolvidas."},
    {"num":10,"text":"Uma empresa de manufatura prepara seus procedimentos de segurança. A equipe sugere um único procedimento abrangente cobrindo todos os requisitos. Qual é a forma mais eficaz de estruturar os procedimentos?","tag":"Documentação do SGSI","options":["A. Desenvolver procedimento único integrando todos os controles técnicos e administrativos","B. Criar conjunto de procedimentos adaptados a processos específicos e alinhados aos fluxos operacionais","C. Confiar nos procedimentos existentes adicionando anexo com referência aos controles ISO","D. Concentrar-se apenas em procedimentos para áreas de alto risco identificadas na avaliação"],"correct":1,"justification_correct":"Procedimentos adaptados a processos específicos garantem praticidade, alinhamento aos fluxos de trabalho e facilidade de uso — suportando a integração da segurança nos processos de negócio conforme Cláusula 7.5 da ISO 27001. (ISO/IEC 27001:2022)","justification_wrong":"Procedimento único torna-se excessivamente complexo; referências sem implementação não garantem conformidade; focar apenas em alto risco cria lacunas significativas no SGSI."},
    {"num":11,"text":"Uma organização terceirizou operações para um provedor externo. Qual é a melhor abordagem para garantir que funcionários do provedor sejam treinados nos requisitos de segurança?","tag":"Gestão de Terceiros","options":["A. Exigir que o provedor implemente seu próprio programa de treinamento e forneça evidências","B. Incluir funcionários do provedor nas sessões de treinamento e conscientização da organização","C. Fornecer ao provedor acesso aos materiais de treinamento para aplicação independente","D. Auditar o provedor periodicamente para garantir que funcionários sejam treinados"],"correct":1,"justification_correct":"Incluir funcionários do provedor nas sessões da organização garante consistência no entendimento e adesão aos requisitos específicos, alinhado à Cláusula 7.2 (Competência) e controle A.5.20 (Endereçando segurança em acordos com fornecedores). (ISO/IEC 27001:2022)","justification_wrong":"Deixar a responsabilidade ao provedor pode gerar desalinhamento; fornecer materiais sem acompanhamento é inconsistente; auditar verifica mas não implementa o treinamento."},
    {"num":12,"text":"Um gerente de projeto finaliza o Plano de Tratamento de Riscos. Qual ação garante conformidade com a ISO/IEC 27001 e praticidade de implementação?","tag":"Tratamento de Riscos","options":["A. Incluir apenas controles técnicos para garantir implementação com boa relação custo-benefício","B. Priorizar controles que tratem riscos de alta probabilidade conforme avaliação de riscos","C. Garantir que o plano inclua justificativa para seleção ou rejeição de cada opção de controle","D. Limitar o plano aos controles especificados no Anexo A da ISO/IEC 27001"],"correct":2,"justification_correct":"A ISO/IEC 27001 (Cláusula 6.1.3) exige justificativa documentada para a seleção ou exclusão de controles, garantindo que as decisões sejam rastreáveis e alinhadas ao perfil de risco da organização. (ISO/IEC 27001:2022)","justification_wrong":"Limitar a controles técnicos ignora controles administrativos e físicos; probabilidade isolada desconsidera impacto e apetite ao risco; o Anexo A não é exaustivo nem prescritivo."},
    {"num":13,"text":"Ações corretivas de auditorias anteriores não estão sendo encerradas nos prazos. Em que a organização deve se concentrar ao desenvolver um plano de ação corretiva?","tag":"Atrasos em Ações Corretivas","options":["A. Estabelecer ferramenta dedicada de acompanhamento para monitorar o progresso de todas as ações","B. Conduzir avaliação de riscos para determinar o impacto dos atrasos nas ações corretivas","C. Investigar e tratar os motivos dos atrasos na implementação das ações corretivas","D. Aumentar a frequência das reuniões de análise crítica para garantir priorização"],"correct":2,"justification_correct":"Investigar as causas dos atrasos — restrições de recursos, falta de responsabilização, ineficiências — ataca a causa raiz do problema, alinhado à Cláusula 10.1 da ISO 27001 sobre análise de causa raiz para não conformidades. (ISO/IEC 27001:2022)","justification_wrong":"Ferramentas de acompanhamento melhoram monitoramento mas não tratam a causa; avaliação de riscos entende o impacto mas não resolve; reuniões mais frequentes melhoram supervisão mas não as causas subjacentes."},
    {"num":14,"text":"O cenário regulatório muda frequentemente, afetando as obrigações de conformidade do SGSI. Qual ação deve ser priorizada para garantir monitoramento contínuo?","tag":"Monitoramento Regulatório","options":["A. Agendar auditorias de conformidade periódicas para identificar lacunas causadas por mudanças","B. Designar oficial de conformidade dedicado para monitorar atualizações regulatórias e suas implicações","C. Desenvolver processo para revisar mudanças regulatórias anualmente e implementar atualizações","D. Usar ferramenta automatizada para rastrear mudanças e notificar partes interessadas imediatamente"],"correct":1,"justification_correct":"Um oficial de conformidade dedicado garante mecanismo contínuo de monitoramento e interpretação das mudanças regulatórias, alinhado à Cláusula 4.2 (Partes interessadas) e 6.1 (Ações para tratar riscos). (ISO/IEC 27001:2022)","justification_wrong":"Auditorias periódicas são reativas; revisão anual é insuficiente para mudanças frequentes; ferramentas automatizadas exigem interpretação humana que o oficial de conformidade provê."},
    {"num":15,"text":"Em auditoria de acompanhamento, o plano de ação para não conformidade maior não especifica como o progresso será monitorado. Como o auditor deve tratar essa lacuna?","tag":"Planos de Ação Corretiva","options":["A. Aceitar o plano como suficiente, pois aborda os elementos-chave exigidos","B. Exigir que a organização inclua mecanismos de monitoramento para rastrear progresso e garantir responsabilização","C. Recomendar monitoramento informal durante reuniões regulares de gestão","D. Adiar avaliação dos mecanismos de monitoramento até a próxima auditoria de supervisão"],"correct":1,"justification_correct":"A ISO/IEC 27001 exige mecanismos de monitoramento documentados para rastrear o progresso das ações corretivas, garantindo responsabilização e conclusão tempestiva — sem esses mecanismos, a supervisão eficaz não pode ser demonstrada. (ISO/IEC 27001:2022, Cláusula 10.1)","justification_wrong":"Plano sem monitoramento está incompleto; monitoramento informal carece de estrutura e documentação; adiar compromete a eficácia do SGSI."},
    {"num":16,"text":"A alta direção exige informações regulares sobre o alinhamento do SGSI com os objetivos estratégicos. Qual ferramenta melhor apoia a melhoria contínua garantindo esse alinhamento?","tag":"Métricas do SGSI","options":["A. Software de planejamento estratégico para integrar objetivos do SGSI às metas organizacionais","B. Ferramenta de acompanhamento de KPIs para medir os resultados do SGSI","C. Sistema ERP para conectar dados do SGSI aos fluxos de trabalho operacionais","D. Mapa de calor de riscos para priorizar e visualizar áreas de alto risco"],"correct":1,"justification_correct":"Uma ferramenta de KPIs mede os resultados do SGSI em relação a objetivos predefinidos, garantindo alinhamento estratégico e suportando a melhoria contínua conforme Cláusula 9.1 (Monitoramento, medição, análise e avaliação). (ISO/IEC 27001:2022)","justification_wrong":"Software de planejamento é alto nível sem métricas contínuas; ERP conecta fluxos operacionais mas não mede desempenho do SGSI; mapa de calor visualiza riscos mas não monitora alinhamento estratégico."},
    {"num":17,"text":"O projeto de implementação do SGSI está atrasado na fase de gap analysis. Qual ação demonstra melhor aplicação de princípios de gerenciamento de projetos?","tag":"Gestão do Projeto SGSI","options":["A. Estender o cronograma do projeto para permitir mais tempo para a análise de lacunas","B. Alocar recursos adicionais e realocar membros da equipe conforme necessário","C. Reduzir o escopo da análise de lacunas para focar apenas em áreas críticas de conformidade","D. Pular a fase de análise de lacunas e prosseguir diretamente para a avaliação de riscos"],"correct":1,"justification_correct":"A alocação de recursos adicionais e realocação demonstra aplicação proativa de princípios de gerenciamento — otimização de recursos e gestão de cronograma — garantindo qualidade sem comprometer o projeto. (ISO/IEC 27001:2022, Cláusula 7.1)","justification_wrong":"Estender cronograma atrasa o projeto todo; reduzir escopo gera entendimento incompleto do estado atual; pular a gap analysis elimina etapa crítica para planejamento eficaz."},
    {"num":18,"text":"Em auditoria interna, descobre-se que permissões de usuário para dados financeiros não foram revisadas por mais de um ano, com acesso desnecessário concedido. Qual controle do Anexo A foi negligenciado?","tag":"Controles de Acesso","options":["A. A.9.2.5 - Análise crítica dos direitos de acesso de usuário","B. A.10.1.1 - Política para o uso de controles criptográficos","C. A.12.6.2 - Restrições quanto à instalação de software","D. A.18.1.4 - Privacidade e proteção de informações de identificação pessoal"],"correct":0,"justification_correct":"O controle A.9.2.5 (na ISO 27001:2013) ou equivalente na versão 2022 enfatiza a revisão periódica dos direitos de acesso para garantir que o acesso seja baseado nas necessidades atuais do negócio, alinhado ao princípio do menor privilégio. (ISO/IEC 27001:2022)","justification_wrong":"A.10.1.1 refere-se a criptografia; A.12.6.2 a restrições de software; A.18.1.4 a privacidade de dados pessoais — nenhum relacionado à revisão de direitos de acesso."},
    {"num":19,"text":"Na seleção de organismo de certificação, um tem ampla experiência setorial mas fraca presença regional. Como o Lead Implementer deve aconselhar a organização?","tag":"Seleção do Organismo de Certificação","options":["A. Recomendar o organismo com especialização regional para melhor eficiência da auditoria","B. Priorizar o organismo com especialização setorial, mesmo sem presença regional","C. Selecionar o organismo com menor custo para otimizar o orçamento","D. Sugerir comparação detalhada da metodologia de auditoria e dos recursos entre as opções"],"correct":3,"justification_correct":"Uma comparação minuciosa de metodologia e recursos determina qual organismo está mais bem equipado para as necessidades específicas, equilibrando especialização setorial e considerações práticas. (PECB Certification Body Selection Guide)","justification_wrong":"Presença regional é secundária à especialização; priorizar apenas especialização ignora desafios logísticos; custo não deve comprometer qualidade da certificação."},
    {"num":20,"text":"A direção expressa preocupação de que relatórios de auditoria interna não fornecem insights acionáveis suficientes. Qual é a forma mais eficaz de aumentar o valor dos futuros relatórios?","tag":"Relatórios de Auditoria","options":["A. Incluir recomendações detalhadas para tratar não conformidades e oportunidades de melhoria","B. Adicionar resumos de melhores práticas do setor para comparação com o SGSI","C. Aumentar a frequência das auditorias para fornecer mais dados para análise","D. Usar ferramentas avançadas de análise de dados para identificar tendências nas constatações"],"correct":0,"justification_correct":"Recomendações detalhadas e acionáveis transformam constatações de auditoria em melhorias concretas, alinhando-se ao foco da ISO 27001 na melhoria contínua e comunicação eficaz (Cláusula 9.2 e 10.2). (ISO/IEC 27001:2022)","justification_wrong":"Melhores práticas fornecem contexto mas não atendem necessidades específicas; mais auditorias sem qualidade melhora quantidade, não relevância; análise de dados melhora insights mas não atende à necessidade imediata de recomendações."},
    {"num":21,"text":"Uma instituição financeira precisa restringir acesso a dados de clientes apenas ao pessoal autorizado. Qual controle do Anexo A melhor atende esse requisito?","tag":"Controle de Acesso","options":["A. Implementar segmentação de rede para isolar dados de clientes de outros sistemas","B. Atribuir IDs de usuário exclusivos a todo pessoal que acessa os dados","C. Conduzir auditorias trimestrais das permissões de acesso aos dados","D. Usar autenticação multifator (MFA) para acessar sistemas de dados de clientes"],"correct":1,"justification_correct":"IDs de usuário exclusivos garantem responsabilização e rastreabilidade conforme controle A.5.16 (Gestão de identidades) da ISO/IEC 27002:2022, assegurando que cada acesso seja atribuído a um indivíduo específico. (ISO/IEC 27001:2022)","justification_wrong":"Segmentação de rede isola sistemas mas não controla acesso por usuário; auditorias são periódicas e não aplicam controle em tempo real; MFA fortalece autenticação mas não garante responsabilização individual sem IDs exclusivos."},
    {"num":22,"text":"Em análise de prontidão para auditoria de certificação, funcionários não conseguem localizar documentação do SGSI relevante para suas funções. O que o Lead Implementer deve fazer?","tag":"Prontidão para Auditoria","options":["A. Garantir armazenamento centralizado e fornecer credenciais de acesso aos funcionários","B. Desenvolver guia de referência rápida resumindo principais documentos e distribuir aos funcionários","C. Conduzir sessão de treinamento para familiarizar funcionários com a estrutura e recuperação da documentação","D. Atribuir aos líderes de equipe a tarefa de lidar com recuperação documental durante a auditoria"],"correct":2,"justification_correct":"O treinamento garante que funcionários possam acessar e usar a documentação eficazmente durante a auditoria, demonstrando engajamento real com o SGSI. Isso atende à Cláusula 7.3 (Conscientização) e ao requisito de prontidão operacional. (ISO/IEC 27001:2022)","justification_wrong":"Armazenamento centralizado resolve acesso mas não a lacuna de conhecimento; guia resumido é insuficiente; centralizar em líderes levanta preocupações do auditor sobre conscientização do pessoal."},
    {"num":23,"text":"Auditoria identifica inconsistências na comunicação de mensagens de segurança entre departamentos. Qual é a forma MAIS eficaz de implementar um plano de comunicação unificado?","tag":"Comunicação da Segurança","options":["A. Desenvolver estratégia de comunicação centralizada com modelos padronizados para todos os departamentos","B. Permitir que cada departamento adapte métodos de comunicação às suas necessidades específicas","C. Focar esforços de comunicação nos departamentos de alto risco como alvos prioritários","D. Introduzir newsletters trimestrais para atualizar todos os funcionários sobre segurança"],"correct":0,"justification_correct":"Uma estratégia centralizada com modelos padronizados garante mensagens consistentes e claras em toda a organização, tratando as inconsistências identificadas e atendendo aos requisitos de comunicação da Cláusula 7.4 da ISO 27001. (ISO/IEC 27001:2022)","justification_wrong":"Adaptação departamental introduz mais inconsistências; focar em alto risco ignora conscientização organizacional ampla; newsletters trimestrais isoladas são insuficientes para garantir consistência."},
    {"num":24,"text":"Na análise do contexto externo do SGSI, qual aspecto deve ser incluído para definição abrangente?","tag":"Contexto da Organização","options":["A. Políticas e procedimentos internos da organização para segurança da informação","B. Requisitos legais e regulamentares aplicáveis, relacionamentos da cadeia de suprimentos e condições de mercado","C. Papéis e responsabilidades dos funcionários na manutenção da segurança","D. Níveis de classificação de segurança usados internamente para informações sensíveis"],"correct":1,"justification_correct":"A Cláusula 4.1 da ISO 27001 especifica que o contexto externo inclui fatores legais, regulamentares, cadeia de suprimentos e condições de mercado que influenciam o SGSI. (ISO/IEC 27001:2022)","justification_wrong":"Políticas internas, papéis de funcionários e classificações de segurança são elementos do contexto interno, não externo."},
    {"num":25,"text":"Uma instituição financeira usa sistema de IA forte para detecção de fraudes, tomando decisões sem intervenção humana. A equipe de conformidade levanta preocupações sobre falta de transparência. Como a organização deve abordar isso?","tag":"IA e Conformidade","options":["A. Continuar usando o sistema sem alterações, pois suas decisões são precisas e eficientes","B. Implementar processo para documentar e validar decisões do sistema de IA para garantir responsabilização","C. Substituir o sistema por IA fraca que forneça apenas recomendações para revisão humana","D. Limitar o sistema a decisões de baixo risco para evitar problemas de conformidade"],"correct":1,"justification_correct":"A ISO 27001 enfatiza responsabilização e rastreabilidade nos processos. Documentar e validar decisões da IA garante transparência e alinhamento com requisitos de conformidade (Cláusula 9.1 — Monitoramento e medição). (ISO/IEC 27001:2022)","justification_wrong":"Continuar sem transparência viola requisitos de conformidade; substituir por IA fraca sacrifica capacidades avançadas sem necessidade; limitar a baixo risco não resolve o problema de responsabilização."},
    {"num":26,"text":"Departamentos não cooperam com auditores citando restrições de tempo e recursos, resultando em constatações incompletas. Qual é a etapa mais eficaz para o gestor do SGSI?","tag":"Cooperação com Auditoria","options":["A. Escalar o problema para a alta direção para que exija cooperação dos departamentos","B. Reagendar auditorias para acomodar a disponibilidade dos recursos departamentais","C. Desenvolver plano de comunicação explicando a importância das auditorias e tratando das preocupações","D. Reduzir o escopo das auditorias para focar em controles que exijam menos recursos"],"correct":2,"justification_correct":"Um plano de comunicação fomenta a cooperação ao esclarecer o valor e a necessidade das auditorias, oferecendo oportunidade para resolver colaborativamente os problemas de recursos — alinhado à Cláusula 7.4 (Comunicação) da ISO 27001. (ISO/IEC 27001:2022)","justification_wrong":"Escalar força conformidade sem tratar as causas; reagendar pode causar mais atrasos; reduzir escopo compromete a eficácia do programa de auditoria."},
    {"num":27,"text":"Uma empresa de tecnologia precisa comunicar regularmente métricas de desempenho do SGSI para a alta direção. Qual método é mais apropriado?","tag":"Comunicação com a Direção","options":["A. Incluir relatório detalhado de desempenho nas reuniões trimestrais do conselho para análise e discussão","B. Enviar atualizações mensais por e-mail com principais métricas e resoluções de incidentes","C. Estabelecer painel em tempo real com métricas de desempenho acessível à alta direção","D. Agendar sessões semestrais com a alta direção para apresentar desempenho e discutir melhorias"],"correct":0,"justification_correct":"Relatórios detalhados nas reuniões trimestrais do conselho garantem que a alta direção receba atualizações estruturadas para tomada de decisão informada, alinhado à Cláusula 9.3 (Análise Crítica pela Direção) da ISO 27001. (ISO/IEC 27001:2022)","justification_wrong":"E-mails mensais carecem de profundidade e discussão estruturada; painel em tempo real pode sobrecarregar sem contexto adequado; reuniões semestrais são infrequentes para problemas contínuos."},
    {"num":28,"text":"Em avaliação de riscos, um gerente sugere que software desatualizado executado em servidores críticos é o principal risco. Como o Lead Implementer deve explicar a relação entre vulnerabilidade, ameaça e risco?","tag":"Conceitos de Risco","options":["A. Software desatualizado é um risco porque expõe a organização a ataques potenciais","B. Software desatualizado é uma vulnerabilidade que combinada a ameaça relevante resulta em risco","C. Software desatualizado é uma ameaça porque cria oportunidade a ser explorada por agentes maliciosos","D. Software desatualizado é um impacto porque afeta diretamente as operações"],"correct":1,"justification_correct":"Software desatualizado é uma vulnerabilidade — fraqueza explorada por ameaças como malware. O risco surge da combinação de vulnerabilidade + ameaça + impacto potencial, conforme ISO 27005:2022 e terminologia da ISO 27000:2018. (ISO/IEC 27001:2022)","justification_wrong":"Risco exige vulnerabilidade + ameaça, não apenas a vulnerabilidade; software não é agente ativo (ameaça); impacto refere-se às consequências de um risco materializado."},
    {"num":29,"text":"Um Lead Implementer se prepara para auditoria de segunda parte conduzida por cliente que avalia conformidade do SGSI. Como essa auditoria difere das de primeira e terceira parte?","tag":"Tipos de Auditoria","options":["A. É conduzida para preparar a organização para certificação, revisando processos internos","B. É conduzida por organismo de certificação para verificar conformidade com ISO/IEC 27001","C. É conduzida pelo cliente para avaliar conformidade com requisitos contratuais ou acordados","D. É conduzida para revisar o SGSI após certificação visando conformidade contínua"],"correct":2,"justification_correct":"Auditoria de segunda parte é conduzida por parte externa — tipicamente cliente — para avaliar conformidade com requisitos contratuais específicos. Primeira parte são auditorias internas; terceira parte são auditorias de certificação. (ISO 19011:2018)","justification_wrong":"Preparação para certificação é foco de auditorias internas; verificação independente para ISO 27001 é terceira parte; revisão pós-certificação refere-se a auditorias de supervisão."},
    {"num":30,"text":"Uma empresa de e-commerce sofreu ataque de ransomware tornando o sistema de processamento de pedidos inacessível por 48 horas. Qual princípio de segurança da informação foi primordialmente afetado?","tag":"Princípios CIA","options":["A. Confidencialidade, porque dados sensíveis foram expostos durante o ataque","B. Integridade, porque o ransomware potencialmente alterou a funcionalidade do sistema","C. Disponibilidade, porque o sistema ficou inacessível por 48 horas","D. Tanto integridade quanto disponibilidade, pois o ataque interrompeu acesso e funcionalidade"],"correct":2,"justification_correct":"O ataque de ransomware causou indisponibilidade do sistema por 48 horas — impacto primário e direto sobre a disponibilidade, pilar do triângulo CIA definido na ISO 27000:2018 como propriedade de estar acessível e utilizável quando demandado. (ISO/IEC 27001:2022)","justification_wrong":"Confidencialidade não foi indicada como afetada; integridade não foi descrita como comprometida; o impacto primário e mais direto foi a disponibilidade, não ambos igualmente."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

# Injeta no dominio planning_implementation do iso27001_li
dir1 = Path("static/quizzes/iso27001_li/planning_implementation")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "iso27001_li",
    "domain_id": "planning_implementation",
    "quiz_num": num1,
    "domain_name": "Planejamento e Implementação",
    "cert_name": "ISO 27001 Lead Implementer",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (ISO 27001 LI) salvas em {path1}")
