#!/usr/bin/env python3
"""
CISM BATCH 5 - Metricas, Frameworks, Classificacao e Documentacao
15 questoes adaptadas - adiciona ao quiz_003 de info_security_governance
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":16,"text":"O conselho de administração deseja métricas trimestrais sobre redução de riscos. Qual seria a melhor métrica para apresentar ao conselho?","tag":"Métricas para o Conselho","options":["A. Número de regras de firewall acionadas","B. Vírus bloqueados por programas antivírus","C. Pacotes descartados pelo firewall","D. Tempo para corrigir vulnerabilidades em servidores críticos"],"correct":3,"justification_correct":"O tempo para corrigir vulnerabilidades em servidores críticos é a métrica mais significativa para o conselho — transmite informação de negócio relevante sobre exposição ao risco. As demais são métricas operacionais sem significado estratégico para membros do conselho. (CISM Review Manual, ISACA)","justification_wrong":"Regras de firewall, vírus bloqueados e pacotes descartados são métricas operacionais técnicas — não transmitem significado de negócio para o conselho de administração."},
    {"num":17,"text":"Qual das seguintes métricas é o melhor exemplo de um indicador antecedente (leading indicator)?","tag":"Indicadores de Segurança","options":["A. Tempo médio para mitigar incidentes de segurança","B. Aumento no número de ataques bloqueados pelo IPS","C. Aumento no número de ataques bloqueados pelo firewall","D. Percentual de servidores críticos com patches aplicados dentro dos SLAs"],"correct":3,"justification_correct":"O percentual de servidores com patches dentro dos SLAs é um indicador antecedente — prediz a probabilidade de incidentes futuros. As demais são indicadores posteriores (lagging), pois reportam eventos passados. (CISM Review Manual, ISACA)","justification_wrong":"Tempo de mitigação, ataques bloqueados por IPS e firewall são indicadores posteriores que reportam o que já aconteceu — apenas a cobertura de patches prediz eventos futuros."},
    {"num":18,"text":"O propósito de um Balanced Scorecard é:","tag":"Balanced Scorecard","options":["A. Medir a eficiência operacional de uma organização de segurança","B. Avaliar o desempenho individual dos colaboradores","C. Comparar processos da organização com organizações do mesmo setor","D. Medir o desempenho e a efetividade organizacional em relação aos objetivos estratégicos"],"correct":3,"justification_correct":"O Balanced Scorecard é uma ferramenta para quantificar o desempenho organizacional em relação aos objetivos estratégicos. Seus focos são: financeiro, cliente, processos internos, e inovação/aprendizado. (CISM Review Manual, ISACA)","justification_wrong":"Eficiência operacional e avaliação individual são métricas parciais; benchmarking com pares é uma técnica distinta — o BSC mede o desempenho holístico em relação à estratégia."},
    {"num":19,"text":"Uma organização usando PCI DSS como framework de controles conclui que controles adicionais presentes na ISO 27001 devem ser implementados. Qual é o melhor curso de ação?","tag":"Frameworks de Controle","options":["A. Adotar a ISO/IEC 27001 como novo framework de controles","B. Manter o PCI DSS e atualizar apenas a documentação de processos","C. Adicionar os controles necessários ao framework de controles existente","D. Adotar o NIST 800-53 como novo framework de controles"],"correct":2,"justification_correct":"Uma organização que precisa implementar novos controles deve fazê-lo dentro do framework existente. Não é necessário adotar um novo framework inteiro quando apenas alguns controles precisam ser adicionados. (CISM Review Manual, ISACA)","justification_wrong":"Adotar novo framework inteiro é desproporcional; atualizar apenas documentação não implementa os controles; trocar para NIST não resolve a necessidade específica identificada."},
    {"num":20,"text":"Um gestor de segurança desenvolveu um esquema que define os métodos obrigatórios para proteger informações em repouso, em movimento e em trânsito. Isso é conhecido como:","tag":"Classificação de Dados","options":["A. Política de classificação de dados","B. Política de classificação de ativos","C. Plano de prevenção de perda de dados","D. Plano de prevenção de perda de ativos"],"correct":0,"justification_correct":"Uma política de classificação de dados define dois ou mais níveis de classificação para dados, juntamente com procedimentos e padrões para a proteção em cada nível para casos de uso como armazenamento, transmissão e backup. (CISM Review Manual, ISACA)","justification_wrong":"Classificação de ativos abrange ativos físicos e lógicos mais amplamente; planos de DLP são ferramentas técnicas, não políticas — o esquema de proteção por nível de sensibilidade é a política de classificação de dados."},
    {"num":21,"text":"Um líder de segurança desenvolveu documento que descreve a missão, visão, papéis, responsabilidades e processos de um programa de segurança. Isso é conhecido como:","tag":"Documentação do Programa","options":["A. Política","B. Estatuto (Charter)","C. Padrão","D. Controle"],"correct":1,"justification_correct":"Um documento de estatuto (charter) descreve múltiplos aspectos de uma função ou programa — missão, visão, papéis, responsabilidades e processos. É o documento fundacional que legitima e define o programa de segurança. (CISM Review Manual, ISACA)","justification_wrong":"Política define regras de comportamento; padrão especifica requisitos técnicos; controle é mecanismo de proteção — apenas o charter descreve o programa de forma abrangente."},
    {"num":22,"text":"A gestão desenvolveu e publicou política que orienta os colaboradores a seguir etapas específicas para proteger vários tipos de informação. Isso é conhecido como:","tag":"Tipos de Documentos","options":["A. Política de privacidade","B. Dicionário de dados","C. Política de classificação de dados","D. Política de governança de dados"],"correct":2,"justification_correct":"A gestão criou uma política de classificação de dados — que define níveis de classificação e procedimentos de tratamento para informações em diversas formas e contextos (armazenamento, transmissão, descarte). (CISM Review Manual, ISACA)","justification_wrong":"Política de privacidade trata do uso de dados pessoais; dicionário de dados descreve estruturas de dados; governança de dados é mais abrangente — a política que define como tratar cada tipo de informação é de classificação de dados."},
    {"num":23,"text":"O líder de segurança está desenvolvendo a primeira política de classificação de dados da organização. Qual é o melhor primeiro passo?","tag":"Classificação de Dados","options":["A. Desenvolver os níveis de classificação","B. Realizar inventário de dados","C. Entrevistar os usuários finais","D. Desenvolver os procedimentos de tratamento"],"correct":1,"justification_correct":"O melhor primeiro passo é realizar um inventário de dados para compreender os vários tipos de dados armazenados e em uso na organização. Sem esse entendimento, não é possível definir níveis de classificação adequados. (CISM Review Manual, ISACA)","justification_wrong":"Desenvolver níveis, entrevistar usuários e criar procedimentos são etapas posteriores — sem saber quais dados existem, não é possível classificá-los adequadamente."},
    {"num":24,"text":"Um líder de segurança quer desenvolver um esquema onde os ativos mais importantes sejam protegidos mais rigorosamente. Qual é o melhor primeiro passo?","tag":"Proteção de Ativos","options":["A. Mapear os dados classificados aos sistemas","B. Estabelecer um inventário de sistemas","C. Entrevistar os usuários finais","D. Desenvolver as diretrizes de proteção"],"correct":1,"justification_correct":"O primeiro passo é desenvolver um inventário de sistemas. Em seguida, o melhor passo é mapear as informações (e suas classificações) armazenadas ou processadas por cada sistema — criando a base para aplicar proteções proporcionais. (CISM Review Manual, ISACA)","justification_wrong":"Mapear dados a sistemas é o segundo passo; entrevistar usuários e desenvolver diretrizes são etapas posteriores — o inventário de sistemas é o ponto de partida."},
    {"num":25,"text":"Um líder de segurança de organização varejista quer desenvolver um SGSI. Qual padrão é o melhor recurso para orientar esse desenvolvimento?","tag":"Padrões ISMS","options":["A. ISO/IEC 27001","B. ISO/IEC 27002","C. NIST SP 800-53","D. PCI DSS"],"correct":0,"justification_correct":"A ISO/IEC 27001 define todas as características de alto nível de um Sistema de Gestão de Segurança da Informação (SGSI) — é o padrão de referência para desenvolver e certificar um SGSI. As demais opções são frameworks de controles. (CISM Review Manual, ISACA)","justification_wrong":"ISO 27002 é catálogo de controles, não framework de SGSI; NIST 800-53 e PCI DSS são frameworks de controles específicos — apenas a ISO 27001 define os requisitos para um SGSI."},
    {"num":26,"text":"Um colaborador de TI lê documento de segurança que fornece sugestões não vinculativas sobre conformidade com uma política específica. Que tipo de documento é esse?","tag":"Hierarquia de Documentos","options":["A. Procedimento","B. Política","C. Padrão","D. Diretriz (Guideline)"],"correct":3,"justification_correct":"Uma diretriz (guideline) é um documento que fornece orientação não vinculativa sobre conformidade com políticas, controles ou padrões. Diferentemente de procedimentos e padrões, diretrizes são recomendações, não obrigações. (CISM Review Manual, ISACA)","justification_wrong":"Procedimento descreve etapas obrigatórias; política define regras de comportamento; padrão especifica requisitos técnicos obrigatórios — apenas a diretriz é orientação não vinculativa."},
    {"num":27,"text":"Um colaborador de TI lê documento de segurança que estipula quais algoritmos devem ser usados para criptografar dados em repouso. Que tipo de documento é esse?","tag":"Hierarquia de Documentos","options":["A. Procedimento","B. Requisitos","C. Padrão","D. Diretriz"],"correct":2,"justification_correct":"Um padrão é um documento que estipula o uso obrigatório de protocolos, algoritmos, técnicas, produtos ou fornecedores específicos — a especificação de algoritmos de criptografia é uma definição clássica de padrão técnico. (CISM Review Manual, ISACA)","justification_wrong":"Procedimento descreve etapas de execução; requisitos descrevem características necessárias; diretriz é não vinculativa — a especificação de algoritmos obrigatórios é um padrão."},
    {"num":28,"text":"Um colaborador de TI lê documento que descreve as características essenciais de um sistema a ser desenvolvido. Que tipo de documento é esse?","tag":"Hierarquia de Documentos","options":["A. Procedimento","B. Requisitos","C. Padrão","D. Diretriz"],"correct":1,"justification_correct":"Um documento de requisitos descreve as características necessárias de um sistema a ser desenvolvido ou adquirido — especificando o que o sistema deve fazer ou possuir. (CISM Review Manual, ISACA)","justification_wrong":"Procedimento descreve etapas de execução; padrão especifica tecnologias obrigatórias; diretriz é orientação não vinculativa — características necessárias de um sistema são requisitos."},
    {"num":29,"text":"O conceito de dividir a gestão de controles em desenvolvimento, operações e garantia (assurance) é conhecido como:","tag":"Três Linhas de Defesa","options":["A. Framework de controles","B. Custódia compartilhada","C. Segregação de funções","D. Três linhas de defesa"],"correct":3,"justification_correct":"O modelo das três linhas de defesa descreve os papéis separados na gestão de controles: desenvolvimento (1ª linha), operações (2ª linha) e garantia/auditoria (3ª linha). (CISM Review Manual, ISACA; IIA Three Lines Model)","justification_wrong":"Framework de controles é o conjunto de controles; custódia compartilhada é conceito de responsabilidade; segregação de funções é princípio de controle interno — o modelo específico de três linhas descreve os papéis de desenvolvimento, operações e auditoria."},
    {"num":30,"text":"Qual é o propósito principal da função de garantia (assurance) no modelo das três linhas de defesa?","tag":"Três Linhas de Defesa","options":["A. Desenvolver e implementar novos controles de segurança","B. Operar os controles de segurança no dia a dia","C. Verificar independentemente se os controles estão funcionando conforme projetado","D. Definir a estratégia e políticas de segurança da organização"],"correct":2,"justification_correct":"A função de garantia (assurance) — tipicamente a auditoria interna — verifica de forma independente se os controles desenvolvidos e operados pelas outras linhas estão funcionando conforme projetado e são eficazes. (CISM Review Manual, ISACA; IIA Three Lines Model)","justification_wrong":"Desenvolver controles é a 1ª linha; operar controles é a 2ª linha; definir estratégia é papel da governança — a garantia independente é a função específica da 3ª linha."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/cism/info_security_governance")
dir1.mkdir(parents=True, exist_ok=True)

quiz003 = dir1 / "quiz_003_pt.json"
if quiz003.exists():
    data = json.loads(quiz003.read_text(encoding="utf-8"))
    existing_q = data.get("questions", [])
    if len(existing_q) < 50:
        next_num = len(existing_q) + 1
        for i, q in enumerate(questions):
            q["num"] = next_num + i
        existing_q.extend(questions)
        data["questions"] = existing_q[:50]
        quiz003.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        total = len(data["questions"])
        print(f"OK - {len(questions)} questoes adicionadas ao quiz_003_pt.json")
        print(f"Total agora: {total}/50")
        if total < 50:
            print(f"AVISO - ainda faltam {50-total} questoes.")
        else:
            print("Bateria completa!")
    else:
        num = get_next_num(dir1)
        path = dir1 / f"quiz_{num:03d}_pt.json"
        out = {"cert_id":"cism","domain_id":"info_security_governance","quiz_num":num,"domain_name":"Information Security Governance","cert_name":"CISM","lang":"pt","questions":questions}
        path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"OK - {len(questions)} questoes salvas em {path}")
else:
    print("quiz_003 nao encontrado — criando novo")
    num = get_next_num(dir1)
    path = dir1 / f"quiz_{num:03d}_pt.json"
    out = {"cert_id":"cism","domain_id":"info_security_governance","quiz_num":num,"domain_name":"Information Security Governance","cert_name":"CISM","lang":"pt","questions":questions}
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"OK - {len(questions)} questoes salvas em {path}")
