#!/usr/bin/env python3
"""
CISM BATCH 11 - Risk Management, Ameacas e Conformidade
30 questoes - 25 para risk_management/quiz_002 + 5 para governance/quiz_004
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

q_risk = [
    {"num":1,"text":"Uma organização possui processo pelo qual riscos de segurança são identificados, analisados e tratados. Como se chama esse processo de negócio?","tag":"Gestão de Riscos","options":["A. Gestão de vulnerabilidades","B. Tratamento de riscos","C. Gestão de riscos","D. Avaliação de riscos"],"correct":2,"justification_correct":"O processo de gestão de riscos consiste em avaliações de riscos, análise dos riscos identificados e decisões sobre o que fazer com eles. Avaliação de riscos e tratamento são partes do processo mais amplo de gestão de riscos. (CISM Review Manual, ISACA)","justification_wrong":"Gestão de vulnerabilidades é tática; tratamento é apenas uma fase; avaliação é apenas uma etapa — gestão de riscos é o processo completo."},
    {"num":2,"text":"Qual é o propósito de um programa de gestão de riscos cibernéticos em uma organização?","tag":"Programa de Riscos","options":["A. Consumir informações de um registro centralizado de riscos","B. Identificar riscos de segurança e tomar decisões sobre eles","C. Planejar projetos futuros de cibersegurança","D. Desenvolver controles mitigadores"],"correct":1,"justification_correct":"O propósito de um programa de gestão de riscos cibernéticos é usar vários meios para identificar riscos de TI e segurança e tomar decisões sobre seu tratamento. O desenvolvimento de controles é um resultado possível, não o propósito. (CISM Review Manual, ISACA)","justification_wrong":"Consumir dados do registro é atividade; planejar projetos é consequência; desenvolver controles é um dos possíveis resultados — identificar e decidir sobre riscos é o propósito central."},
    {"num":3,"text":"Todas as atividades a seguir são entradas típicas para um processo de gestão de riscos, EXCETO:","tag":"Entradas de Risco","options":["A. Revisões de código","B. Avaliações de riscos","C. Avaliações de ameaças","D. Auditorias internas"],"correct":0,"justification_correct":"Revisão de código não é uma entrada típica para o processo de gestão de riscos — representa exame tático e estreito do código-fonte. Avaliações de riscos, ameaças e auditorias internas identificam problemas sistêmicos que alimentam o processo de gestão de riscos. (CISM Review Manual, ISACA)","justification_wrong":"Avaliações de riscos, ameaças e auditorias internas identificam riscos sistêmicos que alimentam o processo — revisões de código são táticas e tipicamente alimentam processos de gestão de vulnerabilidades."},
    {"num":4,"text":"Qual deve ser o objetivo principal de uma estratégia de gestão de riscos?","tag":"Estratégia de Riscos","options":["A. Determinar o apetite ao risco da organização","B. Identificar riscos críveis e transferi-los a terceiros","C. Identificar riscos críveis e reduzi-los a nível aceitável","D. Eliminar riscos críveis"],"correct":2,"justification_correct":"O objetivo principal de uma estratégia de gestão de riscos é a identificação de riscos seguida da redução desses riscos a níveis aceitáveis para a alta gestão. Eliminar riscos é impossível; transferir é apenas uma das opções de tratamento. (CISM Review Manual, ISACA)","justification_wrong":"Determinar apetite ao risco é pré-requisito; transferir é apenas uma opção de tratamento; eliminar riscos é impossível — reduzir a níveis aceitáveis é o objetivo central."},
    {"num":5,"text":"Marie, CISO de empresa manufatureira, está construindo novo processo de governança de riscos cibernéticos. Qual é o melhor primeiro passo?","tag":"Governança de Riscos","options":["A. Desenvolver matriz RACI definindo papéis e responsabilidades executivos","B. Constituir comitê diretor de segurança com líderes de TI e cibersegurança","C. Desenvolver processo de gestão de riscos similar ao da ISO/IEC 27001","D. Constituir comitê diretor de segurança com líderes de TI, segurança e negócio"],"correct":3,"justification_correct":"O melhor primeiro passo é constituir um comitê diretor de segurança composto por executivos seniores, líderes de unidades de negócio e chefes de departamento. Para que a governança de segurança funcione, os líderes de negócio precisam estar envolvidos. (CISM Review Manual, ISACA)","justification_wrong":"Matriz RACI é parte de um comitê constituído; comitê apenas com TI e cibersegurança exclui o negócio; ISO 27001 é framework de controles, não o primeiro passo de governança."},
    {"num":6,"text":"A auditoria interna identificou que a organização não está em conformidade com o PCI DSS quanto ao reconhecimento anual da política de segurança pelos colaboradores. Que tipo de risco foi identificado?","tag":"Risco de Conformidade","options":["A. Risco de ameaça interna","B. Risco de divulgação","C. Risco de conformidade","D. Risco administrativo"],"correct":2,"justification_correct":"Organizações que processam dados de cartão de crédito são obrigadas a cumprir todos os controles do PCI DSS. A não conformidade, mesmo que não represente risco real de segurança, é primariamente um risco de conformidade. (CISM Review Manual, ISACA)","justification_wrong":"Ameaça interna, divulgação e risco administrativo não descrevem a situação — a não conformidade com requisito regulatório específico é risco de conformidade."},
    {"num":7,"text":"Qual afirmação é correta sobre regulamentações aplicáveis e a seleção de um framework de controles de segurança?","tag":"Regulamentação e Frameworks","options":["A. Framework adequado facilitará o mapeamento de detalhes regulatórios para atividades requeridas","B. Não faz diferença qual framework é selecionado para conformidade regulatória","C. Leis aplicáveis e frameworks de controles têm pouca relação entre si","D. Para organizações reguladas, a escolha correta de framework resulta em menores prêmios de seguro"],"correct":0,"justification_correct":"Regulamentações podem ou não especificar atividades específicas. Frameworks disponíveis se assemelham a atividades regulatórias requeridas — selecionar framework alinhado à regulação ajuda a organização a mapear requisitos legais para atividades concretas. (CISM Review Manual, ISACA)","justification_wrong":"Faz diferença escolher o framework; leis e frameworks têm relação direta; prêmios de seguro não são o benefício primário."},
    {"num":8,"text":"No método FAIR (Factor Analysis of Information Risk), como o gestor de riscos determina os tipos potenciais de perda?","tag":"Metodologia FAIR","options":["A. Por meio de avaliação de riscos","B. Usando o registro de perdas anteriores","C. Usando perdas em empresas similares","D. Os tipos de perda são definidos pelo próprio método FAIR"],"correct":3,"justification_correct":"O método FAIR contém seis tipos de perda: produtividade, resposta, substituição, multas e julgamentos, vantagem competitiva e reputação. Qualquer incidente de cibersegurança pode resultar em uma ou mais dessas perdas. (CISM Review Manual, ISACA)","justification_wrong":"Avaliação de riscos, registros históricos e benchmarking são fontes de dados — os tipos de perda são definidos estruturalmente pelo próprio framework FAIR."},
    {"num":9,"text":"Dawn, CISO em organização farmacêutica, está avaliando novas regulamentações com o departamento jurídico. Qual abordagem será mais bem-sucedida?","tag":"Gestão de Conformidade","options":["A. Examinar cada nova regulamentação quanto ao impacto e confirmar se o impacto é significativo","B. Examinar cada nova regulamentação quanto ao impacto e confirmar aplicabilidade em outros países","C. Examinar cada nova regulamentação quanto à aplicabilidade e analisar o impacto nos negócios","D. Assinar serviço de monitoramento de novas leis e implementá-las no próximo orçamento"],"correct":2,"justification_correct":"Como há muitas regulamentações de diferentes tipos, é necessário primeiro determinar quais são aplicáveis. Para as aplicáveis, o próximo passo é compreender o impacto nos processos de negócio e custos, e então desenvolver plano de conformidade. (CISM Review Manual, ISACA)","justification_wrong":"Examinar o impacto antes da aplicabilidade gera trabalho desnecessário; confirmar aplicabilidade em outros países é secundário; assinar serviço sem triagem é ineficiente."},
    {"num":10,"text":"O que deve ser concluído antes do início de uma avaliação de riscos em uma organização?","tag":"Preparação para Avaliação","options":["A. Determinar as qualificações da firma que realizará a auditoria","B. Determinar escopo, propósito e critérios da avaliação","C. Determinar as qualificações das pessoas que realizarão a avaliação","D. Determinar o framework para reportar os resultados"],"correct":1,"justification_correct":"De acordo com a ISO/IEC 27005 e outros frameworks de gestão de riscos, é necessário primeiro estabelecer o contexto — determinar o escopo da avaliação, seu propósito (cobertura de controles, efetividade ou eficácia de processos) e os critérios. (CISM Review Manual, ISACA)","justification_wrong":"Qualificações são determinadas antes deste ponto; framework de reporte é estabelecido após definir propósito — escopo, propósito e critérios são os pré-requisitos fundamentais."},
    {"num":11,"text":"Qual das seguintes NÃO é uma metodologia de gestão de riscos?","tag":"Metodologias","options":["A. Risk-IT","B. ISO/IEC 27005","C. NIST Special Publication 800-39","D. FAIR"],"correct":3,"justification_correct":"FAIR (Factor Analysis of Information Risk) não é um framework de gestão de riscos, mas uma metodologia de avaliação de riscos. Um framework de gestão de riscos trata dos resultados das avaliações, não do desempenho das avaliações em si. (CISM Review Manual, ISACA)","justification_wrong":"Risk-IT, ISO 27005 e NIST 800-39 são frameworks de gestão de riscos — FAIR é metodologia de avaliação, não de gestão."},
    {"num":12,"text":"Qual é o objetivo principal da metodologia FAIR (Factor Analysis of Information Risk)?","tag":"FAIR","options":["A. Determinar a probabilidade de um evento de ameaça","B. Determinar o impacto de um evento de ameaça","C. Determinar o custo de um evento de ameaça","D. Determinar o tipo de um evento de ameaça"],"correct":0,"justification_correct":"O objetivo principal do FAIR é determinar a probabilidade de um evento usando análise 'what if', o que não pode ser facilmente feito usando modelos de maturidade ou checklists. (CISM Review Manual, ISACA)","justification_wrong":"FAIR não determina impacto, custo ou tipo de evento de ameaça — seu foco é na probabilidade usando análise quantitativa."},
    {"num":13,"text":"Novo CISO em organização de serviços financeiros quer controlar o inventário de ativos. A organização usa on-premises e IaaS. Qual abordagem identificará mais efetivamente todos os ativos?","tag":"Inventário de Ativos","options":["A. Executar scans de descoberta em todas as redes","B. Obter lista de todos os ativos da plataforma de gestão de patches","C. Obter lista de todos os ativos do SIEM","D. Contar todos os servidores em cada data center"],"correct":0,"justification_correct":"Embora nenhuma abordagem seja ideal isoladamente, scans de descoberta em todas as redes é o melhor primeiro passo — cobrindo on-premises e ambientes IaaS. Ainda será necessário consultar engenheiros de rede e sistemas para virtualização. (CISM Review Manual, ISACA)","justification_wrong":"Gestão de patches pode não receber logs de todos os ativos; SIEM pode ter lacunas em IaaS; contar servidores físicos não descobre ativos virtuais e IaaS."},
    {"num":14,"text":"Russ, gestor de segurança de varejista online com clientes globais, soube recentemente sobre o GDPR. O que Russ deve fazer?","tag":"GDPR","options":["A. Consultar a gestão sênior ou o departamento jurídico sobre o assunto","B. Assumir que a organização está em conformidade com o GDPR","C. Nada, pois a plataforma de e-commerce em nuvem deve ser compatível com GDPR","D. Contatar a plataforma de e-commerce para confirmar conformidade"],"correct":0,"justification_correct":"Um gestor de segurança responsável sempre consultaria o departamento jurídico ou membro da alta gestão para saber o estado de conformidade da organização com uma lei ou regulamentação. (CISM Review Manual, ISACA)","justification_wrong":"Assumir conformidade é imprudente; a responsabilidade pelo GDPR é da própria organização, independentemente de terceirização; apenas confirmar com o provedor não é suficiente."},
    {"num":15,"text":"Dylan identificou problemas de conformidade com diversas regulamentações em uma organização cliente. Como devem ser documentados esses achados?","tag":"Documentação de Conformidade","options":["A. Entradas separadas no registro de riscos para cada regulamentação","B. Uma entrada única no registro de riscos da organização","C. Entradas separadas no log de incidentes de segurança para cada regulamentação","D. Uma entrada única no log de incidentes de segurança"],"correct":1,"justification_correct":"A melhor forma é criar uma única entrada no registro de riscos — podem existir dezenas de problemas similares com remédios comuns, tornando impraticável criar dezenas de entradas separadas. (CISM Review Manual, ISACA)","justification_wrong":"Entradas separadas por regulamentação criam confusão desnecessária; log de incidentes não é o local adequado para problemas de conformidade regulatória."},
    {"num":16,"text":"Um analista de segurança identificou servidor crítico sem patch importante de segurança do sistema operacional. O que foi identificado?","tag":"Vulnerabilidades","options":["A. Uma vulnerabilidade","B. Uma ameaça","C. Um risco","D. Um incidente"],"correct":0,"justification_correct":"O analista identificou uma vulnerabilidade — uma fraqueza que poderia facilmente permitir que uma ou mais ameaças ocorram. A ausência de patch é uma deficiência técnica explorada por ameaças. (CISM Review Manual, ISACA)","justification_wrong":"Ameaça é o evento potencialmente danoso; risco é a combinação de probabilidade e impacto; incidente é o evento que já ocorreu — patch ausente é especificamente uma vulnerabilidade."},
    {"num":17,"text":"Um analista de segurança identificou nova técnica que cibercriminosos estão usando para invadir sistemas operacionais de servidores. O que foi identificado?","tag":"Ameaças","options":["A. Uma vulnerabilidade","B. Uma ameaça","C. Um risco","D. Um incidente"],"correct":1,"justification_correct":"O analista identificou uma ameaça — uma técnica que, se realizada, poderia resultar em intrusão nos sistemas da organização. (CISM Review Manual, ISACA)","justification_wrong":"Vulnerabilidade é fraqueza nos sistemas; risco combina probabilidade e impacto; incidente é evento já ocorrido — nova técnica de ataque é especificamente uma ameaça."},
    {"num":18,"text":"Atores de ameaça consistem em todos os seguintes, EXCETO:","tag":"Atores de Ameaça","options":["A. Trojans","B. Hacktivistas","C. Organizações criminosas","D. Funcionários"],"correct":0,"justification_correct":"Trojans são ameaças (malware), não atores de ameaça. Atores de ameaça são pessoas ou entidades externas como hackers, organizações criminosas, hacktivistas, e também internos como funcionários (ameaças internas). (CISM Review Manual, ISACA)","justification_wrong":"Hacktivistas, organizações criminosas e funcionários são todos considerados atores de ameaça — Trojans são ferramentas/malware, não agentes."},
    {"num":19,"text":"NotPetya é um exemplo de quê?","tag":"Malware","options":["A. Ameaça","B. Spyware","C. Worm de e-mail em massa","D. Ferramenta de quebra de senhas"],"correct":0,"justification_correct":"NotPetya é uma ameaça — especificamente malware que se assemelha a ransomware mas sem capacidade de descriptografar; muitos o consideram destruware ou software que destrói arquivos de dados. (CISM Review Manual, ISACA)","justification_wrong":"NotPetya não é spyware, worm de e-mail em massa nem ferramenta de senha — é malware destrutivo classificado como ameaça."},
    {"num":20,"text":"Qual lei europeia aplica direitos de privacidade para usuários?","tag":"Legislação de Privacidade","options":["A. GLBA","B. GDPR","C. 95/46/EC","D. SB-1386"],"correct":1,"justification_correct":"O GDPR (Regulamento Geral de Proteção de Dados), em vigor desde 2018, fornece diversos meios para melhorar a privacidade dos residentes europeus — substituindo a diretiva 95/46/EC. (CISM Review Manual, ISACA)","justification_wrong":"GLBA é lei americana para serviços financeiros; 95/46/EC é a diretiva europeia anterior substituída pelo GDPR; SB-1386 é lei californiana de notificação de violações."},
    {"num":21,"text":"Qual mecanismo o GDPR fornece para organizações multinacionais realizarem transferências internas de PII?","tag":"GDPR","options":["A. Cláusulas modelo","B. Privacy Shield","C. Safe Harbor","D. Regras corporativas vinculantes"],"correct":3,"justification_correct":"Regras corporativas vinculantes (Binding Corporate Rules) foram estabelecidas por leis de privacidade europeias para permitir que organizações multinacionais realizem transferências internas de PII entre suas filiais. (CISM Review Manual, ISACA)","justification_wrong":"Cláusulas modelo são usadas para obrigar terceiros a cumprir outras regulamentações; Privacy Shield foi usado para registrar obrigação de conformidade com GDPR (descontinuado); Safe Harbor é mecanismo anterior revogado."},
    {"num":22,"text":"Auditoria interna identificou que controle 'servidores de produção serão corrigidos em 30 dias após patches críticos' falha 30% do tempo. O que deve concluir a auditoria?","tag":"Efetividade de Controles","options":["A. Novo controle é necessário para gestão de vulnerabilidades","B. O controle é ineficaz e precisa ser corrigido","C. O controle deve ser alterado de 30 para 45 dias","D. O controle deve ser alterado de 30 para 21 dias"],"correct":1,"justification_correct":"Existe um controle em vigor que não é eficaz. O melhor remédio é corrigir o controle existente, que ainda é razoável e apropriado — não criar novo controle nem alterar o SLA. (CISM Review Manual, ISACA)","justification_wrong":"Criar novo controle não faz sentido antes de corrigir o existente; alterar o SLA para 45 dias reduziria o padrão; para 21 dias seria mais restritivo sem resolver a causa raiz."},
    {"num":23,"text":"Um novo gestor de segurança descobriu que o processo de controle de mudanças não possui procedimento de impacto de segurança. O que deve recomendar?","tag":"Gestão de Mudanças","options":["A. Varreduras de sistemas antes e depois de cada mudança","B. Revisão de segurança pós-mudança","C. Nenhuma mudança necessária pois segurança não é necessária em controle de mudanças","D. Adicionar procedimento de impacto de segurança ao processo de controle de mudanças"],"correct":3,"justification_correct":"A melhor solução é adicionar procedimento de impacto de segurança ao processo de controle de mudanças — isso permitirá identificar o impacto de segurança de cada mudança proposta antes de ser implementada. (CISM Review Manual, ISACA)","justification_wrong":"Varreduras pós-mudança são reativas; revisão apenas pós-mudança perde a oportunidade de prevenir — o procedimento de impacto pré-mudança é a abordagem proativa correta."},
    {"num":24,"text":"O termo 'ameaça interna' inclui todos os seguintes, EXCETO:","tag":"Ameaça Interna","options":["A. Usuários finais ignorantes que tomam decisões equivocadas","B. Funcionários com rancor contra o empregador","C. Clientes que tentam invadir sistemas enquanto estão no local","D. Usuários finais que estão fazendo a coisa certa mas cometem erros"],"correct":2,"justification_correct":"Clientes, mesmo quando no local, geralmente não são considerados insiders. Ameaças internas são tipicamente funcionários, contratados e outros que têm acesso legítimo concedido — não visitantes externos. (CISM Review Manual, ISACA)","justification_wrong":"Usuários ignorantes, funcionários rancorosos e usuários que cometem erros são todos considerados ameaças internas — clientes não têm acesso privilegiado típico de insiders."},
    {"num":25,"text":"Qual fator em análise de riscos é mais difícil de determinar com precisão?","tag":"Análise de Riscos","options":["A. Fator de exposição","B. Expectativa de perda única (SLE)","C. Probabilidade de evento","D. Impacto do evento"],"correct":2,"justification_correct":"A probabilidade de evento é a mais difícil de determinar com precisão — especialmente para eventos de alto impacto e baixa frequência. Por essa razão, a análise de riscos é qualitativa em natureza. (CISM Review Manual, ISACA)","justification_wrong":"Fator de exposição é percentual relativamente determinável; SLE é calculado a partir do valor do ativo; impacto do evento também é relativamente determinável — a probabilidade é intrinsecamente a mais incerta."},
]

q_gov4 = [
    {"num":6,"text":"Uma estimativa do número de vezes que uma ameaça pode ocorrer em um dado ano é conhecida como:","tag":"Conceitos de Risco","options":["A. Expectativa de perda anualizada (ALE)","B. Taxa de ocorrência anualizada (ARO)","C. Fator de exposição (EF)","D. Fator de exposição anualizado (AEF)"],"correct":1,"justification_correct":"A Taxa de Ocorrência Anualizada (ARO) é definida como estimativa do número de vezes que uma ameaça ocorrerá por ano. (CISM Review Manual, ISACA)","justification_wrong":"ALE é o produto de ARO pelo SLE; fator de exposição é percentual do valor do ativo perdido; AEF não é terminologia padrão."},
    {"num":7,"text":"Joel assina boletins de segurança de três fornecedores de TI. Qual afirmação melhor descreve a adequação dessas fontes?","tag":"Inteligência de Ameaças","options":["A. Joel também deve assinar fontes não fornecedores como US-CERT e InfraGard","B. As fontes de consultoria de segurança de Joel são adequadas","C. Joel deve descontinuar os fornecedores e assinar fontes não fornecedores","D. Joel deve focar em threat hunting na dark web"],"correct":0,"justification_correct":"O melhor conjunto de consultores de segurança inclui todos os fornecedores de TI, além de fontes não fornecedores como US-CERT e InfraGard. Fontes não fornecedores fornecem perspectiva mais ampla sobre o cenário de ameaças. (CISM Review Manual, ISACA)","justification_wrong":"Apenas fornecedores é insuficiente; descontinuar fornecedores perde informações relevantes; threat hunting na dark web não é atividade típica de gestão de riscos."},
    {"num":8,"text":"Janice, CISO em organização de saúde, descobriu que praticamente todos os funcionários são administradores locais em seus laptops. Isso é um exemplo de:","tag":"Vulnerabilidades","options":["A. Ameaça interna","B. Vulnerabilidade","C. Ameaça","D. Incidente"],"correct":1,"justification_correct":"O fato de usuários finais serem administradores locais significa que têm controle administrativo sobre seus computadores — podem instalar software e alterar configurações, o que representa uma vulnerabilidade que pode agravar situações de malware. (CISM Review Manual, ISACA)","justification_wrong":"Não é ameaça interna por si só (embora possa agravá-la); não é uma ameaça ativa; não é um incidente — é uma fraqueza configuracional que é uma vulnerabilidade."},
    {"num":9,"text":"Uma campanha de cibercriminoso para realizar reconhecimento, desenvolver ferramentas especializadas e construir presença de longo prazo silenciosa no ambiente de uma organização é conhecida como:","tag":"APT","options":["A. Ataque watering hole","B. Hacktivismo","C. Campanha de persistência avançada (APC)","D. Ameaça persistente avançada (APT)"],"correct":3,"justification_correct":"Uma APT (Advanced Persistent Threat) é campanha de longo prazo de reconhecimento, desenvolvimento de ferramentas e estabelecimento de presença silenciosa no ambiente — é 'avançada' pelo reconhecimento e ferramentas, 'persistente' pelo design de longo prazo, e 'ameaça' pelo objetivo final. (CISM Review Manual, ISACA)","justification_wrong":"Watering hole é ataque via site comprometido; hacktivismo é motivado por ideologia; APC não é terminologia padrão — APT é o termo correto."},
    {"num":10,"text":"Qual fator em análise de riscos é mais difícil de determinar com precisão e por quê?","tag":"Análise de Riscos","options":["A. Fator de exposição — pois depende do valor do ativo","B. Expectativa de perda única — pois combina múltiplas variáveis","C. Probabilidade do evento — especialmente em eventos de alto impacto e baixa frequência","D. Impacto do evento — pois envolve danos intangíveis difíceis de quantificar"],"correct":2,"justification_correct":"A probabilidade do evento é a mais difícil de determinar com precisão — particularmente para eventos de alto impacto e baixa frequência. É por isso que a análise de riscos é essencialmente qualitativa em sua natureza. (CISM Review Manual, ISACA)","justification_wrong":"Fator de exposição e SLE são relativamente determináveis; impacto tangível é mensurável — a probabilidade de eventos raros e de alto impacto é intrinsecamente a mais incerta."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try: nums.append(int(f.stem.split("_")[1]))
        except: pass
    return max(nums) + 1 if nums else 1

def add_to_quiz(path, new_q):
    if not path.exists(): return False, 0
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = data.get("questions",[])
    if len(existing) >= 50: return False, len(existing)
    next_num = len(existing) + 1
    for i,q in enumerate(new_q): q["num"] = next_num + i
    existing.extend(new_q)
    data["questions"] = existing[:50]
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

# Cria risk_management/quiz_002
dir_risk = Path("static/quizzes/cism/info_risk_management")
dir_risk.mkdir(parents=True, exist_ok=True)
num2 = get_next_num(dir_risk)
out2 = {"cert_id":"cism","domain_id":"info_risk_management","quiz_num":num2,"domain_name":"Information Risk Management","cert_name":"CISM","lang":"pt","questions":q_risk}
path2 = dir_risk / f"quiz_{num2:03d}_pt.json"
path2.write_text(json.dumps(out2, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(q_risk)} questoes salvas em {path2}")
print(f"Total: {len(q_risk)}/50" + (" - COMPLETO!" if len(q_risk)>=50 else f" (faltam {50-len(q_risk)})"))

# Adiciona ao governance/quiz_004
path4 = Path("static/quizzes/cism/info_security_governance/quiz_004_pt.json")
ok, total = add_to_quiz(path4, q_gov4)
if ok:
    print(f"OK - {len(q_gov4)} questoes adicionadas ao governance/quiz_004_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total>=50 else f" (faltam {50-total})"))
