#!/usr/bin/env python3
"""
CFE BATCH 3
Q101-125: Apropriação Indébita de Ativos
Q126-150: Corrupção e Suborno
Ambos: Financial Transactions & Fraud Schemes
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# ── Q101-125: Apropriação Indébita de Ativos ─────────────────────────────────
q101_125 = [
    {"num":1,"text":"A categoria de fraude denominada apropriação indébita de ativos abrange, em sua essência:","tag":"Apropriação de Ativos","options":["A. Manipulação intencional de demonstrações financeiras","B. Roubo ou uso indevido dos recursos patrimoniais da organização","C. Pagamento de subornos a agentes públicos","D. Intrusão cibernética por atacantes externos"],"correct":1,"justification_correct":"A apropriação indébita de ativos compreende o desvio de caixa, estoques e demais recursos organizacionais por meio de esquemas variados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Manipulação de demonstrações é fraude contábil; subornos configuram corrupção; intrusão cibernética é crime tecnológico distinto."},
    {"num":2,"text":"Entre os ativos organizacionais, qual é o mais frequentemente alvo de desvio em esquemas de apropriação indébita?","tag":"Ativos Vulneráveis","options":["A. Bens do ativo imobilizado","B. Estoques de produtos acabados","C. Recursos disponíveis em caixa e equivalentes","D. Direitos de propriedade intelectual"],"correct":2,"justification_correct":"O caixa é o ativo mais frequentemente desviado por sua liquidez imediata e pela dificuldade de rastreamento, especialmente em transações físicas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Imobilizado, estoques e propriedade intelectual são alvos menos frequentes devido à menor liquidez e maior dificuldade de conversão."},
    {"num":3,"text":"O esquema de skimming se distingue do furto de caixa (cash larceny) porque no skimming o desvio ocorre:","tag":"Skimming","options":["A. Após o registro contábil da entrada de recursos","B. Exclusivamente por meios eletrônicos e digitais","C. Antes do registro do recebimento nos sistemas da organização","D. Somente mediante conluio entre dois ou mais funcionários"],"correct":2,"justification_correct":"No skimming, os recursos são subtraídos antes de serem registrados, tornando o esquema mais difícil de detectar pois não há registro da entrada que foi desviada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O furto de caixa ocorre após o registro; o skimming não é exclusivamente eletrônico nem requer conluio."},
    {"num":4,"text":"O furto de caixa (cash larceny) é caracterizado pelo desvio de recursos:","tag":"Furto de Caixa","options":["A. Mediante criação de fornecedores fictícios no sistema","B. Após o efetivo registro contábil do recebimento","C. Por meio da manipulação de relatórios de despesas","D. Via subdeclaração intencional de receitas"],"correct":1,"justification_correct":"O cash larceny ocorre após o dinheiro ter sido registrado nos sistemas, diferenciando-se do skimming e tornando o desvio detectável pela comparação entre registros e saldos físicos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas descrevem outros tipos de fraude — fornecedores fictícios, despesas e subdeclaração de receitas."},
    {"num":5,"text":"Qual controle interno é mais eficaz na prevenção de desvios de caixa?","tag":"Controles de Caixa","options":["A. Contagens surpresa e periódicas de caixa","B. Rodízio sistemático de funções entre colaboradores","C. Segregação das funções de autorização, custódia e registro","D. Programas de treinamento ético para colaboradores"],"correct":2,"justification_correct":"A segregação de funções impede que uma única pessoa controle o ciclo completo — autorizar transações, ter custódia dos recursos e registrar as entradas — reduzindo a oportunidade de desvio. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Contagens surpresa, rodízio e treinamento são controles complementares, mas a segregação de funções é o mecanismo preventivo mais eficaz."},
    {"num":6,"text":"A detecção de desvios de estoque apresenta maior dificuldade quando os itens são:","tag":"Desvio de Estoque","options":["A. Volumosos e de difícil transporte","B. De alto valor unitário e bem identificados","C. De pequenas dimensões e facilmente dissimulados","D. Cobertos por apólice de seguro específica"],"correct":2,"justification_correct":"Itens pequenos e portáteis são mais facilmente subtraídos sem chamar atenção, dificultando a detecção em auditorias e contagens físicas rotineiras. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Itens volumosos e de alto valor são mais facilmente rastreados; a cobertura de seguro não interfere na facilidade de detecção do desvio."},
    {"num":7,"text":"Em esquemas de fraude na folha de pagamento, qual das seguintes práticas NÃO se enquadra como fraude típica?","tag":"Fraude em Folha","options":["A. Inclusão de funcionários fictícios na folha de pagamento","B. Registro de horas trabalhadas superiores às efetivas","C. Inflação artificial das taxas de comissão","D. Pagamento de salários abaixo do acordado em contrato"],"correct":3,"justification_correct":"A fraude em folha de pagamento envolve a superestimação de remunerações — funcionários fictícios, horas falsas e comissões infladas. Pagar abaixo do combinado não é fraude na folha, mas potencial inadimplência contratual. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Funcionários fictícios, horas falsificadas e comissões infladas são modalidades clássicas de fraude em folha de pagamento."},
    {"num":8,"text":"Um esquema de funcionário fantasma (ghost employee) pressupõe a existência de:","tag":"Funcionário Fantasma","options":["A. Aprovação expressa de fornecedores externos","B. Conluio com clientes da organização","C. Controles deficientes nos processos de folha de pagamento","D. Acesso indevido de hackers externos aos sistemas"],"correct":2,"justification_correct":"Controles inadequados na folha de pagamento permitem que colaboradores mal-intencionados incluam indivíduos inexistentes e desviem os pagamentos correspondentes. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O esquema de funcionário fantasma é tipicamente executado internamente, sem necessidade de aprovação de fornecedores, conluio com clientes ou invasão externa."},
    {"num":9,"text":"A fraude de reembolso de despesas ocorre mais frequentemente por meio de:","tag":"Reembolso de Despesas","options":["A. Submissão duplicada da mesma despesa para reembolso","B. Subdeclaração intencional de despesas incorridas","C. Documentação adequada e aprovação regular das despesas","D. Aprovações dentro dos limites e alçadas estabelecidos"],"correct":0,"justification_correct":"A submissão duplicada de comprovantes de despesa é a técnica mais comum, onde o colaborador reembolsa duas vezes a mesma despesa ou divide uma única despesa em múltiplas solicitações. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Subdeclaração, documentação adequada e aprovações dentro das alçadas não configuram fraude de reembolso."},
    {"num":10,"text":"Qual sinal de alerta comportamental pode indicar a ocorrência de apropriação indébita de ativos?","tag":"Red Flags","options":["A. Existência de controles internos robustos e auditados","B. Documentação consistente e completa das transações","C. Padrão de vida incompatível com a remuneração recebida","D. Relatórios financeiros transparentes e detalhados"],"correct":2,"justification_correct":"Riqueza ou padrão de vida evidentemente incompatíveis com a remuneração declarada são red flags comportamentais clássicos de possível apropriação indébita. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Controles robustos, documentação consistente e transparência são indicadores positivos, não sinais de alerta."},
    {"num":11,"text":"Esquemas de adulteração de cheques frequentemente envolvem a prática de:","tag":"Adulteração de Cheques","options":["A. Desvio de recursos antes do registro contábil","B. Alteração dos dados do beneficiário ou do valor do cheque","C. Postergação deliberada de depósitos bancários","D. Classificação incorreta de natureza das despesas"],"correct":1,"justification_correct":"Os perpetradores podem falsificar assinaturas, alterar beneficiários ou modificar valores em cheques emitidos para desviar recursos para si próprios. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Skimming, atraso de depósitos e classificação incorreta são esquemas distintos da adulteração de cheques."},
    {"num":12,"text":"Qual documento é mais relevante para detectar desvios de estoque?","tag":"Detecção de Estoque","options":["A. Registros de folha de pagamento","B. Contratos com fornecedores","C. Registros de estoque e resultados de contagens físicas","D. Conciliações de contas bancárias"],"correct":2,"justification_correct":"A comparação entre as contagens físicas e os registros do sistema de estoque revela discrepâncias e faltas que podem indicar desvios. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Folha de pagamento, contratos e conciliações bancárias são fontes relevantes para outros tipos de fraude, não para desvio de estoque."},
    {"num":13,"text":"Os esquemas de apropriação indébita de ativos são tipicamente perpetrados por:","tag":"Perfil do Perpetrador","options":["A. Executivos seniores e membros do conselho","B. Estruturas financeiras complexas e off-shore","C. Colaboradores individuais em nível operacional","D. Auditores externos independentes"],"correct":2,"justification_correct":"A maioria dos esquemas de apropriação de ativos é executada por colaboradores de nível operacional com acesso direto aos recursos, diferentemente da fraude contábil que tende a envolver a gestão. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Executivos e auditores tendem a estar associados a fraudes contábeis; estruturas off-shore são instrumentos de lavagem, não de apropriação direta."},
    {"num":14,"text":"Qual medida preventiva é mais eficaz para reduzir o risco de fraude na folha de pagamento?","tag":"Prevenção Folha","options":["A. Permitir sobreposições manuais no processo de aprovação","B. Auditorias periódicas e surpresa da folha de pagamento","C. Concentrar o controle da folha em um único responsável","D. Manter o acesso à folha de pagamento irrestrito"],"correct":1,"justification_correct":"Auditorias regulares e não anunciadas da folha de pagamento permitem identificar funcionários fictícios, horas infladas e demais irregularidades. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Sobreposições manuais, controle centralizado e acesso irrestrito são práticas que aumentam, não reduzem, o risco de fraude em folha."},
    {"num":15,"text":"O esquema de lapping consiste em:","tag":"Lapping","options":["A. Alteração de demonstrações financeiras para inflacionar receitas","B. Aplicar o pagamento de um cliente na conta de outro para ocultar desvios anteriores","C. Criação de fornecedores fictícios para desvio de recursos","D. Superestimação de receitas por antecipação de reconhecimento"],"correct":1,"justification_correct":"No lapping, o desvio de um recebimento é ocultado aplicando-se o pagamento subsequente de outro cliente na conta afetada, criando um ciclo contínuo de ocultação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas descrevem fraudes contábeis e de fornecedores, não o esquema específico de lapping."},
    {"num":16,"text":"O controle mais eficaz para prevenir o esquema de lapping é:","tag":"Prevenção Lapping","options":["A. Férias obrigatórias para colaboradores de área financeira","B. Faturamento automatizado por sistemas integrados","C. Segregação entre as funções de recebimento e registro contábil","D. Aprovações formais de despesas e reembolsos"],"correct":2,"justification_correct":"A segregação das funções de recebimento e lançamento contábil impede que o mesmo colaborador execute as etapas necessárias para sustentar o esquema de lapping. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Férias, faturamento automatizado e aprovações de despesas são controles complementares, mas a segregação é o mecanismo mais eficaz."},
    {"num":17,"text":"O desvio de ativos não monetários é mais frequentemente detectado por meio de:","tag":"Ativos Não Monetários","options":["A. Análise de extratos e conciliações bancárias","B. Inspeções e verificações físicas dos ativos","C. Revisão de registros de folha de pagamento","D. Análise de declarações fiscais"],"correct":1,"justification_correct":"As inspeções físicas permitem identificar ativos ausentes, danificados ou substituídos, revelando discrepâncias entre os registros e a realidade patrimonial. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Extratos bancários, folha de pagamento e declarações fiscais são fontes relevantes para outros tipos de fraude, mas não para ativos físicos não monetários."},
    {"num":18,"text":"Qual fator potencializa o risco de ocorrência de apropriação indébita de ativos?","tag":"Fatores de Risco","options":["A. Elevado nível de engajamento e moral dos colaboradores","B. Deficiências na supervisão e no monitoramento dos processos","C. Cultura organizacional de ética consolidada","D. Transparência nos relatórios e divulgações financeiras"],"correct":1,"justification_correct":"A ausência ou insuficiência de supervisão cria a oportunidade necessária para que o colaborador execute e encubra o desvio de ativos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Engajamento, cultura ética e transparência são fatores protetores que reduzem o risco de apropriação indébita."},
    {"num":19,"text":"Os esquemas de fraude com fornecedores podem envolver, entre outras práticas:","tag":"Fraude com Fornecedores","options":["A. Skimming de recebimentos antes do registro","B. Pagamento de propinas (kickbacks) em troca de contratos","C. Manipulação de dados na folha de pagamento","D. Quebras e perdas de estoque não identificadas"],"correct":1,"justification_correct":"As propinas envolvem o conluio entre colaboradores internos e fornecedores, onde o primeiro favorece o segundo em troca de pagamentos ou benefícios ilícitos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Skimming, folha de pagamento e quebras de estoque são esquemas distintos, não tipicamente associados a fraudes com fornecedores."},
    {"num":20,"text":"Qual método analítico é mais eficaz para detectar desvios de ativos?","tag":"Métodos Analíticos","options":["A. Análise de índices financeiros de rentabilidade","B. Análise de tendências em demonstrações de resultado","C. Procedimentos de conciliação entre registros e saldos reais","D. Técnicas de previsão e modelagem financeira"],"correct":2,"justification_correct":"Os procedimentos de conciliação expõem divergências entre os registros contábeis e a situação física ou financeira real, sinalizando possíveis desvios. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Análise de índices, tendências e previsões são técnicas úteis em outros contextos, mas as conciliações são mais eficazes para detectar desvios de ativos."},
    {"num":21,"text":"As perdas decorrentes de apropriação indébita de ativos, comparadas às de fraude em demonstrações financeiras, tendem a ser:","tag":"Impacto","options":["A. Maiores e de maior impacto sistêmico","B. Menores individualmente, porém mais frequentes","C. Raras e restritas a situações isoladas","D. Limitadas exclusivamente a desvios em caixa"],"correct":1,"justification_correct":"Os esquemas de apropriação de ativos são os mais frequentes entre as fraudes ocupacionais, mas geralmente envolvem valores menores por caso do que a fraude contábil. (ACFE Report to the Nations 2024)","justification_wrong":"A fraude em demonstrações financeiras causa maiores perdas individuais; a apropriação de ativos não é rara nem restrita a caixa."},
    {"num":22,"text":"Qual comportamento do colaborador pode sinalizar a prática de desvio de ativos?","tag":"Comportamento Suspeito","options":["A. Recusa sistemática em tirar férias ou afastamentos","B. Postura colaborativa e transparente com colegas","C. Comunicação aberta e proativa com a liderança","D. Cumprimento rigoroso das políticas organizacionais"],"correct":0,"justification_correct":"A recusa em tirar férias pode indicar que o colaborador teme que sua ausência resulte na descoberta do esquema que ele está sustentando. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Postura colaborativa, comunicação aberta e cumprimento de políticas são comportamentos positivos, não indicadores de fraude."},
    {"num":23,"text":"Em investigações de apropriação indébita de ativos, qual categoria de ativo deve ser priorizada pelo examinador?","tag":"Prioridade Investigativa","options":["A. Bens do ativo imobilizado de longa vida útil","B. Ativos de alta liquidez como caixa e equivalentes","C. Ativos intangíveis como patentes e marcas","D. Ágio e intangíveis reconhecidos em combinações de negócios"],"correct":1,"justification_correct":"Ativos de alta liquidez são os mais vulneráveis ao desvio imediato e de difícil rastreamento, devendo ser priorizados na investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Imobilizado, intangíveis e ágio são ativos de menor liquidez e menor vulnerabilidade a desvios imediatos."},
    {"num":24,"text":"Qual controle interno é mais eficaz para prevenir o desvio de estoques?","tag":"Controle de Estoque","options":["A. Documentação limitada para simplificar os processos","B. Sistema de inventário perpétuo com rastreamento contínuo","C. Supervisão informal baseada em confiança pessoal","D. Aprovações verbais para movimentação de itens"],"correct":1,"justification_correct":"Sistemas de inventário perpétuo fornecem rastreamento em tempo real das entradas e saídas, permitindo identificar discrepâncias imediatamente. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Documentação limitada, supervisão informal e aprovações verbais são práticas que aumentam a vulnerabilidade ao desvio de estoques."},
    {"num":25,"text":"O fator mais eficaz para inibir a prática de apropriação indébita de ativos é:","tag":"Dissuasão","options":["A. Aplicação de penalidades severas após a descoberta","B. Combinação de cultura ética com controles internos robustos","C. Aumento da carga de trabalho dos colaboradores","D. Redução de benefícios como forma de pressão"],"correct":1,"justification_correct":"A integração de uma cultura ética com controles efetivos atua sobre os três vértices do Triângulo da Fraude — reduzindo pressão, oportunidade e racionalização simultaneamente. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Penalidades tardias, sobrecarga de trabalho e redução de benefícios são medidas menos eficazes e potencialmente contraproducentes."},
]

# ── Q126-150: Corrupção e Suborno ─────────────────────────────────────────────
q126_150 = [
    {"num":26,"text":"A corrupção, no contexto da fraude ocupacional, é definida como:","tag":"Corrupção","options":["A. Desvio físico de ativos patrimoniais da organização","B. Abuso de poder ou autoridade delegada para obtenção de vantagem indevida","C. Distorção intencional de demonstrações financeiras","D. Deficiências nos mecanismos de governança corporativa"],"correct":1,"justification_correct":"A corrupção envolve o exercício indevido de autoridade ou poder para obter benefícios pessoais ou para terceiros, em detrimento dos interesses da organização ou do público. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Desvio de ativos é apropriação indébita; distorção de demonstrações é fraude contábil; deficiências de governança são fatores de risco, não a definição de corrupção."},
    {"num":27,"text":"Qual das seguintes modalidades representa uma forma comum de corrupção ocupacional?","tag":"Modalidades de Corrupção","options":["A. Skimming de recebimentos antes do registro","B. Fraude nos dados da folha de pagamento","C. Pagamento ou recebimento de suborno","D. Desvio de itens de estoque"],"correct":2,"justification_correct":"O suborno é o esquema central de corrupção, envolvendo o pagamento ou recebimento de valor para influenciar decisões em benefício do corruptor. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Skimming, fraude em folha e desvio de estoque são categorias de apropriação indébita de ativos, não de corrupção."},
    {"num":28,"text":"O suborno (bribery) é caracterizado, em sua essência, como:","tag":"Suborno","options":["A. Roubo de ativos sem consentimento do titular","B. Troca de valor ou benefício para influenciar decisão ou conduta","C. Distorção de registros financeiros para ocultar resultados","D. Ocultação de ativos em estruturas off-shore"],"correct":1,"justification_correct":"O suborno consiste na oferta ou recebimento de vantagem — monetária ou não — para influenciar a conduta de um agente em benefício do corruptor. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Roubo sem consentimento é furto; distorção de registros é fraude contábil; ocultação off-shore é lavagem de dinheiro."},
    {"num":29,"text":"As propinas (kickbacks) se distinguem do suborno convencional porque as propinas são pagas:","tag":"Propinas vs Suborno","options":["A. Sem envolvimento de qualquer valor monetário","B. De forma legal em determinadas jurisdições","C. Após a realização da transação comercial objeto do benefício","D. Exclusivamente no âmbito de contratos governamentais"],"correct":2,"justification_correct":"As propinas são pagas retroativamente após a adjudicação de contratos ou conclusão de transações, como recompensa pela decisão favorável já tomada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Propinas envolvem valor monetário, não são legais e ocorrem tanto no setor público quanto privado."},
    {"num":30,"text":"Qual função organizacional apresenta maior vulnerabilidade a esquemas de suborno?","tag":"Funções de Risco","options":["A. Operadores de caixa e repositores de estoque","B. Agentes de compras e gestores de contratos","C. Equipes de armazenagem e logística","D. Assistentes administrativos e secretários"],"correct":1,"justification_correct":"Profissionais de compras e gestão de contratos exercem poder discricionário sobre a seleção de fornecedores e adjudicação de contratos, tornando-se alvos preferenciais de esquemas de suborno. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Operadores de caixa, armazenagem e assistentes têm menor poder decisório sobre contratações, sendo menos vulneráveis a esse tipo específico de corrupção."},
    {"num":31,"text":"O conflito de interesses ocorre quando:","tag":"Conflito de Interesses","options":["A. Um colaborador subtrai ativos físicos da organização","B. Interesses pessoais interferem ou comprometem os deveres profissionais","C. Demonstrações financeiras apresentam distorções materiais","D. A gestão anula controles internos estabelecidos"],"correct":1,"justification_correct":"O conflito de interesses surge quando interesses privados do colaborador — financeiros, familiares ou pessoais — influenciam ou podem influenciar suas decisões profissionais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Subtração de ativos é apropriação; distorção de demonstrações é fraude contábil; anulação de controles é management override."},
    {"num":32,"text":"Qual situação concreta melhor ilustra um conflito de interesses?","tag":"Exemplos","options":["A. Colaborador recebendo remuneração dentro do pacote contratual","B. Gestor adjudicando contratos à empresa de familiar sem divulgação","C. Fornecedor emitindo faturas conforme contrato vigente","D. Auditor realizando revisão de conformidade de contas"],"correct":1,"justification_correct":"A adjudicação de contratos a empresa de familiar sem a devida divulgação e gestão do conflito é um caso clássico de conflito de interesses. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Remuneração contratual, faturamento regular e auditorias de conformidade são práticas legítimas sem caráter de conflito."},
    {"num":33,"text":"As gratificações ilegais (illegal gratuities) se distinguem do suborno porque as gratificações são concedidas:","tag":"Gratificações Ilegais","options":["A. Antes da tomada de decisão para influenciá-la","B. Após a decisão já ter sido tomada, como recompensa","C. Dentro dos limites legais em qualquer circunstância","D. Sem envolvimento de qualquer contrapartida de valor"],"correct":1,"justification_correct":"As gratificações ilegais recompensam uma ação já realizada, diferentemente do suborno que é pago previamente para influenciar uma decisão futura. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Pagamento prévio para influenciar é suborno; gratificações ilegais não são legais e envolvem contrapartida de valor."},
    {"num":34,"text":"Qual sinal de alerta pode indicar a existência de esquemas de corrupção?","tag":"Red Flags Corrupção","options":["A. Processo de licitação competitivo com múltiplos participantes","B. Seleção de fornecedores baseada em critérios objetivos documentados","C. Favorecimento sistemático e injustificado de determinado fornecedor","D. Processo de compras transparente e auditado regularmente"],"correct":2,"justification_correct":"O favorecimento recorrente e sem justificativa técnica de um fornecedor específico pode indicar a existência de suborno ou propina influenciando as decisões de contratação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Processo competitivo, critérios objetivos e auditoria regular são indicadores de integridade no processo de compras."},
    {"num":35,"text":"O conluio em licitações (bid rigging) tipicamente envolve:","tag":"Bid Rigging","options":["A. Faturamento excessivo por parte do fornecedor vencedor","B. Acordo entre concorrentes para manipular o resultado do processo licitatório","C. Desvio de caixa antes do registro nos sistemas","D. Manipulação de dados na folha de pagamento"],"correct":1,"justification_correct":"No bid rigging, concorrentes conspiram entre si para pré-determinar o vencedor e o preço da licitação, eliminando a competitividade e causando dano ao comprador. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Faturamento excessivo, skimming e fraude em folha são esquemas distintos do conluio em licitações."},
    {"num":36,"text":"A extorsão econômica, no contexto da corrupção ocupacional, ocorre quando:","tag":"Extorsão","options":["A. Fornecedores inflam preços contratuais acima do mercado","B. Colaboradores desviam ativos físicos da organização","C. Colaboradores exigem pagamento de terceiros sob coerção ou ameaça","D. Clientes recusam o pagamento de obrigações contratuais"],"correct":2,"justification_correct":"A extorsão econômica envolve o uso de autoridade ou poder de coerção para exigir pagamentos ou benefícios como condição para a prática ou omissão de determinado ato. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Inflação de preços, desvio de ativos e inadimplência de clientes são situações distintas da extorsão econômica."},
    {"num":37,"text":"Qual fator mais intensifica o risco de corrupção em uma organização?","tag":"Fatores de Risco","options":["A. Existência de auditoria interna estruturada e independente","B. Políticas anticorrupção claras e amplamente divulgadas","C. Ampla discricionariedade combinada com supervisão insuficiente","D. Liderança comprometida com padrões éticos elevados"],"correct":2,"justification_correct":"A combinação de poder discricionário elevado com ausência de supervisão adequada cria o ambiente propício para a corrupção prosperar. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditoria, políticas claras e liderança ética são fatores que reduzem, não ampliam, o risco de corrupção."},
    {"num":38,"text":"Qual legislação aborda especificamente o suborno de funcionários de governos estrangeiros?","tag":"Legislação Anticorrupção","options":["A. Lei Sarbanes-Oxley (SOX)","B. Foreign Corrupt Practices Act (FCPA)","C. Lei RICO (Racketeer Influenced and Corrupt Organizations)","D. USA PATRIOT Act"],"correct":1,"justification_correct":"A FCPA proíbe empresas americanas e seus agentes de subornar funcionários de governos estrangeiros para obter ou manter negócios. (CFE Fraud Examiners Manual 2024)","justification_wrong":"SOX trata de governança e relatórios financeiros; RICO abrange crime organizado; PATRIOT Act foca em terrorismo e lavagem de dinheiro."},
    {"num":39,"text":"Qual prática constitui violação direta da Foreign Corrupt Practices Act (FCPA)?","tag":"FCPA","options":["A. Pagamentos de facilitação expressamente permitidos pela lei","B. Manutenção de registros contábeis precisos e completos","C. Pagamento a funcionário público estrangeiro para obtenção de contratos","D. Adoção de práticas de marketing ético e transparente"],"correct":2,"justification_correct":"A FCPA proíbe explicitamente o pagamento de qualquer vantagem a autoridades estrangeiras para obter ou reter negócios ou vantagens impróprias. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Pagamentos de facilitação têm tratamento específico na lei; registros precisos e marketing ético são práticas conformes."},
    {"num":40,"text":"Qual prática contábil é essencial para suportar a conformidade com legislações anticorrupção?","tag":"Conformidade","options":["A. Manutenção de contas e transações fora dos registros oficiais","B. Escrituração contábil precisa e completa de todas as transações","C. Realização preferencial de transações em espécie","D. Limitação das divulgações financeiras ao mínimo exigido"],"correct":1,"justification_correct":"Registros contábeis precisos e transparentes são exigidos pela FCPA e demais legislações anticorrupção, pois dificultam a ocultação de pagamentos ilícitos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Contas off-book, transações em espécie e divulgações mínimas são práticas que facilitam a ocultação de subornos."},
    {"num":41,"text":"O suborno comercial se distingue do suborno no setor público porque o suborno comercial:","tag":"Suborno Comercial","options":["A. É sempre legalmente permitido","B. Ocorre exclusivamente entre partes do setor privado","C. Envolve necessariamente funcionários de governo","D. Não produz impacto financeiro mensurável"],"correct":1,"justification_correct":"O suborno comercial ocorre em transações entre partes privadas, sem envolvimento de agentes públicos — diferentemente do suborno a funcionários governamentais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O suborno comercial não é legal, não envolve funcionários de governo e produz impactos financeiros reais."},
    {"num":42,"text":"Qual esquema envolve o pagamento de faturas infladas em troca de benefício pessoal ao responsável pela aprovação?","tag":"Esquemas","options":["A. Skimming de recebimentos","B. Conluio em licitações","C. Propinas (kickbacks) vinculadas a contratos","D. Lapping de recebíveis"],"correct":2,"justification_correct":"As propinas frequentemente se manifestam por meio de faturamento excessivo — o fornecedor infla os valores e parte do excesso retorna ao funcionário que aprovou a transação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Skimming, bid rigging e lapping são esquemas distintos, sem a estrutura de retorno financeiro ao aprovador característica das propinas."},
    {"num":43,"text":"Qual medida preventiva é mais eficaz para reduzir o risco de corrupção organizacional?","tag":"Prevenção","options":["A. Supervisão informal baseada em relações de confiança","B. Tom ético no topo (tone at the top) com exemplo da liderança","C. Documentação mínima para agilizar processos","D. Preferência por transações em espécie para maior flexibilidade"],"correct":1,"justification_correct":"O comportamento ético da alta liderança estabelece os padrões culturais que permeiam toda a organização, sendo o fator preventivo mais influente contra a corrupção. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Supervisão informal, documentação mínima e transações em espécie são práticas que aumentam a vulnerabilidade à corrupção."},
    {"num":44,"text":"Qual sinal de alerta pode indicar a existência de conluio em licitações?","tag":"Red Flags Licitação","options":["A. Grande número de licitantes participando do processo","B. Padrões de preços incomumente similares entre concorrentes","C. Processo de avaliação transparente e documentado","D. Descontos competitivos oferecidos pelos licitantes"],"correct":1,"justification_correct":"Propostas com preços excessivamente similares ou padrões atípicos de precificação entre concorrentes podem indicar conluio prévio entre os licitantes. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Múltiplos licitantes, avaliação transparente e descontos competitivos são indicadores de processo licitatório íntegro."},
    {"num":45,"text":"Os esquemas de corrupção frequentemente requerem a existência de:","tag":"Características","options":["A. Camadas complexas de ocultação para disfarçar os pagamentos","B. Ausência total de documentação nas transações envolvidas","C. Perpetrador único sem qualquer conluio externo","D. Detecção imediata pelos mecanismos de controle vigentes"],"correct":0,"justification_correct":"A corrupção tipicamente envolve estruturas elaboradas de dissimulação — contratos fictícios, consultorias de fachada, pagamentos indiretos — para ocultar os fluxos ilícitos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Ausência total de documentação tornaria a ocultação mais difícil; a corrupção frequentemente envolve conluio e não é detectada imediatamente."},
    {"num":46,"text":"Qual setor apresenta maior vulnerabilidade a esquemas de corrupção?","tag":"Setores Vulneráveis","options":["A. Comércio varejista","B. Contratação e licitação governamental","C. Setor educacional","D. Prestação de serviços de saúde"],"correct":1,"justification_correct":"A contratação governamental envolve grandes volumes financeiros e poder discricionário elevado, criando ambiente favorável à corrupção. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Os demais setores apresentam vulnerabilidades específicas, mas o setor de contratação governamental concentra maior exposição à corrupção sistemática."},
    {"num":47,"text":"Em investigações de corrupção, o examinador de fraude deve priorizar a análise de:","tag":"Investigação","options":["A. Exclusivamente as demonstrações financeiras consolidadas","B. Relacionamentos e transações com fornecedores e terceiros","C. Registros de folha de pagamento e remuneração","D. Contagens físicas de estoque e ativos imobilizados"],"correct":1,"justification_correct":"A corrupção tipicamente se manifesta por meio de relacionamentos comerciais com fornecedores, parceiros e terceiros, tornando essa análise prioritária. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Demonstrações financeiras, folha de pagamento e estoque são fontes complementares, mas os relacionamentos com terceiros são o foco central em investigações de corrupção."},
    {"num":48,"text":"Qual controle interno é mais eficaz para detectar esquemas de suborno em andamento?","tag":"Controles Detectivos","options":["A. Auditorias surpresa e não anunciadas","B. Verificações físicas periódicas de inventário","C. Conciliações de folha de pagamento","D. Contagens regulares de caixa"],"correct":0,"justification_correct":"Revisões não anunciadas interrompem e expõem práticas corruptas em andamento, pois os perpetradores não têm tempo para encobrir as evidências. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Verificações de inventário, conciliações de folha e contagens de caixa são controles voltados para outros tipos de fraude."},
    {"num":49,"text":"Os programas de denúncia (whistleblower programs) são eficazes no combate à corrupção principalmente porque:","tag":"Denúncias","options":["A. Substituem integralmente os procedimentos de auditoria","B. Eliminam completamente a ocorrência de fraudes","C. Criam canais seguros que incentivam o relato sem receio de retaliação","D. Reduzem a necessidade de documentação formal"],"correct":2,"justification_correct":"Canais de denúncia seguros e com proteção ao denunciante aumentam a probabilidade de detecção precoce, pois colaboradores que testemunham irregularidades têm incentivo para reportá-las. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Programas de denúncia complementam, mas não substituem auditorias; não eliminam a fraude nem reduzem necessidades de documentação."},
    {"num":50,"text":"A estratégia mais eficaz e sustentável de combate à corrupção organizacional integra:","tag":"Estratégia Anticorrupção","options":["A. Exclusivamente medidas punitivas e sanções severas","B. Apenas conformidade com requisitos legais mínimos","C. Controles robustos, cultura ética e aplicação consistente das normas","D. Apenas monitoramento financeiro de transações suspeitas"],"correct":2,"justification_correct":"A prevenção sustentável da corrupção requer a integração de controles preventivos e detectivos, cultura organizacional ética e aplicação consistente das normas e consequências. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Punições isoladas, conformidade mínima e monitoramento exclusivamente financeiro são abordagens parciais insuficientes para combater a corrupção de forma sustentável."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

# Injeta os dois blocos no domínio Financial Transactions
dir1 = Path("static/quizzes/cfe/financial_transactions")
dir1.mkdir(parents=True, exist_ok=True)

# Bloco 1: Q101-125
num1 = get_next_num(dir1)
out1 = {"cert_id":"cfe","domain_id":"financial_transactions","quiz_num":num1,"domain_name":"Financial Transactions & Fraud Schemes","cert_name":"CFE / ACFE","lang":"pt","questions":q101_125}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(q101_125)} questoes (Apropr. Indebita) salvas em {path1}")

# Bloco 2: Q126-150
num2 = get_next_num(dir1)
out2 = {"cert_id":"cfe","domain_id":"financial_transactions","quiz_num":num2,"domain_name":"Financial Transactions & Fraud Schemes","cert_name":"CFE / ACFE","lang":"pt","questions":q126_150}
path2 = dir1 / f"quiz_{num2:03d}_pt.json"
path2.write_text(json.dumps(out2, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(q126_150)} questoes (Corrupcao) salvas em {path2}")
