#!/usr/bin/env python3
"""
CFE BATCH 1 - Introdução ao Exame de Fraude
50 questões adaptadas de material bibliográfico
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"No contexto da investigação de fraudes, qual das seguintes afirmações melhor descreve o conceito de fraude?","tag":"Conceitos Fundamentais","options":["A. Erro contábil decorrente de falha no processo de conciliação","B. Ato deliberado de enganar terceiros visando obter vantagem indevida","C. Qualquer prejuízo financeiro registrado nas demonstrações contábeis","D. Ausência de controles internos adequados nos processos organizacionais"],"correct":1,"justification_correct":"A fraude pressupõe dolo — intenção deliberada de enganar para obter benefício não autorizado. Sem esse elemento volitivo, o ato configura erro ou negligência, não fraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Erros contábeis, prejuízos financeiros e deficiências de controle não constituem fraude por si sós, pois ausente o elemento da intenção dolosa."},
    {"num":2,"text":"Dentre os elementos constitutivos da fraude, qual é considerado indispensável para sua caracterização jurídica e profissional?","tag":"Elementos da Fraude","options":["A. Ocorrência de prejuízo financeiro mensurável","B. Presença de dolo ou intenção deliberada","C. Existência de controles internos deficientes","D. Envolvimento de membros da alta administração"],"correct":1,"justification_correct":"A intenção dolosa é o elemento que distingue a fraude do erro ou da negligência. Sem dolo, não há fraude, independentemente do prejuízo causado. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Prejuízo financeiro pode ocorrer sem fraude; controles deficientes criam oportunidade mas não configuram fraude; o envolvimento da gestão não é requisito."},
    {"num":3,"text":"O modelo teórico denominado Triângulo da Fraude, amplamente utilizado na análise de riscos de fraude ocupacional, é composto por:","tag":"Triângulo da Fraude","options":["A. Pressão, Oportunidade e Racionalização","B. Motivo, Prejuízo e Evidência","C. Oportunidade, Conluio e Ocultação","D. Intenção, Controle e Detecção"],"correct":0,"justification_correct":"O Triângulo da Fraude, desenvolvido por Donald Cressey, estabelece que a fraude ocorre quando coexistem pressão, oportunidade e racionalização. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas combinam elementos reais mas não representam o modelo teórico conforme definido pela ACFE."},
    {"num":4,"text":"Sob a perspectiva do Triângulo da Fraude, qual fator representa a condição ambiental que mais contribui para a ocorrência de fraude?","tag":"Oportunidade","options":["A. Insatisfação do colaborador com a remuneração","B. Deficiências nos controles internos da organização","C. Endividamento pessoal elevado do perpetrador","D. Ausência de programas formais de capacitação"],"correct":1,"justification_correct":"Controles internos deficientes ou inexistentes criam a oportunidade necessária para que a fraude seja perpetrada, representando o fator ambiental mais relevante. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Insatisfação e endividamento são elementos de pressão; ausência de capacitação é fator organizacional, não o elemento oportunidade do triângulo."},
    {"num":5,"text":"A categoria de fraude conhecida como apropriação indébita de ativos abrange, entre outras modalidades:","tag":"Categorias de Fraude","options":["A. Manipulação de demonstrações financeiras para inflacionar resultados","B. Desvio e uso indevido dos recursos patrimoniais da organização","C. Pagamento de propinas a agentes públicos","D. Operações com informações privilegiadas no mercado de capitais"],"correct":1,"justification_correct":"A apropriação indébita de ativos compreende o desvio de numerário, furto de estoques, fraudes em folha de pagamento e demais esquemas de roubo dos recursos organizacionais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Manipulação de demonstrações é fraude contábil; propinas configuram corrupção; uso de informação privilegiada é crime de mercado de capitais."},
    {"num":6,"text":"Considerando a frequência de ocorrência entre as categorias de fraude ocupacional classificadas pela ACFE, qual delas é registrada com maior incidência?","tag":"Estatísticas de Fraude","options":["A. Fraude em demonstrações financeiras","B. Fraude cibernética e invasão de sistemas","C. Apropriação indébita de ativos","D. Corrupção e pagamento de subornos"],"correct":2,"justification_correct":"A apropriação indébita de ativos é a categoria mais frequente de fraude ocupacional, embora as perdas individuais tendam a ser menores que nas demais categorias. (ACFE Report to the Nations 2024)","justification_wrong":"A fraude em demonstrações financeiras é menos frequente, porém causa maiores perdas; corrupção e fraude cibernética têm incidência inferior à apropriação de ativos."},
    {"num":7,"text":"A fraude em demonstrações financeiras é caracterizada, em sua essência, como:","tag":"Fraude Contábil","options":["A. Desvio de ativos físicos do patrimônio organizacional","B. Distorção dolosa de informações financeiras para induzir terceiros a erro","C. Esquemas de propinas envolvendo fornecedores e prestadores de serviço","D. Evasão fiscal por subdeclaração de receitas"],"correct":1,"justification_correct":"A fraude em demonstrações financeiras consiste na distorção intencional das informações contábeis com o objetivo de enganar investidores, credores e demais usuários. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Desvio de ativos é apropriação indébita; propinas configuram corrupção; evasão fiscal é crime tributário distinto."},
    {"num":8,"text":"Embora menos frequente que outras categorias, qual modalidade de fraude ocupacional tende a gerar as maiores perdas financeiras por caso?","tag":"Impacto Financeiro","options":["A. Apropriação indébita de ativos","B. Corrupção","C. Fraude cibernética","D. Fraude em demonstrações financeiras"],"correct":3,"justification_correct":"A fraude em demonstrações financeiras, apesar de menor incidência, produz as maiores perdas medianas por caso, podendo impactar significativamente o valor de mercado da organização. (ACFE Report to the Nations 2024)","justification_wrong":"As demais categorias são mais frequentes, mas registram perdas individuais inferiores à fraude contábil."},
    {"num":9,"text":"Além das perdas financeiras diretas, a fraude organizacional impacta a entidade principalmente por meio de:","tag":"Impacto da Fraude","options":["A. Redução exclusiva da produtividade operacional","B. Aumento dos custos e deterioração da reputação institucional","C. Melhoria da percepção de riscos pelos stakeholders","D. Incremento da supervisão regulatória como efeito positivo"],"correct":1,"justification_correct":"A fraude acarreta prejuízos financeiros, consequências legais, danos reputacionais e erosão da confiança das partes interessadas, comprometendo a continuidade do negócio. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Os demais efeitos são parcialmente verdadeiros mas não representam o impacto primário e abrangente da fraude nas organizações."},
    {"num":10,"text":"No contexto da análise de impacto da fraude, qual dos seguintes representa um custo indireto típico?","tag":"Custos da Fraude","options":["A. Valores monetários diretamente subtraídos da organização","B. Honorários de advogados e consultores externos","C. Deterioração do clima organizacional e da moral dos colaboradores","D. Pagamentos de indenização determinados judicialmente"],"correct":2,"justification_correct":"Os custos indiretos da fraude incluem a queda da moral, perda de produtividade, danos à reputação e ruptura de relacionamentos, sendo mais difíceis de quantificar que os custos diretos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Valores subtraídos, honorários advocatícios e indenizações são custos diretos e mensuráveis da fraude."},
    {"num":11,"text":"O conluio entre perpetradores afeta primordialmente qual aspecto do sistema de prevenção à fraude?","tag":"Conluio","options":["A. Qualidade da documentação contábil","B. Efetividade dos controles internos","C. Abrangência das auditorias externas","D. Precisão das avaliações de risco"],"correct":1,"justification_correct":"O conluio permite que dois ou mais indivíduos contornem os controles internos, anulando mecanismos de segregação de funções e demais salvaguardas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Embora o conluio possa afetar os demais aspectos, seu impacto primário recai sobre a efetividade dos controles internos."},
    {"num":12,"text":"Qual afirmação melhor descreve a vulnerabilidade setorial à fraude ocupacional?","tag":"Vulnerabilidade Setorial","options":["A. O setor manufatureiro apresenta maior exposição relativa","B. Instituições financeiras são as mais vulneráveis","C. O setor de saúde concentra o maior número de casos","D. A fraude pode ocorrer em qualquer setor, independentemente do segmento"],"correct":3,"justification_correct":"A fraude ocupacional não tem fronteiras setoriais — pode ocorrer em qualquer organização, independentemente do porte, segmento ou localização geográfica. (ACFE Report to the Nations 2024)","justification_wrong":"Embora alguns setores apresentem vulnerabilidades específicas, nenhum é imune à fraude ocupacional."},
    {"num":13,"text":"O risco de fraude organizacional tende a se elevar quando:","tag":"Fatores de Risco","options":["A. Os colaboradores recebem treinamento ético regular","B. A organização possui cultura de integridade consolidada","C. A supervisão gerencial apresenta lacunas significativas","D. Os controles são automatizados e monitorados continuamente"],"correct":2,"justification_correct":"A supervisão gerencial deficiente amplia tanto a oportunidade quanto a racionalização para a fraude, favorecendo sua ocorrência e persistência. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Treinamento, cultura ética e controles automatizados são fatores mitigadores do risco de fraude."},
    {"num":14,"text":"A fraude ocupacional, conforme definição da ACFE, é caracterizada como aquela perpetrada:","tag":"Fraude Ocupacional","options":["A. Por agentes externos mediante invasão de sistemas","B. Exclusivamente por fornecedores e parceiros comerciais","C. Por colaboradores em detrimento da própria organização empregadora","D. Por clientes contra a empresa prestadora de serviços"],"correct":2,"justification_correct":"A fraude ocupacional é definida como o uso do cargo para enriquecimento pessoal mediante o desvio intencional dos recursos ou ativos do empregador. (ACFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas descrevem fraudes externas, não ocupacionais conforme a classificação da ACFE."},
    {"num":15,"text":"Entre os fatores motivacionais do Triângulo da Fraude, qual apresenta maior recorrência como pressão nos casos documentados?","tag":"Pressão","options":["A. Ganância desvinculada de necessidade concreta","B. Pressão financeira decorrente de endividamento ou demandas de estilo de vida","C. Mera disponibilidade de oportunidade","D. Desejo de retaliação contra a organização"],"correct":1,"justification_correct":"A pressão financeira — dívidas, padrão de vida incompatível com a renda ou perdas em apostas — é o motivador mais frequentemente identificado nos casos de fraude ocupacional. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Ganância, oportunidade e retaliação podem motivar fraudes, mas a pressão financeira é o fator predominante nos estudos da ACFE."},
    {"num":16,"text":"A efetividade dos mecanismos de detecção de fraude é maximizada quando:","tag":"Detecção de Fraude","options":["A. A organização depende exclusivamente de auditorias externas periódicas","B. Existem controles robustos integrados a programas de conscientização","C. A gestão adota postura permissiva em relação a irregularidades menores","D. Os controles não são formalizados em documentação"],"correct":1,"justification_correct":"A combinação de controles preventivos e detectivos com programas de conscientização cria um ambiente desfavorável à fraude e melhora significativamente a capacidade de detecção. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Dependência exclusiva de auditoria externa, permissividade gerencial e ausência de documentação reduzem a efetividade da detecção."},
    {"num":17,"text":"No contexto dos sinais de alerta (red flags), qual dos seguintes representa um indicador de natureza comportamental?","tag":"Red Flags","options":["A. Ausência de documentos de suporte em transações","B. Lançamentos contábeis atípicos fora do padrão histórico","C. Padrão de vida incompatível com a remuneração declarada","D. Ocorrência de pagamentos duplicados a fornecedores"],"correct":2,"justification_correct":"O padrão de vida superior à renda é um red flag comportamental clássico, indicando possível enriquecimento ilícito — embora não constitua prova de fraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Documentos ausentes, lançamentos atípicos e pagamentos duplicados são red flags operacionais ou contábeis, não comportamentais."},
    {"num":18,"text":"A correlação entre duração do esquema fraudulento e magnitude das perdas demonstra que:","tag":"Duração e Perdas","options":["A. Perpetradores novatos causam perdas maiores por inexperiência","B. Fraudes de maior duração tendem a acumular perdas mais significativas","C. A automação dos controles prolonga a detecção indefinidamente","D. A detecção imediata não reduz o montante das perdas"],"correct":1,"justification_correct":"Fraudes não detectadas por longos períodos acumulam perdas progressivamente maiores, evidenciando a importância de mecanismos de detecção precoce. (ACFE Report to the Nations 2024)","justification_wrong":"As demais alternativas contradizem os dados empíricos sobre a relação entre duração das fraudes e magnitude das perdas."},
    {"num":19,"text":"O propósito central de um exame de fraude, distinguindo-o de outras formas de auditoria, é:","tag":"Exame de Fraude","options":["A. Impor sanções disciplinares aos responsáveis","B. Evitar litígios e ações judiciais futuras","C. Apurar com base em evidências se houve ou não ocorrência de fraude","D. Substituir as funções desempenhadas por auditores independentes"],"correct":2,"justification_correct":"O exame de fraude tem como objetivo estabelecer fatos mediante coleta e análise de evidências, determinando se a fraude ocorreu — sem emitir juízo de culpabilidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Sanções, prevenção de litígios e substituição de auditores não são o objetivo primário do exame de fraude."},
    {"num":20,"text":"A avaliação de risco de fraude representa, para as organizações, uma ferramenta que permite principalmente:","tag":"Avaliação de Risco","options":["A. Erradicar completamente a ocorrência de fraudes","B. Mapear e priorizar vulnerabilidades nos processos e controles","C. Substituir os procedimentos de auditoria interna","D. Reduzir os custos com a força de trabalho"],"correct":1,"justification_correct":"A avaliação de risco de fraude permite identificar onde e como a fraude tem maior probabilidade de ocorrer, direcionando os esforços de prevenção e controle. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Nenhuma ferramenta erradica completamente a fraude; a avaliação de risco não substitui auditorias nem reduz custos de pessoal."},
    {"num":21,"text":"Qual das alternativas a seguir NÃO constitui uma das três categorias centrais de fraude ocupacional conforme a taxonomia da ACFE?","tag":"Taxonomia ACFE","options":["A. Apropriação indébita de ativos","B. Corrupção","C. Fraude em demonstrações financeiras","D. Lavagem de dinheiro"],"correct":3,"justification_correct":"A lavagem de dinheiro é um crime autônomo, frequentemente associado à fraude, mas não integra as três categorias centrais do modelo da ACFE. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Apropriação de ativos, corrupção e fraude em demonstrações financeiras são as três categorias nucleares da taxonomia da ACFE."},
    {"num":22,"text":"No Triângulo da Fraude, a racionalização cumpre a função de:","tag":"Racionalização","options":["A. Garantir ao perpetrador a impunidade legal","B. Permitir a justificação psicológica de condutas antiéticas","C. Elevar os lucros da organização envolvida","D. Fortalecer os mecanismos de controle interno"],"correct":1,"justification_correct":"A racionalização é o processo cognitivo pelo qual o perpetrador constrói uma justificativa que torna a conduta fraudulenta aceitável em sua própria consciência. (CFE Fraud Examiners Manual 2024)","justification_wrong":"A racionalização não opera no plano jurídico nem organizacional — é um mecanismo psicológico interno do perpetrador."},
    {"num":23,"text":"Segundo as pesquisas da ACFE sobre métodos de detecção de fraude, qual canal apresenta maior efetividade na identificação de casos?","tag":"Detecção","options":["A. Auditorias externas de demonstrações financeiras","B. Investigações conduzidas por autoridades policiais","C. Denúncias espontâneas de colaboradores e terceiros","D. Revisões periódicas conduzidas pela alta gestão"],"correct":2,"justification_correct":"As denúncias (tips) são consistentemente o método mais eficaz de detecção de fraude, respondendo por mais de 40% dos casos identificados conforme o ACFE Report to the Nations. (ACFE 2024)","justification_wrong":"Auditorias externas, investigações policiais e revisões gerenciais são relevantes, mas registram menor efetividade que as denúncias."},
    {"num":24,"text":"A responsabilidade primária pela prevenção da fraude organizacional recai sobre:","tag":"Responsabilidade","options":["A. Auditores externos independentes","B. Alta gestão e conselho de administração","C. Órgãos reguladores e supervisores","D. Clientes e parceiros comerciais"],"correct":1,"justification_correct":"A gestão é a responsável primária por estabelecer controles adequados, promover a cultura ética e criar o ambiente organizacional que inibe a ocorrência de fraudes. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditores externos, reguladores e terceiros têm papéis complementares, mas a responsabilidade primária pela prevenção é da gestão."},
    {"num":25,"text":"Qual afirmação representa de forma mais precisa a natureza da fraude organizacional?","tag":"Natureza da Fraude","options":["A. Envolve invariavelmente perdas de grande magnitude","B. Requer necessariamente a participação da alta administração","C. Pode ser perpetrada em qualquer nível hierárquico da organização","D. É facilmente identificada pelos mecanismos de controle convencionais"],"correct":2,"justification_correct":"A fraude pode ser cometida por colaboradores em qualquer nível hierárquico — da linha operacional à alta gestão — e não está restrita a perfis ou cargos específicos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As perdas variam, o envolvimento da gestão não é requisito e a fraude frequentemente evade os controles convencionais."},
    {"num":26,"text":"A responsabilidade fundamental do Examinador de Fraude Certificado (CFE) no exercício de suas funções investigativas é:","tag":"Papel do CFE","options":["A. Processar judicialmente os suspeitos identificados","B. Apurar a ocorrência de fraude mediante coleta e análise de evidências","C. Aplicar medidas disciplinares internas aos envolvidos","D. Exercer as funções de auditoria independente"],"correct":1,"justification_correct":"O CFE tem como responsabilidade central determinar se houve fraude por meio de evidências suficientes — a responsabilização legal é função do sistema judicial, não do examinador. (ACFE Code of Professional Standards)","justification_wrong":"Processamento judicial, disciplina e auditoria independente são funções distintas, não atribuições primárias do CFE."},
    {"num":27,"text":"Qual postura metodológica deve nortear o examinador de fraude no início de uma investigação?","tag":"Metodologia","options":["A. Presumir a responsabilidade da gestão pelo esquema investigado","B. Adotar a culpabilidade como premissa até prova em contrário","C. Preservar a objetividade e a presunção de inocência","D. Priorizar a obtenção de resultados disciplinares"],"correct":2,"justification_correct":"Os padrões profissionais da ACFE exigem que o CFE mantenha objetividade e presunção de inocência, conduzindo a investigação com base exclusivamente nas evidências coletadas. (ACFE Code of Professional Standards)","justification_wrong":"Presumir culpa ou responsabilidade compromete a imparcialidade e a validade das conclusões investigativas."},
    {"num":28,"text":"O que diferencia fundamentalmente a atuação de um examinador de fraude de um auditor convencional?","tag":"CFE vs Auditor","options":["A. Revisão de controles internos e processos operacionais","B. Realização de testes de conformidade de rotina","C. Condução de investigações direcionadas com base em alegações específicas","D. Avaliação anual de demonstrações financeiras"],"correct":2,"justification_correct":"Enquanto auditores realizam revisões periódicas e sistemáticas, examinadores de fraude conduzem investigações específicas, direcionadas por alegações ou indícios de irregularidades. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Revisão de controles, testes de conformidade e avaliação de demonstrações são atividades típicas de auditoria, não exclusivas do exame de fraude."},
    {"num":29,"text":"Entre as competências essenciais para o exercício eficaz do exame de fraude, qual apresenta maior criticidade?","tag":"Competências do CFE","options":["A. Domínio avançado de legislação tributária","B. Capacidade analítica e de pensamento crítico","C. Habilidades de negociação comercial","D. Expertise em desenvolvimento de sistemas de informação"],"correct":1,"justification_correct":"O exame de fraude demanda raciocínio analítico apurado para coletar, organizar e interpretar evidências de forma lógica e consistente. (ACFE Fraud Examiners Manual 2024)","justification_wrong":"Tributação, negociação e desenvolvimento de sistemas são competências complementares, não a habilidade central do examinador."},
    {"num":30,"text":"A independência do examinador de fraude é considerada requisito fundamental porque:","tag":"Independência","options":["A. Reduz o tempo necessário para conclusão das investigações","B. Dispensa a necessidade de documentação formal","C. Assegura que as conclusões sejam imparciais e tecnicamente defensáveis","D. Elimina a exposição a riscos de ordem legal"],"correct":2,"justification_correct":"A independência garante que o examinador chegue a conclusões baseadas exclusivamente nas evidências, sem influências externas que comprometam a credibilidade do trabalho. (ACFE Code of Professional Standards)","justification_wrong":"A independência não reduz prazo, não dispensa documentação e não elimina riscos legais — sua função é preservar a imparcialidade."},
    {"num":31,"text":"Qual das seguintes atividades está fora do escopo de atribuições do examinador de fraude?","tag":"Limites do CFE","options":["A. Coleta e preservação de evidências relevantes","B. Condução de entrevistas com testemunhas e potenciais envolvidos","C. Declaração de culpabilidade criminal do investigado","D. Elaboração de relatórios investigativos fundamentados"],"correct":2,"justification_correct":"A declaração de culpabilidade criminal é prerrogativa exclusiva do Poder Judiciário. O CFE apura fatos e apresenta evidências; a determinação de culpa compete aos tribunais. (ACFE Code of Professional Standards)","justification_wrong":"Coleta de evidências, entrevistas e relatórios investigativos são atribuições legítimas e centrais do examinador de fraude."},
    {"num":32,"text":"As evidências obtidas no curso de um exame de fraude devem ser tratadas de forma a garantir:","tag":"Evidências","options":["A. Seleção discricionária conforme conveniência da investigação","B. Descarte imediato após a conclusão do exame","C. Preservação adequada e documentação rigorosa da cadeia de custódia","D. Ampla divulgação aos colaboradores da organização"],"correct":2,"justification_correct":"A preservação e documentação adequadas das evidências, incluindo a cadeia de custódia, são essenciais para garantir a admissibilidade legal e a confiabilidade das conclusões. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Seleção discricionária, descarte e divulgação irrestrita comprometem a integridade das evidências e a validade do processo investigativo."},
    {"num":33,"text":"O ceticismo profissional, no contexto do exame de fraude, implica que o examinador deve:","tag":"Ceticismo Profissional","options":["A. Presumir a má-fé de todos os colaboradores investigados","B. Aceitar explicações e documentos sem questionamento adicional","C. Adotar postura questionadora mantendo a objetividade metodológica","D. Partir do pressuposto de que a fraude sempre está presente"],"correct":2,"justification_correct":"O ceticismo profissional consiste em questionar informações e evidências de forma criteriosa, sem presumir má-fé ou boa-fé — mantendo a objetividade como princípio norteador. (ACFE Code of Professional Standards)","justification_wrong":"Presumir má-fé universal ou a existência prévia de fraude viola a objetividade; aceitar explicações sem verificação é o oposto do ceticismo."},
    {"num":34,"text":"Os padrões éticos e profissionais aplicáveis aos Examinadores de Fraude Certificados são estabelecidos e mantidos por:","tag":"ACFE","options":["A. Comissão de Valores Mobiliários (CVM/SEC)","B. Associação de Examinadores de Fraude Certificados (ACFE)","C. Receita Federal (IRS/RFB)","D. Ministério Público ou Departamento de Justiça"],"correct":1,"justification_correct":"A ACFE é o órgão responsável pela certificação CFE e pela definição dos padrões éticos e profissionais que regem a atuação dos examinadores de fraude. (ACFE Code of Professional Standards)","justification_wrong":"CVM/SEC, Receita Federal e Ministério Público são órgãos governamentais com atribuições distintas dos padrões profissionais da certificação CFE."},
    {"num":35,"text":"A manutenção da confidencialidade durante um exame de fraude tem como objetivo precípuo:","tag":"Confidencialidade","options":["A. Resguardar exclusivamente os interesses da alta administração","B. Retardar a divulgação dos resultados da investigação","C. Preservar a integridade das evidências e proteger a reputação dos envolvidos","D. Evitar notificações obrigatórias a autoridades reguladoras"],"correct":2,"justification_correct":"A confidencialidade protege a integridade das evidências, previne adulterações e minimiza danos reputacionais desnecessários durante o curso da investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"A confidencialidade não visa proteger gestão específica, atrasar resultados ou evadir obrigações legais de reporte."},
    {"num":36,"text":"As conclusões apresentadas em um relatório de exame de fraude devem estar necessariamente fundamentadas em:","tag":"Fundamentação","options":["A. Opinião e percepção subjetiva da gestão","B. Suposições baseadas em circunstâncias favoráveis","C. Evidências suficientes, relevantes e confiáveis","D. Exclusivamente depoimentos de colaboradores"],"correct":2,"justification_correct":"Toda conclusão investigativa deve ser sustentada por evidências que atendam aos critérios de suficiência, relevância e confiabilidade para ser profissionalmente defensável. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Opiniões subjetivas, suposições e depoimentos isolados não constituem base suficiente para as conclusões de um exame de fraude."},
    {"num":37,"text":"Durante a condução de entrevistas investigativas, a postura que melhor qualifica o examinador de fraude é:","tag":"Entrevistas","options":["A. Dominar a interação e conduzir de forma diretiva","B. Formular acusações precocemente para obter confissão","C. Praticar escuta ativa e observar indicadores comportamentais","D. Oferecer garantias irrestrictas de confidencialidade"],"correct":2,"justification_correct":"A escuta ativa permite ao examinador captar informações relevantes e avaliar a credibilidade do entrevistado mediante a observação de sinais verbais e não-verbais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Abordagem diretiva, acusações prematuras e promessas indevidas de confidencialidade comprometem a qualidade da entrevista."},
    {"num":38,"text":"Quando questões de natureza jurídica surgem no contexto de um exame de fraude, a conduta adequada do examinador é:","tag":"Aspectos Jurídicos","options":["A. Prosseguir independentemente sem assessoria especializada","B. Divulgar imediatamente os fatos à imprensa","C. Buscar orientação junto ao consultor jurídico competente","D. Suspender definitivamente a investigação"],"correct":2,"justification_correct":"A orientação jurídica assegura que a investigação seja conduzida em conformidade com a legislação aplicável, preservando os direitos dos investigados e a admissibilidade das evidências. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Prosseguir sem orientação, divulgar à mídia ou encerrar a investigação são condutas inadequadas diante de questões jurídicas complexas."},
    {"num":39,"text":"O propósito central da documentação produzida no curso de um exame de fraude é:","tag":"Documentação","options":["A. Justificar os honorários e custos da investigação","B. Embasar procedimentos disciplinares ou ações legais subsequentes","C. Substituir o processo decisório da gestão organizacional","D. Simplificar futuras auditorias de demonstrações financeiras"],"correct":1,"justification_correct":"A documentação do exame de fraude serve para registrar os fatos apurados e as evidências coletadas, tornando as descobertas defensáveis em processos administrativos, cíveis ou criminais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Justificativa de custos, substituição gerencial e simplificação de auditorias são objetivos secundários ou inexistentes na produção documental investigativa."},
    {"num":40,"text":"Os relatórios produzidos em exames de fraude devem ser caracterizados por:","tag":"Relatórios","options":["A. Linguagem persuasiva com embasamento em opiniões técnicas","B. Formato informal e síntese executiva","C. Objetividade factual, clareza e neutralidade","D. Direcionamento exclusivo para o comitê executivo"],"correct":2,"justification_correct":"Relatórios profissionais de exame de fraude devem apresentar fatos objetivos suportados por evidências, com linguagem clara e isenta de viés ou julgamento valorativo. (ACFE Code of Professional Standards)","justification_wrong":"Linguagem persuasiva, informalidade e direcionamento restrito comprometem a credibilidade e a utilidade do relatório investigativo."},
    {"num":41,"text":"A credibilidade profissional do examinador de fraude é primordialmente construída por meio de:","tag":"Credibilidade","options":["A. Adoção de abordagem investigativa agressiva","B. Competência técnica combinada com imparcialidade metodológica","C. Autoridade hierárquica na estrutura organizacional","D. Rapidez na conclusão das investigações"],"correct":1,"justification_correct":"A credibilidade do CFE deriva da combinação de competência técnica, ética profissional e imparcialidade — não de postura agressiva, autoridade ou velocidade. (ACFE Code of Professional Standards)","justification_wrong":"Agressividade, autoridade hierárquica e velocidade são fatores irrelevantes ou contraproducentes para a credibilidade investigativa."},
    {"num":42,"text":"O princípio que exige que o examinador de fraude conduza suas investigações com rigor, diligência e competência técnica denomina-se:","tag":"Princípios Profissionais","options":["A. Princípio do contraditório","B. Zelo profissional (Due Professional Care)","C. Dever de lealdade institucional","D. Princípio da defesa"],"correct":1,"justification_correct":"O Due Professional Care obriga o CFE a conduzir cada investigação com rigor técnico, diligência e competência adequados à natureza do trabalho. (ACFE Code of Professional Standards)","justification_wrong":"Contraditório é princípio processual; lealdade e defesa não são princípios do exame de fraude conforme os padrões da ACFE."},
    {"num":43,"text":"A comunicação dos resultados de um exame de fraude deve ser realizada:","tag":"Comunicação de Resultados","options":["A. De forma informal a todos os colaboradores da organização","B. Exclusivamente às autoridades policiais competentes","C. Seguindo os protocolos e canais organizacionais estabelecidos","D. Publicamente sempre que a fraude for confirmada"],"correct":2,"justification_correct":"A comunicação dos resultados deve respeitar os canais formais e os protocolos organizacionais e legais, assegurando confidencialidade e uso adequado das informações. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Comunicação informal, exclusividade policial ou divulgação pública violam os princípios de confidencialidade e os protocolos profissionais."},
    {"num":44,"text":"Qual comportamento representa a ameaça mais grave à objetividade do examinador de fraude?","tag":"Objetividade","options":["A. Revisão cuidadosa e sistemática das evidências coletadas","B. Consulta prévia ao assessor jurídico da organização","C. Permissão para que vieses pessoais influenciem as conclusões","D. Documentação detalhada das descobertas investigativas"],"correct":2,"justification_correct":"O viés pessoal compromete a imparcialidade, a credibilidade e a validade das conclusões — representando a ameaça mais séria à objetividade investigativa. (ACFE Code of Professional Standards)","justification_wrong":"Revisão de evidências, consulta jurídica e documentação são práticas que reforçam, não comprometem, a objetividade do examinador."},
    {"num":45,"text":"O examinador de fraude é responsável por:","tag":"Responsabilidades","options":["A. Garantir a eliminação total da fraude na organização","B. Assegurar a detecção de todos os esquemas existentes","C. Conduzir investigações com julgamento profissional adequado","D. Aplicar penalidades criminais aos perpetradores identificados"],"correct":2,"justification_correct":"O CFE é responsável por exercer julgamento profissional competente na condução das investigações — sem garantir resultados ou aplicar sanções penais, funções que competem a outros agentes. (ACFE Code of Professional Standards)","justification_wrong":"Nenhum profissional pode garantir eliminação ou detecção total; penalidades criminais são impostas pelo Judiciário, não pelo examinador."},
    {"num":46,"text":"Qual das seguintes atividades se enquadra adequadamente no escopo de atuação do examinador de fraude?","tag":"Escopo de Atuação","options":["A. Desenvolvimento de sistemas contábeis automatizados","B. Apoio às iniciativas de prevenção e detecção de fraudes","C. Processamento judicial de infratores","D. Emissão de pareceres jurídicos vinculantes"],"correct":1,"justification_correct":"O examinador de fraude contribui ativamente para os esforços de prevenção, detecção e investigação de fraudes, dentro dos limites de sua competência profissional. (ACFE Fraud Examiners Manual 2024)","justification_wrong":"Desenvolvimento de sistemas, processo judicial e pareceres jurídicos vinculantes estão fora do escopo de atuação do CFE."},
    {"num":47,"text":"A educação profissional contínua é valorizada na carreira do examinador de fraude principalmente porque:","tag":"Educação Continuada","options":["A. O conteúdo do exame CFE é reformulado anualmente","B. Os esquemas de fraude e o arcabouço legal evoluem continuamente","C. As políticas organizacionais permanecem estáticas ao longo do tempo","D. A tecnologia é irrelevante para a prática investigativa moderna"],"correct":1,"justification_correct":"A evolução constante dos métodos fraudulentos, da legislação e das tecnologias aplicadas exige atualização permanente do examinador para manter sua efetividade profissional. (ACFE Code of Professional Standards)","justification_wrong":"O exame CFE não é reformulado anualmente; políticas e tecnologia são dinâmicas e relevantes para a prática investigativa."},
    {"num":48,"text":"O exercício do julgamento profissional pelo examinador de fraude implica, em sua essência:","tag":"Julgamento Profissional","options":["A. Aplicação mecânica de normas sem análise contextual","B. Tomada de decisões baseadas exclusivamente na intuição","C. Avaliação lógica e ética das evidências disponíveis","D. Recusa a assumir casos de elevada complexidade técnica"],"correct":2,"justification_correct":"O julgamento profissional consiste na avaliação criteriosa das evidências à luz de princípios éticos e metodológicos, equilibrando rigor técnico e senso prático. (ACFE Code of Professional Standards)","justification_wrong":"Aplicação mecânica, intuição exclusiva e recusa de casos complexos são posturas incompatíveis com o exercício do julgamento profissional."},
    {"num":49,"text":"Qual situação representa o risco mais elevado para a integridade de uma investigação de fraude?","tag":"Integridade da Investigação","options":["A. Entrevistas conduzidas em etapas distintas do processo","B. Volume elevado e complexidade das evidências a analisar","C. Existência de conflito de interesses envolvendo o investigador","D. Conjuntos de dados de grande dimensão para análise"],"correct":2,"justification_correct":"O conflito de interesses compromete diretamente a objetividade e a credibilidade do examinador, representando a maior ameaça à integridade e à validade da investigação. (ACFE Code of Professional Standards)","justification_wrong":"Etapas investigativas, complexidade de evidências e volume de dados são desafios metodológicos, não ameaças à integridade do processo."},
    {"num":50,"text":"O objetivo final que norteia a atuação do Examinador de Fraude Certificado em qualquer investigação é:","tag":"Objetivo Final","options":["A. Assegurar a condenação dos suspeitos identificados","B. Proteger os interesses da gestão organizacional","C. Estabelecer fatos concretos com base em evidências sólidas","D. Eliminar completamente o risco de fraude na organização"],"correct":2,"justification_correct":"O objetivo último do CFE é apurar a verdade dos fatos mediante evidências — a responsabilização legal, a proteção de interesses específicos e a eliminação do risco são consequências ou atribuições de outros agentes. (ACFE Code of Professional Standards)","justification_wrong":"Condenação é função judicial; proteção de gestão pode configurar conflito de interesses; eliminação total do risco é objetivo impossível."},
]

# Salva o arquivo
output_dir = Path("static/quizzes/cfe/fraud_investigation")
output_dir.mkdir(parents=True, exist_ok=True)

# Determina o proximo numero de quiz disponivel
existing = list(output_dir.glob("quiz_*_pt.json"))
nums = []
for f in existing:
    try:
        nums.append(int(f.stem.split("_")[1]))
    except:
        pass
next_num = max(nums) + 1 if nums else 1

output = {
    "cert_id": "cfe",
    "domain_id": "fraud_investigation",
    "quiz_num": next_num,
    "domain_name": "Fraud Investigation",
    "cert_name": "CFE / ACFE",
    "lang": "pt",
    "questions": questions
}

path = output_dir / f"quiz_{next_num:03d}_pt.json"
path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")

print(f"OK - {len(questions)} questoes salvas em {path}")
print(f"Quiz numero: {next_num}")
