#!/usr/bin/env python3
"""
CISM BATCH 4 - Tratamento de Riscos
15 questoes adaptadas - injeta no quiz_001 existente ou cria quiz_002
Dominio: info_risk_management
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"Uma startup de software de jogos não realiza testes de penetração em seus sistemas. Isso é um exemplo de:","tag":"Tolerância ao Risco","options":["A. Alta tolerância ao risco","B. Não conformidade regulatória","C. Irresponsabilidade profissional","D. Terceirização da função de segurança"],"correct":0,"justification_correct":"Empresas de software em fase inicial tendem a ser altamente tolerantes ao risco — time to market e aquisição de clientes são prioridades. À medida que a organização amadurece, outras prioridades como segurança são introduzidas. (CISM Review Manual, ISACA)","justification_wrong":"Não conformidade exige regulação específica aplicável; irresponsabilidade é julgamento de valor; terceirização implica contratar externamente — a ausência de pentest reflete tolerância ao risco característica de startups."},
    {"num":2,"text":"As categorias de tratamento de riscos são:","tag":"Tratamento de Riscos","options":["A. Evitar, transferir, mitigar e aceitar o risco","B. Evitar, transferir e mitigar o risco","C. Evitar, reduzir, transferir, mitigar e aceitar o risco","D. Evitar, tratar, mitigar e aceitar o risco"],"correct":0,"justification_correct":"As quatro categorias de tratamento de riscos são: evitar (descontinuar a atividade), transferir (repassar a terceiros como seguradoras), mitigar (reduzir via controles) e aceitar (gestão decide assumir o risco). (CISM Review Manual, ISACA; ISO 27005:2022)","justification_wrong":"As demais opções omitem categorias ou incluem termos redundantes — as quatro categorias padrão são evitar, transferir, mitigar e aceitar."},
    {"num":3,"text":"Em que situação faria sentido gastar R$50.000 para proteger um ativo avaliado em R$10.000?","tag":"Análise Custo-Benefício","options":["A. A medida reduz o impacto da ameaça em mais de 90%","B. Nunca faria sentido gastar R$50.000 para proteger um ativo de R$10.000","C. O ativo é necessário para gerar R$500.000 em receita mensal","D. A medida reduz a probabilidade da ameaça em mais de 90%"],"correct":2,"justification_correct":"Ordinariamente não faria sentido, mas considerações adicionais podem tornar razoável — se o ativo é necessário para operações que geram R$500.000 mensais, o valor real protegido é muito maior que os R$10.000 do ativo em si. (CISM Review Manual, ISACA)","justification_wrong":"Redução de impacto ou probabilidade são fatores relevantes mas insuficientes isoladamente; afirmar que nunca faria sentido ignora o contexto do valor operacional do ativo."},
    {"num":4,"text":"Um comitê diretor de segurança com poderes para tomar decisões de tratamento de riscos optou por aceitar um risco específico. Qual é o melhor curso de ação?","tag":"Aceitação de Risco","options":["A. Encaminhar o risco a uma firma externa de auditoria de segurança","B. Realizar análise de risco adicional para identificar o risco residual","C. Reabrir o item de risco para reconsideração após um ano","D. Marcar o item de risco como permanentemente encerrado"],"correct":2,"justification_correct":"Um risco aceito deve ser revisado periodicamente — em um ano, condições de negócio, ameaças e outras considerações podem mudar, exigindo nova decisão. Fechar permanentemente impede a reavaliação necessária. (CISM Review Manual, ISACA)","justification_wrong":"Encaminhar a auditoria externa e análise adicional são desnecessários após decisão formal; encerrar permanentemente é inadequado pois o contexto pode mudar."},
    {"num":5,"text":"As responsabilidades de um proprietário de controle incluem todos os seguintes, EXCETO:","tag":"Propriedade de Controles","options":["A. Revisar o controle periodicamente","B. Auditar o controle","C. Documentar o controle","D. Manter registros do controle"],"correct":1,"justification_correct":"Proprietários de controles são responsáveis por documentar, manter registros e revisar o controle para garantir que continua operando adequadamente. A auditoria de um controle é realizada por outra parte interna ou externa — não pelo próprio proprietário. (CISM Review Manual, ISACA)","justification_wrong":"Revisar, documentar e manter registros são responsabilidades legítimas do proprietário do controle — apenas auditar é função de terceiro independente."},
    {"num":6,"text":"A responsabilização pelo resultado de um risco aceito é conhecida como:","tag":"Responsabilização","options":["A. Aceitação do risco","B. Transferência do risco","C. Tratamento do risco","D. Propriedade do risco"],"correct":3,"justification_correct":"A propriedade do risco (risk ownership) é a atribuição de responsabilização pelo risco específico — quem responde pelo resultado caso o risco se materialize. (CISM Review Manual, ISACA)","justification_wrong":"Aceitação é a decisão de assumir o risco; transferência repassa a terceiros; tratamento é o processo geral — a responsabilização específica pelo risco aceito é a propriedade do risco."},
    {"num":7,"text":"Um comitê de riscos formalmente decidiu que um risco específico será mitigado por meio de um tipo específico de controle. O que o comitê realizou?","tag":"Tratamento de Riscos","options":["A. Aceitação do risco","B. Tratamento do risco","C. Redefinição da tolerância ao risco","D. Redefinição do apetite ao risco"],"correct":1,"justification_correct":"O comitê formalmente tratou o risco — decidiu mitigá-lo por meio de controle específico, que é uma das formas de tratamento de risco. A decisão formal de mitigar constitui tratamento. (CISM Review Manual, ISACA)","justification_wrong":"Aceitação seria assumir o risco sem controle; redefinir tolerância ou apetite são decisões estratégicas diferentes — a decisão de mitigar por controle específico é tratamento de risco."},
    {"num":8,"text":"Um comitê de riscos formalmente decidiu mitigar um risco específico. Onde deve ser documentada essa decisão?","tag":"Documentação de Risco","options":["A. Registro de riscos","B. Atas de reunião","C. Estatuto de riscos","D. Indicador-chave de risco"],"correct":0,"justification_correct":"O registro de riscos é o melhor local para documentar decisões formais de tratamento de risco. Atas de reunião também podem ser adequadas se existir um log de decisões, mas o registro de riscos é o repositório primário. (CISM Review Manual, ISACA)","justification_wrong":"Atas são complementares; estatuto define o programa, não decisões individuais; KRIs medem riscos, não documentam decisões — o registro de riscos é o repositório formal primário."},
    {"num":9,"text":"Um gestor de riscos avalia opções de tratamento para um risco particularmente grande que excede a tolerância declarada da organização. Como deve proceder o tratamento?","tag":"Escalamento de Riscos","options":["A. O risco deve ser dividido em riscos menores para facilitar o tratamento","B. O gestor de riscos está autorizado a tomar a decisão de tratamento autonomamente","C. O gestor deve escalar a decisão para a alta gestão","D. O risco deve ser colocado em espera indefinidamente"],"correct":2,"justification_correct":"Quando um risco excede a tolerância declarada da organização, a alta gestão pode precisar tomar ou aprovar a decisão de tratamento — riscos desta magnitude requerem autoridade superior à do gestor de riscos. (CISM Review Manual, ISACA)","justification_wrong":"Dividir o risco não resolve sua magnitude real; o gestor não tem autoridade para riscos acima da tolerância; colocar em espera indefinida é ignorar o risco."},
    {"num":10,"text":"Um líder de cibersegurança está registrando a decisão de aceitar um risco específico. O que deve ser feito em relação a esse risco aceito?","tag":"Aceitação de Risco","options":["A. Programar o risco aceito para redeliberação em um ano","B. Considerar o risco como aceito em perpetuidade","C. Converter o risco aceito em risco residual","D. Realizar análise de risco para confirmar a aceitação"],"correct":0,"justification_correct":"Riscos aceitos não devem ser aceitos em perpetuidade — condições podem mudar no futuro, exigindo nova decisão. Programar uma revisão em um ano é a prática recomendada. (CISM Review Manual, ISACA)","justification_wrong":"Aceitar em perpetuidade ignora mudanças futuras; converter em residual é impreciso conceitualmente; confirmar com nova análise após decisão já tomada é redundante."},
    {"num":11,"text":"Em avaliação de riscos, um gestor identifica risco que causaria grande constrangimento à organização se revelado. A alta gestão instruiu omitir o achado do relatório final. O que a alta gestão fez?","tag":"Ignorar Riscos","options":["A. Postergou o risco para análise futura","B. Cometeu um crime ao suprimir informação","C. Transferiu o risco para outra parte","D. Ignorou o risco ao não documentá-lo formalmente"],"correct":3,"justification_correct":"Ignorar o risco é a resposta mais precisa — embora pudesse ser dito que a gestão aceitou o risco informalmente, como o risco não foi documentado formalmente, não houve aceitação formal. Ignorar mantém riscos 'fora dos livros'. (CISM Review Manual, ISACA)","justification_wrong":"Postergar implica revisão futura programada; constituir crime requer análise jurídica específica; transferir implica repasse formal a terceiros — a ausência de documentação caracteriza ignorar o risco."},
    {"num":12,"text":"Um gestor de riscos documenta novo risco e identifica o chefe do departamento como proprietário. O chefe instrui o gestor a identificar um gerente de nível inferior como proprietário. O que o chefe fez?","tag":"Delegação de Risco","options":["A. Abdicou de sua responsabilidade de propriedade do risco","B. Aceitou o risco formalmente","C. Delegou a propriedade do risco ao gerente de nível inferior","D. Transferiu o risco para outra parte"],"correct":2,"justification_correct":"A propriedade do risco foi delegada a outro membro do departamento — o que não é necessariamente inapropriado, pois o gerente indicado pode ter maior responsabilidade operacional sobre o processo relacionado ao risco. (CISM Review Manual, ISACA)","justification_wrong":"Abdicar implica abandono sem transferência; aceitar é decisão sobre o risco, não sua propriedade; transferir implica outra organização — delegar internamente é a ação correta descrita."},
    {"num":13,"text":"O risco remanescente após a realização das atividades de mitigação de risco é conhecido como:","tag":"Risco Residual","options":["A. Risco residual","B. Risco aberto","C. Risco não tratado","D. Risco aceito"],"correct":0,"justification_correct":"O risco residual é o nível de risco que permanece após a aplicação dos controles de mitigação — é o risco que a organização ainda carrega após implementar suas medidas de proteção. (CISM Review Manual, ISACA; ISO 31000:2018)","justification_wrong":"Risco aberto e não tratado implicam ausência de ação; risco aceito é uma decisão formal — o risco remanescente pós-mitigação é especificamente o risco residual."},
    {"num":14,"text":"Uma avaliação de riscos identificou risco de perda de dados associado ao uso de software não aprovado. A gestão determinou a remoção do software. Qual decisão de risco foi tomada?","tag":"Evitar Riscos","options":["A. Mitigação do risco","B. Evitar o risco (risk avoidance)","C. Abrogação do risco","D. Redução do risco"],"correct":1,"justification_correct":"Evitar o risco é a decisão tomada — a atividade associada ao risco (uso do software não aprovado) está sendo descontinuada. Risk avoidance é definido como a descontinuação da atividade associada ao risco identificado. (CISM Review Manual, ISACA)","justification_wrong":"Mitigação implementaria controles mantendo o software; abrogação não é categoria padrão; redução é sinônimo de mitigação — a remoção do software que causa o risco é evitar o risco."},
    {"num":15,"text":"Diante de risco de alto impacto, a alta gestão decide terceirizar a operação de negócio associada ao risco para um fornecedor, com contrato que estabelece que o fornecedor aceita os riscos operacionais. O que acontece com a responsabilização pelo risco?","tag":"Transferência de Risco","options":["A. A responsabilização é transferida para o fornecedor","B. A responsabilização permanece com a alta gestão","C. A responsabilização é reduzida proporcionalmente ao risco","D. A responsabilização é transferida para o conselho de administração"],"correct":1,"justification_correct":"Ao transferir o risco para outra entidade de negócio, a responsabilização permanece com quem originalmente é responsável pela função de negócio e pelo risco associado. A responsabilização não pode ser transferida para outra parte. (CISM Review Manual, ISACA)","justification_wrong":"A responsabilização não segue a terceirização — mesmo com contrato, a organização original mantém a accountability perante seus stakeholders e reguladores."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

# Tenta adicionar ao quiz_001 se ainda incompleto, senão cria quiz_002
dir1 = Path("static/quizzes/cism/info_risk_management")
dir1.mkdir(parents=True, exist_ok=True)

quiz001 = dir1 / "quiz_001_pt.json"
if quiz001.exists():
    data = json.loads(quiz001.read_text(encoding="utf-8"))
    existing_q = data.get("questions", [])
    if len(existing_q) < 50:
        # Adiciona ao quiz existente
        next_num = len(existing_q) + 1
        for i, q in enumerate(questions):
            q["num"] = next_num + i
        existing_q.extend(questions)
        data["questions"] = existing_q[:50]  # limita a 50
        quiz001.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        total = len(data["questions"])
        print(f"OK - {len(questions)} questoes adicionadas ao quiz_001_pt.json")
        print(f"Total agora: {total}/50")
        if total < 50:
            print(f"AVISO - ainda faltam {50-total} questoes para completar.")
    else:
        # quiz_001 ja completo, cria quiz_002
        num2 = get_next_num(dir1)
        out = {"cert_id":"cism","domain_id":"info_risk_management","quiz_num":num2,"domain_name":"Information Risk Management","cert_name":"CISM","lang":"pt","questions":questions}
        path2 = dir1 / f"quiz_{num2:03d}_pt.json"
        path2.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"OK - {len(questions)} questoes salvas em {path2}")
else:
    num1 = get_next_num(dir1)
    out = {"cert_id":"cism","domain_id":"info_risk_management","quiz_num":num1,"domain_name":"Information Risk Management","cert_name":"CISM","lang":"pt","questions":questions}
    path1 = dir1 / f"quiz_{num1:03d}_pt.json"
    path1.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"OK - {len(questions)} questoes salvas em {path1}")
