#!/usr/bin/env python3
"""
CFE BATCH 5
Q1-25: Financial Transactions & Fraud Schemes
Q26-50: Law (Direito e Aspectos Jurídicos)
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# ── Q1-25: Financial Transactions ─────────────────────────────────────────────
financial = [
    {"num":1,"text":"Um funcionário retém em caixa o valor de uma venda sem registá-la no sistema. De acordo com o CFE Examiners Manual, como se denomina esse tipo de fraude?","tag":"Skimming","options":["A. Skimming","B. Cash larceny","C. Lapping","D. Kiting"],"correct":0,"justification_correct":"O skimming envolve o roubo de recursos antes de serem registados no sistema contábil, não deixando rastro de auditoria direto da transação desviada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Cash larceny ocorre após o registro; lapping é um esquema de cobertura de desvios em contas a receber; kiting envolve manipulação de cheques entre contas."},
    {"num":2,"text":"Quando uma empresa capitaliza custos de reparações de rotina em vez de reconhecê-los como despesa, qual é o impacto principal na equação contábil?","tag":"Capitalização Indevida","options":["A. Ativos e capital próprio ficam sobreavaliados","B. Passivos e despesas ficam subavaliados","C. Receitas e ativos ficam subavaliados","D. Capital próprio diminui e passivos aumentam"],"correct":0,"justification_correct":"Capitalizar custos cria ou aumenta ativos e evita o reconhecimento da despesa, inflando o lucro líquido e consequentemente o patrimônio líquido. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Passivos não são diretamente afetados; receitas não são alteradas; o patrimônio aumenta (não diminui) pela supressão indevida da despesa."},
    {"num":3,"text":"Um gestor direciona contrato importante para fornecedor que é familiar próximo, sem divulgar o relacionamento. Este é um exemplo de qual tipo de fraude?","tag":"Partes Relacionadas","options":["A. Suborno a funcionário público","B. Abuso de transações com partes relacionadas","C. Conluio em licitações","D. Esquema de empresa fantasma"],"correct":1,"justification_correct":"O abuso de transações com partes relacionadas ocorre quando vínculos com proprietários, familiares ou entidades controladas não são adequadamente divulgados e são usados para benefício próprio. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Suborno envolve agentes públicos; conluio em licitações é acordo entre concorrentes; empresa fantasma cria entidade fictícia — o caso descreve especificamente um conflito de partes relacionadas não divulgado."},
    {"num":4,"text":"Qual profissional é o principal responsável por investigar, documentar e provar a fraude para fins de ações legais ou disciplinares?","tag":"Papel do CFE","options":["A. Examinador de fraudes (CFE)","B. Auditor externo independente","C. Controller financeiro","D. Analista de compliance"],"correct":0,"justification_correct":"O examinador de fraudes define-se especificamente pelo foco em provar a fraude, coletar provas, entrevistar suspeitos e preparar casos para acusação ou ação disciplinar. (ACFE Code of Professional Standards)","justification_wrong":"Auditores externos verificam demonstrações; controllers gerenciam registros financeiros; analistas de compliance monitoram conformidade — o CFE é o especialista em investigação e prova de fraudes."},
    {"num":5,"text":"Uma gestora de vendas incentiva sua equipe a expedir produtos em excesso para distribuidores no final do trimestre, registando as expedições como vendas, apesar de saber que a maioria pode ser devolvida. Esse esquema é conhecido como:","tag":"Channel Stuffing","options":["A. Reconhecimento prematuro de receita","B. Fraude em demonstrações financeiras por omissão","C. Lapping de contas a receber","D. Channel stuffing (sobrecarga do canal de distribuição)"],"correct":3,"justification_correct":"O channel stuffing infla artificialmente as vendas por meio do envio de mercadorias além da capacidade real de absorção do canal de distribuição, registando receitas que provavelmente serão revertidas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Reconhecimento prematuro é mais amplo; fraude por omissão suprime informações; lapping é esquema de contas a receber — o channel stuffing é específico ao envio excessivo para canais de venda."},
    {"num":6,"text":"Um funcionário do processamento de folha cria um trabalhador falso, aprova suas folhas de horas e direciona os pagamentos para sua própria conta. Esse tipo de fraude é conhecido como:","tag":"Funcionário Fantasma","options":["A. Fraude de reembolso de despesas","B. Manipulação de comissões","C. Esquema de funcionário fantasma","D. Kiting de folha de pagamento"],"correct":2,"justification_correct":"O esquema de funcionário fantasma envolve uma pessoa na folha de pagamentos que não trabalha efetivamente para a empresa, sendo seu salário desviado pelo fraudador responsável pelo processo. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Reembolso de despesas e comissões são categorias distintas; kiting envolve manipulação de cheques — o funcionário fantasma é a inclusão de indivíduo inexistente na folha de pagamentos."},
    {"num":7,"text":"Qual dos seguintes representa um dos riscos de fraude mais perigosos por envolver autoridade superior para contornar controles internos estabelecidos?","tag":"Management Override","options":["A. Conluio entre funcionários operacionais","B. Skimming de recebimentos","C. Lapping de contas a receber","D. Sobreposição pela gestão (Management override)"],"correct":3,"justification_correct":"O management override permite que executivos forcem funcionários a realizar registros indevidos ou ignorar políticas, tornando os controles normais ineficazes. É um risco central identificado no COSO Framework. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Conluio operacional, skimming e lapping são esquemas específicos — o management override é estrutural e abrangente, pois anula o sistema de controles como um todo."},
    {"num":8,"text":"Se a gestão pretender subavaliar os lucros, possivelmente para fins fiscais, qual manipulação seria mais provável?","tag":"Manipulação de Resultados","options":["A. Sobreavaliar a provisão para devedores duvidosos","B. Capitalizar despesas operacionais indevidamente","C. Reconhecer receitas fictícias antecipadamente","D. Subavaliar o estoque final do período"],"correct":0,"justification_correct":"O aumento da provisão para devedores duvidosos é tratado como despesa, reduzindo o lucro líquido reportado — técnica utilizada para subavaliar resultados com fins fiscais ou criar reservas (cookie jar). (CFE Fraud Examiners Manual 2024)","justification_wrong":"Capitalização indevida e receitas fictícias inflam o lucro; subavaliar o estoque aumenta o CMV reduzindo o lucro, mas não é a resposta primária — a provisão em excesso é a técnica mais direta."},
    {"num":9,"text":"Um fraudador altera o nome do beneficiário em cheque da empresa já assinado, tornando-o pagável a si próprio. Esse é um exemplo de qual esquema?","tag":"Adulteração de Cheques","options":["A. Kiting entre contas bancárias","B. Skimming de recebimentos em caixa","C. Adulteração de cheques (Check tampering)","D. Lapping de contas a receber"],"correct":2,"justification_correct":"A adulteração de cheques envolve interceptar e modificar um cheque legítimo da empresa — alterando beneficiário, valor ou outros dados — para ganho pessoal. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Kiting explora float bancário; skimming é desvio antes do registro; lapping é cobertura de desvios em recebíveis — a alteração física de um cheque é especificamente adulteração."},
    {"num":10,"text":"Qual é o principal efeito de sobreavaliar fraudulentamente o estoque final nas demonstrações financeiras?","tag":"Manipulação de Estoque","options":["A. O CMV fica sobreavaliado e o lucro bruto diminui","B. Os passivos circulantes ficam sobreavaliados","C. As receitas ficam subavaliadas no período","D. O CMV fica subavaliado e o lucro bruto fica sobreavaliado"],"correct":3,"justification_correct":"CMV = Estoque Inicial + Compras - Estoque Final. Um estoque final maior reduz o CMV calculado, inflando artificialmente o lucro bruto e o resultado do período. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O CMV diminui (não aumenta) com estoque final sobreavaliado; passivos e receitas não são diretamente afetados por essa manipulação específica."},
    {"num":11,"text":"Um aumento rápido nas receitas reportadas por uma empresa que não é acompanhado por crescimento equivalente no fluxo de caixa operacional é considerado:","tag":"Red Flags Contábeis","options":["A. Indicador normal em períodos de expansão acelerada","B. Evidência conclusiva de fraude contábil","C. Red flag sugerindo potencial manipulação de receitas","D. Resultado esperado em estratégias de expansão a crédito"],"correct":2,"justification_correct":"A divergência entre receitas reportadas e geração real de caixa sugere que as receitas podem não se converter em dinheiro real — indicador comum de vendas fictícias ou incobráveis. (CFE Fraud Examiners Manual 2024)","justification_wrong":"A divergência não é normal nem conclusiva isoladamente — é um red flag que justifica investigação, não prova definitiva de fraude."},
    {"num":12,"text":"Um gestor de compras cria empresa falsa e submete faturas por bens que nunca foram entregues. Esse tipo de fraude em aquisições é um exemplo de:","tag":"Fornecedor Fantasma","options":["A. Conluio em licitações com fornecedores reais","B. Suborno disfarçado de pagamento de consultoria","C. Lapping entre contas de fornecedores","D. Esquema de empresa fantasma (Shell vendor scheme)"],"correct":3,"justification_correct":"O shell vendor scheme envolve a criação de entidade fictícia com o único propósito de faturar serviços ou produtos falsos à organização, desviando recursos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Conluio envolve fornecedores reais; suborno é pagamento indevido para obter favorecimento; lapping é manipulação de contas — o esquema de fornecedor fantasma cria entidade inexistente para emitir faturas fraudulentas."},
    {"num":13,"text":"O exame CFE é desafiante na área de Transações Financeiras porque exige que os candidatos pensem como quem?","tag":"Abordagem CFE","options":["A. Um advogado e um auditor externo","B. Um controlador financeiro e um analista de crédito","C. Um contabilista e um investigador de fraudes","D. Um perito judicial e um gestor de riscos"],"correct":2,"justification_correct":"É necessário compreender como os números são registados (perspectiva contábil) e como os sistemas de registro podem ser explorados (perspectiva investigativa) — combinação única exigida pelo CFE. (ACFE Fraud Examiners Manual 2024)","justification_wrong":"As demais combinações não capturam a dualidade específica exigida no exame CFE: conhecimento contábil aliado à mentalidade investigativa."},
    {"num":14,"text":"Uma empresa não registra passivo acrescido referente a bônus de funcionários já ganhos mas ainda não pagos. Essa manipulação resulta em:","tag":"Passivos Não Registrados","options":["A. Ativos subavaliados e capital próprio diminuído","B. Passivos subavaliados e capital próprio sobreavaliado","C. Receitas subavaliadas e passivos aumentados","D. CMV sobreavaliado e lucro bruto reduzido"],"correct":1,"justification_correct":"Ao não registrar o passivo acrescido, a empresa também suprime a despesa correspondente, inflando o lucro líquido e consequentemente o patrimônio líquido. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Ativos não são afetados; receitas não são relevantes nesse contexto; CMV não é impactado por passivos de pessoal — a omissão de passivos e despesas inflam o patrimônio."},
    {"num":15,"text":"Qual dos seguintes é um exemplo de apropriação indevida de ativos envolvendo um ativo fixo?","tag":"Apropriação de Ativos Fixos","options":["A. Submissão de relatório de despesas com recibos duplicados","B. Utilização do veículo da empresa para viagens pessoais","C. Desvio de cheques de pagamento a fornecedores","D. Criação de funcionário fantasma na folha de pagamento"],"correct":1,"justification_correct":"O uso do veículo corporativo para fins pessoais representa o uso indevido de ativo fixo da empresa para benefício próprio — categoria de apropriação indevida de ativos não monetários. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Despesas duplicadas são fraude de reembolso; desvio de cheques é adulteração; funcionário fantasma é fraude em folha — apenas o uso pessoal do veículo envolve ativo fixo."},
    {"num":16,"text":"Ao analisar demonstrações financeiras em busca de red flags de fraude no reconhecimento de receitas, qual indicador seria o mais sugestivo?","tag":"Red Flags de Receita","options":["A. Melhoria súbita e significativa na margem bruta","B. Aumento gradual e consistente das despesas operacionais","C. Crescimento proporcional entre receitas e contas a pagar","D. Redução nas provisões para devedores duvidosos"],"correct":0,"justification_correct":"Um aumento abrupto na margem bruta pode indicar receitas fictícias sem o respectivo custo associado, ou manipulação de estoques que reduz artificialmente o CMV. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Aumento de despesas e crescimento proporcional são indicadores normais; redução de provisões pode ser legítima — apenas a melhora súbita na margem bruta é red flag específico de manipulação de receitas."},
    {"num":17,"text":"A principal diferença entre cash larceny e skimming é que o cash larceny envolve roubar dinheiro que:","tag":"Skimming vs Larceny","options":["A. Não pertence ao perpetrador","B. Já foi registado no sistema contábil","C. Foi obtido por meios eletrônicos","D. Envolve necessariamente conluio"],"correct":1,"justification_correct":"Essa é a distinção crítica: o cash larceny ocorre após o dinheiro ser registado, deixando rastro contábil; o skimming ocorre antes do registro, sem deixar evidência direta. (CFE Fraud Examiners Manual 2024)","justification_wrong":"A propriedade do dinheiro, o meio eletrônico e o conluio não são os fatores que distinguem as duas categorias — o ponto diferenciador é o momento do registro contábil."},
    {"num":18,"text":"Que técnica de ocultação envolve o uso de contas destinadas a entradas temporárias para esconder transações ilícitas?","tag":"Técnicas de Ocultação","options":["A. Utilização de contas transitórias ou de suspensão","B. Adulteração de documentos de suporte","C. Manipulação de lançamentos de depreciação","D. Criação de empresas de propósito específico"],"correct":0,"justification_correct":"Contas transitórias e de suspensão são frequentemente utilizadas para reter transações temporariamente, tornando-as em locais privilegiados para ocultar registros fraudulentos por períodos prolongados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Adulteração de documentos e depreciação são técnicas distintas; SPEs são estruturas jurídicas — as contas transitórias são o veículo específico para ocultação temporária de transações irregulares."},
    {"num":19,"text":"Se a gestão infla receitas criando vendas fictícias a crédito, como isso afeta a equação contábil fundamental?","tag":"Equação Contábil","options":["A. Ativos (Contas a receber) e Capital Próprio aumentam","B. Passivos aumentam e Capital Próprio diminui","C. Ativos diminuem e Passivos aumentam","D. Capital Próprio aumenta e Passivos diminuem"],"correct":0,"justification_correct":"Registrar venda fictícia a crédito aumenta os ativos (contas a receber) e a receita, inflando o lucro líquido e consequentemente o patrimônio líquido — mantendo a equação equilibrada de forma fraudulenta. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Passivos não são afetados por vendas fictícias a crédito — o efeito é o aumento simultâneo de ativos (recebíveis) e patrimônio (via lucro inflado)."},
    {"num":20,"text":"Como os esquemas de apropriação indevida de ativos são tipicamente ocultados nos registros contábeis?","tag":"Ocultação de Desvios","options":["A. Por meio de conluio com auditores externos","B. Pela criação de entidades offshore para absorver os desvios","C. Mediante o uso de criptomoedas não rastreáveis","D. Manipulando registros para cobrir a falta do ativo com despesas falsas ou baixas contábeis"],"correct":3,"justification_correct":"Quando um ativo é desviado, deve ser criado um registro fraudulento — como uma despesa falsa ou baixa contábil — para justificar sua ausência e manter a equação contábil equilibrada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Conluio com auditores, entidades offshore e criptomoedas são métodos possíveis mas não descrevem o mecanismo contábil fundamental de ocultação de desvios de ativos."},
    {"num":21,"text":"Qual falha de controle interno é a principal que permite um esquema de funcionário fantasma na folha de pagamento?","tag":"Controles de Folha","options":["A. Ausência de autenticação multifator no sistema de RH","B. Falta de política formal de contratação documentada","C. Ausência de segregação entre aprovação e pagamento","D. Ausência de reconciliação independente entre registros de salários e arquivos de RH"],"correct":3,"justification_correct":"Uma reconciliação independente identificaria colaboradores sendo pagos sem registro ativo correspondente no sistema de RH — controle fundamental para detectar funcionários fantasmas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Autenticação, política de contratação e segregação de aprovação/pagamento são controles complementares — a reconciliação independente entre folha e RH é o controle específico que detecta o esquema."},
    {"num":22,"text":"O controller usa lançamento manual para mover despesas da demonstração de resultados para conta de ativos recém-criada antes do fechamento anual. Essa ação é red flag para:","tag":"Capitalização Indevida","options":["A. Manipulação de provisões para devedores duvidosos","B. Esquema de vendor fantasma","C. Capitalização indevida de despesas","D. Lapping de contas a receber"],"correct":2,"justification_correct":"Transferir despesas que deveriam ser reconhecidas no resultado para contas de ativo indevidamente é capitalização indevida — esquema que inflaciona ativos e lucros do período. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Provisões para devedores e vendor fantasma são categorias distintas; lapping envolve recebíveis — o movimento de despesas para ativos via lançamentos manuais é especificamente capitalização indevida."},
    {"num":23,"text":"O manual do exame CFE enfatiza que qualquer esquema de fraude complexo deve manipular qual conceito fundamental?","tag":"Conceito Central","options":["A. O plano de contas da organização","B. Os registros de auditoria e trilhas de evidência","C. A equação contábil fundamental","D. Os contratos com partes relacionadas"],"correct":2,"justification_correct":"A equação contábil fundamental (Ativos = Passivos + Patrimônio Líquido) é a espinha dorsal de qualquer registro financeiro — todos os esquemas de fraude contábil precisam falsificar contas para mantê-la equilibrada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Plano de contas, trilhas de auditoria e contratos são elementos importantes mas não o conceito fundamental que todo esquema precisa manipular."},
    {"num":24,"text":"Um investigador observa inúmeros lançamentos manuais com valores redondos, feitos pelo CFO fora do horário normal. De acordo com o material CFE, esse é um exemplo clássico de:","tag":"Técnicas de Ocultação","options":["A. Erro contábil por falta de treinamento","B. Técnica de ocultação de fraude","C. Procedimento normal de fechamento contábil","D. Ajuste de estimativas dentro dos GAAP"],"correct":1,"justification_correct":"Lançamentos com valores redondos, sobreposições manuais e horários incomuns são métodos clássicos identificados pelo manual CFE como técnicas usadas para disfarçar atividades fraudulentas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Erros por falta de treinamento e ajustes de estimativas são explicações legítimas; fechamentos normais não ocorrem fora do horário — a combinação de fatores suspeitos indica técnica de ocultação."},
    {"num":25,"text":"Um gestor em subsidiária com dificuldades vende estoque com forte desconto à empresa-mãe, que o revende ao preço normal, permitindo à subsidiária registrar lucro rápido sem afetar o consolidado. Isso pode ser um exemplo de:","tag":"Partes Relacionadas","options":["A. Abuso de transações com partes relacionadas","B. Channel stuffing entre unidades do grupo","C. Capitalização indevida de estoques","D. Esquema de vendor fantasma entre empresas"],"correct":0,"justification_correct":"Transações entre entidades afiliadas estruturadas para manipular o desempenho de uma entidade à custa de outra — sem divulgação adequada — configuram abuso de transações com partes relacionadas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Channel stuffing envolve excesso de envios a distribuidores; capitalização e vendor fantasma são esquemas distintos — a manipulação entre entidades do mesmo grupo é abuso de partes relacionadas."},
]

# ── Q26-50: Law ────────────────────────────────────────────────────────────────
law = [
    {"num":1,"text":"Uma empresa demite funcionário após investigação interna concluir ser 'mais provável que sim' que ele submeteu despesas fraudulentas. O Ministério Público recusa denúncia criminal. Qual é a razão mais provável?","tag":"Ônus da Prova","options":["A. A empresa não tinha competência para investigar o funcionário","B. O funcionário tem imunidade por ter cooperado na investigação","C. A prova cumpriu preponderância da prova, mas não prova além de dúvida razoável","D. A empresa descumpriu o devido processo legal ao demiti-lo"],"correct":2,"justification_correct":"Processos internos/cíveis exigem preponderância da prova (mais provável que sim); processos criminais exigem prova além de dúvida razoável — limiar muito mais elevado que justifica a diferença de desfecho. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Competência investigativa, imunidade e devido processo não explicam a diferença de resultado — é a distinção entre os padrões de prova civil e criminal."},
    {"num":2,"text":"Um investigador provou que o relatório continha informações falsas, que o diretor sabia que eram falsas e que investidores sofreram danos. O caso falha em tribunal. Qual elemento da fraude provavelmente faltou?","tag":"Elementos da Fraude","options":["A. Conhecimento da falsidade da declaração","B. Intenção de enganar as vítimas","C. Materialidade do dano causado","D. Confiança (reliance) da vítima na declaração falsa"],"correct":3,"justification_correct":"Para fraude na common law, a vítima deve ter efetivamente confiado e dependido da declaração falsa ao tomar sua decisão — sem essa ligação causal, o caso não se sustenta mesmo com os demais elementos presentes. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Conhecimento, intenção e dano foram provados — o elemento ausente é o reliance (confiança), que vincula causalmente a declaração falsa à decisão da vítima."},
    {"num":3,"text":"Durante entrevista, o examinador diz ao suspeito: 'Se confessar agora, garanto que a empresa não reporta à polícia'. O suspeito confessa. Por que essa confissão provavelmente será inadmissível?","tag":"Admissibilidade de Prova","options":["A. Não foi voluntária por ter sido obtida mediante promessa indevida de clemência","B. O examinador não era funcionário público autorizado","C. A entrevista não foi gravada em vídeo","D. O suspeito não foi acompanhado por advogado"],"correct":0,"justification_correct":"Uma confissão deve ser voluntária e livre de coerção. Oferecer promessa de evitar ação legal em troca de confissão invalida sua voluntariedade, tornando-a inadmissível. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O examinador privado não precisa ser funcionário público; gravação e advogado são relevantes em contextos criminais com custódia — o problema central é a promessa que vicia a voluntariedade."},
    {"num":4,"text":"Um examinador obtém legalmente um documento original falsificado. Qual é o procedimento mais crítico a seguir?","tag":"Cadeia de Custódia","options":["A. Fazer cópias digitais e destruir o original para proteção","B. Compartilhar imediatamente com as autoridades policiais","C. Armazenar em local seguro sem necessidade de documentação","D. Documentar cadeia de custódia completa e cronológica"],"correct":3,"justification_correct":"A cadeia de custódia documenta cronologicamente o manuseio da prova, sendo essencial para provar que não foi adulterada entre a coleta e a apresentação em tribunal. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Destruir o original, compartilhar prematuramente e armazenar sem documentação comprometem a integridade da prova — a cadeia de custódia é o procedimento crítico fundamental."},
    {"num":5,"text":"Um contabilista reporta de boa-fé fraude de valores mobiliários às autoridades. Subsequentemente, é despromovido e recebe tarefas menores. Qual é a consequência mais provável para a empresa?","tag":"Proteção ao Whistleblower","options":["A. O contabilista deve provar intenção de retaliação para obter reparação","B. A empresa pode ser processada apenas se o contabilista tiver provas documentadas","C. A empresa pode enfrentar ações legais e penalidades por retaliar contra o denunciante","D. Nenhuma consequência, pois a demissão foi formal e documentada"],"correct":2,"justification_correct":"Leis de proteção ao whistleblower proíbem especificamente ações adversas — demissão, rebaixamento, assédio — contra funcionários que denunciam má conduta de boa-fé. (Sarbanes-Oxley Act, Dodd-Frank; CFE Fraud Examiners Manual 2024)","justification_wrong":"A retaliação é proibida independentemente da prova de intenção explícita; a formalidade da demissão não protege a empresa quando há nexo com a denúncia."},
    {"num":6,"text":"Dois indivíduos concordam em criar e vender faturas falsas a uma empresa. Elaboram as faturas, mas são detidos antes de enviá-las. Qual estatuto provavelmente violaram?","tag":"Conspiração","options":["A. Fraude eletrônica, por usar computador para elaborar as faturas","B. Falsificação de documentos comerciais","C. Conspiração para cometer fraude, pelo acordo para praticar ato ilícito","D. Tentativa de fraude, pois o ato principal não foi concluído"],"correct":2,"justification_correct":"A conspiração criminaliza o próprio acordo entre as partes para cometer um ato ilícito — independentemente de o ato principal ser ou não concluído. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Fraude eletrônica exige uso de comunicação eletrônica na execução do esquema; falsificação e tentativa são categorias distintas — o acordo em si configura conspiração."},
    {"num":7,"text":"Um investigador deseja usar em tribunal a declaração: 'Meu colega me disse que viu o diretor destruindo documentos'. Por que o tribunal provavelmente excluiria essa declaração?","tag":"Hearsay","options":["A. É considerada prova de ouvir dizer (hearsay) e geralmente inadmissível","B. O colega deveria ter reportado diretamente às autoridades","C. A declaração foi feita sem testemunhas presentes","D. O investigador não é advogado e não pode apresentar provas"],"correct":0,"justification_correct":"Hearsay é declaração feita fora do tribunal, oferecida para provar a verdade dos fatos — geralmente inadmissível, salvo exceções específicas previstas nas normas de evidência. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O dever de reportar, a presença de testemunhas e a qualificação do investigador não são as razões para a exclusão — é a natureza de ouvir dizer da declaração."},
    {"num":8,"text":"O conselho jurídico contrata examinador para investigar potencial litígio. A parte contrária solicita as notas e análises do examinador. Qual princípio legal protege esses materiais?","tag":"Work Product Doctrine","options":["A. Privilégio advogado-cliente","B. Sigilo profissional do examinador","C. Confidencialidade das investigações internas","D. Doutrina do produto de trabalho (Work product doctrine)"],"correct":3,"justification_correct":"A work product doctrine protege especificamente materiais preparados por ou para uma parte (ou seu representante) em antecipação de litígio — incluindo notas e análises de investigadores contratados pelo conselho jurídico. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Privilégio advogado-cliente protege comunicações confidenciais; sigilo profissional e confidencialidade interna têm escopos distintos — a work product doctrine é a proteção específica para materiais preparados para litígio."},
    {"num":9,"text":"Qual das seguintes provas seria considerada prova DIRETA de um roubo?","tag":"Tipos de Prova","options":["A. Conta bancária do suspeito com depósitos inexplicáveis no período do furto","B. Imagens de segurança mostrando o funcionário retirando dinheiro do cofre","C. Testemunho de colega afirmando que o suspeito 'parecia nervoso' no dia","D. Documentos mostrando que o suspeito tinha acesso ao cofre"],"correct":1,"justification_correct":"Prova direta comprova o fato em questão por si mesma, sem necessidade de inferência — as imagens mostram diretamente o ato de subtrair o dinheiro. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Depósitos inexplicáveis, nervosismo e acesso ao cofre são provas circunstanciais que requerem inferência para estabelecer a ligação ao crime."},
    {"num":10,"text":"Um examinador acessa sem consentimento a conta pessoal de armazenamento em nuvem de um funcionário suspeito e encontra provas incriminatórias. Qual é o risco legal mais significativo?","tag":"Admissibilidade de Prova","options":["A. O examinador pode ser responsabilizado por danos morais","B. A prova pode ser suprimida por violação de leis de privacidade","C. O funcionário pode processar a empresa por demissão indevida","D. A investigação perde validade por vício de procedimento interno"],"correct":1,"justification_correct":"Prova obtida ilegalmente pode ser excluída sob a regra de exclusão — mesmo quando obtida por entidade privada, se usada em processo criminal ou direcionada por autoridades, pode violar leis de privacidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Danos morais e demissão indevida são consequências secundárias; vício de procedimento interno é menos grave — a supressão da prova é o risco legal primário e mais significativo."},
    {"num":11,"text":"Em julgamento civil, o advogado contesta a admissibilidade do testemunho de um perito contábil sob o Padrão Daubert. Qual fator o tribunal teria MENOS probabilidade de considerar?","tag":"Padrão Daubert","options":["A. Se a teoria ou técnica pode ser testada e foi testada","B. Se o método foi revisado por pares e publicado","C. A convicção pessoal do perito na precisão de seus resultados","D. A taxa de erro conhecida ou potencial da metodologia"],"correct":2,"justification_correct":"O Padrão Daubert foca em indicadores objetivos e verificáveis de confiabilidade metodológica — não na crença subjetiva ou confiança pessoal do perito em seus próprios resultados. (Daubert v. Merrell Dow Pharmaceuticals; CFE Fraud Examiners Manual 2024)","justification_wrong":"Testabilidade, revisão por pares e taxa de erro são critérios objetivos do Padrão Daubert — apenas a convicção pessoal é critério subjetivo excluído da análise."},
    {"num":12,"text":"Uma empresa foi induzida a assinar contrato por falsas alegações sobre as capacidades de um produto. Em processo civil, a empresa quer anular o contrato como se nunca tivesse existido. Qual recurso legal é apropriado?","tag":"Recursos Legais","options":["A. Rescisão (Rescission) do contrato","B. Indenização por perdas e danos","C. Injunção proibindo o fornecedor de atuar no mercado","D. Arbitragem para renegociação dos termos"],"correct":0,"justification_correct":"A rescisão é o recurso legal específico que cancela e anula um contrato, tratando-o efetivamente como se nunca tivesse existido — adequado quando o contrato foi obtido por fraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Indenização compensa danos mas mantém o contrato; injunção limita atividades futuras; arbitragem renegocia — apenas a rescisão anula retroativamente o contrato."},
    {"num":13,"text":"Um CFE acusa publicamente um gestor específico de desvio de fundos nas redes sociais antes de a investigação estar concluída. Essa ação expõe o CFE a qual responsabilidade legal?","tag":"Responsabilidade do CFE","options":["A. Violação do sigilo profissional da ACFE","B. Difamação por acusação pública não fundamentada","C. Fraude processual por interferir na investigação","D. Quebra de contrato com o cliente que o contratou"],"correct":1,"justification_correct":"Fazer acusação pública não fundamentada que prejudica a reputação de um indivíduo pode configurar difamação (calúnia oral ou injúria escrita), expondo o CFE a responsabilidade civil. (ACFE Code of Professional Standards; CFE Fraud Examiners Manual 2024)","justification_wrong":"Sigilo profissional, fraude processual e quebra de contrato são preocupações relevantes mas secundárias — a difamação é o risco legal primário de acusações públicas precipitadas."},
    {"num":14,"text":"Qual é o foco principal de um processo criminal por fraude, em contraposição a um processo civil?","tag":"Processo Criminal vs Civil","options":["A. Obter compensação financeira para a vítima pelo dano sofrido","B. Recuperar os ativos desviados e restituir a organização prejudicada","C. Punir o infrator e proteger o interesse público","D. Determinar a responsabilidade civil e o valor das perdas"],"correct":2,"justification_correct":"O direito penal visa punir atos que prejudicam a sociedade e desencorajar futura má conduta — representando o interesse público, não apenas o interesse privado da vítima. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Compensação financeira, recuperação de ativos e responsabilidade civil são objetivos de processos civis — o processo criminal foca na punição e proteção da sociedade."},
    {"num":15,"text":"O conselho jurídico envia e-mail ao CEO com aconselhamento legal sobre fraude. O CEO reencaminha esse e-mail para auditores externos. Qual é o efeito mais provável dessa ação?","tag":"Privilégio Advogado-Cliente","options":["A. O privilégio advogado-cliente é provavelmente renunciado","B. O privilégio é mantido porque os auditores são parceiros de confiança","C. O privilégio é estendido para cobrir os auditores externos","D. O e-mail torna-se confidencial por ser enviado por CEO"],"correct":0,"justification_correct":"Incluir terceiros que não fazem parte da relação legal confidencial — como auditores externos — geralmente quebra o privilégio advogado-cliente, pois o sigilo é condição essencial da proteção. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditores externos não são protegidos pelo privilégio; a posição de CEO não confere privilégio automático — qualquer divulgação a terceiros não cobertos geralmente anula o privilégio."},
    {"num":16,"text":"Um examinador conclui que um suspeito é culpado com base apenas em nervosismo e evitação de contato visual durante entrevista. Por que essa conclusão é problemática do ponto de vista probatório?","tag":"Prova Circunstancial","options":["A. Prova circunstancial comportamental requer corroboração substancial","B. O examinador violou o princípio de presunção de inocência","C. Observações comportamentais não são permitidas em investigações","D. O suspeito deveria ter sido informado que estava sendo avaliado"],"correct":0,"justification_correct":"Indicadores comportamentais são formas fracas de prova circunstancial que podem ser mal interpretadas — requerem corroboração probatória substancial antes de sustentar conclusões sobre culpabilidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Presunção de inocência é relevante, mas a questão é probatória; observações comportamentais são permitidas mas devem ser contextualizadas; informar o suspeito não é requisito para observação."},
    {"num":17,"text":"Qual direito fundamental garante que os procedimentos legais serão justos e que os indivíduos serão notificados e terão oportunidade de ser ouvidos?","tag":"Devido Processo","options":["A. Direito à presunção de inocência","B. Direito ao contraditório em processos administrativos","C. Direito à proteção contra auto-incriminação","D. Direito ao devido processo legal (Due process)"],"correct":3,"justification_correct":"O devido processo legal é a garantia constitucional de tratamento justo pelo sistema judicial, incluindo notificação adequada e audiência justa — aplicável tanto em processos civis quanto criminais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Presunção de inocência, contraditório e proteção contra auto-incriminação são direitos específicos importantes, mas o due process é o conceito mais abrangente que engloba a garantia de procedimentos justos."},
    {"num":18,"text":"No modelo do 'Diamante da Fraude', a capacidade (capability) se refere a qual atributo do indivíduo?","tag":"Diamante da Fraude","options":["A. A pressão financeira que motiva a ação fraudulenta","B. As competências, autoridade e confiança para explorar uma oportunidade","C. A racionalização que justifica internamente a conduta","D. O acesso físico ou lógico aos recursos da organização"],"correct":1,"justification_correct":"A capacidade no Diamante da Fraude engloba traços pessoais, posição hierárquica, inteligência e autoridade que permitem ao indivíduo não apenas cometer a fraude, mas também ocultá-la eficazmente. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Pressão financeira é o elemento 'pressão'; racionalização é o elemento 'racionalização' do Triângulo; acesso físico é parte da 'oportunidade' — a capacidade refere-se às habilidades e autoridade do perpetrador."},
    {"num":19,"text":"Por que a ausência de segregação de funções é uma fraqueza de controle tão grave?","tag":"Segregação de Funções","options":["A. Cria dependência excessiva de um único funcionário","B. Permite a um único indivíduo perpetrar e ocultar fraude sem conluio","C. Viola requisitos legais de auditoria interna","D. Impede a detecção durante auditorias externas periódicas"],"correct":1,"justification_correct":"Quando uma pessoa controla uma transação desde a autorização até o registro e reconciliação, pode cometer e ocultar fraude sem necessidade de conluio — o controle mais crítico para prevenção de fraudes individuais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Dependência e violações legais são preocupações válidas mas secundárias; a detecção em auditorias externas é afetada mas não é a razão principal — a capacidade de cometer e ocultar sozinho é o risco central."},
    {"num":20,"text":"Um grupo de funcionários usa o sistema de mensagens internas da empresa para planejar um esquema para defraudar um fornecedor. Qual estatuto específico pode ser acionado pelo uso do sistema de mensagens?","tag":"Fraude Eletrônica","options":["A. Fraude eletrônica (Wire fraud) por uso de sistema de comunicação eletrônica","B. Espionagem corporativa por acesso não autorizado ao sistema","C. Conspiração qualificada pela presença de múltiplos participantes","D. Fraude contratual por envolver terceiro fornecedor"],"correct":0,"justification_correct":"Os estatutos de fraude eletrônica aplicam-se ao uso de comunicações eletrônicas — incluindo e-mail e sistemas de mensagens — para executar ou tentar executar um esquema de fraude. (18 U.S.C. § 1343; CFE Fraud Examiners Manual 2024)","justification_wrong":"Espionagem corporativa envolve roubo de informações; conspiração é crime separado; fraude contratual não é o tipo específico ativado pelo uso de comunicação eletrônica."},
    {"num":21,"text":"O relatório final do examinador contém provas sólidas de fraude, mas inclui também opiniões pessoais não fundamentadas sobre o caráter do suspeito. Qual risco profissional essa inclusão apresenta?","tag":"Responsabilidade Profissional","options":["A. Violação do sigilo profissional da ACFE","B. Perda da certificação CFE por conduta antiética","C. Negligência e potencial difamação","D. Conflito de interesses com o cliente"],"correct":2,"justification_correct":"O examinador tem dever de objetividade e de basear conclusões em provas. Incluir opiniões pessoais prejudiciais não suportadas pode ser considerado negligente e difamatório. (ACFE Code of Professional Standards)","justification_wrong":"Sigilo, certificação e conflito de interesses são preocupações relevantes — mas a negligência e difamação são os riscos legais diretamente gerados por opiniões pessoais não fundamentadas em relatório profissional."},
    {"num":22,"text":"Qual afirmação descreve melhor a diferença fundamental entre prova direta e prova circunstancial?","tag":"Tipos de Prova","options":["A. Prova direta é mais confiável; prova circunstancial é inadmissível","B. Prova direta vem de testemunhas; prova circunstancial vem de documentos","C. Prova circunstancial requer inferência para provar um fato; prova direta estabelece o fato por si mesma","D. Prova direta é suficiente por si só; prova circunstancial sempre precisa ser corroborada"],"correct":2,"justification_correct":"A prova direta (como um vídeo do ato) estabelece o fato por si mesma; a prova circunstancial (como riqueza inexplicável) requer inferência lógica para conectar a evidência ao fato a ser provado. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Prova circunstancial pode ser admissível e confiável; ambas podem vir de testemunhas ou documentos; a distinção não é de suficiência mas de necessidade de inferência."},
    {"num":23,"text":"Um vendedor faz conscientemente declaração falsa sobre um produto. O cliente compra o produto, mas não foi influenciado pela declaração falsa — comprou por outra característica. A fraude foi legalmente estabelecida?","tag":"Elementos da Fraude","options":["A. Sim, porque o vendedor sabia que a declaração era falsa","B. Não, porque o elemento de confiança (reliance) está ausente","C. Sim, porque houve dano ao consumidor pela compra","D. Não, porque não houve intenção de causar dano financeiro"],"correct":1,"justification_correct":"Para fraude na common law, todos os elementos devem estar presentes — incluindo o reliance (confiança). Se a decisão de compra foi independente da declaração falsa, a ligação causal se rompe e a fraude não está estabelecida. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O conhecimento da falsidade foi demonstrado; o dano por si só não estabelece fraude sem o nexo causal; a intenção estava presente — o elemento ausente é especificamente o reliance."},
    {"num":24,"text":"Um examinador privado entrevista um funcionário sobre violações de política. O funcionário não está sob custódia policial. Qual direito o examinador NÃO é legalmente obrigado a providenciar?","tag":"Direitos do Investigado","options":["A. Os Avisos de Miranda (direito ao silêncio e a um advogado)","B. Notificação de que a entrevista é voluntária","C. Oportunidade de apresentar sua versão dos fatos","D. Acesso ao relatório final da investigação"],"correct":0,"justification_correct":"Os Avisos de Miranda são exigidos apenas para interrogatórios policiais com suspeito sob custódia — um examinador privado conduzindo entrevista interna sem custódia não é obrigado a fornecê-los. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais opções podem ser práticas recomendadas em investigações internas, mas apenas os Avisos de Miranda são especificamente inaplicáveis em contexto de examinador privado sem custódia."},
    {"num":25,"text":"Um arquivo digital foi copiado de servidor para pen drive, depois para laptop do investigador e finalmente enviado a laboratório forense. O investigador esqueceu de registrar a data e hora da cópia inicial. Por que isso cria problema significativo?","tag":"Cadeia de Custódia","options":["A. Viola regulamentos de proteção de dados ao copiar sem autorização","B. Impede que a prova seja analisada pelo laboratório forense","C. Cria responsabilidade civil para o investigador pela omissão","D. Quebra a cadeia de custódia, tornando a autenticidade da prova contestável"],"correct":3,"justification_correct":"Qualquer lacuna no registro cronológico de manuseio enfraquece a cadeia de custódia e permite que a defesa questione a integridade da prova — a data e hora são elementos essenciais da documentação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Proteção de dados, análise pelo laboratório e responsabilidade civil são preocupações secundárias — a quebra da cadeia de custódia é o problema primário que afeta a admissibilidade da prova."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

# Injeta Financial Transactions
dir1 = Path("static/quizzes/cfe/financial_transactions")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {"cert_id":"cfe","domain_id":"financial_transactions","quiz_num":num1,"domain_name":"Financial Transactions & Fraud Schemes","cert_name":"CFE / ACFE","lang":"pt","questions":financial}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(financial)} questoes (Financial Transactions) salvas em {path1}")

# Injeta Law
dir2 = Path("static/quizzes/cfe/law_cfe")
dir2.mkdir(parents=True, exist_ok=True)
num2 = get_next_num(dir2)
out2 = {"cert_id":"cfe","domain_id":"law_cfe","quiz_num":num2,"domain_name":"Law","cert_name":"CFE / ACFE","lang":"pt","questions":law}
path2 = dir2 / f"quiz_{num2:03d}_pt.json"
path2.write_text(json.dumps(out2, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(law)} questoes (Law) salvas em {path2}")
