#!/usr/bin/env python3
"""
CISM BATCH 8 - Incident Management (continuacao)
15 questoes - adiciona ao quiz_001 de incident_management
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions_new = [
    {"num":16,"text":"Os tipos de testes de plano de resposta a incidentes de segurança são:","tag":"Testes de Planos","options":["A. Revisão de documentos, walkthrough e simulação","B. Revisão de documentos e simulação","C. Revisão de documentos, walkthrough, simulação, teste paralelo e cutover","D. Revisão de documentos, walkthrough e teste cutover"],"correct":0,"justification_correct":"Os tipos de teste de plano de resposta a incidentes são revisão de documentos, walkthrough e simulação. Testes paralelos e cutover são usados em planejamento de recuperação de desastres, não em resposta a incidentes. (CISM Review Manual, ISACA)","justification_wrong":"Teste paralelo e cutover são específicos de recuperação de desastres — não fazem parte dos testes de planos de resposta a incidentes de segurança."},
    {"num":17,"text":"O período de tempo entre a ocorrência de um incidente e sua detecção é conhecido como:","tag":"Métricas de Incidentes","options":["A. Dwell time","B. Lag time","C. Lead time","D. Propagation time"],"correct":0,"justification_correct":"O dwell time refere-se ao período entre a ocorrência de um incidente de segurança e a conscientização da organização sobre sua existência — quanto maior o dwell time, maior o potencial de dano acumulado. (CISM Review Manual, ISACA)","justification_wrong":"Lag time é atraso genérico; lead time é tempo de antecipação; propagation time não é terminologia padrão CISM — dwell time é o termo específico para o período de inconsciência sobre o incidente."},
    {"num":18,"text":"O propósito do privilégio advogado-cliente durante uma investigação é:","tag":"Aspectos Jurídicos","options":["A. Melhorar os resultados da investigação","B. Obter melhores serviços de perícia forense","C. Proteger os procedimentos da investigação de uma ordem de descoberta judicial","D. Melhorar a integridade dos procedimentos investigativos"],"correct":2,"justification_correct":"O privilégio advogado-cliente protege correspondências e registros, incluindo os de uma investigação. Uma organização que crê estar sendo processada pode proteger sua investigação de ordens de descoberta judicial, evitando divulgar informações ao adversário. (CISM Review Manual, ISACA)","justification_wrong":"Melhora de resultados e integridade são benefícios indiretos; serviços forenses não são o foco — a proteção contra ordens de descoberta é o propósito central do privilégio."},
    {"num":19,"text":"O propósito dos procedimentos de cadeia de custódia é:","tag":"Cadeia de Custódia","options":["A. Provar a propriedade dos dados da investigação","B. Determinar a causa de um incidente","C. Provar a integridade dos dados da investigação","D. Determinar quem é responsável por um incidente"],"correct":2,"justification_correct":"O propósito da cadeia de custódia é demonstrar a integridade da investigação — que nenhuma informação foi alterada, incluindo o conteúdo de memória e discos rígidos. (CISM Review Manual, ISACA)","justification_wrong":"Propriedade, causa e responsabilidade são determinadas por outros meios — a cadeia de custódia especificamente garante que as evidências não foram adulteradas desde a coleta."},
    {"num":20,"text":"O propósito de um SIEM (Security Information and Event Management) é:","tag":"SIEM","options":["A. Registrar centralmente dados de eventos","B. Correlacionar eventos e gerar alertas","C. Rastrear a remediação de vulnerabilidades conhecidas","D. Varrer sistemas em busca de novas vulnerabilidades"],"correct":1,"justification_correct":"Um SIEM é um sistema central de processamento de logs de eventos que correlaciona eventos entre vários dispositivos e produz alertas que podem indicar intrusões e outros tipos de incidentes de segurança. (CISM Review Manual, ISACA)","justification_wrong":"Registro centralizado é uma função, mas não o propósito central; rastreamento de vulnerabilidades é função de gestão de vulnerabilidades; varredura é função de scanners — a correlação e geração de alertas é o diferencial do SIEM."},
    {"num":21,"text":"Uma organização não possui pessoal nem ferramentas para conduzir análise forense computacional. Qual é a melhor forma de adquirir essa capacidade?","tag":"Capacidade Forense","options":["A. Adquirir ferramentas avançadas de antimalware","B. Adquirir um SIEM","C. Contratar um retainer de resposta a incidentes","D. Contratar um especialista forense em tempo integral"],"correct":2,"justification_correct":"Uma organização sem pessoal e ferramentas para forense computacional deve contratar um retainer de resposta a incidentes — com esse contrato, especialistas forenses ficam disponíveis on-call para responder a incidentes. Contratar internamente pode ser custoso e demorado. (CISM Review Manual, ISACA)","justification_wrong":"Antimalware e SIEM não fornecem capacidade forense; contratar internamente é válido mas custoso e demorado — o retainer oferece capacidade imediata com custo previsível."},
    {"num":22,"text":"Pessoal de segurança está conduzindo análise forense sobre irregularidades de ex-funcionário onde processos legais são possíveis. Como os resultados devem ser protegidos?","tag":"Forense e Direito","options":["A. Backup em mídia de escrita única","B. Double locked","C. Cadeia de custódia","D. Controle de acesso baseado em função"],"correct":2,"justification_correct":"Os resultados de uma investigação forense, particularmente quando processos legais são possíveis, devem ser protegidos por cadeia de custódia — garantindo que nenhuma informação foi alterada e que as evidências são admissíveis. (CISM Review Manual, ISACA)","justification_wrong":"Backup em mídia de escrita única, double locked e RBAC são controles de proteção físicos ou lógicos — a cadeia de custódia é o procedimento específico que garante integridade para fins legais."},
    {"num":23,"text":"Um respondedor de incidentes declarou um incidente de segurança, mobilizando outros respondedores e a gestão sênior. Posteriormente, constatou-se que nenhum incidente estava ocorrendo. Qual é o melhor curso de ação?","tag":"Gestão de Falsos Positivos","options":["A. Treinar o respondedor que declarou o incidente","B. Disciplinar o respondedor que declarou o incidente","C. Encerrar as atividades de resposta ao incidente","D. Continuar com a resposta ao incidente até sua conclusão"],"correct":0,"justification_correct":"Uma revisão pós-ação pode ser justificada para identificar melhorias nos procedimentos de declaração de incidentes e reduzir a probabilidade de falsos positivos no futuro — sem punir o respondedor que agiu de boa fé. (CISM Review Manual, ISACA)","justification_wrong":"Disciplinar por falso positivo de boa fé é contraproducente; continuar com incidente inexistente desperdiça recursos — treinar melhora o processo sem desmotivar a equipe."},
    {"num":24,"text":"Uma organização detectou ataque de ransomware que destruiu dados em workstations e está destruindo dados em um servidor de arquivos central. O servidor está offline. Qual ação deve ser tomada?","tag":"Resposta a Ransomware","options":["A. Informar a organização que o servidor está indisponível","B. Parar os procedimentos de resposta a incidentes e ativar os planos de continuidade e recuperação","C. Aguardar o fim do incidente e então ativar os planos de continuidade e recuperação","D. Ativar simultaneamente os planos de continuidade e recuperação de desastres"],"correct":3,"justification_correct":"A organização deve imediatamente ativar os planos de continuidade e recuperação de desastres para retomar rapidamente as operações críticas e recuperar o servidor afetado o mais rápido possível. (CISM Review Manual, ISACA)","justification_wrong":"Apenas informar é insuficiente; parar a resposta ao incidente abandona a contenção; aguardar prolonga o impacto — a ativação simultânea é a resposta mais eficaz."},
    {"num":25,"text":"Uma organização com apólice de seguro cibernético detectou ataque de ransomware ativo. Qual deve ser a prioridade máxima da organização?","tag":"Seguro Cibernético","options":["A. Conter e encerrar o incidente, depois notificar a seguradora","B. Notificar imediatamente a seguradora sobre o ataque","C. Notificar a seguradora apenas se o resgate for pago","D. Acionar cadeia de custódia para proteção perante a seguradora"],"correct":1,"justification_correct":"A organização deve notificar imediatamente a seguradora cibernética — seguradoras geralmente assistem seus segurados apenas se forem notificadas imediatamente sobre um ataque. Atrasar a notificação pode comprometer a cobertura. (CISM Review Manual, ISACA)","justification_wrong":"Conter primeiro e notificar depois pode comprometer a cobertura; notificar apenas se pagar o resgate é condição incorreta; cadeia de custódia é procedimento investigativo, não de seguro."},
    {"num":26,"text":"Qual é o objetivo principal de um plano de comunicação de incidentes de segurança?","tag":"Comunicação de Incidentes","options":["A. Documentar todos os detalhes técnicos do incidente para análise posterior","B. Garantir que as partes certas recebam as informações certas no momento certo","C. Cumprir obrigações regulatórias de notificação de violações","D. Proteger a organização de responsabilidade legal durante o incidente"],"correct":1,"justification_correct":"O objetivo central do plano de comunicação é garantir que as partes interessadas corretas — internas e externas — recebam informações apropriadas e oportunas durante e após um incidente. (CISM Review Manual, ISACA)","justification_wrong":"Documentação técnica, conformidade regulatória e proteção legal são objetivos complementares — o propósito central é a comunicação eficaz com as partes certas no momento certo."},
    {"num":27,"text":"Uma organização está desenvolvendo um plano de resposta a incidentes pela primeira vez. Qual elemento é mais crítico para garantir a eficácia do plano?","tag":"Plano de Resposta","options":["A. Incluir procedimentos técnicos detalhados para cada tipo de incidente","B. Obter aprovação e patrocínio da alta gestão","C. Contratar consultores externos especializados em resposta a incidentes","D. Adquirir ferramentas avançadas de detecção e resposta"],"correct":1,"justification_correct":"O patrocínio e aprovação da alta gestão é o elemento mais crítico — sem o suporte executivo, o plano não terá os recursos, a autoridade e o engajamento organizacional necessários para ser eficaz. (CISM Review Manual, ISACA)","justification_wrong":"Procedimentos técnicos, consultores e ferramentas são importantes mas secundários — sem o patrocínio executivo, o plano não obtém os recursos e a autoridade necessários."},
    {"num":28,"text":"Durante a fase de contenção de um incidente de segurança, qual é a consideração mais importante?","tag":"Contenção de Incidentes","options":["A. Preservar todas as evidências digitais antes de qualquer ação de contenção","B. Erradicar imediatamente a ameaça do ambiente","C. Equilibrar a necessidade de contenção com a continuidade das operações de negócio","D. Notificar imediatamente todas as partes interessadas sobre o incidente"],"correct":2,"justification_correct":"Durante a contenção, é essencial equilibrar a necessidade de limitar o dano com a manutenção da continuidade operacional — ações de contenção muito agressivas podem paralisar operações críticas desnecessariamente. (CISM Review Manual, ISACA)","justification_wrong":"Preservação de evidências é importante mas não pode atrasar a contenção; erradicação imediata pode ser prematura; notificação é necessária mas secundária à decisão de contenção."},
    {"num":29,"text":"Qual métrica é mais útil para avaliar a eficácia do processo de resposta a incidentes ao longo do tempo?","tag":"Métricas de Incidentes","options":["A. Número total de incidentes registrados por período","B. Custo médio por incidente de segurança","C. Tempo médio de detecção e tempo médio de resposta","D. Número de ferramentas de segurança implementadas"],"correct":2,"justification_correct":"O tempo médio de detecção (MTTD) e o tempo médio de resposta (MTTR) são as métricas mais diretas para avaliar a eficácia do processo de resposta — medem a velocidade e eficiência do ciclo de vida do incidente. (CISM Review Manual, ISACA)","justification_wrong":"Número de incidentes e custo são métricas de impacto; número de ferramentas é métrica de recursos — MTTD e MTTR medem diretamente a eficácia do processo de resposta."},
    {"num":30,"text":"Uma lição aprendida após um incidente de ransomware revelou que o backup não havia sido testado. Qual controle teria prevenido esse problema?","tag":"Lições Aprendidas","options":["A. Política formal de backup e retenção","B. Testes regulares e documentados dos procedimentos de restauração","C. Criptografia das mídias de backup","D. Armazenamento offsite das mídias de backup"],"correct":1,"justification_correct":"Testes regulares e documentados dos procedimentos de restauração garantem que os backups são funcionais e que a equipe sabe como executar a recuperação — a política sem teste não garante a capacidade de recuperação. (CISM Review Manual, ISACA)","justification_wrong":"Política de backup, criptografia e armazenamento offsite são controles importantes mas não garantem que a restauração funcione — apenas os testes regulares validam a capacidade real de recuperação."},
]

def add_to_quiz(quiz_path, new_questions):
    if not quiz_path.exists():
        return False, 0
    data = json.loads(quiz_path.read_text(encoding="utf-8"))
    existing = data.get("questions", [])
    if len(existing) >= 50:
        return False, len(existing)
    next_num = len(existing) + 1
    for i, q in enumerate(new_questions):
        q["num"] = next_num + i
    existing.extend(new_questions)
    data["questions"] = existing[:50]
    quiz_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

path = Path("static/quizzes/cism/incident_management/quiz_001_pt.json")
ok, total = add_to_quiz(path, questions_new)
if ok:
    print(f"OK - {len(questions_new)} questoes adicionadas ao incident_management/quiz_001_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total >= 50 else f" (faltam {50-total})"))
else:
    print(f"Quiz nao encontrado ou ja completo. Total: {total}")
