#!/usr/bin/env python3
"""
CISM BATCH 12 - Risk Management Avancado
25 questoes -> info_risk_management/quiz_002 (fecha em 50)
5 questoes  -> info_security_governance/quiz_004
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

q_risk = [
    {"num":26,"text":"Todas as atividades a seguir são entradas típicas para um processo de reporte de riscos, EXCETO:","tag":"Processo de Risco","options":["A. Revisões de código","B. Avaliações de riscos","C. Avaliações de ameaças","D. Auditorias internas"],"correct":0,"justification_correct":"Revisão de código não é entrada típica para processo de reporte de riscos — é exame tático e estreito de código-fonte, cujo output alimenta processos de gestão de vulnerabilidades, não de reporte de riscos. (CISM Review Manual, ISACA)","justification_wrong":"Avaliações de riscos, ameaças e auditorias internas identificam problemas sistêmicos que tipicamente alimentam o processo de gestão e reporte de riscos."},
    {"num":27,"text":"Quais são os possíveis resultados de um risco identificado e analisado em um processo de gestão de riscos?","tag":"Tratamento de Riscos","options":["A. Aceitação, evitar, mitigação, transferência e residual","B. Aceitação, eliminação, redução e transferência","C. Aceitação, evitar, eliminação, mitigação e transferência","D. Aceitação, evitar, mitigação e transferência"],"correct":3,"justification_correct":"As quatro opções de tratamento de riscos são: aceitação, evitar, mitigação e transferência. Eliminação não é opção válida (riscos não podem ser eliminados); residual é o risco remanescente após tratamento, não uma opção de tratamento. (CISM Review Manual, ISACA)","justification_wrong":"Eliminação não é opção de tratamento de risco válida; residual é resultado do tratamento, não uma opção — as quatro opções padrão são aceitação, evitar, mitigar e transferir."},
    {"num":28,"text":"Dawn observou que o processo de gestão de riscos de sua organização determina que o CISO toma todas as decisões de tratamento. O que pode concluir?","tag":"Decisão de Risco","options":["A. O processo deve mudar para que outros líderes de negócio possam colaborar nas decisões","B. O processo é adequado pois é responsabilidade do CISO tomar decisões de risco","C. O processo deve mudar para que a auditoria interna aprove as decisões de tratamento","D. O processo deve mudar para que reguladores externos aprovem as decisões de risco"],"correct":0,"justification_correct":"Decisões de tratamento de risco são decisões de negócio que devem ser tomadas por líderes de negócio em colaboração com o CISO. O CISO não deve tomar decisões unilaterais de risco em nome do negócio. (CISM Review Manual, ISACA)","justification_wrong":"CISO unilateral reduz o engajamento do negócio; auditoria interna não aprova decisões de risco; reguladores externos não tomam decisões de risco operacional."},
    {"num":29,"text":"Para qual audiência devem ser enviadas comunicações sobre novos riscos de segurança da informação?","tag":"Comunicação de Riscos","options":["A. Clientes da organização","B. Comitê diretor de segurança e alta gestão","C. Todos os colaboradores","D. Conselho de administração"],"correct":1,"justification_correct":"Novos desenvolvimentos sobre riscos de segurança da informação devem ser enviados ao comitê diretor de segurança e à alta gestão — parte típica do processo de gestão de riscos que inclui comunicação de riscos. (CISM Review Manual, ISACA)","justification_wrong":"Clientes raramente recebem informações de risco interno; todos os colaboradores não precisam de todos os detalhes de risco; o conselho não precisa conhecer todos os riscos individualmente."},
    {"num":30,"text":"Uma auditoria interna concluiu que vários controles são ineficazes. Qual é o próximo passo recomendado?","tag":"Controles Ineficazes","options":["A. Correlacionar resultados com teste de penetração apropriadamente escopado","B. Desenvolver controles compensatórios para reduzir riscos","C. Realizar avaliação de riscos","D. Desenvolver plano de ação baseado em riscos para remediar controles ineficazes"],"correct":3,"justification_correct":"Organizações são tipicamente compelidas a remediar a maioria ou todos os achados da auditoria interna. Uma abordagem baseada em riscos para desenvolver plano de ação é sensata — permite remediar achados priorizando pelos de maior risco primeiro. (CISM Review Manual, ISACA)","justification_wrong":"Pentest não resolve ineficácia de controles; controles compensatórios não são o recurso padrão; avaliação de riscos não remedeia achados de auditoria — plano de ação é o próximo passo correto."},
    {"num":31,"text":"Um gestor de riscos foi solicitado pela alta gestão a remover um achado do relatório final. Isso é exemplo de quê?","tag":"Aceitação de Risco","options":["A. Gerrymandering","B. Política interna","C. Evitar o risco","D. Aceitação do risco"],"correct":3,"justification_correct":"A remoção implícita de um achado de risco de um relatório é, implicitamente, aceitação do risco. Poderia ser ainda pior — em algumas indústrias poderia ser considerado negligência. O gestor de riscos normalmente deve se opor a tal ação. (CISM Review Manual, ISACA)","justification_wrong":"Gerrymandering é termo eleitoral; política interna é possível mas não a melhor resposta; evitar o risco é descontinuar a atividade — remover achado do relatório é forma de aceitação implícita."},
    {"num":32,"text":"Ravila, CISO, apresenta métricas à gestão. A métrica 'Percentual de patches aplicados dentro do SLA' caiu de 100% para 74.5% nos últimos meses. O que Ravila deve fazer?","tag":"Métricas de Segurança","options":["A. Explicar que os níveis de risco caíram correspondentemente","B. Nenhuma ação é necessária pois isso é normal para patching","C. Investigar a causa da redução e reportar à gestão","D. Aguardar o próximo mês para ver se a métrica volta ao normal"],"correct":2,"justification_correct":"Como o patching é atividade crítica que suporta operações de negócio, essa queda súbita na cobertura precisa ser investigada imediatamente e corrigida o mais rápido possível. (CISM Review Manual, ISACA)","justification_wrong":"Redução de patching não implica queda de risco; não é situação normal; aguardar sem agir é imprudente para atividade crítica como patching de servidores."},
    {"num":33,"text":"Duncan, CISO de grande empresa de energia, recebeu aviso sobre falha grave em CPUs Intel. Antes de analisar o impacto nos dispositivos ICS, qual é o melhor primeiro passo?","tag":"Gestão de Riscos de Advisories","options":["A. Reportar a situação à gestão executiva","B. Criar nova entrada no registro de riscos","C. Analisar a situação para entender o impacto no negócio","D. Declarar incidente de segurança"],"correct":2,"justification_correct":"Embora seja tentador notificar imediatamente a gestão, sem entender o impacto potencial no negócio há pouco a comunicar. O primeiro passo é analisar o advisory para que algum impacto de negócio possa ser determinado. (CISM Review Manual, ISACA)","justification_wrong":"Reportar sem análise prévia deixa a gestão sem informação útil; registro de riscos vem após a análise; declarar incidente é prematuro antes de confirmar o impacto."},
    {"num":34,"text":"Após analisar o advisory e confirmar que muitos dispositivos ICS são Intel, Duncan deve:","tag":"Gestão de Riscos","options":["A. Criar nova entrada no registro de riscos","B. Reportar à gestão executiva com impacto e plano de remediação","C. Criar entrada no registro de vulnerabilidades","D. Declarar incidente de segurança"],"correct":1,"justification_correct":"Após confirmar o impacto, Duncan deve reportar à gestão executiva com explicação do impacto no negócio e plano de remediação — pois o impacto é agora conhecido e a gestão precisa estar ciente. (CISM Review Manual, ISACA)","justification_wrong":"Registro de riscos pode ser criado mas não é o passo mais urgente; vulnerabilidades são táticas; declarar incidente não é apropriado para advisory ainda não explorado."},
    {"num":35,"text":"Auditoria interna encontrou que 20% das contas de usuários de funcionários desligados não foram removidas. Qual ação corretiva é recomendada?","tag":"Controles de Acesso","options":["A. Aumentar a frequência de revisões de acesso para duas vezes por semana","B. Aumentar a frequência de revisões de acesso para semanal","C. Nenhuma ação necessária pois 20% é taxa de falha aceitável","D. Melhorar o processo de desligamento para reduzir o número de encerramentos perdidos"],"correct":3,"justification_correct":"A taxa de encerramento de contas incorreto está muito alta. O melhor remédio é encontrar formas de melhorar o processo de desligamento. Aumentar a frequência de revisões provavelmente requer muito esforço; 20% não é taxa aceitável. (CISM Review Manual, ISACA)","justification_wrong":"Revisões mais frequentes consomem muito esforço sem resolver a causa raiz; 20% de miss não é aceitável — melhorar o processo de desligamento ataca a causa raiz."},
    {"num":36,"text":"Russ está completando questionário de autoavaliação para conformidade com PCI DSS. Nenhum auditor verificará a precisão. Qual é o melhor curso de ação?","tag":"Ética Profissional","options":["A. Completar o formulário com veracidade e notificar a gestão sobre as exceções","B. Completar o formulário com veracidade e submeter às autoridades","C. Marcar cada controle como conforme e submeter","D. Marcar cada controle como conforme e notificar a gestão que precisa ser veraz na próxima submissão"],"correct":0,"justification_correct":"Profissionais de segurança com certificações como CISM devem ser verídicos, mesmo quando isso signifique consequências pessoais, profissionais ou organizacionais. O formulário deve ser preenchido com veracidade e a gestão notificada sobre exceções. (CISM Review Manual, ISACA)","justification_wrong":"Marcar controles como conformes quando não são é antiético e potencialmente fraudulento; submeter às autoridades sem consultar a gestão é precipitado."},
    {"num":37,"text":"Membros do comitê diretor de cibersegurança decidiram descontinuar nova funcionalidade da plataforma de mídia social da organização. Isso é exemplo de:","tag":"Tratamento de Riscos","options":["A. Transferência de risco","B. Aceitação do risco","C. Mitigação do risco","D. Evitar o risco"],"correct":3,"justification_correct":"Evitar o risco é uma das quatro opções de tratamento — a atividade associada ao risco identificado é descontinuada. Descontinuar a funcionalidade é evitar o risco associado a ela. (CISM Review Manual, ISACA)","justification_wrong":"Transferência repassa a terceiros; aceitação mantém a atividade assumindo o risco; mitigação implementa controles — descontinuar a atividade é especificamente evitar o risco."},
    {"num":38,"text":"Auditoria interna encontrou que 20% das contas de terminados não foram encerradas. O controle é 'contas encerradas em 48 horas'. Qual recomendação deve fazer a auditoria?","tag":"Controles","options":["A. Alterar o prazo do controle de 48 horas para 7 dias","B. Adicionar controle compensatório para revisão mensal de contas de terminados","C. Adicionar mais pessoal à equipe de gestão de contas","D. Nenhuma mudança necessária pois 20% é taxa de falha aceitável"],"correct":1,"justification_correct":"Um controle compensatório na forma de revisão periódica de acesso é a melhor resposta — revisões periódicas são comuns e usadas para este propósito. O prazo de 48 horas está correto; 20% não é taxa aceitável; mais pessoal não resolve a causa. (CISM Review Manual, ISACA)","justification_wrong":"Estender para 7 dias relaxa o controle sem resolver o problema; mais pessoal pode não ser a causa raiz; 20% não é aceitável — controle compensatório de revisão periódica é a solução prática."},
    {"num":39,"text":"Provedor SaaS realiza pentests anuais com muitos achados. O CISO deve recomendar todas as seguintes mudanças, EXCETO:","tag":"Testes de Segurança","options":["A. Adicionar revisão de segurança ao SDLC para mudanças propostas","B. Introduzir treinamento de codificação segura para desenvolvedores","C. Aumentar a frequência de pentests de anual para trimestral","D. Incluir requisitos de segurança e privacidade no SDLC"],"correct":2,"justification_correct":"Aumentar a frequência de pentests provavelmente não resolverá a causa raiz — que é a criação de muitos defeitos de segurança. As outras medidas abordam diretamente a causa raiz integrando segurança no desenvolvimento. (CISM Review Manual, ISACA)","justification_wrong":"Revisão de segurança no SDLC, treinamento de codificação segura e requisitos de segurança no SDLC atacam a causa raiz dos defeitos de segurança — pentest mais frequente apenas detecta, não previne."},
    {"num":40,"text":"Provedor SaaS quer reportar resultados de pentest à gestão executiva. Qual é o melhor método?","tag":"Reporte de Segurança","options":["A. Desenvolver KRI que ilustre o risco representado pelos defeitos de segurança ao longo do tempo","B. Distribuir relatórios de pentest à gestão para compreensão do problema","C. Distribuir sumário executivo dos relatórios de pentest","D. Reportar o número de defeitos encontrados"],"correct":0,"justification_correct":"Um KRI deve ser desenvolvido para ilustrar o risco que os defeitos de segurança representam para a organização — por exemplo, 'Número de dias que vulnerabilidades críticas existiram em aplicações de produção'. (CISM Review Manual, ISACA)","justification_wrong":"Relatórios técnicos são muito detalhados para executivos; sumário executivo é melhor mas KRI é mais acionável; número de defeitos isolado não expressa risco de negócio."},
    {"num":41,"text":"O número de dias que vulnerabilidades críticas de software não mitigadas existiram em aplicações de produção é o melhor KRI porque:","tag":"KRI","options":["A. Número de vulnerabilidades em aplicações SaaS de produção","B. Total de dias que vulnerabilidades não mitigadas existiram em produção","C. Número de scans de vulnerabilidade realizados em produção","D. Nomes dos desenvolvedores que introduziram mais defeitos"],"correct":1,"justification_correct":"O total de dias que vulnerabilidades não mitigadas existiram em produção é o melhor KRI — especialmente rastreado ao longo do tempo. Captura tanto a quantidade de vulnerabilidades quanto a velocidade de remediação, expressando risco de negócio real. (CISM Review Manual, ISACA)","justification_wrong":"Número isolado de vulnerabilidades não expressa suficientemente o risco; scans realizados não medem risco; nomes de desenvolvedores não são KRI adequado."},
    {"num":42,"text":"O número de defeitos de segurança em aplicações SaaS está crescendo gradualmente para níveis inaceitáveis. Qual é o melhor primeiro passo?","tag":"Gestão de Riscos","options":["A. Contatar o líder de desenvolvimento de software e reportar que mais defeitos estão sendo criados","B. Iniciar processo de aquisição de WAF","C. Iniciar incidente de baixa severidade","D. Criar nova entrada no registro de riscos descrevendo o problema e possíveis correções"],"correct":3,"justification_correct":"Quando há tendência perturbadora, criar entrada no registro de riscos é o melhor primeiro passo — isso facilitará ação na organização, permitindo que líderes de tecnologia e negócio discutam e tomem decisões para gerenciar o risco. (CISM Review Manual, ISACA)","justification_wrong":"Contatar o líder de desenvolvimento é prudente mas não o primeiro passo formal; WAF pode não ser a melhor solução; incidente não é a classificação correta para tendência de defeitos."},
    {"num":43,"text":"Qual é o melhor método para reportar riscos à gestão sênior?","tag":"Comunicação de Riscos","options":["A. Enviar relatórios pós-ação de revisão de incidentes de segurança","B. Enviar resultados de decisões de tratamento de riscos","C. Relatório periódico sobre o conteúdo do registro de riscos","D. Enviar memos cada vez que novo risco é identificado"],"correct":2,"justification_correct":"O melhor método é fornecer briefing resumido periódico sobre o conteúdo do registro de riscos — isso permite à equipe de liderança focar nas áreas-chave ou riscos emergentes e entender melhor o catálogo completo de riscos não gerenciados. (CISM Review Manual, ISACA)","justification_wrong":"Relatórios pós-ação são sobre incidentes passados; resultados de tratamento são parciais; memos para cada risco sobrecarregam a gestão — o briefing periódico do registro é o método mais eficaz."},
    {"num":44,"text":"Janice identificou que engenharia só contata segurança antes do lançamento de produtos. Qual é a melhor solução de longo prazo?","tag":"Security by Design","options":["A. Introduzir segurança nas etapas conceitual, de requisitos e de design do desenvolvimento","B. Treinar engenharia em uso de ferramentas de varredura de vulnerabilidades","C. Adicionar requisitos de segurança a outros requisitos desenvolvidos nos projetos","D. Não há problema — é adequado que engenharia contate segurança antes do lançamento"],"correct":0,"justification_correct":"A melhor solução é introduzir segurança no ciclo de vida de desenvolvimento de produtos desde a fase conceitual, passando por requisitos e design — garantindo que os produtos sejam seguros por design. (CISM Review Manual, ISACA)","justification_wrong":"Varredura de vulnerabilidades não identifica todos os problemas; adicionar apenas requisitos não é suficiente; contatar apenas antes do lançamento é tarde demais para mudanças significativas."},
    {"num":45,"text":"Qual é o melhor primeiro passo para Janice resolver o problema de segurança sendo adicionada apenas antes do lançamento?","tag":"Gestão de Riscos","options":["A. Iniciar incidente de baixa severidade","B. Criar nova entrada no registro de riscos descrevendo o problema e possíveis correções","C. Iniciar incidente de alta severidade","D. Escrever memo ao líder da engenharia solicitando que segurança seja adicionada ao SDLC"],"correct":1,"justification_correct":"Criar entrada no registro de riscos é o melhor primeiro passo — presumindo que existe um conselho de cibersegurança cross-funcional, o próximo passo será a discussão mais ampla que levará a uma decisão eventual. (CISM Review Manual, ISACA)","justification_wrong":"Incidentes não são a classificação correta para problemas de processo; memo unilateral ao líder de engenharia é decisão unilateral do CISO — o registro de riscos inicia o processo colaborativo correto."},
    {"num":46,"text":"Ransomware executando na estação de trabalho de um usuário final é exemplo de:","tag":"Classificação de Eventos","options":["A. Incidente","B. Vulnerabilidade","C. Ameaça","D. Ameaça interna"],"correct":0,"justification_correct":"Ransomware executando em uma estação de trabalho é considerado um incidente — pode ter sido permitido por uma ou mais vulnerabilidades. (CISM Review Manual, ISACA)","justification_wrong":"Vulnerabilidade é a fraqueza que permitiu a execução; ameaça é o ransomware em si como conceito; ameaça interna é clicar em phishing, não o ransomware em si — o ransomware executando é o incidente."},
    {"num":47,"text":"Joel, CISO em empresa manufatureira, identificou novo risco cibernético e está discutindo-o privadamente com o CRO, que pediu para não incluir no registro de riscos. Que forma de tratamento isso representa?","tag":"Tratamento de Riscos","options":["A. Não é tratamento de risco, mas recusa de gerenciar o risco","B. Evitar o risco, a organização elege evitar completamente","C. Transferência de risco, implicitamente transferido para o seguro","D. Aceitação do risco, a organização aceitando o risco como está"],"correct":0,"justification_correct":"A 'ocultação' deliberada de um risco não é tratamento de risco, mas recusa de lidar com o risco completamente. Embora possa haver razões legítimas, há aparência de negligência ou encobrimento por parte do CRO. (CISM Review Manual, ISACA)","justification_wrong":"Evitar requer descontinuar a atividade; transferência requer ação formal com terceiro; aceitação requer documentação formal no registro — não documentar é recusa de gestão, não tratamento."},
    {"num":48,"text":"Qual é o melhor método para priorizar riscos e tratamentos?","tag":"Priorização de Riscos","options":["A. Probabilidade do evento vezes valor do ativo, do maior para o menor","B. Probabilidade do evento seguida pelo valor do ativo","C. Julgamento profissional","D. Combinação de probabilidade do evento, valor do ativo e julgamento profissional"],"correct":3,"justification_correct":"O melhor método combina probabilidade de ocorrência (difícil de determinar), valor do ativo e impacto para a organização, com julgamento profissional — fatores como reputação do negócio são difíceis de quantificar mas importantes. (CISM Review Manual, ISACA)","justification_wrong":"Probabilidade × ativo não deixa espaço para julgamento; apenas probabilidade ignora impacto; julgamento isolado ignora dados objetivos — a combinação é mais robusta."},
    {"num":49,"text":"Uma empresa comissionou avaliação de riscos externa. Quem deve ser o dono de cada risco identificado?","tag":"Propriedade de Riscos","options":["A. O conselho de administração","B. O gestor de segurança","C. Chefes de departamento","D. A empresa externa"],"correct":2,"justification_correct":"A propriedade de riscos é melhor atribuída a chefes de departamento e líderes de unidades de negócio associados à atividade onde o risco existe — eles têm o contexto e a responsabilidade pelo processo de negócio afetado. (CISM Review Manual, ISACA)","justification_wrong":"Conselho raramente é atribuído como dono de riscos individuais; gestor de segurança e empresa externa não têm responsabilidade sobre as operações de negócio onde o risco existe."},
    {"num":50,"text":"Qual categoria de risco seria reportada ao conselho de administração?","tag":"Reporte ao Conselho","options":["A. Todos os riscos disponíveis","B. Riscos em nível de processo","C. Riscos em nível de ativo","D. Riscos no registro ERM"],"correct":3,"justification_correct":"Das opções disponíveis, riscos presentes no registro de ERM (Enterprise Risk Management) seriam reportados ao conselho de administração. Riscos em nível de processo e ativo não seriam normalmente reportados ao conselho — seria quantidade excessiva de detalhe. (CISM Review Manual, ISACA)","justification_wrong":"Todos os riscos seriam excessivos; riscos de processo e ativo são operacionais e táticos demais para o conselho — o ERM representa os riscos estratégicos mais relevantes."},
]

q_gov4 = [
    {"num":11,"text":"Qual é a melhor descrição do que é tratamento de risco?","tag":"Tratamento de Riscos","options":["A. Adicionar um risco ao registro de riscos","B. Atribuir um risco a líder de departamento","C. Reduzir um risco por meio de mitigação","D. Decidir o que fazer com um risco"],"correct":3,"justification_correct":"O tratamento de risco é melhor descrito como uma decisão sobre o que fazer com um risco específico. As escolhas são aceitar, mitigar, transferir ou evitar o risco. (CISM Review Manual, ISACA)","justification_wrong":"Adicionar ao registro e atribuir são atividades de documentação; reduzir por mitigação é apenas uma das opções — tratamento é a decisão abrangente sobre o que fazer."},
    {"num":12,"text":"Um analista de riscos estuda um risco após decisão de mitigação e constata que a mitigação não elimina todo o risco. Como deve proceder?","tag":"Risco Residual","options":["A. Rejeitar o plano de tratamento","B. Registrar o risco residual","C. Informar a gestão que o plano está incompleto","D. Não fazer nada"],"correct":1,"justification_correct":"Após o tratamento de risco, frequentemente existe risco residual que é tipicamente registrado no registro de riscos como novo risco a ser analisado e tratado. (CISM Review Manual, ISACA)","justification_wrong":"Rejeitar o plano é desnecessário; informar que está incompleto é impreciso; não fazer nada equivale a ignorar o risco residual — registrá-lo é o procedimento correto."},
    {"num":13,"text":"Qual é a pessoa mais adequada para ser proprietária de controle relacionado ao acesso a uma aplicação de negócio?","tag":"Propriedade de Controles","options":["A. Chefe do departamento que usa a aplicação","B. Service desk de TI","C. Gestor de segurança","D. Líder de TI"],"correct":0,"justification_correct":"O chefe do departamento que usa a aplicação é o mais adequado para ser proprietário do controle de acesso — essa pessoa decidirá quem deve ter acesso à aplicação e com quais papéis. (CISM Review Manual, ISACA)","justification_wrong":"Service desk executa mudanças de acesso mas não deve revisar seu próprio trabalho; gestor de segurança e líder de TI não conhecem suficientemente as operações de negócio para decidir sobre acesso."},
    {"num":14,"text":"Um departamento de segurança conduz revisões trimestrais de acesso dos usuários ao sistema financeiro. Quem é a melhor pessoa para aprovar o acesso contínuo?","tag":"Revisão de Acesso","options":["A. Gestor de segurança","B. Gerente de TI","C. Controller corporativo","D. Gerentes dos respectivos usuários"],"correct":2,"justification_correct":"A melhor pessoa para aprovar acesso contínuo a uma aplicação é um líder de unidade de negócio ou chefe de departamento — alguém responsável pelos processos de negócio suportados pelo sistema. O controller corporativo é responsável pelas operações financeiras suportadas. (CISM Review Manual, ISACA)","justification_wrong":"Gestor de segurança e gerente de TI não estão familiarizados com operações financeiras; gerentes dos usuários podem não conhecer o departamento financeiro suficientemente."},
    {"num":15,"text":"Qual é a melhor descrição do que é gestão de riscos de segurança da informação?","tag":"Gestão de Riscos","options":["A. Identificar e tratar ameaças à organização","B. Identificar e tratar vulnerabilidades nos sistemas","C. Identificar riscos e tomar decisões sobre eles","D. Identificar riscos e mitigá-los a níveis aceitáveis"],"correct":2,"justification_correct":"A gestão de riscos de segurança da informação consiste em identificar riscos e tomar decisões sobre o que fazer com eles — as decisões podem resultar em mitigação, mas também em aceitação, transferência ou evitar o risco. (CISM Review Manual, ISACA)","justification_wrong":"Ameaças e vulnerabilidades são entradas para o processo; mitigar é apenas uma das opções de tratamento — identificar e decidir é a definição mais abrangente e correta."},
]

def add_to_quiz(path, new_q):
    if not path.exists(): return False, 0
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = data.get("questions",[])
    if len(existing) >= 50: return False, len(existing)
    next_num = len(existing) + 1
    for i,q in enumerate(new_q): q["num"] = next_num + i
    existing.extend(new_q)
    data["questions"] = existing[:50]
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

# Fecha risk_management/quiz_002
path_risk = Path("static/quizzes/cism/info_risk_management/quiz_002_pt.json")
ok, total = add_to_quiz(path_risk, q_risk)
if ok:
    print(f"OK - {len(q_risk)} questoes adicionadas ao risk_management/quiz_002_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total>=50 else f" (faltam {50-total})"))

# Adiciona ao governance/quiz_004
path_gov = Path("static/quizzes/cism/info_security_governance/quiz_004_pt.json")
ok2, total2 = add_to_quiz(path_gov, q_gov4)
if ok2:
    print(f"OK - {len(q_gov4)} questoes adicionadas ao governance/quiz_004_pt")
    print(f"Total: {total2}/50" + (" - COMPLETO!" if total2>=50 else f" (faltam {50-total2})"))
