#!/usr/bin/env python3
"""
CFE BATCH 2
Q51-75: Fraud Investigation (continuacao)
Q76-100: Financial Transactions & Fraud Schemes
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# ── BLOCO 1: Q51-75 — Fraud Investigation ────────────────────────────────────
fraud_investigation = [
    {"num":51,"text":"Os examinadores de fraude devem evitar a postura de defesa (advocacy) porque tal postura:","tag":"Objetividade","options":["A. Prolonga desnecessariamente as investigações","B. Reduz a cooperação dos entrevistados","C. Compromete a neutralidade e a credibilidade do examinador","D. Viola as obrigações de confidencialidade"],"correct":2,"justification_correct":"A defesa implica tomar partido, o que prejudica a imparcialidade e invalida a credibilidade das conclusões investigativas. (ACFE Code of Professional Standards)","justification_wrong":"A defesa não afeta primariamente prazos, cooperação ou confidencialidade — seu impacto central é sobre a objetividade do examinador."},
    {"num":52,"text":"Qual papel pode ser desempenhado pelo examinador de fraude no contexto de um processo judicial?","tag":"Papel do CFE","options":["A. Juiz responsável pela sentença","B. Promotor de justiça","C. Testemunha pericial (expert witness)","D. Membro do conselho de jurados"],"correct":2,"justification_correct":"O examinador de fraude pode atuar como testemunha pericial, apresentando e interpretando evidências de forma objetiva e técnica para o tribunal. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Juiz, promotor e jurado são funções do sistema judicial, não atribuições do examinador de fraude."},
    {"num":53,"text":"Em qual circunstância o encerramento de uma investigação de fraude é mais adequado?","tag":"Condução da Investigação","options":["A. Quando as evidências tornam-se tecnicamente complexas","B. Quando a gestão manifesta interesse em encerrar o processo","C. Quando evidências suficientes fundamentam as descobertas","D. Quando o consultor jurídico orienta a suspensão por razões legais"],"correct":3,"justification_correct":"A orientação do consultor jurídico é determinante quando questões de direitos ou riscos legais relevantes exigem a suspensão da investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Complexidade de evidências e pressão gerencial não são justificativas adequadas para encerrar uma investigação; a conclusão natural ocorre quando as evidências são suficientes."},
    {"num":54,"text":"Qual característica profissional é mais determinante para sustentar a credibilidade do examinador de fraude?","tag":"Credibilidade","options":["A. Postura assertiva e investigativa agressiva","B. Velocidade na conclusão dos trabalhos","C. Imparcialidade nas conclusões e no processo","D. Autoridade hierárquica na organização"],"correct":2,"justification_correct":"A imparcialidade assegura que as conclusões sejam tecnicamente defensáveis e percebidas como confiáveis por todas as partes envolvidas. (ACFE Code of Professional Standards)","justification_wrong":"Agressividade, velocidade e autoridade hierárquica não são atributos que sustentam a credibilidade profissional do examinador."},
    {"num":55,"text":"Na fundamentação de suas conclusões, os examinadores de fraude devem basear-se primordialmente em:","tag":"Evidências","options":["A. Denúncias anônimas recebidas","B. Explicações fornecidas pela gestão","C. Evidências documentadas e verificáveis","D. Experiência pessoal acumulada"],"correct":2,"justification_correct":"A evidência documentada fornece suporte verificável, objetivo e defensável para as conclusões do exame de fraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Denúncias anônimas, explicações gerenciais e experiência pessoal podem orientar a investigação, mas não substituem evidências documentadas como fundamento das conclusões."},
    {"num":56,"text":"Qual abordagem de entrevista é mais adequada na fase inicial de uma investigação de fraude?","tag":"Entrevistas","options":["A. Acusatória, para obter confissão imediata","B. Confrontadora, para testar a versão do entrevistado","C. Voltada à coleta de informações e apuração de fatos","D. Baseada em pressão para acelerar o processo"],"correct":2,"justification_correct":"As entrevistas iniciais têm caráter exploratório, focando na coleta de fatos e no mapeamento do contexto — o confronto é reservado para fases posteriores. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Abordagens acusatória, confrontadora ou coercitiva nas fases iniciais comprometem a qualidade das informações e podem violar direitos dos entrevistados."},
    {"num":57,"text":"A documentação das entrevistas realizadas durante um exame de fraude tem como finalidade principal:","tag":"Documentação","options":["A. Substituir o depoimento formal em processos judiciais","B. Fundamentar e corroborar as descobertas investigativas","C. Reduzir o tempo necessário para as entrevistas","D. Exercer controle sobre as testemunhas"],"correct":1,"justification_correct":"A documentação das entrevistas preserva a precisão das informações e fornece evidência de suporte para as conclusões do exame. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Documentação não substitui depoimento formal, não reduz tempo de entrevista nem serve como instrumento de controle."},
    {"num":58,"text":"Qual medida melhor preserva a integridade das evidências durante uma investigação de fraude?","tag":"Integridade da Evidência","options":["A. Compartilhar as descobertas com partes interessadas precocemente","B. Restringir o acesso às evidências a pessoas autorizadas","C. Resumir verbalmente o conteúdo para facilitar o uso","D. Confiar na memória dos investigadores para detalhes relevantes"],"correct":1,"justification_correct":"Restringir o acesso previne adulteração, perda ou comprometimento das evidências, preservando sua integridade e admissibilidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Compartilhamento prematuro, resumos verbais e dependência da memória são práticas que comprometem a integridade das evidências."},
    {"num":59,"text":"Ao descobrir que possui relacionamento pessoal com um suspeito investigado, o examinador de fraude deve:","tag":"Conflito de Interesses","options":["A. Prosseguir discreetamente sem divulgar o relacionamento","B. Ignorar o relacionamento e manter a investigação inalterada","C. Revelar o conflito e declarar-se impedido, se necessário","D. Acelerar a investigação para concluí-la antes que o conflito seja percebido"],"correct":2,"justification_correct":"A revelação do conflito de interesses e o eventual impedimento são obrigações éticas que preservam a integridade e a credibilidade do processo investigativo. (ACFE Code of Professional Standards)","justification_wrong":"Prosseguir sem revelar, ignorar ou acelerar para ocultar o conflito violam os padrões éticos da ACFE e comprometem a validade da investigação."},
    {"num":60,"text":"Qual normativo governa os padrões de conduta profissional dos Examinadores de Fraude Certificados?","tag":"Padrões Profissionais","options":["A. Princípios Contábeis Geralmente Aceitos (GAAP)","B. Normas de Auditoria Geralmente Aceitas (GAAS)","C. Código de Ética Profissional da ACFE","D. Circular 230 da Receita Federal dos EUA (IRS)"],"correct":2,"justification_correct":"O Código de Ética Profissional da ACFE estabelece os padrões de conduta, integridade e objetividade que regem a atuação dos CFEs. (ACFE Code of Professional Standards)","justification_wrong":"GAAP, GAAS e normativas fiscais regulam práticas contábeis e de auditoria, não os padrões éticos específicos da certificação CFE."},
    {"num":61,"text":"As conclusões comunicadas por um examinador de fraude devem ser embasadas primordialmente em:","tag":"Conclusões","options":["A. Probabilidades e estimativas estatísticas","B. Opiniões técnicas do examinador","C. Fatos verificados e evidências documentadas","D. Expectativas e direcionamentos da gestão"],"correct":2,"justification_correct":"As conclusões investigativas devem ser sustentadas exclusivamente por fatos verificáveis e evidências documentadas, não por suposições ou expectativas. (ACFE Code of Professional Standards)","justification_wrong":"Probabilidades, opiniões e expectativas gerenciais não constituem base suficiente para conclusões profissionalmente defensáveis."},
    {"num":62,"text":"Qual ação concreta demonstra a aplicação do princípio de zelo profissional (due professional care)?","tag":"Zelo Profissional","options":["A. Apressar as conclusões para atender prazos organizacionais","B. Desconsiderar inconsistências de baixo valor aparente","C. Conduzir avaliação minuciosa e abrangente das evidências","D. Delegar integralmente as tarefas investigativas à equipe"],"correct":2,"justification_correct":"O devido cuidado profissional exige avaliação criteriosa, completa e competente de todas as evidências relevantes, sem atalhos ou simplificações. (ACFE Code of Professional Standards)","justification_wrong":"Pressa, desconsideração de inconsistências e delegação integral são práticas incompatíveis com o due professional care."},
    {"num":63,"text":"Ao conduzir análises de evidências digitais, o examinador de fraude deve adotar qual procedimento?","tag":"Evidências Digitais","options":["A. Modificar os arquivos originais para facilitar a análise","B. Trabalhar exclusivamente em cópias forenses dos arquivos","C. Desconsiderar metadados por serem tecnicamente complexos","D. Focar apenas em resumos executivos dos arquivos"],"correct":1,"justification_correct":"Trabalhar em cópias forenses preserva a integridade dos arquivos originais, assegurando que as evidências digitais permaneçam íntegras e admissíveis. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Modificar originais, ignorar metadados e limitar-se a resumos comprometem a integridade e a completude da análise de evidências digitais."},
    {"num":64,"text":"Qual formato de relatório é mais adequado para comunicar as descobertas de um exame de fraude?","tag":"Relatórios","options":["A. Emocional e impactante para sensibilizar os tomadores de decisão","B. Persuasivo para convencer sobre a culpabilidade dos envolvidos","C. Neutro, factual e objetivamente fundamentado em evidências","D. Exclusivamente narrativo, sem estrutura formal"],"correct":2,"justification_correct":"O relatório neutro e factual garante a objetividade, a credibilidade e a defensabilidade legal das descobertas investigativas. (ACFE Code of Professional Standards)","justification_wrong":"Abordagens emocionais, persuasivas ou exclusivamente narrativas comprometem a credibilidade e a utilidade profissional do relatório."},
    {"num":65,"text":"As evidências coletadas em um exame de fraude devem atender ao requisito fundamental de terem sido:","tag":"Admissibilidade","options":["A. Mantidas sob sigilo absoluto durante toda a investigação","B. Tornadas prontamente acessíveis a todas as partes","C. Obtidas por meios legais e em conformidade com a lei","D. Confirmadas exclusivamente por depoimento verbal"],"correct":2,"justification_correct":"Evidências obtidas por meios ilegais podem ser inadmissíveis judicialmente e invalidar as descobertas da investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Sigilo absoluto, acesso irrestrito e confirmação verbal são requisitos distintos e não substituem a legalidade na obtenção das evidências."},
    {"num":66,"text":"Qual elemento exerce maior influência na definição do escopo de uma investigação de fraude?","tag":"Escopo","options":["A. Preferências metodológicas do investigador responsável","B. Políticas internas da organização investigada","C. Natureza e especificidade das alegações recebidas","D. Limitações orçamentárias disponíveis"],"correct":2,"justification_correct":"As alegações recebidas determinam o objeto da investigação, definindo o escopo, a profundidade e os métodos investigativos a serem aplicados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Preferências do investigador, políticas organizacionais e restrições orçamentárias são fatores secundários na definição do escopo investigativo."},
    {"num":67,"text":"Nas recomendações constantes de um relatório de exame de fraude, o examinador deve evitar:","tag":"Recomendações","options":["A. Sugestões de melhoria nos controles internos","B. Propostas de redução de riscos operacionais","C. Atribuição explícita de culpa a indivíduos","D. Recomendações de fortalecimento da governança"],"correct":2,"justification_correct":"Atribuir culpa excede o escopo de atuação do examinador de fraude, que se limita a apresentar fatos e evidências — a responsabilização é função dos processos legal e disciplinar. (ACFE Code of Professional Standards)","justification_wrong":"Melhorias de controles, redução de riscos e fortalecimento da governança são recomendações legítimas e dentro do escopo do examinador."},
    {"num":68,"text":"Qual princípio profissional assegura a aplicação consistente e imparcial dos padrões investigativos?","tag":"Princípios","options":["A. Lealdade institucional","B. Confidencialidade","C. Julgamento profissional","D. Objetividade"],"correct":3,"justification_correct":"A objetividade garante que os padrões sejam aplicados de forma justa, isenta e consistente, independentemente das partes envolvidas. (ACFE Code of Professional Standards)","justification_wrong":"Lealdade, confidencialidade e julgamento profissional são princípios relevantes, mas é a objetividade que assegura a aplicação imparcial dos padrões."},
    {"num":69,"text":"O exame de fraude se distingue da contabilidade forense convencional principalmente por:","tag":"Exame vs Contabilidade Forense","options":["A. Excluir dados financeiros de sua análise","B. Focar exclusivamente em estratégias de prevenção","C. Integrar investigação, direito e criminologia em abordagem multidisciplinar","D. Prescindir de entrevistas em seu processo metodológico"],"correct":2,"justification_correct":"O exame de fraude é multidisciplinar, combinando técnicas de investigação, conhecimentos jurídicos e princípios criminológicos, ultrapassando os limites da contabilidade forense. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Dados financeiros são essenciais; prevenção é apenas uma das dimensões; entrevistas são componente central da metodologia investigativa."},
    {"num":70,"text":"Qual resultado melhor representa o sucesso de um exame de fraude conduzido com padrão profissional?","tag":"Sucesso Investigativo","options":["A. Exposição pública dos envolvidos na mídia","B. Condenação criminal dos perpetradores","C. Conclusões precisas e sustentadas por evidências sólidas","D. Aplicação de medidas disciplinares imediatas"],"correct":2,"justification_correct":"O sucesso do exame de fraude é medido pela qualidade e precisão das conclusões baseadas em evidências — não pelos resultados legais ou disciplinares subsequentes. (ACFE Code of Professional Standards)","justification_wrong":"Exposição pública, condenação e disciplina são consequências possíveis, mas não o critério de sucesso do exame em si."},
    {"num":71,"text":"Os papéis de trabalho (working papers) produzidos durante um exame de fraude têm como finalidade principal:","tag":"Papéis de Trabalho","options":["A. Justificar os honorários cobrados pela investigação","B. Substituir a elaboração de relatórios formais","C. Fundamentar e documentar as conclusões investigativas","D. Servir como material de treinamento para novos investigadores"],"correct":2,"justification_correct":"Os papéis de trabalho registram o raciocínio, as evidências e o processo investigativo, substanciando as conclusões e tornando-as auditáveis e defensáveis. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Justificativa de honorários, substituição de relatórios e treinamento são funções secundárias ou inexistentes dos papéis de trabalho."},
    {"num":72,"text":"Qual situação exige com maior urgência a consulta ao consultor jurídico durante uma investigação de fraude?","tag":"Assessoria Jurídica","options":["A. Revisão e organização de evidências documentais","B. Condução de entrevistas de rotina com testemunhas","C. Questões envolvendo rescisão contratual ou direitos trabalhistas","D. Formatação e estruturação do relatório final"],"correct":2,"justification_correct":"Questões trabalhistas e de rescisão contratual envolvem riscos legais significativos que requerem orientação jurídica especializada antes de qualquer ação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Revisão de evidências, entrevistas de rotina e formatação de relatório são atividades de menor complexidade jurídica."},
    {"num":73,"text":"Os examinadores de fraude devem evitar fazer promessas durante as entrevistas investigativas porque:","tag":"Entrevistas","options":["A. Promessas reduzem a disposição dos entrevistados para cooperar","B. Promessas podem gerar obrigações jurídicas ou configurar induzimento","C. Promessas desperdiçam tempo valioso da entrevista","D. Promessas violam as obrigações de confidencialidade"],"correct":1,"justification_correct":"Promessas feitas durante entrevistas podem criar obrigações legais, configurar induzimento à confissão ou resultar em deturpação das declarações obtidas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O impacto principal das promessas é jurídico — não se trata de cooperação, tempo ou confidencialidade."},
    {"num":74,"text":"A manutenção da competência profissional pelo examinador de fraude requer, fundamentalmente:","tag":"Competência","options":["A. Especialização restrita em um único tipo de fraude","B. Evitar a educação continuada para preservar abordagens consolidadas","C. Atualização constante do conhecimento técnico e legal","D. Dependência de equipes jurídicas para todas as decisões investigativas"],"correct":2,"justification_correct":"A evolução contínua dos esquemas de fraude, da legislação e das tecnologias aplicadas exige atualização permanente para manter a efetividade profissional. (ACFE Code of Professional Standards)","justification_wrong":"Especialização excessivamente restrita, abandono da educação continuada e dependência jurídica total são posturas incompatíveis com a competência profissional exigida."},
    {"num":75,"text":"Qual princípio sustenta de forma mais abrangente a confiança pública na validade dos exames de fraude?","tag":"Confiança Pública","options":["A. Velocidade na conclusão das investigações","B. Sigilo absoluto sobre todos os procedimentos","C. Conduta ética em todos os aspectos da investigação","D. Autoridade institucional do examinador"],"correct":2,"justification_correct":"A conduta ética — imparcialidade, integridade, competência e objetividade — é o alicerce da credibilidade e da confiança pública nos exames de fraude. (ACFE Code of Professional Standards)","justification_wrong":"Velocidade, sigilo absoluto e autoridade institucional não sustentam a confiança pública da mesma forma que a conduta ética."},
]

# ── BLOCO 2: Q76-100 — Financial Transactions & Fraud Schemes ────────────────
financial_transactions = [
    {"num":1,"text":"Os relatórios financeiros fraudulentos são definidos, em sua essência, como:","tag":"Fraude Contábil","options":["A. Desvio de ativos físicos do patrimônio organizacional","B. Distorção ou omissão intencional nas demonstrações financeiras","C. Práticas contábeis inadequadas por insuficiência técnica","D. Erros sistemáticos originados em falhas nos sistemas de informação"],"correct":1,"justification_correct":"Os relatórios financeiros fraudulentos envolvem atos dolosos destinados a enganar os usuários das demonstrações, distorcendo a situação patrimonial ou os resultados da entidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Desvio de ativos é apropriação indébita; práticas inadequadas por insuficiência técnica configuram erro; falhas sistêmicas sem dolo não constituem fraude."},
    {"num":2,"text":"Quem está mais comumente associado à prática de relatórios financeiros fraudulentos?","tag":"Perfil do Perpetrador","options":["A. Colaboradores da linha operacional de menor hierarquia","B. Auditores externos independentes","C. Alta gestão e executivos da organização","D. Clientes e usuários externos das demonstrações"],"correct":2,"justification_correct":"A alta gestão possui autoridade, acesso e capacidade para manipular políticas contábeis e suprimir mecanismos de controle, tornando-se o perfil mais frequente nessa categoria. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Colaboradores de nível operacional têm acesso restrito; auditores externos têm papel de verificação; clientes não têm ingerência sobre as demonstrações."},
    {"num":3,"text":"A motivação primária por trás dos relatórios financeiros fraudulentos está geralmente relacionada a:","tag":"Motivação","options":["A. Obtenção de vantagem pessoal por meio de roubo direto de ativos","B. Cumprimento de exigências regulatórias específicas","C. Pressão por desempenho financeiro ou para ocultar resultados negativos","D. Busca de eficiência nos processos operacionais"],"correct":2,"justification_correct":"A gestão pode manipular demonstrações para atender metas de lucro, garantir acesso a crédito, sustentar o preço das ações ou encobrir deterioração do desempenho. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Roubo direto é apropriação indébita; conformidade regulatória e eficiência operacional não motivam a distorção intencional de demonstrações."},
    {"num":4,"text":"Qual demonstração financeira é mais frequentemente alvo de manipulação em esquemas de fraude contábil?","tag":"Demonstrações Financeiras","options":["A. Demonstração dos Fluxos de Caixa","B. Balanço Patrimonial","C. Demonstração do Resultado do Exercício (DRE)","D. Demonstração das Mutações do Patrimônio Líquido"],"correct":2,"justification_correct":"A DRE é o principal alvo de manipulação por ser a demonstração que reporta lucros e resultados, diretamente vinculada às expectativas de mercado e metas de desempenho. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais demonstrações também podem ser manipuladas, mas a DRE concentra a maior incidência de fraudes por sua ligação direta com indicadores de desempenho."},
    {"num":5,"text":"Os esquemas de fraude no reconhecimento de receitas normalmente envolvem:","tag":"Reconhecimento de Receita","options":["A. Registro de vendas fictícias ou prematuras","B. Postergação deliberada do reconhecimento de despesas","C. Superestimação dos passivos de curto prazo","D. Antecipação da baixa contábil de ativos"],"correct":0,"justification_correct":"O reconhecimento de receita fictícia, prematura ou imprópria é a técnica central de inflação de resultados nas fraudes de demonstrações financeiras. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Postergação de despesas, superestimação de passivos e baixas antecipadas são outras técnicas de manipulação, mas não descrevem especificamente a fraude no reconhecimento de receitas."},
    {"num":6,"text":"Qual sinal de alerta pode indicar a ocorrência de relatórios financeiros fraudulentos?","tag":"Red Flags Contábeis","options":["A. Lucratividade estável e consistente ao longo dos exercícios","B. Controles internos robustos e bem documentados","C. Lançamentos contábeis incomuns concentrados no final do período","D. Divulgações financeiras transparentes e detalhadas"],"correct":2,"justification_correct":"Lançamentos de fim de período complexos, incomuns ou de difícil justificativa são red flags clássicos de tentativas de ajuste artificial dos resultados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Lucratividade consistente, controles robustos e divulgações transparentes são indicadores de saúde organizacional, não de fraude."},
    {"num":7,"text":"A capitalização inadequada de despesas operacionais resulta nos seguintes efeitos sobre as demonstrações financeiras:","tag":"Capitalização Indevida","options":["A. Redução do lucro líquido reportado","B. Aumento das despesas reconhecidas no período","C. Superestimação dos ativos e dos resultados da organização","D. Incremento dos passivos registrados no balanço"],"correct":2,"justification_correct":"Ao capitalizar despesas que deveriam ser reconhecidas imediatamente no resultado, a organização infla seus ativos e posterga o impacto no lucro, distorcendo a posição patrimonial. (CFE Fraud Examiners Manual 2024)","justification_wrong":"A capitalização indevida produz efeito oposto aos descritos nas alternativas A, B e D — ela eleva ativos e lucros, não os reduz."},
    {"num":8,"text":"Qual estimativa contábil apresenta maior vulnerabilidade à manipulação gerencial?","tag":"Estimativas Contábeis","options":["A. Saldo de disponibilidades e equivalentes de caixa","B. Taxa e vida útil para fins de depreciação","C. Saldo de contas a pagar a fornecedores","D. Valor de empréstimos e financiamentos bancários"],"correct":1,"justification_correct":"A depreciação depende de julgamentos sobre vida útil e valor residual, oferecendo margem para manipulação que impacta diretamente o lucro reportado. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Caixa, contas a pagar e empréstimos bancários são valores objetivos com menor dependência de estimativas subjetivas."},
    {"num":9,"text":"A técnica conhecida como cookie jar reserves consiste em:","tag":"Técnicas de Manipulação","options":["A. Acumulação física de recursos em caixa não declarado","B. Subestimação sistemática de provisões em todos os períodos","C. Constituição excessiva de reservas em períodos favoráveis para posterior reversão","D. Manutenção de contas bancárias ilegais fora do balanço"],"correct":2,"justification_correct":"As cookie jar reserves são provisionamentos excessivos constituídos em períodos de bons resultados e posteriormente revertidos para suavizar artificialmente os lucros em períodos negativos. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas descrevem práticas distintas que não correspondem ao conceito de cookie jar reserves."},
    {"num":10,"text":"Qual índice financeiro pode sinalizar a ocorrência de inflação artificial de receitas?","tag":"Análise de Índices","options":["A. Índice de liquidez corrente","B. Giro de estoques","C. Giro de contas a receber","D. Índice de endividamento"],"correct":2,"justification_correct":"A desaceleração no giro de contas a receber pode indicar o registro de vendas fictícias ou não realizadas, onde os recebíveis crescem sem correspondência com a atividade real. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Liquidez corrente, giro de estoques e endividamento são indicadores relevantes, mas o giro de recebíveis tem ligação mais direta com a detecção de fraudes no reconhecimento de receitas."},
    {"num":11,"text":"A anulação de controles pela gestão (management override) representa, no contexto de riscos de fraude:","tag":"Management Override","options":["A. Prática rara e de impacto negligenciável","B. Procedimento estimulado para aumentar a eficiência operacional","C. Fator de risco significativo que viabiliza a fraude contábil","D. Mecanismo limitado ao escopo das auditorias externas"],"correct":2,"justification_correct":"O management override permite que executivos ignorem salvaguardas e controles, criando a oportunidade para manipulação das demonstrações financeiras. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O override não é raro, não é eficiente e não se limita a auditorias — é uma das principais ameaças identificadas em fraudes de alto impacto."},
    {"num":12,"text":"Qual característica do ambiente de negócios eleva o risco de fraude em relatórios financeiros?","tag":"Fatores de Risco","options":["A. Demanda estável e previsível pelos produtos da organização","B. Ambiente regulatório altamente estruturado e fiscalizado","C. Pressão por crescimento acelerado e metas de resultado ambiciosas","D. Adoção de políticas contábeis conservadoras"],"correct":2,"justification_correct":"A pressão por alto crescimento cria incentivos para a manipulação de resultados, especialmente quando os gestores têm remuneração variável atrelada ao desempenho financeiro. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Demanda estável, regulação estruturada e contabilidade conservadora são fatores que reduzem o risco de fraude."},
    {"num":13,"text":"O esquema denominado channel stuffing consiste em:","tag":"Esquemas de Fraude","options":["A. Venda de estoques com prejuízo deliberado para gerar fluxo de caixa","B. Envio de mercadorias em excesso a distribuidores para antecipar o reconhecimento de receita","C. Ocultação de estoques obsoletos para evitar baixas contábeis","D. Antecipação indevida da baixa de recebíveis vencidos"],"correct":1,"justification_correct":"No channel stuffing, a empresa força o envio de produtos além da demanda real para reconhecer receitas antes que existam vendas genuínas ao consumidor final. (CFE Fraud Examiners Manual 2024)","justification_wrong":"As demais alternativas descrevem práticas distintas que não correspondem à definição de channel stuffing."},
    {"num":14,"text":"Qual documento representa a fonte mais útil na detecção de manipulação de receitas?","tag":"Fontes de Evidência","options":["A. Contratos e acordos de venda","B. Registros de folha de pagamento","C. Declarações de impostos sobre o lucro","D. Registros de ativos imobilizados"],"correct":0,"justification_correct":"Os contratos de venda estabelecem os termos, condições e prazos de reconhecimento de receita, permitindo comparar o registro contábil com as obrigações contratuais reais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Folha de pagamento, declarações fiscais e registros de ativos são fontes relevantes para outros tipos de análise, mas contratos são prioritários na análise de receitas."},
    {"num":15,"text":"A fraude em relatórios financeiros se distingue da apropriação indébita de ativos principalmente porque:","tag":"Distinção de Categorias","options":["A. Envolve perdas de menor magnitude","B. É de mais fácil detecção pelos mecanismos de controle","C. É tipicamente perpetrada pela própria alta gestão","D. Requer acesso físico aos ativos da organização"],"correct":2,"justification_correct":"A fraude em demonstrações financeiras é frequentemente conduzida pela gestão, que tem autoridade para determinar políticas contábeis e suprimir controles. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Essa categoria envolve perdas maiores, é mais difícil de detectar e não requer acesso físico a ativos — ao contrário da apropriação indébita."},
    {"num":16,"text":"Qual técnica é comumente empregada para ocultar prejuízos ou resultados negativos?","tag":"Ocultação","options":["A. Superestimação de passivos existentes","B. Subestimação das receitas reconhecidas","C. Criação de ativos fictícios no balanço patrimonial","D. Antecipação do reconhecimento de despesas"],"correct":2,"justification_correct":"A criação de ativos fictícios infla artificialmente o balanço patrimonial, mascarando o desempenho negativo e criando a aparência de solidez financeira. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Superestimação de passivos e antecipação de despesas reduziriam o lucro reportado; subestimação de receitas também prejudicaria os resultados."},
    {"num":17,"text":"A presença de estruturas contábeis excessivamente complexas em uma organização pode indicar:","tag":"Complexidade Contábil","options":["A. Eficiência e sofisticação nos processos operacionais","B. Governança corporativa sólida e madura","C. Elevação do risco de fraude e manipulação","D. Conformidade com requisitos regulatórios avançados"],"correct":2,"justification_correct":"Estruturas desnecessariamente complexas podem ser deliberadamente criadas para obscurecer transações fraudulentas e dificultar a análise por auditores e investigadores. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Eficiência operacional, governança sólida e conformidade regulatória não justificam complexidade excessiva sem propósito econômico legítimo."},
    {"num":18,"text":"Qual fator organizacional é mais eficaz na limitação dos relatórios financeiros fraudulentos?","tag":"Prevenção","options":["A. Forças competitivas de mercado externas","B. Cultura ética consolidada e disseminada","C. Alta rentabilidade sustentada","D. Crescimento acelerado dos negócios"],"correct":1,"justification_correct":"Uma cultura ética forte, com tone at the top adequado, desencoraja a deturpação intencional e cria ambiente organizacional refratário à fraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Forças de mercado, rentabilidade e crescimento são fatores externos ou financeiros que não impedem por si sós a fraude contábil."},
    {"num":19,"text":"Qual mecanismo é frequentemente utilizado para ocultar fraudes em demonstrações financeiras?","tag":"Ocultação","options":["A. Baixas contábeis regulares de ativos obsoletos","B. Ampliação e transparência nas divulgações financeiras","C. Transações com partes relacionadas para deslocamento de resultados","D. Relatórios de fluxo de caixa detalhados"],"correct":2,"justification_correct":"Transações com partes relacionadas permitem deslocar lucros, ocultar perdas ou criar receitas fictícias por meio de entidades controladas pelo perpetrador. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Baixas regulares, divulgações transparentes e relatórios detalhados são práticas de governança que reduzem, não ampliam, as oportunidades de ocultação."},
    {"num":20,"text":"Os procedimentos analíticos são ferramentas úteis na detecção de fraudes porque permitem:","tag":"Procedimentos Analíticos","options":["A. Substituir completamente os procedimentos de auditoria substantiva","B. Identificar tendências, relações e valores incomuns nas demonstrações","C. Confirmar a culpabilidade dos responsáveis pela fraude","D. Eliminar a necessidade de entrevistas com a gestão"],"correct":1,"justification_correct":"Tendências e relações inesperadas identificadas pelos procedimentos analíticos funcionam como sinais de alerta que orientam investigações mais aprofundadas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Procedimentos analíticos não substituem testes substantivos, não determinam culpa e não eliminam a necessidade de entrevistas."},
    {"num":21,"text":"Qual cenário melhor ilustra a prática de gerenciamento fraudulento de resultados?","tag":"Gerenciamento de Resultados","options":["A. Revisão de estimativas contábeis dentro de parâmetros razoáveis e bem fundamentados","B. Aplicação consistente dos princípios contábeis geralmente aceitos","C. Alteração deliberada de estimativas para atingir metas de desempenho predefinidas","D. Correção de erros contábeis identificados em exercícios anteriores"],"correct":2,"justification_correct":"A manipulação intencional de estimativas para atingir metas específicas constitui fraude, pois distorce a realidade econômica da organização em benefício de interesses particulares. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Revisão fundamentada, aplicação consistente de princípios e correção de erros são práticas legítimas de contabilidade."},
    {"num":22,"text":"As fraudes em relatórios financeiros tendem a causar o maior impacto negativo sobre:","tag":"Impacto","options":["A. Colaboradores individuais da organização","B. Fornecedores e prestadores de serviço","C. Investidores, credores e demais usuários das demonstrações","D. Exclusivamente os clientes da organização"],"correct":2,"justification_correct":"Investidores e credores tomam decisões econômicas com base nas demonstrações financeiras, sendo os principais prejudicados quando essas informações são distorcidas intencionalmente. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Embora todos os stakeholders sejam impactados, investidores e credores são os usuários primários das demonstrações e os mais diretamente afetados."},
    {"num":23,"text":"Qual controle preventivo é mais eficaz no combate à fraude em relatórios financeiros?","tag":"Controles Preventivos","options":["A. Segurança física das instalações e dos ativos tangíveis","B. Segregação de funções nos processos contábeis","C. Liderança ética e supervisão independente do conselho","D. Contagens físicas periódicas de inventário"],"correct":2,"justification_correct":"O tone at the top — liderança ética combinada com supervisão independente — é o controle mais eficaz contra a fraude em demonstrações financeiras, pois atua diretamente nos incentivos e na cultura organizacional. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Segurança física e contagens de inventário são controles voltados para a apropriação de ativos; segregação de funções é relevante, mas menos eficaz que a cultura ética na prevenção de fraudes contábeis."},
    {"num":24,"text":"A fraude em relatórios financeiros tem maior probabilidade de ser detectada por meio de:","tag":"Detecção","options":["A. Reclamações de clientes sobre produtos ou serviços","B. Auditores internos com acesso e conhecimento dos processos","C. Reguladores externos em inspeções periódicas","D. Descoberta fortuita por acaso"],"correct":1,"justification_correct":"Auditores internos, por seu acesso contínuo aos processos e pela proximidade com as operações, estão melhor posicionados para identificar anomalias contábeis precocemente. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Clientes, reguladores e descobertas fortuitas são canais menos eficazes que a auditoria interna na detecção de fraudes contábeis."},
    {"num":25,"text":"Qual é a resposta mais eficaz e estruturada diante de suspeita de fraude em relatórios financeiros?","tag":"Resposta à Fraude","options":["A. Acusar publicamente a gestão para pressionar pela confissão","B. Ignorar discrepâncias de menor materialidade aparente","C. Conduzir investigação estruturada com metodologia profissional","D. Republicar imediatamente as demonstrações financeiras sem apuração prévia"],"correct":2,"justification_correct":"A investigação estruturada, conduzida com metodologia profissional e baseada em evidências, é a resposta adequada que preserva a integridade do processo e os direitos dos investigados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Acusações públicas, ignorar discrepâncias e republicar demonstrações sem apuração são respostas inadequadas que podem agravar os danos e expor a organização a riscos legais adicionais."},
]

# ── INJETA OS DOIS BLOCOS ─────────────────────────────────────────────────────
def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

# Bloco 1 — Fraud Investigation
dir1 = Path("static/quizzes/cfe/fraud_investigation")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {"cert_id":"cfe","domain_id":"fraud_investigation","quiz_num":num1,"domain_name":"Fraud Investigation","cert_name":"CFE / ACFE","lang":"pt","questions":fraud_investigation}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(fraud_investigation)} questoes salvas em {path1}")

# Bloco 2 — Financial Transactions
dir2 = Path("static/quizzes/cfe/financial_transactions")
dir2.mkdir(parents=True, exist_ok=True)
num2 = get_next_num(dir2)
out2 = {"cert_id":"cfe","domain_id":"financial_transactions","quiz_num":num2,"domain_name":"Financial Transactions & Fraud Schemes","cert_name":"CFE / ACFE","lang":"pt","questions":financial_transactions}
path2 = dir2 / f"quiz_{num2:03d}_pt.json"
path2.write_text(json.dumps(out2, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(financial_transactions)} questoes salvas em {path2}")
