#!/usr/bin/env python3
"""
CISM BATCH 13 - Governanca, Metricas, Politicas e Frameworks
30 questoes -> info_security_governance/quiz_004 (vai de 15 para 45)
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":16,"text":"O CISO deve expandir o licenciamento da ferramenta de varredura de vulnerabilidades para incluir quais redes?","tag":"Gestão de Vulnerabilidades","options":["A. Todas as redes internas e externas","B. Apenas o data center primário","C. Todas as redes, mas sem manter registros por limitação de licença","D. Apenas o data center secundário"],"correct":0,"justification_correct":"O CISO deve expandir o licenciamento para incluir todas as redes internas e externas. Muitas ferramentas mantêm histórico de vulnerabilidades por ativo — expandir o licenciamento habilita essa funcionalidade para todas as redes. (CISM Review Manual, ISACA)","justification_wrong":"Licenciar apenas o primário ou secundário deixa lacunas; operar sem manter registros destrói histórico valioso — todas as redes precisam de cobertura completa."},
    {"num":17,"text":"Uma organização decide desenvolver um conjunto completo de políticas, procedimentos, padrões e diretrizes. Qual deve ser desenvolvido primeiro?","tag":"Hierarquia de Documentos","options":["A. Procedimentos","B. Padrões","C. Processos","D. Políticas"],"correct":3,"justification_correct":"Políticas são as regras de negócio que regem o comportamento e devem ser desenvolvidas primeiro. Em seguida, processos e procedimentos alinhados com as políticas. Por último, diretrizes que oferecem sugestões de implementação. (CISM Review Manual, ISACA)","justification_wrong":"Procedimentos não devem ser criados antes das políticas; padrões especificam como implementar políticas; processos dependem das políticas — políticas são sempre o ponto de partida."},
    {"num":18,"text":"A declaração 'Senhas devem conter letras maiúsculas e minúsculas, números e símbolos, com no mínimo 12 caracteres' é um exemplo de:","tag":"Hierarquia de Documentos","options":["A. Padrão","B. Política","C. Diretriz","D. Procedimento"],"correct":0,"justification_correct":"Essa é uma declaração de padrão — especificações detalhadas sobre qualquer tópico devem aparecer em um padrão, não em uma política. (CISM Review Manual, ISACA)","justification_wrong":"Política não deve conter especificações técnicas detalhadas; diretriz é não vinculativa; procedimento descreve etapas de execução — especificações técnicas são padrões."},
    {"num":19,"text":"A métrica 'Percentual de patches aplicados dentro do SLA em servidores de manufatura' transmite qual mensagem à gestão executiva?","tag":"Métricas","options":["A. O risco associado aos SLAs e se são adequados","B. O tempo de inatividade na manufatura enquanto patches são aplicados","C. O esforço para aplicar patches de segurança nos servidores","D. O risco de incidentes de segurança que poderiam interromper as operações"],"correct":3,"justification_correct":"Essa métrica ajuda a gestão a entender o risco de incidente ou violação de segurança. Se a tendência cair, levará mais tempo para servidores serem corrigidos — aumentando a probabilidade de intrusão e interrupção da manufatura. (CISM Review Manual, ISACA)","justification_wrong":"SLAs e tempo de inatividade são aspectos operacionais; esforço para patching não revela risco — o risco de incidentes que podem interromper operações é a mensagem estratégica."},
    {"num":20,"text":"Qual tipo de relatório é mais apropriado para enviar a um conselho de administração?","tag":"Reporte ao Conselho","options":["A. Métricas trimestrais de alto nível e lista de incidentes de segurança","B. Métricas semanais detalhadas","C. Relatórios semanais detalhados e de varredura de vulnerabilidades","D. Relatórios de varredura de vulnerabilidades e lista de incidentes"],"correct":0,"justification_correct":"Um conselho de administração estará interessado em informações de alto nível sobre o programa de segurança, geralmente em formato resumido. Uma lista de incidentes de segurança também é informação valiosa. (CISM Review Manual, ISACA)","justification_wrong":"Métricas semanais detalhadas e relatórios de vulnerabilidades são excessivamente técnicos para o conselho — alto nível e resumido é o formato correto."},
    {"num":21,"text":"Qual é a melhor solução para proteger aplicação SaaS de ataques de camada 7?","tag":"Controles Técnicos","options":["A. Proteção avançada contra malware","B. Cloud Access Security Broker (CASB)","C. Filtro de conteúdo web","D. Web Application Firewall (WAF)"],"correct":3,"justification_correct":"Um WAF é a melhor solução para proteger aplicações SaaS de ataques de camada 7, como injeção de SQL, buffer overflow e cross-site scripting. (CISM Review Manual, ISACA)","justification_wrong":"Antimalware é para endpoints; CASB controla acesso a aplicações em nuvem; filtro de conteúdo bloqueia sites — apenas WAF protege especificamente ataques de camada 7 em aplicações web."},
    {"num":22,"text":"Como uma política de uso aceitável (AUP) difere de uma política de segurança da informação?","tag":"Políticas","options":["A. Diferem apenas no nome; são funcionalmente idênticas","B. AUP define comportamento esperado dos colaboradores; política de SI detalha regras de negócio de cibersegurança","C. Política de SI define comportamento esperado; AUP detalha regras de negócio de cibersegurança","D. AUP se aplica apenas a trabalhadores não técnicos; política de SI apenas a técnicos"],"correct":1,"justification_correct":"AUP define comportamento esperado de todos os trabalhadores. Política de segurança da informação também se aplica a todos, mas define regras de negócio de cibersegurança em muitos tópicos, incluindo alguns não relevantes para trabalhadores não técnicos. (CISM Review Manual, ISACA)","justification_wrong":"São documentos distintos; a política de SI não define comportamento esperado — a AUP faz isso; ambas se aplicam a todos, não apenas a grupos específicos."},
    {"num":23,"text":"Qual certificação é reconhecida por conhecimento e experiência em auditoria de sistemas de informação e proteção?","tag":"Certificações","options":["A. CGEIT","B. CRISC","C. CISA","D. CISSP"],"correct":2,"justification_correct":"CISA (Certified Information Systems Auditor) é reconhecida por exigir experiência em auditoria de sistemas de informação e proteção de sistemas de informação. (CISM Review Manual, ISACA)","justification_wrong":"CGEIT é para governança de TI empresarial; CRISC é para gestão de riscos e controles de SI; CISSP é certificação geral de segurança — apenas CISA é específica para auditoria de sistemas."},
    {"num":24,"text":"O CISO de organização com 1.000 colaboradores quer implementar função de monitoramento de segurança 24/7/365. Qual é a melhor opção?","tag":"Operações de Segurança","options":["A. Terceirizar para MSSP especializado em monitoramento de eventos de segurança","B. Montar equipe de TI e monitoramento de segurança 24/7 com funcionários próprios","C. Montar função de monitoramento 24/7/365 com funcionários permanentes de tempo integral","D. Implementar plataforma de monitoramento e enviar alertas para equipe 5x8 após horas"],"correct":0,"justification_correct":"A melhor opção é terceirizar para um MSSP. A principal vantagem é custo — as taxas de um MSSP serão fração do custo de contratar e equipar equipe própria capaz de cobrir 21 turnos por semana com férias, afastamentos e treinamento. (CISM Review Manual, ISACA)","justification_wrong":"Montar equipe própria 24/7 é extremamente custoso; equipe 5x8 deixa lacunas críticas de cobertura — MSSP oferece cobertura completa com custo controlado."},
    {"num":25,"text":"Qual é o melhor regime para gerenciar o conteúdo de uma política de segurança?","tag":"Gestão de Políticas","options":["A. Desenvolver política alinhada com ISO 27001, NIST 800-53 ou CIS CSC e revisar anualmente","B. Desenvolver política alinhada com padrões conhecidos e o negócio, revisar anualmente e quando mudanças significativas ocorrem","C. Terceirizar desenvolvimento de política e ter a firma revisando anualmente","D. Desenvolver política alinhada com padrões conhecidos e o negócio"],"correct":1,"justification_correct":"A melhor política inicial harmoniza com a organização e é estruturada em padrão apropriado como ISO 27001, NIST 800-53 ou CIS CSC. Deve ser revisada pelo menos anualmente e quando a organização passa por mudanças significativas. (CISM Review Manual, ISACA)","justification_wrong":"Revisão apenas anual pode ser insuficiente diante de mudanças significativas; terceirizar sem controle interno compromete o alinhamento; desenvolver sem revisão cria documentos desatualizados."},
    {"num":26,"text":"Novo CISO em empresa manufatureira descobriu que mais de um terço dos sistemas operacionais de ICS são muito antigos. Qual é a melhor resposta?","tag":"Segurança de ICS","options":["A. Mudar para fornecedores com sistemas operacionais modernos e suportados","B. Atualizar sistemas operacionais e instalar bibliotecas retrocompatíveis","C. Virtualizar sistemas operacionais desatualizados","D. Isolar sistemas ICS em redes segmentadas e endurecidas"],"correct":3,"justification_correct":"A melhor resposta é isolar os ambientes ICS em redes separadas e endurecidas com controles rígidos de acesso — isso reduz significativamente a probabilidade e o impacto de ameaças comuns. (CISM Review Manual, ISACA)","justification_wrong":"Mudar de fornecedores pode ser proibitivamente caro; virtualizar não resolve a vulnerabilidade do SO subjacente; atualizar pode ser impossível com software ICS legado — isolamento é a solução prática."},
    {"num":27,"text":"Como o CISO deve descrever a situação de ICS desatualizado para a gestão sênior?","tag":"Comunicação Executiva","options":["A. A organização precisa modernizar seus sistemas de controle industrial","B. A organização precisa isolar e proteger seus sistemas de controle industrial","C. A organização precisa exigir que fornecedores de ICS migrem para sistemas mais modernos","D. A organização deve terceirizar seu ICS para provedor de nuvem ICS"],"correct":1,"justification_correct":"A melhor mensagem para a gestão sênior é de mitigação por meio de isolamento protetor — mesmo ambientes ICS com sistemas operacionais modernos devem ser isolados das demais redes da organização. (CISM Review Manual, ISACA)","justification_wrong":"Modernizar é proibitivamente caro; exigir atualização de fornecedores pode não ser viável; terceirizar para nuvem não resolve a questão de segurança — isolamento é a mensagem correta."},
    {"num":28,"text":"Qual é a melhor linguagem para política de verificação de antecedentes em organização multinacional?","tag":"Políticas de RH","options":["A. Antes de contratar, todos os funcionários devem passar por verificação de antecedentes onde permitido por lei","B. Antes de contratar, todos os trabalhadores, funcionários ou consultores, devem passar por verificação","C. Antes de contratar, todos os trabalhadores, independentemente do tipo, devem passar por verificação onde permitido por lei","D. Antes de contratar e anualmente, todos os funcionários devem passar por verificação de antecedentes"],"correct":2,"justification_correct":"A melhor linguagem inclui todos os tipos de trabalhadores (funcionários, contratados, temporários, consultores) E reconhece que verificações não são permitidas em todos os países com a frase 'onde permitido por lei'. (CISM Review Manual, ISACA)","justification_wrong":"Excluir tipos específicos de trabalhadores cria lacunas; não incluir 'onde permitido por lei' torna a política inflexível para países restritivos; revisão anual é boa prática mas não é o foco da linguagem."},
    {"num":29,"text":"Um funcionário vazou informações vitais via serviço de armazenamento em nuvem não aprovado. Qual é o melhor controle administrativo para prevenir isso no futuro?","tag":"Controles de Segurança","options":["A. Exigir que funcionários reconheçam a conformidade com a política de segurança anualmente por escrito","B. Implementar sistema CASB","C. Implementar DLP baseado em endpoint","D. Implementar GPO para bloquear dispositivos USB de armazenamento em massa"],"correct":0,"justification_correct":"Exigir reconhecimento anual da política de segurança é o único controle administrativo entre as opções. CASB, DLP e GPO são controles técnicos, não administrativos como a questão especifica. (CISM Review Manual, ISACA)","justification_wrong":"CASB, DLP e GPO são controles técnicos — a questão pede controle administrativo, que é o reconhecimento formal da política."},
    {"num":30,"text":"Qual controle pode melhorar mais a segurança de software em organização SaaS que já realiza pentests trimestrais?","tag":"SDLC Seguro","options":["A. Scans SAST como parte do processo de build de software","B. Testes de penetração mensais","C. Treinamento obrigatório de desenvolvimento seguro para todos os desenvolvedores","D. Scans diários de aplicações web em produção"],"correct":0,"justification_correct":"SAST (Static Application Security Testing) integrado ao processo de build é a melhor solução — organizações modernas com DevOps e DevSecOps integram segurança às ferramentas de automação, identificando defeitos antes do deploy. (CISM Review Manual, ISACA)","justification_wrong":"Pentests mais frequentes não atacam a causa raiz; treinamento produz melhoria gradual; scans diários de produção não previnem defeitos na fase de desenvolvimento."},
    {"num":31,"text":"Qual é a melhor fonte para padrões de hardening de sistemas e componentes?","tag":"Hardening","options":["A. Microsoft","B. NIST","C. SANS","D. Center for Internet Security (CIS)"],"correct":3,"justification_correct":"O CIS (Center for Internet Security) possui biblioteca abrangente de padrões de hardening para sistemas operacionais de servidores, dispositivos de rede, sistemas operacionais de endpoint e vários subsistemas incluindo SGBDs. Os controles CIS são altamente respeitados e mantidos atualizados. (CISM Review Manual, ISACA)","justification_wrong":"Microsoft é fonte para seus próprios produtos; NIST não é a melhor fonte para hardening; SANS não é o melhor fonte para padrões de hardening — CIS tem a cobertura mais abrangente e reconhecida."},
    {"num":32,"text":"Ao implementar CIS Benchmarks em servidores de produção pela primeira vez, qual é o melhor método?","tag":"Hardening","options":["A. Implementar todas as configurações de uma vez em ambientes de teste e depois produção","B. Implementar as configurações gradualmente em ambientes de teste e depois produção","C. Implementar todas as configurações de uma vez diretamente em produção","D. Implementar as configurações gradualmente diretamente em produção"],"correct":1,"justification_correct":"CIS Benchmarks são altamente detalhados — há dezenas de configurações para sistemas de servidor. Aplicar gradualmente garante que mudanças de configuração não afetem adversamente os sistemas de produção, testando primeiro em ambiente de teste. (CISM Review Manual, ISACA)","justification_wrong":"Aplicar tudo de uma vez pode resultar em falhas difíceis de diagnosticar; implementar diretamente em produção sem teste é má prática — gradual em teste primeiro é a abordagem segura."},
    {"num":33,"text":"Qual é a melhor abordagem para triagem de candidatos a diretor de segurança em organização financeira midsize?","tag":"Recrutamento","options":["A. Exigir CISSP ou CISM ou certificações similares","B. Desejar CISSP ou CISM e experiência relevante","C. Exigir CISSP e CISM","D. Exigir CISSP ou CISM e diploma avançado"],"correct":1,"justification_correct":"A experiência relevante é a característica mais importante em candidato a diretor de segurança. Certificações como CISSP e CISM são ótimos complementos. Exigir certificações avançadas em excesso pode excluir candidatos qualificados. (CISM Review Manual, ISACA)","justification_wrong":"Exigir certificações sem considerar experiência pode excluir candidatos qualificados; exigir ambas CISSP e CISM é excessivo; diploma avançado obrigatório reduz desnecessariamente o pool de candidatos."},
    {"num":34,"text":"Como uma estatística operacional sobre varreduras de segurança pode ser transformada em métrica significativa para a gestão sênior?","tag":"Métricas de Segurança","options":["A. Evitar o uso de jargão técnico","B. Expressar a métrica em termos de negócio e resultados potenciais","C. Mostrar a métrica em dashboard visualmente atraente","D. Descrever a estatística em narrativa de sumário executivo"],"correct":1,"justification_correct":"Uma estatística operacional pode ser transformada em métrica de negócio significativa usando termos de negócio e descrevendo resultados potenciais — por exemplo, tempo para aplicar patches pode ser descrito em termos de exposição ao risco de violação que poderia interromper operações críticas. (CISM Review Manual, ISACA)","justification_wrong":"Remover jargão sem contexto de negócio é insuficiente; dashboard visual pode não adicionar contexto; narrativa executiva sem quantificação é menos eficaz — termos de negócio com outcomes é o diferencial."},
    {"num":35,"text":"Qual das seguintes métricas de segurança é melhor descrita como um indicador líder (leading indicator) de ataque?","tag":"KRI e KPI","options":["A. Número de regras de firewall acionadas","B. Número de sessões de treinamento de conscientização concluídas","C. Percentual de sistemas escaneados","D. Tempo médio para aplicar patches de segurança"],"correct":3,"justification_correct":"Existe forte correlação entre a ausência de patches e a probabilidade e sucesso de ataques. Sistemas patcheados rapidamente são muito menos provavelmente atacados com sucesso — tempo de patching prediz eventos futuros. (CISM Review Manual, ISACA)","justification_wrong":"Regras de firewall e sistemas escaneados são indicadores operacionais; treinamento indica conscientização mas não prediz ataques diretamente — tempo de patching tem correlação direta com probabilidade de ataque."},
    {"num":36,"text":"A métrica 'Percentual de sistemas com instalação completa de antimalware avançado' é melhor descrita como:","tag":"Tipos de Métricas","options":["A. Indicador operacional chave (KOI)","B. Indicador de desempenho chave (KPI)","C. Indicador de meta chave (KGI)","D. Indicador de risco chave (KRI)"],"correct":2,"justification_correct":"Uma métrica de conclusão de instalação está mais associada a uma meta estratégica — neste caso, a instalação de antimalware avançado em todos os sistemas. Esta métrica poderia ser um KRI também, pois pode indicar redução de risco por melhoria na capacidade. (CISM Review Manual, ISACA)","justification_wrong":"KOI não é termo padrão da indústria; KPI mede desempenho contínuo; KRI indica áreas de risco potencial — a conclusão de uma instalação é melhor como KGI de meta estratégica."},
    {"num":37,"text":"Qual tipo de métrica é mais adequado para mostrar a redução de risco resultante de melhorias no SIEM de uma organização?","tag":"Métricas","options":["A. KGI","B. RACI","C. KRI","D. ROSI"],"correct":2,"justification_correct":"Um KRI (Key Risk Indicator) é a métrica mais adequada — este será um desafio pois eventos de alto impacto ocorrem raramente. Ainda assim, o KRI é o tipo mais correto para medir redução de risco. (CISM Review Manual, ISACA)","justification_wrong":"KGI é para metas; RACI é framework de responsabilidades; ROSI é retorno sobre investimento em segurança — KRI indica áreas de risco potencial e sua variação ao longo do tempo."},
    {"num":38,"text":"O que SMART significa no contexto de métricas de segurança?","tag":"Métricas SMART","options":["A. Security Metrics Are Risk Treatment","B. Específico, Mensurável, Alcançável, Relevante e Baseado no Tempo","C. Específico, Mensurável, Acionável, Relevante e Baseado no Tempo","D. Específico, Gerenciável, Acionável, Relevante e Baseado no Tempo"],"correct":1,"justification_correct":"SMART, no contexto de métricas, significa Específico, Mensurável, Alcançável (Achievable), Relevante e Baseado no Tempo (Time-related). (CISM Review Manual, ISACA)","justification_wrong":"Security Metrics Are Risk Treatment é um distrator; Acionável e Gerenciável não são as definições corretas das letras A e M no acrônimo SMART de métricas."},
    {"num":39,"text":"Métricas que mostram a efetividade de um programa de gestão de riscos NÃO incluiriam qual das seguintes?","tag":"Métricas de Risco","options":["A. Redução no número de eventos de segurança","B. Redução no impacto de eventos de segurança","C. Redução no tempo para remediar vulnerabilidades","D. Redução no número de patches aplicados"],"correct":3,"justification_correct":"O número de patches aplicados não é métrica que indica efetividade de um programa de gestão de riscos nem de gestão de vulnerabilidades. As outras métricas são potencialmente úteis para programas de gestão de riscos. (CISM Review Manual, ISACA)","justification_wrong":"Redução de eventos, impacto e tempo de remediação são métricas válidas de efetividade do programa de riscos — número de patches aplicados mede volume de trabalho, não efetividade."},
    {"num":40,"text":"Exemplos de métricas de desempenho de programa de segurança incluem todos os seguintes, EXCETO:","tag":"Métricas de Desempenho","options":["A. Tempo para detectar incidentes de segurança","B. Tempo para remediar incidentes de segurança","C. Tempo para realizar scans de segurança","D. Tempo para descobrir vulnerabilidades"],"correct":2,"justification_correct":"O tempo para realizar scans de segurança não é um bom exemplo de métrica de desempenho de programa de segurança. As outras métricas — detectar incidentes, remediar incidentes e descobrir vulnerabilidades — são exemplos válidos. (CISM Review Manual, ISACA)","justification_wrong":"Detectar incidentes, remediar incidentes e descobrir vulnerabilidades são métricas de desempenho diretas do programa — tempo de realização de scans é métrica operacional de menor valor estratégico."},
    {"num":41,"text":"Qual é o propósito de métricas de entrega de valor (value delivery metrics)?","tag":"Métricas de Valor","options":["A. Redução de custos de longo prazo","B. Redução no ROSI","C. Aumento no ROSI","D. Aumento no lucro líquido"],"correct":0,"justification_correct":"Métricas de entrega de valor são mais frequentemente associadas à redução de custos de longo prazo em proporção a outras medidas como número de funcionários e ativos. (CISM Review Manual, ISACA)","justification_wrong":"ROSI e lucro líquido não são as associações primárias de métricas de entrega de valor — a redução proporcional de custos é o foco central."},
    {"num":42,"text":"Joseph, CISO, precisa de método padrão para medir e publicar informações sobre a efetividade do programa de segurança. Qual é a melhor abordagem?","tag":"Frameworks de Medição","options":["A. Scaled score","B. NIST Cybersecurity Framework (CSF)","C. Business Model for Information Security (BMIS)","D. Balanced Scorecard (BSC)"],"correct":3,"justification_correct":"O Balanced Scorecard é uma ferramenta bem conhecida para medir o desempenho e a efetividade de uma organização — determina quão bem a organização está cumprindo sua missão e objetivos estratégicos e quão bem está alinhada com os objetivos organizacionais gerais. (CISM Review Manual, ISACA)","justification_wrong":"Scaled score não é método para publicar métricas; NIST CSF não é tipicamente usado para publicar métricas de programa; BMIS é para entender relacionamentos, não publicar métricas."},
    {"num":43,"text":"Qual é a melhor descrição do framework COBIT?","tag":"COBIT","options":["A. Framework de processos e controles de segurança integrável com ITIL ou ISO 20000","B. Framework de controles de TI sobre o qual controles de segurança podem ser adicionados","C. Framework de processos de TI com processos de segurança opcionais quando Extended COBIT é implementado","D. Framework de processos de TI com processos de segurança integrados em todo o framework"],"correct":3,"justification_correct":"COBIT é framework de processos de TI com processos de segurança integrados em todo o framework. Desenvolvido pela ISACA, seus quatro domínios são: planejar e organizar, adquirir e implementar, entregar e suportar, e monitorar e avaliar. (CISM Review Manual, ISACA)","justification_wrong":"COBIT não é estritamente framework de controles de segurança; não existe Extended COBIT; os processos de segurança estão integrados, não são opcionais."},
    {"num":44,"text":"Uma organização é obrigada pelo PCI DSS a incluir várias políticas altamente técnicas. Qual é a melhor abordagem?","tag":"PCI DSS e Políticas","options":["A. Implementar política técnica de segurança com todos os itens PCI, com AUP separada para todos os trabalhadores","B. Incorporar todas as políticas PCI na política de SI e deixar os usuários identificarem o que é relevante","C. Incluir todos os itens PCI na política de SI e indicar quais são aplicáveis aos usuários finais","D. Manter as políticas PCI fora da política geral de segurança para não confundir usuários não técnicos"],"correct":0,"justification_correct":"A melhor abordagem é separar: documento de política técnica/mandatória para trabalhadores técnicos com todas as políticas PCI, e AUP separada para todos os usuários finais com conteúdo de segurança acessível. (CISM Review Manual, ISACA)","justification_wrong":"Incorporar tudo em um documento é confuso para usuários não técnicos; deixar usuários identificarem relevância é inadequado; excluir da política geral cria lacunas de conformidade."},
    {"num":45,"text":"Qual é a melhor métrica de nível gerencial para gestão de vulnerabilidades?","tag":"Métricas de Vulnerabilidades","options":["A. Tempo médio desde disponibilidade do patch até aplicação bem-sucedida","B. Tempo médio desde varredura de vulnerabilidades até aplicação do patch","C. Tempo médio para aplicar um patch com sucesso","D. Número de patches de segurança aplicados"],"correct":0,"justification_correct":"Esta é a métrica mais significativa — mostra a história sobre quanto tempo servidores ficam desprotegidos por patches de segurança, o que equivale a exposição e risco de intrusão e violação com impactos potencialmente danos. (CISM Review Manual, ISACA)","justification_wrong":"Tempo desde varredura ignora o período antes da varredura; tempo apenas para aplicar patch tem pouca relevância de negócio; número de patches mede volume de trabalho, não exposição ao risco."},
]

def add_to_quiz(path, new_q):
    if not path.exists(): return False, 0
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = data.get("questions",[])
    if len(existing) >= 50: return False, len(existing)
    next_num = len(existing) + 1
    for i,q in enumerate(new_q): q["num"] = next_num + i
    existing.extend(new_q)
    data["questions"] = existing[:50]
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

path = Path("static/quizzes/cism/info_security_governance/quiz_004_pt.json")
ok, total = add_to_quiz(path, questions)
if ok:
    print(f"OK - {len(questions)} questoes adicionadas ao governance/quiz_004_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total>=50 else f" (faltam {50-total})"))
else:
    print(f"Quiz nao encontrado ou ja completo. Total: {total}")
