#!/usr/bin/env python3
"""
CISM BATCH 7 - Continuidade de Negocios e Resposta a Incidentes
15 questoes adaptadas
Dominio: incident_management
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"Qual dos seguintes objetivos de recuperação está associado ao maior período tolerável de interrupção de serviço?","tag":"RTO e RPO","options":["A. Objetivo de tolerância de recuperação (RTO)","B. Objetivo de ponto de recuperação (RPO)","C. Objetivo de capacidade de recuperação (RCaPO)","D. Objetivo de tempo de recuperação (RTO)"],"correct":3,"justification_correct":"O RTO (Recovery Time Objective) é o período máximo de tempo desde o início de uma interrupção até a retomada do serviço — representa o maior período tolerável de indisponibilidade. (CISM Review Manual, ISACA)","justification_wrong":"RPO define a quantidade máxima de dados que podem ser perdidos; RCaPO não é terminologia padrão; o RTO é especificamente o tempo máximo tolerável de interrupção."},
    {"num":2,"text":"Um gestor de segurança está desenvolvendo estratégia para melhorar o processo de gestão de incidentes. Ele definiu o estado futuro desejado. Antes de desenvolver planos específicos, deve realizar:","tag":"Planejamento","options":["A. Sessão de treinamento para a equipe de resposta","B. Teste de penetração no ambiente","C. Avaliação de vulnerabilidades","D. Análise de lacunas (gap analysis)"],"correct":3,"justification_correct":"Quando o estado futuro desejado está definido, deve-se realizar uma gap analysis para compreender o estado atual e identificar as lacunas — só então é possível desenvolver planos específicos para alcançar o estado futuro. (CISM Review Manual, ISACA)","justification_wrong":"Treinamento, pentest e avaliação de vulnerabilidades são atividades operacionais — a gap analysis é o pré-requisito para desenvolver o plano estratégico de melhoria."},
    {"num":3,"text":"Uma grande organização opera centenas de aplicações de negócio. Como o gestor de segurança deve priorizar as aplicações para proteção em caso de desastre?","tag":"BIA","options":["A. Conduzir análise de impacto nos negócios (BIA)","B. Conduzir avaliação de riscos","C. Conduzir análise de processos de negócio","D. Classificar as aplicações em ordem de criticidade"],"correct":0,"justification_correct":"Uma BIA (Business Impact Analysis) identifica os processos de negócio e os sistemas de informação mais críticos para as operações contínuas da organização — é a ferramenta adequada para priorizar proteção em cenários de desastre. (CISM Review Manual, ISACA)","justification_wrong":"Avaliação de riscos e análise de processos são complementares mas menos específicos; classificar por criticidade é o resultado da BIA, não o método — a BIA é o processo correto."},
    {"num":4,"text":"Os tipos de testes de plano de resposta a incidentes de segurança são:","tag":"Testes de Planos","options":["A. Revisão de documentos, walkthrough e simulação","B. Revisão de documentos e simulação","C. Revisão de documentos, walkthrough, simulação, teste paralelo e cutover","D. Revisão de documentos, walkthrough e teste cutover"],"correct":0,"justification_correct":"Os tipos de teste de plano de resposta a incidentes são revisão de documentos, walkthrough e simulação. Testes paralelos e cutover são usados em planejamento de recuperação de desastres, não em resposta a incidentes. (CISM Review Manual, ISACA)","justification_wrong":"Teste paralelo e cutover são específicos de recuperação de desastres; a lista correta para resposta a incidentes é revisão de documentos, walkthrough e simulação."},
    {"num":5,"text":"Uma organização desenvolveu seu primeiro plano de continuidade de negócios. Qual é o primeiro teste que deve ser realizado?","tag":"Testes de BCP","options":["A. Walkthrough","B. Simulação","C. Teste paralelo","D. Teste cutover"],"correct":0,"justification_correct":"A melhor escolha de teste para um plano de continuidade de primeira vez é a revisão de documentos ou o walkthrough. Como é o primeiro plano, os demais testes não são as melhores escolhas — o walkthrough é menos arriscado e mais adequado para validação inicial. (CISM Review Manual, ISACA)","justification_wrong":"Simulação, teste paralelo e cutover são mais disruptivos e arriscados — inadequados para validação inicial de um plano nunca testado anteriormente."},
    {"num":6,"text":"Uma organização sofre ataque de ransomware que está danificando dados críticos. Qual é o melhor curso de ação?","tag":"Resposta a Ransomware","options":["A. Acionar apenas o plano de resposta a incidentes de segurança","B. Acionar o plano de resposta a incidentes seguido pelo plano de continuidade","C. Acionar simultaneamente o plano de resposta a incidentes e o plano de continuidade","D. Acionar apenas o plano de continuidade de negócios"],"correct":2,"justification_correct":"Quando dados críticos estão sendo danificados, a organização deve acionar simultaneamente o plano de resposta a incidentes (para conter o ataque) e o plano de continuidade (para restaurar serviços aos clientes). (CISM Review Manual, ISACA)","justification_wrong":"Acionar apenas um dos planos é insuficiente; aguardar a conclusão do primeiro para iniciar o segundo atrasa a recuperação — a resposta simultânea é a mais eficaz."},
    {"num":7,"text":"Qual é a consideração mais importante na seleção de um hot site?","tag":"Sites de Recuperação","options":["A. Fuso horário em relação à sede","B. Localização geográfica em relação ao site primário","C. Proximidade a transporte de grande porte","D. Ausência de riscos naturais na localidade"],"correct":1,"justification_correct":"A localização geográfica em relação ao site primário é o critério mais importante — sites muito próximos podem ser afetados pelo mesmo desastre. A distância adequada garante que o hot site não seja atingido pelo mesmo evento que afetou o site principal. (CISM Review Manual, ISACA)","justification_wrong":"Fuso horário, transporte e riscos naturais são considerações secundárias — a separação geográfica suficiente é o critério primário para evitar que um único evento afete ambos os sites."},
    {"num":8,"text":"Uma organização estabeleceu RPO de 14 dias para suas aplicações de negócio mais críticas. Qual estratégia de recuperação seria a melhor escolha?","tag":"Estratégias de Recuperação","options":["A. Site móvel","B. Site morno (warm site)","C. Hot site","D. Cold site"],"correct":3,"justification_correct":"Uma organização com RPO de 14 dias pode usar um cold site — 14 dias é tempo suficiente para a maioria das organizações adquirir hardware e recuperar aplicações. Hot e warm sites são necessários para RTOs mais curtos. (CISM Review Manual, ISACA)","justification_wrong":"Hot site é para RTOs de horas; warm site para dias a uma semana; site móvel é solução específica — para RPO de 14 dias, o cold site é economicamente adequado."},
    {"num":9,"text":"Que tecnologia uma organização deve usar em seus servidores de aplicação para garantir disponibilidade contínua aos usuários?","tag":"Alta Disponibilidade","options":["A. Fontes de alimentação redundantes","B. Clustering de servidores","C. Redes redundantes","D. Monitoramento de transações"],"correct":1,"justification_correct":"Clustering de servidores garante que pelo menos um servidor estará sempre disponível para atender às solicitações dos usuários — se um servidor falhar, outro assume automaticamente o serviço. (CISM Review Manual, ISACA)","justification_wrong":"Fontes e redes redundantes protegem contra falhas de infraestrutura específicas; monitoramento detecta problemas mas não garante continuidade — apenas o clustering garante disponibilidade contínua do serviço."},
    {"num":10,"text":"Uma organização armazena mídias de backup em armário ao lado dos computadores sendo copiados. Qual risco o consultor provavelmente considerou ao recomendar armazenamento externo?","tag":"Backup Offsite","options":["A. Um desastre que danifique sistemas também pode danificar as mídias de backup","B. A rotação de mídias pode resultar em perda de dados com semanas de atraso","C. A corrupção de dados online exigirá recuperação rápida do armazenamento externo","D. Os controles físicos no local de processamento são insuficientes"],"correct":0,"justification_correct":"A razão primária para armazenar mídias de backup externamente é mitigar os efeitos de um desastre que poderia destruir simultaneamente os sistemas computacionais e suas mídias de backup. (CISM Review Manual, ISACA)","justification_wrong":"Rotação de mídias, corrupção online e controles físicos são preocupações secundárias — a proteção contra desastre simultâneo é a razão principal para o armazenamento externo."},
    {"num":11,"text":"Um grande terremoto afetou o centro de operações de uma organização. Qual deve ser a prioridade máxima da organização?","tag":"Resposta a Desastres","options":["A. Garantir que ocorra failover automático para o site de recuperação","B. Garantir que visitantes e pessoal saibam evacuar e onde se abrigar","C. Garantir que a replicação de dados para o site de recuperação esteja funcionando","D. Garantir que mídias de backup estejam disponíveis no site de recuperação"],"correct":1,"justification_correct":"A segurança do pessoal é sempre a prioridade máxima em qualquer evento de desastre. A condição dos sistemas de informação é uma preocupação secundária — vidas humanas precedem qualquer consideração tecnológica. (CISM Review Manual, ISACA)","justification_wrong":"Failover, replicação de dados e backups são preocupações importantes mas secundárias — a segurança das pessoas é invariavelmente a prioridade máxima em qualquer desastre."},
    {"num":12,"text":"Uma organização quer proteger seus dados dos efeitos de um ataque de ransomware de alta velocidade. Qual é a melhor abordagem de proteção?","tag":"Proteção contra Ransomware","options":["A. Varrer periodicamente o ambiente em busca de malware","B. Replicar dados para provedor de armazenamento em nuvem","C. Replicar dados para sistema de armazenamento secundário","D. Fazer backup dos dados em mídia offline"],"correct":3,"justification_correct":"O backup em mídia offline é a melhor proteção — ransomware de alta velocidade não consegue acessar ou criptografar mídia offline desconectada da rede. Replicar para sistemas conectados pode resultar na replicação dos próprios dados criptografados. (CISM Review Manual, ISACA)","justification_wrong":"Varredura é controle detectivo; replicação em nuvem e armazenamento secundário podem ser alcançados pelo ransomware se conectados — apenas a mídia offline garante isolamento completo."},
    {"num":13,"text":"Um auditor está avaliando o plano de recuperação de desastres de uma organização. Qual artefato deve ser examinado primeiro?","tag":"Auditoria de DRP","options":["A. Análise de impacto nos negócios (BIA)","B. Relatórios de ações pós-incidente","C. Resultados de testes","D. Registros de treinamento"],"correct":0,"justification_correct":"O auditor deve examinar primeiro os documentos de BIA — eles definem a prioridade dos processos críticos de negócio e os alvos de recuperação, sendo a base sobre a qual todo o plano de recuperação é construído. (CISM Review Manual, ISACA)","justification_wrong":"Relatórios pós-incidente, resultados de testes e registros de treinamento são evidências de execução — a BIA é o documento fundacional que valida se o plano protege o que é realmente crítico."},
    {"num":14,"text":"Os executivos de uma organização estão cansados de receber relatórios sobre incidentes de segurança menores. Qual é o melhor curso de ação?","tag":"Comunicação de Incidentes","options":["A. Implementar controles para impedir a ocorrência dos incidentes","B. Deixar de informar executivos sobre incidentes","C. Desenvolver escala de severidade de incidentes","D. Revisar requisitos regulatórios de divulgação de incidentes"],"correct":2,"justification_correct":"É evidente que o plano de resposta a incidentes não possui níveis de severidade. Uma propriedade dos níveis de severidade é a frequência e o nível de comunicações internas — incidentes menores não chegam a executivos, enquanto incidentes graves geram notificações mais frequentes para a liderança. (CISM Review Manual, ISACA)","justification_wrong":"Implementar controles não elimina todos os incidentes; deixar de informar pode violar obrigações; revisar requisitos regulatórios é secundário — a escala de severidade resolve o problema de comunicação proporcional."},
    {"num":15,"text":"Uma organização estabeleceu RTO de quatro horas para suas aplicações mais críticas. Qual estratégia de recuperação seria a melhor escolha?","tag":"Estratégias de Recuperação","options":["A. Site móvel","B. Site morno (warm site)","C. Hot site","D. Cold site"],"correct":2,"justification_correct":"Uma organização com RTO de quatro horas deve usar um hot site — apenas um hot site consegue retomar o processamento primário dentro de um período tão curto, pois já possui sistemas configurados e prontos para uso imediato. (CISM Review Manual, ISACA)","justification_wrong":"Site móvel é solução alternativa específica; warm site requer horas a dias de configuração; cold site requer dias a semanas — apenas o hot site pode atender a um RTO de quatro horas."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/cism/incident_management")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "cism",
    "domain_id": "incident_management",
    "quiz_num": num1,
    "domain_name": "Incident Management",
    "cert_name": "CISM",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (CISM Incident Management) salvas em {path1}")
print(f"AVISO - quiz incompleto: {len(questions)}/50. Continue com mais material.")
