"""
injetar_cism_govQ5.py
Gera quiz_005_pt.json (50 questoes) para CISM / info_security_governance
e traduz automaticamente para EN e ES via API Anthropic.

Uso:
    cd C:\\NEXOR\\nexor_quiz
    python injetar_cism_govQ5.py
"""

import json, os, time
from pathlib import Path
import anthropic

# ── Configuracao ──────────────────────────────────────────────────────────────
CERT_ID     = "cism"
DOMAIN_ID   = "info_security_governance"
DOMAIN_NAME = "Information Security Governance"
CERT_NAME   = "CISM"
QUIZ_NUM    = 5

DEST_DIR = Path("static/quizzes/cism/info_security_governance")

# ── 50 questoes em Portugues ──────────────────────────────────────────────────
QUESTIONS_PT = [
    {"num":1,"text":"Ravila é uma nova CISO em uma organização de saúde. Durante o desenvolvimento da estratégia, ela descobriu que os administradores de TI aplicam patches de segurança apenas quando a equipe de segurança lhes envia relatórios trimestrais de varredura de vulnerabilidades. Qual é a mudança mais eficaz que pode ser feita no processo de gestão de vulnerabilidades para torná-lo mais proativo versus reativo?","tag":"Gestão de Vulnerabilidades","options":["A. Fazer com que os administradores de TI executem varreduras de vulnerabilidades em seus próprios sistemas.","B. Nenhuma mudança é necessária porque o processo já está funcionando corretamente.","C. Revisar o processo de patching para garantir que os patches sejam aplicados em um cronograma definido baseado no risco da vulnerabilidade, usando a varredura como controle de qualidade.","D. Executar relatórios de varredura de vulnerabilidades mensalmente em vez de trimestralmente."],"correct":2,"justification_correct":"Em um programa eficaz de gestão de vulnerabilidades, os engenheiros de processo aplicam proativamente patches de segurança e outras mudanças de configuração conforme um processo que pode incluir análise de novos patches disponíveis, além de um regime de testes para garantir que os patches não introduzam novos problemas. As varreduras servem como controle de qualidade (QA) para garantir que todos os sistemas estejam configurados e com patches aplicados dentro dos prazos estabelecidos. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque essa mudança não atinge a raiz do problema. B é incorreta porque o processo descrito não está funcionando adequadamente, sendo apenas reativo. D é incorreta porque o patching ainda seria reativo."},
    {"num":2,"text":"Uma organização terceirizou a maioria de suas aplicações de negócio e operações de TI para provedores SaaS e outros prestadores de serviços. Atualmente, a organização não possui uma lista mestre de prestadores de serviços; em vez disso, TI, jurídico, aquisições e segurança possuem listas separadas que não estão alinhadas. Qual deve ser o primeiro passo a tomar?","tag":"Gestão de Terceiros","options":["A. Implementar um cloud access security broker (CASB) para descobrir quais outros prestadores de serviços estão em uso.","B. Criar uma lista mestre de prestadores de serviços a partir das listas de TI, jurídico, aquisições e segurança.","C. Desenvolver uma política que exija que a equipe de segurança avalie todos os novos prestadores de serviços.","D. Desenvolver uma política que exija que o jurídico revise todos os contratos com novos prestadores de serviços."],"correct":1,"justification_correct":"O melhor primeiro passo é criar uma lista mestre de todos os prestadores de serviços conhecidos que combine informações disponíveis de jurídico, TI, aquisições e segurança. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque implementar um CASB pode fornecer informações sobre prestadores adicionais, mas não é o melhor primeiro passo. C e D são incorretas porque o primeiro passo é a consolidação das listas existentes."},
    {"num":3,"text":"Uma organização de manufatura global decidiu desenvolver uma solução SaaS em suporte a um de seus produtos. Quais recursos relacionados à segurança precisarão ser adquiridos em suporte a esse novo empreendimento?","tag":"Segurança em Desenvolvimento de Software","options":["A. Requisitos funcionais, sistema de controle de código-fonte e IDEs.","B. Treinamento de codificação segura, ferramentas de varredura de conteúdo web e um web application firewall.","C. Treinamento de codificação segura, ferramentas DAST e SAST e um web application firewall.","D. Treinamento de codificação segura, ferramentas de varredura de aplicações web e um web application firewall."],"correct":2,"justification_correct":"Para suportar as necessidades de segurança do novo SaaS, a organização precisa adquirir treinamento de codificação segura, testes dinâmicos (DAST) e estáticos (SAST) de segurança de aplicações, e um web application firewall para bloquear ataques de camada 7. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque esses itens não são recursos de segurança. B é incorreta porque ferramentas de varredura de conteúdo web protegem usuários internos, não aplicações web. D é incorreta porque DAST e SAST são mais específicos e eficazes."},
    {"num":4,"text":"Qual é o propósito de desenvolver conteúdo de conscientização de segurança em várias formas?","tag":"Conscientização de Segurança","options":["A. Para fornecer mensagens inesperadas que os usuários têm menos probabilidade de notar.","B. Para maximizar o valor do licenciamento de conteúdo de treinamento de conscientização de segurança.","C. Para aliviar o pessoal do tédio de um único tipo de mensagem.","D. Para abordar a questão de que diferentes pessoas têm diferentes estilos de aprendizado e cognição."],"correct":3,"justification_correct":"Os programas de conscientização de segurança mais eficazes incluem conteúdo em várias formas em reconhecimento ao fato de que diferentes pessoas têm diferentes estilos de aprendizado e cognição. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque o objetivo não é surpreender as pessoas. B é incorreta porque tipos de mídia variados têm pouco a ver com licenciamento. C é incorreta porque o objetivo é alcançar as pessoas de forma eficaz, não aliviar o tédio."},
    {"num":5,"text":"O CISO em uma empresa de capital de risco quer que o processo de aquisição inclua uma avaliação de risco de cibersegurança antes da aquisição de uma nova empresa. Qual é a melhor razão para essa mudança?","tag":"Risco em Fusões e Aquisições","options":["A. Para descobrir riscos de conformidade antes da aquisição.","B. Para identificar riscos relacionados à cibersegurança que podem impactar a avaliação da empresa.","C. Para ter um ponto de partida para entender os riscos que devem ser remediados.","D. Para entender os riscos relacionados à cibersegurança antes de conectar redes."],"correct":1,"justification_correct":"A identificação de riscos de cibersegurança antes da aquisição afetará, às vezes, o verdadeiro valor da empresa sendo adquirida. Vulnerabilidades graves e evidências de violação teriam impacto significativo no valor da empresa. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque riscos de conformidade são úteis, mas não é a melhor resposta. C é incorreta porque a avaliação é mais importante que a remediação nesse contexto. D é incorreta porque empresas de capital de risco tipicamente não conectam suas redes às empresas adquiridas."},
    {"num":6,"text":"Qual é o propósito de enviar questionários de segurança a terceiros no início do processo de due diligence?","tag":"Due Diligence de Terceiros","options":["A. Para determinar as regras de firewall necessárias para conectar-se a um terceiro.","B. Para determinar quais controles precisam ser adicionados ou modificados.","C. Para abordar riscos durante as negociações contratuais.","D. Para registrar o terceiro junto às autoridades regulatórias."],"correct":2,"justification_correct":"O propósito é entender os riscos envolvidos em um relacionamento de negócio com um terceiro. Ao enviar questionários antecipadamente, quaisquer problemas identificados podem ser abordados durante as negociações contratuais. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque regras de firewall são assunto menor do processo de integração. B é incorreta porque este não é o melhor próximo passo. D é incorreta porque apenas em circunstâncias estreitas é necessário registrar o uso de um terceiro junto a autoridades regulatórias."},
    {"num":7,"text":"O CISO de uma organização determinou que a organização de desenvolvimento de software está introduzindo um número crescente de vulnerabilidades de segurança sérias. Qual novo controle seria mais eficaz para garantir que os sistemas de produção estejam livres dessas vulnerabilidades?","tag":"Segurança no SDLC","options":["A. Implementar um sistema de prevenção de intrusão.","B. Implementar um web application firewall.","C. Realizar uma varredura de segurança durante o processo de build do software e exigir que nenhuma vulnerabilidade crítica ou de alto nível exista no software lançado para produção.","D. Administrar treinamento de codificação segura a todos os desenvolvedores uma vez por ano."],"correct":2,"justification_correct":"Varreduras durante o build noturno identificarão novas vulnerabilidades. Exigir que os lançamentos não contenham vulnerabilidades críticas ou de alto nível é um controle eficaz quando ambos os mecanismos estão implementados. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque IPS pode ser parcialmente eficaz mas não resulta na aplicação sendo livre de vulnerabilidades. B é incorreta porque WAF protege contra ataques mas não elimina vulnerabilidades. D é incorreta porque treinamento não tem efeito imediato nas vulnerabilidades existentes."},
    {"num":8,"text":"Qual é a forma mais eficaz de garantir que o pessoal esteja ciente das políticas de segurança de uma organização?","tag":"Políticas de Segurança","options":["A. Exigir que o pessoal reconheça a conformidade com as políticas de segurança anualmente por escrito.","B. Exigir que o pessoal reconheça a conformidade com as políticas de segurança no momento da contratação.","C. Publicar as políticas de segurança da informação na intranet da organização.","D. Distribuir cópias impressas das políticas de segurança da informação a todo o pessoal."],"correct":0,"justification_correct":"Exigir reconhecimento anual por escrito da conformidade com as políticas de segurança é a melhor escolha. Melhor ainda é exigir reconhecimento no momento da contratação E anualmente a partir de então. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque novos funcionários estão frequentemente sobrecarregados com informações na contratação. C é incorreta porque publicar na intranet não garante que o pessoal estará ciente. D é incorreta porque não há garantia de que o pessoal lerá ou entenderá as políticas."},
    {"num":9,"text":"Qual é o melhor método para determinar se os funcionários entendem a política de segurança da informação de uma organização?","tag":"Eficácia do Programa de Segurança","options":["A. Exigir que os funcionários reconheçam a política de segurança da informação por escrito.","B. Incorporar questionários ao treinamento de conscientização de segurança.","C. Exigir que os funcionários leiam a política de segurança da informação.","D. Distribuir cópias da política de segurança da informação aos funcionários."],"correct":1,"justification_correct":"Incorporar questionários ao treinamento de conscientização estabelece um registro do conhecimento dos funcionários sobre a política, particularmente quando as pontuações são retidas. Os questionários ajudam a reforçar o aprendizado e dissuadem o não-repúdio. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque o reconhecimento por escrito não significa que leram ou retiveram conhecimento da política. C é incorreta porque ler não garante retenção. D é incorreta porque distribuir cópias não garante leitura ou retenção."},
    {"num":10,"text":"Um processo de gestão de acesso inclui procedimentos de solicitação, revisão e encerramento de acesso. Qual parte deve revisar periodicamente as solicitações de acesso para garantir que os registros estejam completos e que os acessos foram corretamente provisionados?","tag":"Revisão de Acesso","options":["A. Service desk de TI.","B. Auditoria interna.","C. Proprietário da aplicação.","D. Gerente do funcionário."],"correct":1,"justification_correct":"A auditoria interna é a melhor parte para realizar a revisão de acesso, pois não tem conflito de interesses e possui visão independente do processo. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque o service desk estaria revisando seu próprio trabalho — conflito de interesses. C é incorreta, embora o proprietário da aplicação possa participar. D é incorreta porque os gerentes podem não estar familiarizados com os processos de negócio do sistema."},
    {"num":11,"text":"Qual é o melhor momento para o departamento jurídico revisar um contrato com um prestador de serviços terceirizado?","tag":"Gestão Contratual de Terceiros","options":["A. Após um questionário de segurança ter sido completado pelo prestador de serviços.","B. No início do processo de aquisição.","C. Na fase de seleção do fornecedor.","D. Antes de um questionário de segurança ter sido enviado ao prestador de serviços."],"correct":0,"justification_correct":"O melhor momento é após o prestador de serviços ter completado e retornado um questionário de segurança. Problemas identificados no questionário podem ser mitigados durante as negociações contratuais. (CISM Review Manual, ISACA)","justification_wrong":"B e C são incorretas porque não há informações suficientes disponíveis nessas fases. D é incorreta porque finalizar o contrato antes do questionário é tarde demais para abordar problemas identificados."},
    {"num":12,"text":"Quais aspectos das revisões de acesso de segurança seriam melhor reportados à alta administração?","tag":"Métricas e Reporte Executivo","options":["A. Número de contas revisadas nas revisões de acesso de segurança.","B. Número de revisões de acesso de segurança concluídas.","C. Número de revisões de acesso de segurança realizadas.","D. Número de exceções identificadas durante as revisões de acesso de segurança."],"correct":3,"justification_correct":"O número de exceções identificadas é a melhor métrica operacional para reportar à alta administração. Um número maior indica violações de regras ou falta de atenção; um número baixo indica que os funcionários seguem as regras adequadamente. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque o número de contas revisadas fornece pouco insight sobre a eficácia do processo. B e C são incorretas porque quantidade de revisões não reflete qualidade do processo."},
    {"num":13,"text":"Em uma auditoria do processo de desprovisionamento de contas de usuário para uma instituição financeira, três de cada dez registros selecionados aleatoriamente indicaram que as contas não foram encerradas dentro do limite de controle de 24 horas. Como a auditoria deve prosseguir?","tag":"Auditoria de Controles de Acesso","options":["A. Publicar os achados da auditoria e declarar o controle como ineficaz.","B. Selecionar outra amostra de dez registros e publicar os achados com base nos vinte registros.","C. Testar todas as solicitações de encerramento restantes para ver se mais foram perdidas.","D. Publicar os achados da auditoria e declarar o controle como eficaz."],"correct":2,"justification_correct":"Com três de cada dez amostras falhando, o controle claramente não é eficaz. Todos os registros devem ser examinados para determinar o alcance completo da falha e desprovisionar todas as contas que foram perdidas. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque publicar sem examinar todos os registros não é suficiente. B é incorreta porque a gravidade da situação exige uma ação mais drástica. D é incorreta porque o controle claramente não é eficaz."},
    {"num":14,"text":"O conselho de administração de uma empresa de manufatura solicitou um relatório ao CISO que descreva o estado do programa de cibersegurança da organização. Qual é a melhor forma para o CISO atender a essa solicitação?","tag":"Governança e Reporte ao Board","options":["A. Reunir-se com o conselho em sua próxima reunião agendada e apresentar o estado do programa de cibersegurança.","B. Enviar o teste de penetração mais recente aos membros do conselho.","C. Enviar a avaliação de risco mais recente aos membros do conselho.","D. Enviar o registro de riscos aos membros do conselho."],"correct":2,"justification_correct":"A melhor opção disponível é o CISO enviar a avaliação de risco mais recente. Uma resposta ainda melhor seria um relatório contendo KRIs, incidentes significativos e narrativas sobre realizações recentes e projetos futuros. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque o conselho solicitou um relatório, não apenas tempo de reunião. B é incorreta porque um teste de penetração é muito detalhado e restrito para o conselho. D é incorreta porque o registro de riscos não diz ao conselho o suficiente sobre o que está acontecendo."},
    {"num":15,"text":"Um dos objetivos da estratégia de longo prazo do programa de segurança da informação afirma que um esforço concentrado na melhoria do desenvolvimento de software será empreendido. Qual das seguintes abordagens será MENOS eficaz para atingir esse objetivo?","tag":"Estratégia de Segurança em Desenvolvimento","options":["A. Promulgar incentivos financeiros vinculados a reduções em defeitos de segurança.","B. Implementar web application firewalls (WAFs) e sistemas de prevenção de intrusão (IPSs) para proteger aplicações de ataques.","C. Promulgar uma política de que novos lançamentos de software não podem ser lançados até que vulnerabilidades críticas e de alto nível sejam remediadas.","D. Fornecer treinamento obrigatório de código seguro para todos os desenvolvedores de software."],"correct":1,"justification_correct":"Implementar WAFs e IPSs é MENOS eficaz para melhorar o desenvolvimento de software — apenas cobre e habilita práticas desleixadas de desenvolvimento em relação a defeitos de segurança. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque incentivos financeiros podem ser poderosos para reduzir defeitos. C é incorreta porque a política de não lançar software com vulnerabilidades críticas é eficaz. D é incorreta porque o treinamento de código seguro ajuda os desenvolvedores a evitar defeitos."},
    {"num":16,"text":"O setor de recursos humanos de uma grande multinacional está planejando consolidar seus sistemas de informação de RH (HRIS) em uma única plataforma global. Como a função de segurança da informação pode alinhar sua estratégia a essa iniciativa?","tag":"Alinhamento Estratégico","options":["A. Contratados e trabalhadores temporários podem ser gerenciados no novo HRIS global.","B. Trabalhadores em todos os países podem reconhecer a conformidade com a política de segurança da informação.","C. Trabalhadores em todos os países podem ser inscritos no treinamento de conscientização de segurança.","D. A função de identidade e gestão de acesso pode ser integrada ao novo HRIS global."],"correct":3,"justification_correct":"A melhor oportunidade de alinhamento está no potencial de integrar o novo HRIS global à plataforma de gestão de identidade e acesso da organização. A consolidação deve simplificar grandemente os processos e tecnologias de gestão de identidade e acesso. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque a gestão de contratados pode já estar sendo feita em algumas plataformas HRIS. B é incorreta porque o reconhecimento de conformidade com políticas não é a melhor oportunidade de alinhamento. C é incorreta porque a conscientização de segurança não é tão relevante quanto o alinhamento da plataforma HRIS com a gestão de identidade e acesso."},
    {"num":17,"text":"Qual é a forma mais eficaz de confirmar a conformidade geral com a política de segurança?","tag":"Conformidade com Política de Segurança","options":["A. Realizar testes de penetração nos principais sistemas e aplicações e revisar o código-fonte quando aplicável.","B. Revisar pontuações de testes de treinamentos de conscientização de segurança.","C. Circular questionários para os proprietários dos processos e pedir-lhes que anexem evidências.","D. Entrevistar os proprietários dos processos e examinar os registros de negócio."],"correct":3,"justification_correct":"A forma mais eficaz é realizar auditorias de políticas e controles: entrevistar os proprietários dos controles, examinar documentos de processo e verificar os registros de negócio e outras evidências. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque testes de penetração medirão apenas uma pequena parte da política geral. B é incorreta porque pontuações de testes de conscientização revelam apenas a compreensão dos trabalhadores sobre a política. C é incorreta porque questionários não são um meio eficaz de coletar informações sobre processos."},
    {"num":18,"text":"Qual é o propósito de um exercício de phishing?","tag":"Testes de Phishing","options":["A. Determinar se as mensagens de phishing podem contornar os controles de phishing.","B. Determinar se os links nas mensagens de phishing podem ser confirmados.","C. Determinar quantos funcionários podem ser enganados por mensagens de phishing.","D. Determinar quantas mensagens de phishing reais contornam as defesas anti-phishing."],"correct":2,"justification_correct":"O propósito de um exercício de phishing é determinar que proporção da força de trabalho é potencialmente suscetível a campanhas de phishing reais. As ferramentas rastreiam a resposta de cada usuário e coletam estatísticas sobre a porcentagem da força de trabalho enganada. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque o propósito não é contornar os controles de phishing. B é incorreta porque determinar se os links são confirmáveis não é o objetivo. D é incorreta porque testar defesas anti-phishing não é o propósito principal."},
    {"num":19,"text":"Uma equipe de segurança realizou uma avaliação de risco de um prestador de serviços terceirizado que hospeda o sistema de contabilidade financeira da organização. A avaliação identificou alguns riscos críticos. Como a equipe de segurança e a liderança devem responder?","tag":"Tratamento de Risco de Terceiros","options":["A. Discutir o assunto com o prestador de serviços para ver quais mitigações podem ser implementadas.","B. Promulgar controles para mitigar os riscos críticos.","C. Negociar um novo acordo com o prestador de serviços.","D. Selecionar um prestador de serviços diferente com base na ausência desses riscos."],"correct":0,"justification_correct":"O melhor curso de ação é engajar com o prestador de serviços para entender melhor os riscos e determinar quais ações podem ser tomadas para mitigá-los parcial ou completamente. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque uma organização não pode promulgar controles no ambiente de outra organização. C é incorreta porque negociações contratuais durante o prazo de um contrato são frequentemente infrutíferas. D é incorreta porque a descoberta de novos riscos raramente é suficiente para mudar de prestadores."},
    {"num":20,"text":"Qual é o melhor momento para identificar requisitos de segurança e privacidade em um projeto para identificar e avaliar um prestador de serviços de software?","tag":"Requisitos de Segurança em Projetos","options":["A. Logo antes da implementação.","B. Ao mesmo tempo em que os requisitos funcionais de negócio são identificados.","C. Após a implementação.","D. Após a implementação, antes do primeiro teste de penetração."],"correct":1,"justification_correct":"O melhor momento é na fase mais inicial possível do projeto — tipicamente quando os requisitos de negócio e outros requisitos também são identificados. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque a identificação logo antes da implementação remove a oportunidade de selecionar um prestador baseado em suas capacidades de segurança. C e D são incorretas porque após a implementação é tarde demais."},
    {"num":21,"text":"Qual é a razão principal para descontinuar o uso de SMS para autenticação de dois fatores?","tag":"Autenticação e Controles de Acesso","options":["A. Mensagens SMS podem ser facilmente falsificadas.","B. Ataques de troca de SIM podem fazer com que mensagens SMS sejam enviadas para outro lugar.","C. Mensagens SMS não são criptografadas em trânsito.","D. Senhas de uso único enviadas via SMS não provam a posse física de um dispositivo confiável."],"correct":3,"justification_correct":"Vários métodos estão disponíveis para os usuários obterem mensagens SMS sem ter seu dispositivo móvel com eles, com apenas um ID de usuário e senha, tornando o SMS insuficiente como segundo fator de posse. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque a falsificação de SMS sozinha não ameaça a autenticação de dois fatores. B é incorreta porque este não é o melhor ponto, embora ataques de troca de SIM sejam uma ameaça. C é incorreta porque a criptografia de SMS ocorre em camadas inferiores."},
    {"num":22,"text":"Uma organização vivenciou um incidente no qual um funcionário vazou informações vitais via um provedor de armazenamento em nuvem não aprovado. Qual é o melhor controle automático para evitar esse tipo de evento no futuro?","tag":"Prevenção de Vazamento de Dados","options":["A. Exigir que os funcionários reconheçam a conformidade com a política de segurança anualmente por escrito.","B. Implementar um sistema CASB.","C. Implementar DLP baseado em endpoint.","D. Implementar um GPO para bloquear o uso de dispositivos de armazenamento em massa USB."],"correct":1,"justification_correct":"Um sistema CASB é especificamente projetado para fornecer visibilidade e controle sobre o uso de serviços baseados em nuvem, impedindo que os usuários contatem serviços de nuvem não aprovados. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque reconhecimento de política não é um controle automático. C é incorreta porque DLP endpoint não é tão eficaz quanto CASB para bloquear nuvem não aprovada. D é incorreta porque bloqueio de USB não aborda o armazenamento em nuvem."},
    {"num":23,"text":"Qual é o melhor processo de gestão de vulnerabilidades?","tag":"Gestão de Vulnerabilidades","options":["A. Patching proativo e endurecimento conforme SLAs e varredura de segurança como atividade de QA.","B. Relatórios de varredura de segurança iniciam o patching e o endurecimento conforme SLAs.","C. Patching proativo conforme SLAs e varredura de segurança como atividade de QA.","D. Relatórios de varredura de segurança iniciam o patching conforme SLAs."],"correct":0,"justification_correct":"O melhor processo é aquele em que o patching e o endurecimento são realizados proativamente conforme SLAs estabelecidos e onde a varredura de segurança é uma atividade de QA para confirmar que o patching proativo e o endurecimento são eficazes. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque a varredura não deve ser o motor para o patching. C é incorreta porque deve incluir também o endurecimento proativo. D é incorreta porque depende de varreduras para iniciar o patching e não menciona endurecimento."},
    {"num":24,"text":"Qual é a maior vantagem de implementar unidades menores de treinamento de conscientização de segurança trimestralmente em vez de um treinamento único anual?","tag":"Conscientização de Segurança","options":["A. Manutenção de registros mais simples para fins de conformidade.","B. Menos interrupção para os trabalhadores em uma organização.","C. Redução dos custos de licença de provedores de conteúdo de treinamento.","D. Manter o tópico de segurança da informação atualizado por meio de treinamentos mais frequentes."],"correct":3,"justification_correct":"O propósito principal é manter o tópico de segurança da informação atualizado e manter a conscientização de segurança na mente dos trabalhadores ao longo do ano. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque manter registros de treinamento é simples tanto para treinamentos anuais quanto trimestrais. B é incorreta porque os cursos de conscientização são geralmente curtos. C é incorreta porque as diferenças de custo de licença devem ser mínimas."},
    {"num":25,"text":"Qual é o propósito de avaliar periodicamente riscos em um prestador de serviços terceirizado?","tag":"Avaliação Periódica de Terceiros","options":["A. A avaliação periódica de terceiros é exigida pelo PCI DSS.","B. Avaliar um terceiro é prudente quando o relacionamento de negócio muda ou aumenta.","C. A avaliação periódica ajuda a detectar mudanças nas condições de risco que podem não ter existido no início do relacionamento.","D. Avaliações periódicas determinam a necessidade de realizar testes de penetração de prestadores específicos."],"correct":2,"justification_correct":"Avaliações periódicas de risco são necessárias porque as condições de negócio em qualquer prestador de serviços podem mudar de formas que influenciam o risco para melhor ou para pior. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque isso é muito restrito como posição. B é incorreta porque avaliações também são necessárias quando o relacionamento não muda. D é incorreta porque o resultado de uma avaliação de risco ordinariamente não determina a necessidade de testes de penetração."},
    {"num":26,"text":"Em grandes organizações, qual é a melhor técnica para incorporar linguagem relacionada à cibersegurança em contratos com prestadores de serviços terceirizados?","tag":"Contratos e Gestão de Terceiros","options":["A. Desenvolver termos jurídicos personalizados para cada prestador de serviços com base em questionários.","B. Desenvolver termos jurídicos personalizados para cada prestador de serviços com base no risco.","C. Desenvolver modelos de termos jurídicos para vários tipos de prestadores de serviços.","D. Desenvolver modelos de termos jurídicos para vários tipos de prestadores de serviços e adaptá-los conforme necessário."],"correct":3,"justification_correct":"Grandes organizações com programas de segurança sólidos desenvolvem modelos de termos e condições de segurança para vários tipos de situações. Em seguida, para cada terceiro, mudanças específicas são feitas conforme necessário. (CISM Review Manual, ISACA)","justification_wrong":"A e B são incorretas porque o desenvolvimento de termos e condições puramente personalizados é muito demorado. C é incorreta porque, embora o uso de um modelo seja um bom ponto de partida, cada contrato precisará de mudanças específicas."},
    {"num":27,"text":"O líder de segurança em uma organização soube de uma violação de segurança em um prestador de serviços estratégico que fornece serviços de armazenamento de dados. Qual primeiro passo o líder de segurança deve tomar em relação ao prestador de serviços?","tag":"Resposta a Incidentes de Terceiros","options":["A. Examinar o acordo para ver quais são as obrigações do prestador de serviços.","B. Encerrar o contrato se houver uma cláusula de saída por violação.","C. Solicitar uma cópia do incidente de segurança do prestador de serviços.","D. Realizar um teste de penetração dos endpoints de serviço do prestador de serviços."],"correct":0,"justification_correct":"Antes de tomar qualquer ação, o líder de segurança precisa primeiro entender quais atividades relacionadas à violação o prestador de serviços é obrigado a realizar. Saber isso ajudará a tomar as etapas certas como parte da resposta ao incidente. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque o encerramento de contrato deve ser uma ação de último recurso. C é incorreta porque raramente é decisão do líder de segurança encerrar um contrato. D é incorreta porque um teste de penetração pode não ser permitido ou apropriado."},
    {"num":28,"text":"Qual é o melhor método para testar o seguinte controle: 'Apenas pessoas autorizadas podem aprovar solicitações de acesso de usuário'?","tag":"Teste de Controles","options":["A. Fazer algumas solicitações de acesso fictícias e ver quem as aprova.","B. Entrevistar pelo menos dois especialistas no assunto do processo e revisar os registros de negócio.","C. Entrevistar os proprietários do processo e perguntar quem são os aprovadores.","D. Revisar os registros de negócio e ver quem aprovou as solicitações de acesso."],"correct":1,"justification_correct":"A melhor forma é entrevistar dois ou mais especialistas no assunto sobre o processo de solicitação de acesso e examinar os registros de negócio para ver quem revisou as solicitações de acesso. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque os proprietários do processo podem estar cientes de que os auditores estão observando. C é incorreta porque não inclui o exame de registros de negócio. D é incorreta porque não inclui entrevistas com especialistas."},
    {"num":29,"text":"Em um programa de segurança da informação, uma das declarações de estratégia diz: 'Melhorar o alcance de conscientização de segurança para os funcionários da empresa.' Quais atividades melhor suportariam esse objetivo?","tag":"Conscientização de Segurança","options":["A. Varrer estações de trabalho de usuários finais com mais frequência.","B. Elevar a pontuação mínima necessária para concluir o treinamento de conscientização de segurança com sucesso.","C. Publicar um boletim informativo trimestral com dicas e artigos de segurança.","D. Todos estes estão corretos."],"correct":2,"justification_correct":"Publicar um boletim informativo trimestral é a melhor atividade. Dicas e artigos de segurança ajudarão os funcionários a entender melhor a natureza dos riscos de cibersegurança e as ações que podem tomar para reduzi-los. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque varrer estações de trabalho não melhora o alcance da conscientização. B é incorreta porque elevar a pontuação mínima não melhora o alcance, mas o nível de competência necessário. D é incorreta porque nem todas as respostas ajudam a atingir esse objetivo."},
    {"num":30,"text":"A organização de TI de uma empresa decidiu implementar um portal de single sign-on (SSO) no próximo ano. Quais são as considerações de segurança mais importantes a incluir no planejamento avançado para o portal SSO?","tag":"Identidade e Gestão de Acesso","options":["A. Integração SAML com aplicações.","B. Qualidade de senha e redefinição de senha.","C. Autenticação multifator.","D. Integração HMAC."],"correct":0,"justification_correct":"O objetivo do SSO é tornar a autenticação em um grande número de aplicações uma questão de clicar um botão. Sem SAML ou capacidades de integração equivalentes, será consideravelmente mais difícil integrar um portal SSO com as aplicações de negócio de uma organização. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque qualidade e redefinição de senha nem sempre são controladas por um portal SSO. C é incorreta porque a autenticação multifator, embora vital, nem sempre é controlada por um portal SSO. D é incorreta porque HMAC é um protocolo descontinuado."},
    {"num":31,"text":"Qual é o propósito de um programa de conscientização de segurança?","tag":"Conscientização de Segurança","options":["A. Ajuda o pessoal a entender o uso adequado do computador.","B. Informa o pessoal sobre a política de segurança.","C. Ajuda o pessoal a desenvolver melhor julgamento ao lidar com informações da empresa.","D. Atende aos requisitos de conformidade para PCI DSS e SOX."],"correct":2,"justification_correct":"O objetivo principal da conscientização de segurança é ajudar o pessoal a estar mais ciente dos riscos relacionados à cibersegurança e ajudá-lo a desenvolver melhor julgamento para que tome melhores decisões em uma ampla variedade de situações. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque a conscientização de segurança também inclui conteúdo sobre uso adequado do computador em outros contextos. B é incorreta porque a conscientização de segurança vai além da política de segurança. D é incorreta porque a conformidade não é o único motor do treinamento de conscientização de segurança."},
    {"num":32,"text":"O que significa o termo 'mover para a esquerda' no contexto de segurança da informação e desenvolvimento de sistemas?","tag":"Segurança no SDLC","options":["A. Introduzir segurança mais cedo no ciclo de vida de desenvolvimento.","B. Introduzir segurança mais tarde no ciclo de vida de desenvolvimento.","C. Remediar falhas de segurança mais lentamente.","D. Remediar falhas de segurança mais rapidamente."],"correct":0,"justification_correct":"O termo 'mover para a esquerda' significa que a segurança é introduzida mais cedo nos sistemas no ciclo de vida de desenvolvimento. Por exemplo, realizar varreduras de vulnerabilidades em software pré-lançamento em vez de após o lançamento para produção é 'mover para a esquerda'. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque 'mover para a esquerda' significa que a segurança é introduzida mais cedo, não mais tarde. C e D são incorretas porque 'mover para a esquerda' não está relacionado ao tempo de remediação."},
    {"num":33,"text":"Uma organização realiza testes de phishing mensalmente. Ao longo do último ano, a média das taxas de cliques mudou de 42% para 14%. Que conclusão pode ser extraída dessa tendência?","tag":"Eficácia de Conscientização","options":["A. Os usuários finais são mais propensos a clicar em mensagens de phishing reais.","B. As mensagens de phishing são mais propensas a chegar às caixas de entrada dos usuários finais.","C. Os usuários finais são menos propensos a clicar em mensagens de phishing reais.","D. As mensagens de phishing são menos propensas a chegar às caixas de entrada dos usuários finais."],"correct":2,"justification_correct":"Uma redução nas taxas de cliques em testes de phishing significa que menos usuários finais estão sendo enganados. Isso é uma indicação de que os usuários finais são menos propensos a clicar em mensagens de phishing reais. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque a tendência indica que são menos propensos a clicar, não mais. B e D são incorretas porque essa métrica não fornece indicação sobre a probabilidade de mensagens de phishing reais chegarem às caixas de entrada."},
    {"num":34,"text":"Qual é a melhor abordagem para a implementação inicial de um sistema DLP no ambiente de e-mail de uma organização?","tag":"Prevenção de Perda de Dados","options":["A. Desenvolver uma política de classificação de dados e implementar controles ativos.","B. Desenvolver uma política de classificação de dados, treinar usuários e realizar varreduras de repositórios de dados não estruturados.","C. Desenvolver uma política de classificação de dados, treinar usuários e implementar controles ativos.","D. Desenvolver uma política de classificação de dados, treinar usuários e implementar controles passivos."],"correct":3,"justification_correct":"O sucesso na implementação de DLP requer uma política de classificação de dados bem definida e treinamento de usuários. Implementar DLP no modo passivo (monitoramento) permite que a organização aprenda sobre o movimento de dados; controles ativos podem ser lentamente implementados depois. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque implementar controles ativos imediatamente é altamente provável que interrompa os processos de negócio. B é incorreta porque a varredura estática de dados não está altamente relacionada ao uso de e-mail. C é incorreta porque é necessário primeiro implementar controles passivos para aprender sobre o fluxo de dados."},
    {"num":35,"text":"Uma organização tem experimentado numerosas instâncias de exfiltração não intencional de dados via sistema de e-mail corporativo. Todas as abordagens a seguir para resolver esse problema são válidas EXCETO qual?","tag":"Prevenção de Perda de Dados","options":["A. Avisar os usuários que estão enviando e-mail para destinatários externos para que possam verificar novamente os destinatários.","B. Criptografar automaticamente os anexos nas mensagens enviadas para destinatários externos.","C. Desabilitar o preenchimento automático de destinatários de e-mail.","D. Avisar os usuários que estão enviando e-mails com anexos para destinatários externos para que possam verificar novamente os destinatários."],"correct":1,"justification_correct":"A criptografia automática de anexos não é provável que ajude na situação descrita. Dependendo do método de criptografia, a solução resultará em ninguém conseguindo ler os anexos ou os destinatários errados conseguindo ler os anexos assim mesmo. (CISM Review Manual, ISACA)","justification_wrong":"A e D são incorretas porque avisar os usuários sobre e-mail enviado a partes externas é uma etapa válida. C é incorreta porque desabilitar o preenchimento automático pode ser um remédio eficaz se o problema tiver sido usuários selecionando os destinatários errados."},
    {"num":36,"text":"Em uma organização com uma cultura de segurança estabelecida, alguns funcionários reclamam do tempo necessário para realizar o treinamento anual de conscientização de segurança de oito horas, alegando que já são proficientes no assunto. Qual é a melhor abordagem para resolver essa questão?","tag":"Conscientização de Segurança","options":["A. Permitir que o pessoal pule tópicos do treinamento de conscientização de segurança se primeiro passar em testes sobre esses tópicos.","B. Permitir que essas pessoas pulem o treinamento de conscientização de segurança.","C. Permitir que o pessoal pule o treinamento de conscientização de segurança se tiver obtido boas pontuações em testes em anos anteriores.","D. Exigir que todo o pessoal realize o treinamento porque é exigido pela política."],"correct":0,"justification_correct":"Conhecido como 'teste de saída', a técnica de permitir que o pessoal faça testes sobre vários tópicos e permiti-los pular a instrução se passarem nesses testes é uma prática comum. (CISM Review Manual, ISACA)","justification_wrong":"B e C são incorretas porque alguns dos funcionários que eram proficientes em anos anteriores podem não estar atualizados sobre novas ameaças e práticas. D é incorreta porque isso não aborda diretamente a preocupação deles, o que é razoável."},
    {"num":37,"text":"Uma organização realiza testes de phishing trimestrais. Qual é a melhor abordagem para lidar com os indivíduos que clicam nas mensagens de phishing de teste?","tag":"Gestão de Conscientização","options":["A. Publicar seus nomes em um 'mural da vergonha' para que o pessoal trabalhe mais na detecção de mensagens de phishing.","B. Exigir que eles realizem treinamento de reforço.","C. Remover seus acessos por um período de tempo.","D. Exigir que escrevam um breve ensaio sobre o risco de mensagens de phishing."],"correct":1,"justification_correct":"Quando os trabalhadores clicam em uma mensagem de phishing de teste, a melhor prática é enviá-los de volta a algum treinamento de reforço com a esperança de que sua proficiência melhore. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque envergonhar publicamente o pessoal por um erro não é produtivo e pode ter impacto operacional negativo. C é incorreta porque remover acessos é uma ação muito drástica. D é incorreta porque escrever um ensaio não é uma sanção típica em uma empresa."},
    {"num":38,"text":"Uma organização é obrigada, por um acordo legal, a realizar revisões de atividades de contas. Qual das seguintes melhor define uma revisão de atividade de conta?","tag":"Revisão de Contas","options":["A. Uma revisão para ver quantas mudanças nas contas dos usuários são realizadas durante um período de tempo.","B. Uma revisão para ver com que frequência os usuários fazem login em suas contas.","C. Uma revisão para ver quão ocupados os usuários estão quando fazem login em suas contas.","D. Uma revisão para ver se os usuários fizeram login em suas contas durante um período de tempo específico."],"correct":3,"justification_correct":"Uma revisão de atividade de conta determina se cada conta de usuário está ativa em um determinado período de tempo. Quaisquer contas de usuário sem logins são candidatas para bloqueio ou remoção, reduzindo os riscos de acesso não autorizado. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque uma revisão de atividade de conta não está relacionada ao número de mudanças feitas nas contas. B é incorreta porque a frequência de logins não é a preocupação principal. C é incorreta porque quão ocupados os usuários estão quando fazem login não é relevante."},
    {"num":39,"text":"Uma organização específica é um provedor de software financeiro como serviço (SaaS) no setor de serviços financeiros. Muitos dos clientes afirmam que têm um requisito regulatório para realizar auditorias do provedor SaaS. Qual remédio está disponível para minimizar ou eliminar essas auditorias dos clientes?","tag":"Auditoria e Conformidade SaaS","options":["A. Realizar uma auditoria anual SOC 2 Tipo 2.","B. Realizar uma auditoria anual SOC 2 Tipo 1.","C. Realizar uma auditoria anual SOC 1 Tipo 2 dos controles relevantes.","D. Realizar uma auditoria anual SOC 1 Tipo 1 dos controles relevantes."],"correct":0,"justification_correct":"Uma organização que fornece serviços relacionados a financeiros a clientes pode realizar auditorias SOC 1 Tipo 2 anuais ou semestrais. Esta auditoria é uma alternativa eficaz e econômica para clientes que realizam suas próprias auditorias. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque uma auditoria SOC 2 Tipo 1 ou Tipo 2 não dissuadirá efetivamente os auditores dos clientes. D é incorreta porque uma auditoria SOC 1 Tipo 1 não fornecerá conforto suficiente aos auditores nas organizações clientes."},
    {"num":40,"text":"Uma organização fornece conteúdo de treinamento a clientes corporativos por meio de uma plataforma SaaS. Como a organização SaaS pode reduzir o número de solicitações de auditoria de seus clientes?","tag":"Auditoria e Conformidade SaaS","options":["A. Realizar um teste de penetração anual de sua aplicação SaaS.","B. Realizar um teste de penetração anual de sua infraestrutura.","C. Realizar uma auditoria anual SOC 2 Tipo 1.","D. Realizar uma auditoria anual SOC 2 Tipo 2."],"correct":3,"justification_correct":"A melhor abordagem para uma organização SaaS não financeira é realizar uma auditoria SOC 2 Tipo 2 anual. Os auditores examinam os processos de negócio, bem como os registros de negócio, e desenvolvem relatórios detalhados sobre a eficácia de cada controle. (CISM Review Manual, ISACA)","justification_wrong":"A e B são incorretas porque testes de penetração revelam apenas uma faixa estreita de risco para os clientes. C é incorreta porque uma auditoria SOC 1 é um exame apenas da documentação de processos de negócio da organização."},
    {"num":41,"text":"Um CISO está preocupado com o 'escopo crescente' entre seus terceiros em um processo de gestão de risco de terceiros com classificações de risco em níveis. O que isso significa?","tag":"Gestão de Risco de Terceiros","options":["A. Terceiros que, ao longo do tempo, fornecem serviços adicionais que deveriam elevá-los a níveis de maior risco.","B. Terceiros cujos programas de segurança se degradam ao longo do tempo.","C. Terceiros que terceirizam mais e mais de suas operações para quartos-partidos.","D. Terceiros que melhoram seus programas de segurança ao longo do tempo."],"correct":0,"justification_correct":"O 'escopo crescente' significa que um terceiro é inicialmente classificado em um nível de baixo risco. Uma mudança nos serviços que o terceiro fornece à organização resulta em sua colocação em um nível de maior risco. Infelizmente, muitas vezes o CISO não é informado sobre as mudanças no relacionamento de negócio. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque a degradação do programa de segurança de um terceiro não é conhecida como 'escopo crescente'. C é incorreta porque terceiros terceirizando para quartos-partidos também não é 'escopo crescente'. D é incorreta porque a melhoria do programa de segurança de um terceiro não é 'escopo crescente'."},
    {"num":42,"text":"Quando em uma auditoria é aceitável usar uma amostra em vez de toda a população?","tag":"Metodologia de Auditoria","options":["A. Quando toda a população é muito grande para testar individualmente.","B. Quando a automação está em vigor para garantir consistência.","C. Quando o registro está em vigor para medir os resultados.","D. Quando o alerta está em vigor para notificar o pessoal sobre exceções."],"correct":0,"justification_correct":"A amostragem é aceitável quando toda a população de objetos é muito grande para examinar individualmente. Durante uma auditoria, se um número excessivo de exceções for encontrado, amostras adicionais podem ser coletadas para entender melhor o problema. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque a automação não é um requisito para amostragem. C é incorreta porque a presença de registro geralmente não é um fator em uma decisão de amostragem. D é incorreta porque o alerta não está relacionado a decisões de amostragem."},
    {"num":43,"text":"Uma auditoria de uma conta de usuário privilegiado apresentou um alto número de exceções na amostra. Qual é o próximo passo adequado?","tag":"Exceções de Auditoria","options":["A. Notificar a administração de que houve uma violação.","B. Parar a auditoria.","C. Selecionar amostras adicionais.","D. Completar o relatório de auditoria."],"correct":2,"justification_correct":"De modo geral, durante uma auditoria em que um grande número de exceções foi identificado em uma determinada amostragem, é apropriado selecionar amostras adicionais para determinar a extensão da ineficácia do controle. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque exceções de auditoria não significam automaticamente que uma violação ocorreu. B é incorreta porque não é o momento de parar a auditoria. D é incorreta porque a auditoria não está completa."},
    {"num":44,"text":"Qual regulamentação dos EUA regula a proteção de dados relacionados a cuidados médicos?","tag":"Conformidade Regulatória","options":["A. PIPEDA.","B. HIPAA.","C. GLBA.","D. GDPR."],"correct":1,"justification_correct":"HIPAA, o Health Insurance Portability and Accountability Act, compreende uma Regra de Privacidade e uma Regra de Segurança. A Regra de Privacidade limita o que as organizações de saúde estão autorizadas a fazer com ePHI, enquanto a Regra de Segurança estipula os processos e ferramentas necessários para a proteção de ePHI. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque PIPEDA é a lei federal de privacidade canadense. C é incorreta porque GLBA é para o setor de serviços financeiros dos EUA. D é incorreta porque GDPR é o regulamento europeu de proteção de dados."},
    {"num":45,"text":"A regulamentação 'Security and Privacy Controls for Federal Information Systems and Organizations' é mais conhecida como?","tag":"Frameworks de Segurança","options":["A. ISO/IEC 27001.","B. ISO/IEC 27002.","C. NIST CSF.","D. NIST SP 800-53."],"correct":3,"justification_correct":"NIST SP 800-53 é o framework de controles de segurança desenvolvido pelo NIST, exigido de todos os ramos do governo federal dos EUA e amplamente adotado pela indústria privada. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque ISO/IEC 27001 é o padrão de sistemas de gestão de segurança da informação. B é incorreta porque ISO/IEC 27002 é o código de prática para controles de segurança da informação. C é incorreta porque NIST CSF é o Framework de Cibersegurança do NIST."},
    {"num":46,"text":"Jeffrey é CISO em uma organização que presta serviços financeiros para organizações privadas e agências governamentais dos EUA, incluindo agências federais dos EUA. Qual é o melhor framework de controles de segurança da informação para essa organização?","tag":"Seleção de Framework","options":["A. CIS CSC.","B. ISO/IEC 27001.","C. NIST CSF.","D. NIST SP 800-53."],"correct":3,"justification_correct":"Como prestador de serviços para o governo federal dos EUA, a organização de Jeffrey é obrigada a adotar o framework de controles NIST SP 800-53. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque CIS CSC não é exigido para organizações que prestam serviços de informação ao governo federal dos EUA. B é incorreta porque ISO/IEC 27001 não é exigido para prestadores de serviços ao governo federal. C é incorreta porque NIST CSF é uma metodologia, não um framework de controles."},
    {"num":47,"text":"Qual é o escopo dos requisitos do PCI DSS?","tag":"PCI DSS","options":["A. Todos os sistemas que armazenam, processam e transmitem números de cartão de crédito, bem como todos os outros sistemas que podem se comunicar com esses sistemas.","B. Todos os sistemas que armazenam, processam e transmitem números de cartão de crédito.","C. Todos os sistemas que armazenam, processam e transmitem números de cartão de crédito não criptografados.","D. Todos os sistemas em uma organização onde números de cartão de crédito são armazenados, processados e transmitidos."],"correct":0,"justification_correct":"Os sistemas no escopo do PCI DSS são todos aqueles que armazenam, processam ou transmitem números de cartão de crédito, bem como todos os outros sistemas que podem se comunicar com esses sistemas. (CISM Review Manual, ISACA)","justification_wrong":"B é incorreta porque o escopo inclui também sistemas que se comunicam com os que processam cartões. C é incorreta porque inclui sistemas com dados criptografados. D é incorreta porque o escopo não é necessariamente todos os sistemas da organização."},
    {"num":48,"text":"Qual das seguintes afirmações sobre os controles do Payment Card Industry Data Security Standard é verdadeira?","tag":"PCI DSS","options":["A. Muitos controles são obrigatórios, enquanto alguns são opcionais, com base no risco.","B. Todos os controles são obrigatórios, independentemente do risco real.","C. Os controles obrigatórios são determinados para cada organização pelo banco adquirente.","D. Além dos controles centrais, cada marca de cartão de crédito tem seus próprios controles únicos."],"correct":1,"justification_correct":"Todos os controles são obrigatórios para todas as organizações. Existem controles adicionais obrigatórios para prestadores de serviços. As marcas de cartão individuais impõem requisitos específicos de relatório de conformidade. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque nenhum controle no PCI DSS é opcional. C é incorreta porque os bancos adquirentes não determinam a aplicabilidade dos controles. D é incorreta porque marcas de cartão não impõem controles adicionais, apenas requisitos de relatório."},
    {"num":49,"text":"O PCI DSS é um exemplo de quê?","tag":"Padrões da Indústria","options":["A. Uma regulamentação da indústria que é aplicada com multas.","B. Um padrão privado da indústria que é aplicado por contratos.","C. Um padrão voluntário que, se usado, pode reduzir prêmios de seguro cibernético.","D. Uma lei internacional aplicada por meio de tratados com nações membros."],"correct":1,"justification_correct":"O PCI DSS foi desenvolvido por um consórcio das principais marcas de cartão de crédito do mundo: Visa, MasterCard, American Express, Discover e JCB. O PCI DSS é aplicado por meio das regras operacionais das marcas de cartão de crédito e pelos bancos adquirentes. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque PCI DSS não é uma lei ou regulamentação. C é incorreta porque PCI DSS não é voluntário para comerciantes e prestadores de serviços que processam cartões. D é incorreta porque PCI DSS não é uma lei internacional."},
    {"num":50,"text":"Qual das seguintes afirmações sobre frameworks de controle é correta?","tag":"Frameworks de Controle","options":["A. Os frameworks de controle são usados apenas em ambientes regulados.","B. Todos os frameworks de controle são essencialmente iguais, com diferentes grupos de controles.","C. Não importa qual framework de controle é selecionado, desde que os controles sejam operados eficazmente.","D. Diferentes frameworks de controle estão associados a diferentes indústrias."],"correct":3,"justification_correct":"Diferentes frameworks de controle são de fato associados a diferentes indústrias. Por exemplo, controles PCI DSS são usados em organizações que processam cartões de crédito, e controles NIST 800-53 são usados em agências do governo federal dos EUA e organizações que prestam serviços de informação a essas agências. (CISM Review Manual, ISACA)","justification_wrong":"A é incorreta porque frameworks de controle são usados tanto em ambientes regulados quanto não regulados. B é incorreta porque frameworks de controle podem ser similares mas não idênticos. C é incorreta porque diferentes frameworks têm diferenças que em alguns casos podem ser significativas."},
]

# ── Funcoes ───────────────────────────────────────────────────────────────────
def build_payload(questions, lang):
    return {
        "cert_id": CERT_ID,
        "domain_id": DOMAIN_ID,
        "quiz_num": QUIZ_NUM,
        "domain_name": DOMAIN_NAME,
        "cert_name": CERT_NAME,
        "lang": lang,
        "questions": questions,
    }

def traduzir_bloco(client, bloco, lang_label):
    prompt = f"""Voce e um tradutor especialista em certificacoes de seguranca da informacao (CISM, CISSP, ISO 27001).

Traduza o JSON abaixo para {lang_label}. Regras:
- Mantenha terminologia tecnica precisa (ex: CISM, ISACA, SOC, PCI DSS, NIST, CASB, DLP, WAF, SAST, DAST, SSO, SAML, SLA, KRI, SaaS, SDLC).
- Mantenha todos os campos: num, text, tag, options, correct, justification_correct, justification_wrong.
- O campo "correct" e um inteiro — NAO traduza, copie exatamente.
- Retorne APENAS o array JSON das questoes traduzidas, sem markdown, sem explicacoes, sem texto antes ou depois.

JSON para traduzir:
{json.dumps(bloco, ensure_ascii=False)}"""

    resp = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=16000,
        messages=[{"role": "user", "content": prompt}]
    )
    raw = resp.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    return json.loads(raw.strip())

def traduzir(client, questions_pt, lang):
    lang_label = "INGLES TECNICO" if lang == "en" else "ESPANHOL TECNICO"
    meio = len(questions_pt) // 2
    bloco1 = questions_pt[:meio]
    bloco2 = questions_pt[meio:]
    print(f"    Bloco 1 ({len(bloco1)} questoes)...")
    resultado1 = traduzir_bloco(client, bloco1, lang_label)
    time.sleep(3)
    print(f"    Bloco 2 ({len(bloco2)} questoes)...")
    resultado2 = traduzir_bloco(client, bloco2, lang_label)
    return resultado1 + resultado2

def salvar(payload, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"  SALVO: {path} ({len(payload['questions'])} questoes)")

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ERRO: variavel ANTHROPIC_API_KEY nao encontrada.")
        return

    client = anthropic.Anthropic(api_key=api_key)

    print("=" * 60)
    print(f"  INJETOR CISM / {DOMAIN_ID} / quiz_{QUIZ_NUM:03d}")
    print("=" * 60)

    # 1. Salva PT
    print("\n[1/3] Salvando Portugues...")
    pt_payload = build_payload(QUESTIONS_PT, "pt")
    salvar(pt_payload, DEST_DIR / f"quiz_{QUIZ_NUM:03d}_pt.json")

    # 2. Traduz e salva EN
    print("\n[2/3] Traduzindo para Ingles via API...")
    questions_en = traduzir(client, QUESTIONS_PT, "en")
    en_payload = build_payload(questions_en, "en")
    salvar(en_payload, DEST_DIR / f"quiz_{QUIZ_NUM:03d}_en.json")
    time.sleep(2)

    # 3. Traduz e salva ES
    print("\n[3/3] Traduzindo para Espanhol via API...")
    questions_es = traduzir(client, QUESTIONS_PT, "es")
    es_payload = build_payload(questions_es, "es")
    salvar(es_payload, DEST_DIR / f"quiz_{QUIZ_NUM:03d}_es.json")

    print("\n" + "=" * 60)
    print("  CONCLUIDO! 3 arquivos gerados:")
    for lang in ["pt", "en", "es"]:
        p = DEST_DIR / f"quiz_{QUIZ_NUM:03d}_{lang}.json"
        print(f"    {p}")
    print("=" * 60)

    # Limpeza dos arquivos errados anteriores
    print("\n[LIMPEZA] Removendo arquivos incorretos gerados anteriormente...")
    errados = [
        "static/quizzes/cism/info_security_governance/quiz_005_pt.json",
        "static/quizzes/cism/info_security_governance/quiz_005_en.json",
        "static/quizzes/cism/info_security_governance/quiz_005_es.json",
        "static/quizzes/cism/info_risk_management/quiz_003_pt.json",
        "static/quizzes/cism/info_risk_management/quiz_003_en.json",
        "static/quizzes/cism/info_risk_management/quiz_003_es.json",
        "static/quizzes/cism/incident_management/quiz_002_pt.json",
        "static/quizzes/cism/incident_management/quiz_002_en.json",
        "static/quizzes/cism/incident_management/quiz_002_es.json",
    ]
    for f in errados:
        p = Path(f)
        if p.exists():
            p.unlink()
            print(f"  REMOVIDO: {p}")
        else:
            print(f"  NAO ENCONTRADO (ok): {p}")
    print("\nTudo pronto!")

if __name__ == "__main__":
    main()
