#!/usr/bin/env python3
"""
CISM BATCH 9 - Governanca e Gestao Estrategica
10 questoes -> governance/quiz_003 (fecha em 50)
9 questoes  -> risk_management/quiz_001 (fecha em 50)
6 questoes  -> governance/quiz_003 overflow ou novo quiz
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# 10 questoes para fechar governance/quiz_003
q_gov = [
    {"num":41,"text":"Qual das seguintes afirmações melhor descreve a governança de segurança da informação?","tag":"Governança","options":["A. Políticas de segurança da informação","B. Políticas de segurança combinadas com auditorias","C. Controle, pela gestão, dos processos de segurança da informação","D. Benchmarking de métricas com organizações similares"],"correct":2,"justification_correct":"A ISACA define governança como o conjunto de processos que garante que necessidades das partes interessadas sejam avaliadas, direção seja estabelecida por priorização e tomada de decisão, e desempenho seja monitorado em relação aos objetivos acordados. (CISM Review Manual, ISACA)","justification_wrong":"Políticas e auditorias são componentes; benchmarking não é elemento central — governança é o controle gerencial abrangente dos processos de segurança."},
    {"num":42,"text":"Em um processo de gestão de riscos, quem é a melhor pessoa para tomar a decisão de tratamento de risco?","tag":"Decisão de Risco","options":["A. Chief Risk Officer (CRO)","B. Chief Information Officer (CIO)","C. Dono do processo de negócio associado ao risco","D. Chief Information Security Officer (CISO)"],"correct":2,"justification_correct":"A decisão de tratamento de risco é uma decisão de negócio e deve ser tomada pelo responsável pela função de negócio. CRO, CIO e CISO devem facilitar o processo, não decidir em nome dos donos de processo. (CISM Review Manual, ISACA)","justification_wrong":"CRO, CIO e CISO devem facilitar discussões — a decisão pertence ao dono do processo de negócio afetado pelo risco."},
    {"num":43,"text":"A responsabilidade final pelo programa de cibersegurança de uma organização recai sobre:","tag":"Responsabilidade","options":["A. O conselho de administração","B. O diretor executivo (CEO)","C. O diretor de tecnologia da informação (CIO)","D. O diretor de segurança da informação (CISO)"],"correct":0,"justification_correct":"A responsabilidade final por tudo em uma organização — incluindo o programa de cibersegurança — recai sobre o conselho de administração, conforme definido em diversas leis e regulamentações, especialmente para empresas de capital aberto. (CISM Review Manual, ISACA)","justification_wrong":"CEO, CIO e CISO têm responsabilidades operacionais, mas a responsabilidade final e fiduciária pertence ao conselho de administração."},
    {"num":44,"text":"Em uma empresa pública nos EUA, para qual instância o CISO geralmente reporta o estado do programa de cibersegurança?","tag":"Reporte","options":["A. À Treadway Commission","B. Aos auditores externos independentes","C. À Securities and Exchange Commission (SEC)","D. Ao comitê de auditoria do conselho de administração"],"correct":3,"justification_correct":"Na maioria das empresas de capital aberto nos EUA, o CISO reporta o estado do programa de cibersegurança ao comitê de auditoria do conselho — que tem responsabilidade fiduciária sobre controles e riscos. (CISM Review Manual, ISACA)","justification_wrong":"Treadway Commission não recebe relatórios; auditores externos e SEC recebem relatórios financeiros — o reporte de cibersegurança é direcionado ao comitê de auditoria."},
    {"num":45,"text":"Qual é a melhor parte responsável por conduzir revisões de acesso a sistemas de negócio?","tag":"Revisão de Acesso","options":["A. Gerentes diretos dos usuários","B. Gerente de segurança da informação","C. Equipe de service desk de TI","D. Chefe do departamento de negócio responsável pela atividade"],"correct":3,"justification_correct":"Os responsáveis pelas atividades de negócio são quem melhor conhece quem deve ter acesso e em que nível — TI raramente possui conhecimento operacional suficiente para tomar decisões de qualidade sobre acesso. (CISM Review Manual, ISACA)","justification_wrong":"Gestores, segurança e service desk têm conhecimento técnico mas limitado sobre operações de negócio — o chefe do departamento tem visão completa das necessidades operacionais."},
    {"num":46,"text":"Qual é a melhor parte para tomar decisões sobre o propósito e funcionalidade das aplicações de negócio?","tag":"Propriedade de Aplicações","options":["A. Chefe do departamento de negócio","B. Analista de negócios de TI","C. Desenvolvedor da aplicação","D. Usuário final da aplicação"],"correct":0,"justification_correct":"O chefe do departamento é responsável pela continuidade e sucesso das operações — sendo a parte mais adequada para definir o comportamento e as funcionalidades das aplicações que suportam esses processos. (CISM Review Manual, ISACA)","justification_wrong":"Analistas facilitam; desenvolvedores conhecem a tecnologia; usuários finais não são responsáveis por decisões estratégicas — o chefe do departamento tem autoridade e visão operacional."},
    {"num":47,"text":"Qual é o principal risco quando a área de TI atua como custodiante para donos de processos de negócio?","tag":"Custódia de TI","options":["A. TI pode não ter interesse suficiente para cuidar das aplicações","B. TI pode não ter equipe suficiente para gerenciar as aplicações","C. TI pode ter conhecimento insuficiente das operações de negócio","D. Departamentos de negócio podem restringir o acesso da TI"],"correct":2,"justification_correct":"Profissionais de TI tendem a focar na tecnologia, não nas operações de negócio — frequentemente fazem suposições sobre necessidades dos clientes sem compreender o que os usuários realmente precisam. (CISM Review Manual, ISACA)","justification_wrong":"Falta de interesse, equipe insuficiente e restrição de acesso não são o risco primário — o conhecimento insuficiente das operações é o risco central da custódia de TI."},
    {"num":48,"text":"Qual é o propósito principal das métricas em um programa de segurança da informação?","tag":"Métricas","options":["A. Medir o desempenho e a eficácia dos controles de segurança","B. Medir a probabilidade de um ataque à organização","C. Prever a probabilidade de ataques futuros","D. Prever o método de ataque mais provável"],"correct":0,"justification_correct":"As métricas medem o desempenho e a eficácia dos controles de segurança, fornecendo evidências objetivas de que o programa funciona conforme planejado e identificando áreas de melhoria. (CISM Review Manual, ISACA; ISO/IEC 27004)","justification_wrong":"Probabilidade de ataques e previsão de métodos são funções de inteligência de ameaças — as métricas medem a efetividade dos controles existentes."},
    {"num":49,"text":"Qual é a utilidade de um processo de Gestão de Riscos de Terceiros (TPRM) para um CISO desenvolvendo estratégia de longo prazo?","tag":"TPRM","options":["A. Fornece informações sobre as capacidades de segurança de provedores críticos","B. Fornece informações sobre o processo de compras da organização","C. Fornece lista de todos os provedores de serviços utilizados","D. Não agrega valor ao CISO por se preocupar com processos de negócio"],"correct":0,"justification_correct":"Um programa de TPRM eficaz captura informações detalhadas sobre controles de segurança de provedores terceirizados, permitindo ao CISO compreender o cenário de riscos associado à proteção de dados e capacidades críticas. (CISM Review Manual, ISACA)","justification_wrong":"TPRM vai além de listas e processos de compras — seu valor estratégico está na avaliação das capacidades de segurança de terceiros que acessam dados e sistemas críticos."},
    {"num":50,"text":"Qual é o melhor primeiro passo para formalizar um programa de segurança da informação em uma organização?","tag":"Formalização","options":["A. Criar site de intranet de segurança da informação","B. Lançar boletim informativo de segurança","C. Desenvolver política de segurança da informação","D. Desenvolver estatuto (charter) do programa de segurança"],"correct":3,"justification_correct":"O estatuto do programa define missão, visão, papéis, responsabilidades e engajamento com stakeholders — sendo o documento fundacional que legitima e formaliza o programa antes de qualquer outra iniciativa. (CISM Review Manual, ISACA)","justification_wrong":"Site, boletins e política são importantes mas secundários — o charter é o documento fundacional que deve existir primeiro."},
]

# 9 questoes para fechar risk_management/quiz_001
q_risk = [
    {"num":42,"text":"Um novo CISO está construindo um programa de cibersegurança e precisa garantir colaboração entre líderes de negócio. Qual estrutura deve ser formada?","tag":"Comitê Diretor","options":["A. Um comitê de riscos do conselho de administração","B. Um comitê diretor de cibersegurança","C. Um comitê de auditoria do conselho","D. Uma política de segurança alinhada ao negócio"],"correct":1,"justification_correct":"Um comitê diretor de cibersegurança, composto por executivos seniores e líderes de negócio, promove colaboração e permite discussões estratégicas sobre risco cibernético quando conduzido pelo CISO. (CISM Review Manual, ISACA)","justification_wrong":"Comitê de riscos e de auditoria do conselho não são criados pelo CISO; política não cria colaboração executiva estruturada — o comitê diretor é o mecanismo correto."},
    {"num":43,"text":"Qual é o melhor grupo para tomar decisões de tratamento de riscos cibernéticos em uma organização?","tag":"Decisão de Risco","options":["A. O CISO de forma unilateral","B. O comitê de auditoria do conselho","C. O comitê diretor de cibersegurança","D. O CRO de forma unilateral"],"correct":2,"justification_correct":"O comitê diretor, com executivos seniores e líderes de negócio, promove decisões colaborativas — decisões unilaterais do CISO ou CRO geram menor engajamento dos líderes de negócio. (CISM Review Manual, ISACA)","justification_wrong":"Decisões unilaterais reduzem a adesão; comitês de auditoria raramente se envolvem em decisões operacionais de risco — o comitê diretor é o fórum correto."},
    {"num":44,"text":"A declaração 'Migração completa do sistema principal para a versão mais recente do software do fornecedor' é um exemplo de:","tag":"Planejamento Estratégico","options":["A. Declaração de missão","B. Declaração de visão","C. Declaração de propósito","D. Declaração de objetivo"],"correct":3,"justification_correct":"A declaração é específica, mensurável e orientada a resultado — características de um objetivo estratégico, não de missão, visão ou propósito que são declarações amplas e duradouras. (CISM Review Manual, ISACA)","justification_wrong":"Missão descreve o propósito permanente; visão descreve o estado futuro amplo; propósito é abstrato — a especificidade da declaração caracteriza um objetivo."},
    {"num":45,"text":"Um CISO deseja criar declaração de missão para seu grupo de segurança. Qual é a melhor abordagem inicial?","tag":"Missão de Segurança","options":["A. Começar com a declaração de missão da organização","B. Começar com a avaliação de desempenho mais recente","C. Começar com os resultados da avaliação de risco","D. Começar com o registro de riscos em aberto"],"correct":0,"justification_correct":"Alinhar a missão da equipe de segurança à missão da organização garante que a função de segurança suporte os objetivos estratégicos — fundamento do alinhamento estratégico. (CISM Review Manual, ISACA)","justification_wrong":"Avaliação de desempenho, resultados de risco e registro são insumos operacionais — a missão deve derivar do propósito organizacional mais amplo."},
    {"num":46,"text":"Um líder de segurança avaliou a maturidade com o modelo CMMI e obteve média 3.2. O que deve fazer a seguir?","tag":"Maturidade CMMI","options":["A. Comparar níveis atuais com os desejados e desenvolver estratégia para atingi-los","B. Determinar etapas para elevar todos os processos ao nível 5","C. Identificar processos de menor maturidade e elevá-los ao nível dos demais","D. Realizar análise de causa raiz para determinar por que a maturidade caiu"],"correct":0,"justification_correct":"A melhor abordagem é comparar os níveis atuais com os desejados, identificar as lacunas e desenvolver estratégia para fechá-las — não elevar tudo ao máximo nem focar apenas nos menores. (CISM Review Manual, ISACA)","justification_wrong":"Elevar todos ao nível 5 pode não ser necessário ou viável; focar apenas nos menores ignora o alinhamento estratégico; análise de causa raiz é inadequada pois 3.2 pode ser o nível esperado."},
    {"num":47,"text":"Um estrategista analisa vários processos com maturidades entre Repetível e Otimizado. Qual é o melhor estado futuro?","tag":"Maturidade","options":["A. Todos os processos devem ser elevados ao Repetível","B. Todos devem ser elevados ao Otimizado","C. Não há informações suficientes para determinar os estados futuros","D. Processos Repetíveis devem ser elevados ao Definido"],"correct":2,"justification_correct":"Não existe regra que determine que todos os processos devam estar no mesmo nível. O nível adequado depende do apetite ao risco, do nível de risco e de outras considerações estratégicas não disponíveis neste cenário. (CISM Review Manual, ISACA)","justification_wrong":"Elevar todos ao mesmo nível ignora o contexto de risco de cada processo — sem informações de risco e apetite, não é possível definir o estado futuro ideal."},
    {"num":48,"text":"Um estrategista constata que um processo é executado consistentemente mas sem documentação. Qual é o nível de maturidade?","tag":"Maturidade CMMI","options":["A. Inicial","B. Repetível","C. Definido","D. Gerenciado"],"correct":1,"justification_correct":"Um processo executado consistentemente mas sem documentação formal é classificado como Repetível (nível 2 do CMMI) — existe padronização informal baseada na prática, mas sem a formalização que caracteriza o nível Definido. (CISM Review Manual, ISACA)","justification_wrong":"Inicial é ad hoc; Definido exige documentação formal; Gerenciado exige métricas — apenas Repetível descreve consistência sem documentação."},
    {"num":49,"text":"Qual é o propósito de uma gap analysis no contexto do desenvolvimento de estratégia de segurança?","tag":"Gap Analysis","options":["A. Identificar necessidades de melhoria em processos, sistemas, políticas e controles","B. Identificar sistemas e ativos vulneráveis","C. Identificar políticas ambíguas que necessitam revisão","D. Identificar controles ineficazes que devem ser substituídos"],"correct":0,"justification_correct":"No contexto de estratégia, a gap analysis identifica as lacunas entre o estado atual e o estado futuro desejado em sistemas, processos, políticas e controles — habilitando o estrategista a desenvolver planos para fechar cada lacuna. (CISM Review Manual, ISACA)","justification_wrong":"Vulnerabilidades, políticas ambíguas e controles ineficazes são identificados por processos específicos — a gap analysis é mais abrangente e estratégica."},
    {"num":50,"text":"Qual afirmação descreve melhor a relação entre estratégia de segurança e objetivos de negócio?","tag":"Alinhamento Estratégico","options":["A. A estratégia de segurança deve ser desenvolvida independentemente dos objetivos de negócio","B. Os objetivos de negócio devem ser adaptados para acomodar os requisitos de segurança","C. A estratégia de segurança deve ser desenvolvida para suportar e habilitar os objetivos de negócio","D. Segurança e negócio têm objetivos naturalmente conflitantes que devem ser equilibrados"],"correct":2,"justification_correct":"A estratégia de segurança da informação deve ser desenvolvida para suportar e habilitar os objetivos de negócio — não como uma função isolada. O alinhamento estratégico é um princípio fundamental da governança CISM. (CISM Review Manual, ISACA)","justification_wrong":"Independência e conflito natural são premissas incorretas; o negócio não deve se adaptar à segurança — a segurança existe para habilitar o negócio de forma segura."},
]

def add_to_quiz(quiz_path, new_questions, start_num=None):
    if not quiz_path.exists():
        return False, 0
    data = json.loads(quiz_path.read_text(encoding="utf-8"))
    existing = data.get("questions", [])
    if len(existing) >= 50:
        return False, len(existing)
    next_num = start_num if start_num else len(existing) + 1
    for i, q in enumerate(new_questions):
        q["num"] = next_num + i
    existing.extend(new_questions)
    data["questions"] = existing[:50]
    quiz_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

# Fecha governance/quiz_003
path_gov = Path("static/quizzes/cism/info_security_governance/quiz_003_pt.json")
ok, total = add_to_quiz(path_gov, q_gov)
if ok:
    print(f"OK - {len(q_gov)} questoes adicionadas ao governance/quiz_003_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total >= 50 else f" (faltam {50-total})"))

# Fecha risk_management/quiz_001
path_risk = Path("static/quizzes/cism/info_risk_management/quiz_001_pt.json")
ok2, total2 = add_to_quiz(path_risk, q_risk)
if ok2:
    print(f"OK - {len(q_risk)} questoes adicionadas ao risk_management/quiz_001_pt")
    print(f"Total: {total2}/50" + (" - COMPLETO!" if total2 >= 50 else f" (faltam {50-total2})"))
