#!/usr/bin/env python3
"""
CISM BATCH 3 - Gestao de Riscos de Seguranca da Informacao
21 questoes adaptadas
Dominio: info_risk_management
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"Um gestor de riscos planeja realizar a primeira avaliação de riscos em uma organização. Qual é a melhor abordagem para garantir o sucesso?","tag":"Avaliação de Riscos","options":["A. Entrevistar colaboradores separadamente para comparar respostas","B. Selecionar framework que corresponda ao framework de controles da organização","C. Trabalhar com a alta gestão para definir o escopo correto","D. Não informar a alta gestão até que a avaliação esteja concluída"],"correct":2,"justification_correct":"Ter o apoio da alta gestão e definir o escopo correto com ela é a melhor abordagem para garantir o sucesso de um programa de gestão de riscos. O escopo pode ser definido por unidade de negócio, área geográfica ou outros critérios. (CISM Review Manual, ISACA)","justification_wrong":"Entrevistas separadas são técnica de coleta, não garantia de sucesso; selecionar framework é passo posterior; excluir a gestão do processo compromete o suporte necessário."},
    {"num":2,"text":"Um gestor de segurança concluiu uma varredura de vulnerabilidades e identificou inúmeras vulnerabilidades em servidores de produção. Qual é o melhor curso de ação?","tag":"Vulnerabilidades","options":["A. Notificar os proprietários dos ativos dos servidores de produção","B. Conduzir investigação formal sobre as vulnerabilidades","C. Criar uma entrada única no registro de riscos","D. Inserir entradas individuais de vulnerabilidade no registro de riscos"],"correct":0,"justification_correct":"O registro de riscos é primariamente para questões estratégicas, não táticas como vulnerabilidades individuais. A melhor ação é notificar os proprietários dos ativos, que são responsáveis por avaliar e tratar as vulnerabilidades em seus sistemas. (CISM Review Manual, ISACA)","justification_wrong":"Investigação formal é desproporcional para resultado de varredura; uma entrada única perde o detalhamento; múltiplas entradas no registro de riscos sobrecarregam o processo estratégico."},
    {"num":3,"text":"O conceito de divisão de responsabilidades de segurança em um ambiente SaaS ou IaaS é representado por qual modelo?","tag":"Cloud Security","options":["A. Modelo de controle discricionário","B. Modelo de controle obrigatório","C. Modelo de risco Monte Carlo","D. Modelo de responsabilidade compartilhada"],"correct":3,"justification_correct":"O modelo de responsabilidade compartilhada (shared responsibility model) descreve a divisão de responsabilidades entre o provedor de nuvem e o cliente — o provedor gerencia a segurança da infraestrutura e o cliente gerencia a segurança dos dados e acessos. (CISM Review Manual, ISACA)","justification_wrong":"Controle discricionário e obrigatório são modelos de acesso; Monte Carlo é técnica de simulação de riscos — apenas o modelo de responsabilidade compartilhada descreve a divisão entre provedor e cliente."},
    {"num":4,"text":"Um gestor de segurança está desenvolvendo a visão do estado futuro de um programa de gestão de riscos. Antes de desenvolver o plano para alcançar essa visão, ela deve realizar:","tag":"Gap Analysis","options":["A. Análise de lacunas (gap analysis)","B. Análise de riscos","C. Avaliação de riscos","D. Avaliação de ameaças"],"correct":0,"justification_correct":"Para desenvolver o plano de alcance do estado futuro, é necessário primeiro realizar uma gap analysis para entender a diferença entre o estado atual e o estado futuro desejado. Só então ficará claro quais passos precisam ser executados. (CISM Review Manual, ISACA)","justification_wrong":"Análise e avaliação de riscos identificam riscos, não lacunas entre estados; avaliação de ameaças é atividade específica — a gap analysis é o pré-requisito para planejar a transformação."},
    {"num":5,"text":"Todas as seguintes são técnicas para identificar riscos, EXCETO:","tag":"Identificação de Riscos","options":["A. Testes de penetração (penetration tests)","B. Modelagem de ameaças (threat modeling)","C. Avaliação de vulnerabilidades","D. Tratamento de riscos (risk treatment)"],"correct":3,"justification_correct":"O tratamento de riscos é o processo de decidir o que fazer com um risco já identificado — não é uma técnica de identificação de riscos. Testes de penetração, modelagem de ameaças e avaliação de vulnerabilidades são técnicas de identificação. (CISM Review Manual, ISACA)","justification_wrong":"Testes de penetração, modelagem de ameaças e avaliação de vulnerabilidades identificam riscos ativamente — o tratamento é a resposta ao risco, não sua identificação."},
    {"num":6,"text":"A principal vantagem dos padrões NIST em relação aos padrões ISO é:","tag":"Frameworks","options":["A. Os padrões NIST são considerados padrões globais reconhecidos internacionalmente","B. Os padrões NIST não são protegidos por direitos autorais","C. Os padrões NIST estão disponíveis gratuitamente","D. Os padrões NIST custam menos para implementar"],"correct":2,"justification_correct":"A principal vantagem dos padrões NIST é que estão disponíveis gratuitamente. Os padrões ISO são relativamente caros, variando de US$100 a US$200 por cópia para usuário único, o que pode ser uma barreira significativa. (CISM Review Manual, ISACA)","justification_wrong":"O NIST é um padrão americano, não global como o ISO; direitos autorais e custo de implementação não são as principais diferenças — a disponibilidade gratuita é a vantagem central."},
    {"num":7,"text":"Qual das seguintes afirmações é verdadeira sobre o risco de conformidade?","tag":"Risco de Conformidade","options":["A. O risco de conformidade pode ser tolerado quando as multas custam menos do que os controles","B. O risco de conformidade é apenas mais um risco que precisa ser compreendido e gerenciado","C. O risco de conformidade nunca pode ser tolerado","D. O risco de conformidade pode ser tolerado quando a conformidade é opcional"],"correct":1,"justification_correct":"O risco de conformidade é como qualquer outro risco — precisa ser compreendido no contexto das multas potenciais, sanções e danos reputacionais em relação aos custos dos controles. A não conformidade pode também resultar em danos maiores se a organização sofrer uma violação. (CISM Review Manual, ISACA)","justification_wrong":"Tolerar não conformidade com base apenas no custo das multas ignora danos reputacionais e responsabilidades legais; afirmar que nunca pode ser tolerado é absolutista e ignora o contexto de risco."},
    {"num":8,"text":"Firewalls mal configurados, ausência de antivírus e falta de treinamento de pessoal são exemplos de:","tag":"Vulnerabilidades","options":["A. Riscos","B. Ameaças","C. Vulnerabilidades","D. Atores de ameaça"],"correct":2,"justification_correct":"Firewalls mal configurados, ausência de antivírus e falta de treinamento são fraquezas ou deficiências que podem ser exploradas por ameaças — constituindo vulnerabilidades nos sistemas e processos da organização. (CISM Review Manual, ISACA; ISO 27000:2018)","justification_wrong":"Risco é a combinação de ameaça e vulnerabilidade; ameaças são eventos potencialmente danosos; atores de ameaça são os agentes — as deficiências exploráveis são vulnerabilidades."},
    {"num":9,"text":"Ataques de phishing, varreduras de rede e engenharia social são exemplos de:","tag":"Ameaças","options":["A. Riscos","B. Ameaças","C. Vulnerabilidades","D. Atores de ameaça"],"correct":1,"justification_correct":"Phishing, varreduras de rede e engenharia social são ações potencialmente prejudiciais que podem ser mais facilmente realizadas quando os alvos são vulneráveis — constituindo ameaças. (CISM Review Manual, ISACA; ISO 27000:2018)","justification_wrong":"Risco é a combinação de probabilidade e impacto; vulnerabilidades são fraquezas exploráveis; atores de ameaça são os agentes — as ações potencialmente prejudiciais são as ameaças em si."},
    {"num":10,"text":"Um gestor de segurança foi instruído pela alta gestão a NÃO documentar um risco específico no registro de riscos. Como se denomina esse curso de ação?","tag":"Estratégias de Risco","options":["A. Enterrar o risco (burying the risk)","B. Transferir o risco","C. Aceitar o risco","D. Ignorar o risco"],"correct":3,"justification_correct":"A recusa de uma organização em considerar formalmente um risco é conhecida como ignorar o risco. Não é um método formal de tratamento de risco — é uma prática não recomendada pois mantém riscos 'fora dos livros' sem deliberação ou decisão formal. (CISM Review Manual, ISACA)","justification_wrong":"Transferir o risco é repassá-lo a terceiros; aceitar o risco é uma decisão formal documentada; enterrar não é terminologia padrão — apenas ignorar descreve a ausência proposital de documentação."},
    {"num":11,"text":"Durante avaliação de riscos em uma aplicação de negócio, o gestor constata que patches de segurança não são instalados há mais de um ano. Esse achado é classificado como:","tag":"Vulnerabilidades","options":["A. Probabilidade","B. Ameaça","C. Vulnerabilidade","D. Risco"],"correct":2,"justification_correct":"A ausência de patches de segurança é uma fraqueza no sistema que pode permitir a execução de um ataque — constituindo uma vulnerabilidade, definida como deficiência que pode ser explorada por uma ameaça. (CISM Review Manual, ISACA; ISO 27000:2018)","justification_wrong":"Probabilidade mede a likelihood de um evento; ameaça é o evento potencialmente danoso; risco combina vulnerabilidade e ameaça — a ausência de patches é especificamente uma vulnerabilidade."},
    {"num":12,"text":"Durante avaliação de um data center, o gestor constata que é possível que pessoal não autorizado entre pela doca de carga e desligue a energia do prédio. Esse achado é classificado como:","tag":"Vulnerabilidades","options":["A. Probabilidade","B. Ameaça","C. Vulnerabilidade","D. Risco"],"correct":2,"justification_correct":"A possibilidade de acesso não autorizado pela doca de carga é uma fraqueza física — uma vulnerabilidade que pode ser explorada. A exploração dessa vulnerabilidade (alguém realmente desligar a energia) seria o risco materializado. (CISM Review Manual, ISACA)","justification_wrong":"Probabilidade é a likelihood; ameaça seria o ato de desligar a energia; risco é a combinação de probabilidade e impacto — a falha de controle de acesso físico é a vulnerabilidade."},
    {"num":13,"text":"Hacktivistas, organizações criminosas e crackers são todos conhecidos como:","tag":"Atores de Ameaça","options":["A. Atores de ameaça (threat actors)","B. Riscos","C. Ameaças","D. Exploits"],"correct":0,"justification_correct":"Hacktivistas, organizações criminosas e crackers são atores de ameaça — pessoas ou entidades que podem realizar ameaças contra alvos se suficientemente motivados. (CISM Review Manual, ISACA; ISO 27000:2018)","justification_wrong":"Riscos são combinações de probabilidade e impacto; ameaças são ações potencialmente danosas; exploits são técnicas de ataque — os agentes que executam as ameaças são os atores de ameaça."},
    {"num":14,"text":"Todos os seguintes são elementos centrais usados na identificação de riscos, EXCETO:","tag":"Identificação de Riscos","options":["A. Ameaças","B. Vulnerabilidades","C. Valor do ativo","D. Proprietário do ativo"],"correct":3,"justification_correct":"A identidade do proprietário do ativo não é relevante na fase de identificação de riscos. Os fatores relevantes são ameaças, atores de ameaça, vulnerabilidades, valor do ativo e impacto potencial. O proprietário é importante em fases subsequentes do processo. (CISM Review Manual, ISACA)","justification_wrong":"Ameaças, vulnerabilidades e valor do ativo são elementos centrais da identificação de riscos — apenas o proprietário do ativo não é necessário nessa fase específica."},
    {"num":15,"text":"Qual é tipicamente o principal objetivo de um programa de gestão de riscos?","tag":"Objetivos da Gestão de Riscos","options":["A. Reduzir o número e a severidade dos incidentes de segurança","B. Eliminar completamente os incidentes de segurança","C. Melhorar a conformidade regulatória da organização","D. Reduzir o número de achados em auditorias externas"],"correct":0,"justification_correct":"O objetivo mais comum de um programa de gestão de riscos é a redução no número e na severidade dos incidentes de segurança — não a eliminação total, que é inviável, nem apenas a conformidade ou resultados de auditoria. (CISM Review Manual, ISACA)","justification_wrong":"Eliminar completamente incidentes é objetivo impossível; conformidade e resultados de auditoria são objetivos secundários — a redução de incidentes é o objetivo primário da gestão de riscos."},
    {"num":16,"text":"Um gestor de segurança identifica que a organização não possui processo formal de gestão de vulnerabilidades. Qual é o impacto mais significativo dessa lacuna?","tag":"Gestão de Vulnerabilidades","options":["A. A organização não consegue demonstrar conformidade com frameworks de segurança","B. A organização não tem visibilidade sobre fraquezas exploráveis em seus sistemas","C. A organização não consegue calcular o risco residual com precisão","D. A organização não consegue emitir relatórios para o conselho de administração"],"correct":1,"justification_correct":"Sem gestão de vulnerabilidades, a organização não tem visibilidade sobre as fraquezas em seus sistemas que podem ser exploradas por ameaças — comprometendo fundamentalmente a capacidade de gerenciar riscos. (CISM Review Manual, ISACA)","justification_wrong":"Conformidade, risco residual e relatórios ao conselho são impactos secundários — a perda de visibilidade sobre vulnerabilidades é o impacto primário e mais significativo."},
    {"num":17,"text":"Qual é a principal diferença entre uma avaliação de riscos quantitativa e uma qualitativa?","tag":"Metodologias de Risco","options":["A. A avaliação quantitativa é mais rápida e menos custosa","B. A avaliação qualitativa produz resultados mais precisos e defensáveis","C. A avaliação quantitativa atribui valores monetários a riscos e impactos","D. A avaliação qualitativa requer mais dados históricos que a quantitativa"],"correct":2,"justification_correct":"A principal diferença é que a avaliação quantitativa atribui valores monetários a riscos, ativos e impactos, enquanto a qualitativa usa escalas descritivas (alto/médio/baixo). A quantitativa é mais precisa mas exige dados históricos substanciais. (CISM Review Manual, ISACA; ISO 27005:2022)","justification_wrong":"A quantitativa geralmente é mais demorada; a qualitativa é mais subjetiva, não mais precisa; a qualitativa requer menos dados históricos — a distinção central é o uso de valores monetários."},
    {"num":18,"text":"Um conselho de administração solicita um relatório sobre o programa de gestão de riscos cibernéticos. Qual métrica seria mais útil para comunicar o status do programa?","tag":"Comunicação de Riscos","options":["A. Número total de vulnerabilidades identificadas na última varredura","B. Lista completa de todos os riscos no registro de riscos","C. Tendência no número e severidade de incidentes ao longo do tempo","D. Detalhamento técnico de cada configuração de firewall revisada"],"correct":2,"justification_correct":"Para o conselho, métricas de tendência — evolução do número e severidade de incidentes ao longo do tempo — são mais significativas e acionáveis do que listas técnicas detalhadas. O conselho precisa de visão estratégica, não operacional. (CISM Review Manual, ISACA)","justification_wrong":"Vulnerabilidades individuais e detalhes técnicos são informações operacionais; listas completas do registro são excessivamente detalhadas — a tendência de incidentes é a métrica estratégica mais relevante."},
    {"num":19,"text":"O conceito de 'risco inerente' em gestão de riscos de segurança refere-se a:","tag":"Conceitos de Risco","options":["A. O risco que permanece após a aplicação de controles de mitigação","B. O nível de risco antes da aplicação de quaisquer controles","C. O risco transferido para terceiros por meio de seguros","D. O risco aceito formalmente pela alta gestão"],"correct":1,"justification_correct":"O risco inerente é o nível de exposição existente antes da aplicação de controles — o ponto de partida da análise de riscos. O risco residual é o que permanece após os controles. (CISM Review Manual, ISACA; ISO 31000:2018)","justification_wrong":"O risco após controles é o risco residual; risco transferido é estratégia de tratamento; risco aceito é decisão de gestão — o risco inerente é especificamente o nível bruto, sem controles."},
    {"num":20,"text":"Qual é a relação correta entre ameaça, vulnerabilidade e risco?","tag":"Conceitos Fundamentais","options":["A. Risco = Ameaça + Vulnerabilidade + Impacto","B. Vulnerabilidade = Ameaça × Risco","C. Ameaça = Vulnerabilidade + Risco","D. Risco = Ameaça × Vulnerabilidade × Impacto"],"correct":0,"justification_correct":"O risco resulta da combinação de uma ameaça que explora uma vulnerabilidade, gerando um impacto potencial. A fórmula conceitual Risco = Ameaça + Vulnerabilidade + Impacto captura essa interdependência. (CISM Review Manual, ISACA; ISO 27005:2022)","justification_wrong":"As demais fórmulas invertem ou distorcem a relação — o risco é produto da convergência de ameaça, vulnerabilidade e impacto potencial."},
    {"num":21,"text":"Um gestor de segurança está priorizando riscos para tratamento. Qual critério deve ter maior peso na priorização?","tag":"Priorização de Riscos","options":["A. O custo de implementação do controle mitigador","B. A facilidade de implementação do controle","C. A combinação de probabilidade e impacto do risco","D. A visibilidade do risco para auditores externos"],"correct":2,"justification_correct":"A priorização de riscos deve basear-se primariamente na combinação de probabilidade (likelihood) e impacto potencial — os riscos de maior probabilidade e impacto devem ser tratados primeiro, independentemente do custo ou visibilidade. (CISM Review Manual, ISACA; ISO 27005:2022)","justification_wrong":"Custo, facilidade e visibilidade para auditores são critérios secundários — a priorização deve refletir a criticidade real do risco, medida pela combinação de probabilidade e impacto."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/cism/info_risk_management")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "cism",
    "domain_id": "info_risk_management",
    "quiz_num": num1,
    "domain_name": "Information Risk Management",
    "cert_name": "CISM",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (CISM Risk Management) salvas em {path1}")
print(f"AVISO - quiz incompleto: {len(questions)}/50. Continue com mais material.")
