#!/usr/bin/env python3
"""
CISM BATCH 10
20 questoes -> incident_management/quiz_001 (fecha em 50)
5 questoes  -> info_security_governance/quiz_004 (novo)
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# 20 questoes para fechar incident_management/quiz_001
q_incident = [
    {"num":31,"text":"Qual é o melhor método para garantir que o programa de segurança de uma organização alcance alinhamento adequado com o negócio?","tag":"Alinhamento Estratégico","options":["A. Localizar e ler os artigos de incorporação da organização","B. Compreender a declaração de visão, missão e objetivos estratégicos","C. Estudar o organograma de gestão","D. Estudar as demonstrações financeiras da organização"],"correct":1,"justification_correct":"A melhor forma de alinhar o programa de segurança ao negócio é compreender a visão, missão e objetivos estratégicos — qualquer coisa encontrada aqui é valiosa para priorizar atividades e recursos de segurança que suportem esses objetivos. (CISM Review Manual, ISACA)","justification_wrong":"Artigos de incorporação fornecem pouca informação estratégica; organograma revela estrutura, não direção; demonstrações financeiras revelam pouco sobre objetivos estratégicos."},
    {"num":32,"text":"Robert localizou a declaração de missão e os objetivos estratégicos de sua organização. O que deve fazer para garantir o alinhamento do programa de segurança?","tag":"Alinhamento Estratégico","options":["A. Discutir os objetivos com líderes de negócio para entender como alcançá-los","B. Desenvolver lista de atividades que suportem cada objetivo e determinar seus custos","C. Selecionar controles do framework que atendam a cada objetivo","D. Identificar políticas de segurança relevantes para cada objetivo"],"correct":0,"justification_correct":"O melhor primeiro passo é discutir os objetivos com líderes de negócio para compreender plenamente o que querem alcançar e que etapas estão sendo tomadas — apenas então é possível desenvolver atividades e recursos adequados. (CISM Review Manual, ISACA)","justification_wrong":"Desenvolver atividades sem diálogo pode perder detalhes importantes; seleção de controles e políticas são etapas posteriores — o diálogo com o negócio é o pré-requisito."},
    {"num":33,"text":"Michael quer criar diretrizes que orientem a gestão sobre quando certos riscos devem ser aceitos e quando devem ser mitigados. Como se chama a política que precisa criar?","tag":"Apetite ao Risco","options":["A. Política de segurança","B. Framework de controles","C. Declaração de apetite ao risco","D. Procedimento de teste de controles"],"correct":2,"justification_correct":"Uma declaração de apetite ao risco (também conhecida como declaração de tolerância ao risco) fornece orientação sobre os tipos e a quantidade de risco que a organização está disposta a aceitar versus mitigar — promovendo consistência nas decisões de tratamento. (CISM Review Manual, ISACA)","justification_wrong":"Política de segurança não é o meio primário para decisões de tratamento; framework de controles não orienta decisões de risco; procedimento de teste não está relacionado."},
    {"num":34,"text":"Duas organizações de porte similar estão se fundindo. Paul será o CISO da organização combinada. Qual é o maior risco resultante da fusão?","tag":"Fusões e Riscos","options":["A. Diferenças nas práticas que podem não ser compreendidas inicialmente","B. Duplicação de esforços e atividades","C. Lacunas na cobertura de processos críticos","D. Custos mais elevados de ferramentas e licenças"],"correct":0,"justification_correct":"A fusão de duas organizações tipicamente introduz novas práticas nem sempre compreendidas pela nova equipe de segurança. O CISO pode emitir diretrizes que aumentem um ou mais riscos — por exemplo, combinar padrões de hardening diferentes pode gerar novos pontos vulneráveis. (CISM Review Manual, ISACA)","justification_wrong":"Duplicação de esforços não é o maior risco; lacunas de cobertura são um risco mas não o principal; custos de ferramentas são temporários e gerenciáveis."},
    {"num":35,"text":"O modelo BMIS (Business Model for Information Security) da ISACA descreve as interconexões dinâmicas entre quais elementos?","tag":"BMIS","options":["A. Política, pessoas, processos e tecnologia","B. Pessoas, processos, tecnologia e organização","C. Processos, pessoas e tecnologia","D. Interconexões dinâmicas entre pessoas, processos e tecnologia"],"correct":1,"justification_correct":"O BMIS descreve as interconexões dinâmicas entre os quatro elementos: pessoas, processos, tecnologia e a própria organização. As interconexões dinâmicas descrevem o relacionamento entre cada par de elementos. (CISM Review Manual, ISACA)","justification_wrong":"Política não é elemento do BMIS; o modelo tem quatro elementos incluindo organização; as interconexões dinâmicas são os relacionamentos, não os elementos em si."},
    {"num":36,"text":"Uma deficiência foi identificada no processo de gestão de vulnerabilidades. Como o CISO usaria o BMIS para analisar essa deficiência?","tag":"BMIS","options":["A. Identificar os elementos conectados ao DI de processo","B. Identificar as interconexões dinâmicas (DIs) conectadas ao elemento processo","C. Identificar os elementos dinâmicos conectados a fatores humanos","D. Identificar os elementos dinâmicos conectados a tecnologia"],"correct":1,"justification_correct":"A deficiência foi identificada no processo de gestão de vulnerabilidades. O CISO identificaria as DIs conectadas ao elemento processo: emergência (conectando a pessoas), habilitação e suporte (conectando a tecnologia) e governança (conectando à organização). (CISM Review Manual, ISACA)","justification_wrong":"Identificar elementos conectados ao DI é uso impróprio do BMIS; fatores humanos e tecnologia são outros elementos — o correto é identificar as DIs conectadas ao elemento onde a deficiência foi encontrada."},
    {"num":37,"text":"Qual seria um uso apropriado do framework empresarial Zachman?","tag":"Frameworks de Arquitetura","options":["A. Como modelo de gerenciamento de serviços de TI alternativo ao ITIL","B. Identificar componentes de sistema por funções de design e negócio","C. Desenvolvimento de requisitos de negócio traduzidos em arquitetura técnica","D. Sistemas de TI descritos em alto nível e com crescentes níveis de detalhe"],"correct":3,"justification_correct":"O Zachman é um framework de arquitetura empresarial que descreve sistemas de TI em alto nível e em crescentes níveis de detalhe, até os componentes individuais — sendo um framework de cima para baixo. (CISM Review Manual, ISACA)","justification_wrong":"Zachman não é framework de gerenciamento de serviços; não é framework de baixo para cima; não parte de requisitos de negócio — descreve sistemas em múltiplos níveis de abstração."},
    {"num":38,"text":"Um arquiteto de TI precisa documentar o fluxo de dados entre sistemas internos e externos, incluindo sistemas de provedores de serviços. Que documentação deve desenvolver?","tag":"Arquitetura de TI","options":["A. Diagramas de fluxo de dados (DFDs)","B. Diagramas de entidade-relacionamento (ERDs)","C. Framework de arquitetura Zachman","D. Diagramas Visio mostrando sistemas e fluxos"],"correct":0,"justification_correct":"O arquiteto de TI deve desenvolver diagramas de fluxo de dados (DFDs) — representações visuais dos sistemas de informação e dos fluxos de dados detalhados entre eles, incluindo metadados como especificações e descrições do sistema. (CISM Review Manual, ISACA)","justification_wrong":"ERDs descrevem entidades e relacionamentos, não fluxos de dados; Zachman descreve a arquitetura geral; diagramas Visio são ferramenta genérica — DFDs são o padrão específico para fluxos de dados."},
    {"num":39,"text":"Carole é CISO em nova organização e precisa identificar mecanismos para garantir resultados desejados em processos de negócio selecionados. Como se chama esse termo?","tag":"Controles","options":["A. Checkpoints","B. Controles detectivos","C. Controles","D. Controles preventivos"],"correct":2,"justification_correct":"'Controles' é o melhor termo para descrever mecanismos destinados a garantir resultados desejados em processos de negócio — abrangendo controles preventivos, detectivos, administrativos, compensatórios e de recuperação. (CISM Review Manual, ISACA)","justification_wrong":"Checkpoints não é o termo padrão; controles detectivos e preventivos são subtipos — o termo genérico 'controles' é o mais abrangente e correto."},
    {"num":40,"text":"Qual é a melhor abordagem para desenvolver controles de segurança em uma nova organização?","tag":"Desenvolvimento de Controles","options":["A. Iniciar com framework de controles padrão e ajustar conforme necessário","B. Desenvolver do zero com base nos riscos identificados","C. Iniciar com NIST CSF e migrar para ISO/IEC 27001","D. Desenvolver controles em resposta a uma avaliação de riscos inicial"],"correct":0,"justification_correct":"Iniciar com um framework de controles padrão relevante para o setor é a melhor abordagem — um framework de gestão de riscos avaliará e ajustará os controles ao longo do tempo, adicionando, melhorando e removendo conforme necessário. (CISM Review Manual, ISACA)","justification_wrong":"Desenvolver do zero é ineficiente; migrar entre frameworks desperdiça recursos; resposta apenas a avaliação inicial pode deixar lacunas — o framework padrão é o ponto de partida mais eficiente."},
    {"num":41,"text":"Qual é a principal desvantagem do padrão ISO/IEC 27001?","tag":"ISO 27001","options":["A. O padrão custa mais de US$100 por cópia","B. O padrão custa alguns milhares de dólares por cópia","C. Está disponível apenas nos Estados Unidos","D. É adequado apenas para grandes organizações"],"correct":0,"justification_correct":"Cópias individuais da ISO/IEC 27001 (como virtualmente todos os padrões ISO) custam mais de US$100 — isso desencoraja a adoção ampla pois o padrão é caro para adquirir e difícil de entender. Contraste com os padrões NIST, que são gratuitos. (CISM Review Manual, ISACA)","justification_wrong":"Não custa alguns milhares; está disponível globalmente; é adequada para organizações de todos os tamanhos — o custo de aquisição é a principal desvantagem."},
    {"num":42,"text":"Qual das afirmações sobre a ISO/IEC 27001 é correta?","tag":"ISO 27001","options":["A. Consiste principalmente em framework de controles de segurança seguido de requisitos","B. Consiste principalmente em requisitos para um programa de gestão de segurança com Anexo A de controles","C. Consiste em framework de controles de segurança da informação","D. Consiste em framework de requisitos para um programa de gestão"],"correct":1,"justification_correct":"O foco principal da ISO/IEC 27001 é o corpo de requisitos (cláusulas) que descreve todas as atividades e processos necessários para operar um SGSI. Inclui também o Anexo A com lista de controles. A ISO 27002 contém o mesmo framework de controles com explicações mais longas. (CISM Review Manual, ISACA)","justification_wrong":"A ISO 27001 não é primariamente um framework de controles — os controles estão no Anexo A; seu foco é nos requisitos do SGSI."},
    {"num":43,"text":"Qual é a melhor explicação para os Tiers de Implementação no NIST Cybersecurity Framework?","tag":"NIST CSF","options":["A. Tiers são níveis de risco determinados pela organização","B. Tiers são estágios de implementação de controles no framework","C. Tiers são semelhantes a níveis de maturidade","D. Tiers são níveis de risco determinados por auditor externo"],"correct":2,"justification_correct":"Embora o CSF afirme que os Tiers de Implementação não são estritamente níveis de maturidade, são muito similares a níveis de maturidade — descrevem o grau em que as práticas de gestão de riscos exibem as características definidas. (CISM Review Manual, ISACA)","justification_wrong":"Tiers não são determinados externamente; não são estágios de implementação no sentido sequencial — são níveis que descrevem a sofisticação das práticas de gestão de risco."},
    {"num":44,"text":"Três fatores que um gestor de riscos deve considerar ao desenvolver uma estratégia de segurança de longo prazo são:","tag":"Estratégia de Segurança","options":["A. Ameaças, riscos e soluções","B. Prevenção, detecção e resposta","C. Níveis de risco, qualificações da equipe e ferramentas de segurança","D. Níveis de risco, custos operacionais e níveis de conformidade"],"correct":3,"justification_correct":"Os três melhores fatores para uma estratégia de longo prazo são: níveis de risco (para redução de risco), custos operacionais (orçamento) e níveis de conformidade (para conformidade). Estes podem ter importâncias diferentes em cada organização. (CISM Review Manual, ISACA)","justification_wrong":"Ameaças e soluções são táticas; prevenção e detecção são capacidades; qualificações de equipe são recursos — a combinação de risco, custo e conformidade é a mais estratégica."},
    {"num":45,"text":"Jerome, novo CISO em organização SaaS, foi solicitado a entender o estado atual do programa de segurança. Qual é o melhor primeiro passo?","tag":"Avaliação do Estado Atual","options":["A. Realizar revisão de código das ofertas SaaS","B. Estudar o conteúdo do registro de riscos","C. Realizar avaliação de riscos baseline abrangente","D. Encomendar teste de penetração das redes internas e externas"],"correct":2,"justification_correct":"O melhor primeiro passo para entender o estado atual do programa de segurança é realizar uma avaliação de riscos baseline abrangente — que avalia o estado de risco mais amplo e dos controles existentes. (CISM Review Manual, ISACA)","justification_wrong":"Revisão de código é muito estreita; registro de riscos pode estar desatualizado ou incompleto; pentest cobre apenas vulnerabilidades técnicas — a avaliação baseline é a mais abrangente."},
    {"num":46,"text":"Jerome descobriu que a política de segurança de sua organização é amplamente aspiracional. Qual é a consequência mais importante disso?","tag":"Política Aspiracional","options":["A. Confusão por parte dos usuários finais","B. Aparência de que a organização não está no controle de suas práticas de segurança","C. Multas e sanções de reguladores","D. Riscos e vulnerabilidades não mitigados"],"correct":1,"justification_correct":"Uma organização com política aspiracional (não conforme com suas práticas reais) terá a aparência de não estar no controle de suas práticas de segurança — o que seria uma responsabilidade em processos relacionados à segurança cibernética. (CISM Review Manual, ISACA)","justification_wrong":"Confusão de usuários e vulnerabilidades são consequências secundárias; multas são possíveis mas não a consequência mais importante — a aparência de falta de controle é o risco jurídico primário."},
    {"num":47,"text":"Jerome descobriu que a política de segurança é amplamente aspiracional. Qual deve ser o próximo passo?","tag":"Política Aspiracional","options":["A. Criar entrada no registro de riscos","B. Retirar a política e escrever uma nova mais realista","C. Realizar gap analysis e determinar ações para fechar as lacunas","D. Consultar o assessor jurídico da organização para plano de ação"],"correct":3,"justification_correct":"Consultar o assessor jurídico é o primeiro passo — uma política aspiracional introduz responsabilidade legal à organização, e a ação precisa ser decidida com assessoria jurídica. Embora o CISO possa descrever as lacunas, a ação precisa ser orientada pelo jurídico. (CISM Review Manual, ISACA)","justification_wrong":"Entrada no registro não é o passo mais substancial; retirar a política deixaria a organização sem política alguma; gap analysis é passo subsequente — o jurídico deve orientar a ação diante da responsabilidade legal."},
    {"num":48,"text":"Jerome identificou documento que descreve protocolos de criptografia aceitáveis. Que tipo de documento é esse?","tag":"Hierarquia de Documentos","options":["A. Política","B. Padrão","C. Prática","D. Diretriz"],"correct":1,"justification_correct":"Um documento que descreve ferramentas, produtos ou protocolos específicos é um padrão — especifica o uso obrigatório de protocolos, algoritmos ou tecnologias. (CISM Review Manual, ISACA)","justification_wrong":"Política não especifica ferramentas ou protocolos; prática não é categoria padrão da hierarquia; diretriz é orientação não vinculativa — especificação de protocolos é padrão."},
    {"num":49,"text":"Jerome identificou documento que descreve técnicas sugeridas para implementar protocolos de criptografia. Que tipo de documento é esse?","tag":"Hierarquia de Documentos","options":["A. Política","B. Padrão","C. Diretriz","D. Procedimento"],"correct":2,"justification_correct":"Um documento que fornece sugestões sobre a implementação ou uso de uma política ou padrão é uma diretriz — é orientação não vinculativa sobre como implementar o que os padrões e políticas exigem. (CISM Review Manual, ISACA)","justification_wrong":"Política define regras; padrão especifica tecnologias obrigatórias; procedimento descreve etapas — técnicas sugeridas (não obrigatórias) de implementação são diretrizes."},
    {"num":50,"text":"Qual é o resultado mais provável em uma organização que não possui função de arquitetura de segurança?","tag":"Arquitetura de Segurança","options":["A. Procedimentos de segurança inconsistentes","B. Aplicação inconsistente de padrões","C. Menor maturidade de processos","D. Maior complexidade nas ferramentas de gestão de vulnerabilidades"],"correct":1,"justification_correct":"Sem arquitetura de segurança, há maior probabilidade de que os padrões sejam aplicados de forma inconsistente. A função de arquitetura inclui arquiteturas de referência — documentos que definem em detalhe como a tecnologia é implementada, configurada e gerida. (CISM Review Manual, ISACA)","justification_wrong":"Inconsistência em procedimentos pode ocorrer mas não é o resultado mais direto; maturidade e ferramentas de vulnerabilidades são consequências mais indiretas — inconsistência de padrões é o impacto mais imediato."},
]

# 5 questoes para iniciar governance/quiz_004
q_gov4 = [
    {"num":1,"text":"Um novo CISO em organização manufatureira está coletando artefatos para entender o estado de segurança. Qual seria o MENOS valioso para avaliar a postura de risco?","tag":"Avaliação de Estado","options":["A. Log de incidentes de segurança","B. Registros de treinamento de conscientização","C. Resultados de testes de penetração","D. Relatório ao conselho de administração"],"correct":3,"justification_correct":"Um relatório ao conselho é informação secundária que pode ter sido filtrada e editada — os outros artefatos são registros primários mais valiosos e menos sujeitos a viés. (CISM Review Manual, ISACA)","justification_wrong":"Log de incidentes, registros de treinamento e resultados de pentest são evidências primárias diretas do estado de segurança — o relatório ao conselho é derivado e pode estar editado."},
    {"num":2,"text":"Qual é o valor de uma análise de impacto nos negócios (BIA) para um líder de segurança?","tag":"BIA","options":["A. Fornece visão da criticidade dos sistemas de TI","B. Fornece visão da criticidade dos processos de negócio","C. Fornece visão da criticidade das aplicações de software","D. Não agrega valor pois foca em continuidade de negócios, não em segurança"],"correct":1,"justification_correct":"O propósito da BIA é fornecer visão concisa da criticidade dos processos de negócio — a partir daí, as dependências nos sistemas de informação (aplicações e infraestrutura) podem ser determinadas. (CISM Review Manual, ISACA)","justification_wrong":"A criticidade de sistemas e aplicações são derivadas da BIA, não seu foco primário; a BIA é valiosa para segurança ao identificar quais processos e sistemas merecem maior proteção."},
    {"num":3,"text":"Um líder de segurança foi solicitado a justificar a implementação de nova estratégia de segurança. Como deve responder?","tag":"Business Case","options":["A. Desenvolver plano de projeto com pessoal, tarefas e cronograma","B. Desenvolver matriz de riscos com consequências se a estratégia não for implementada","C. Desenvolver diagrama SWOT com forças, fraquezas, oportunidades e ameaças","D. Desenvolver business case com critérios de sucesso, requisitos, custos e plano de ação"],"correct":3,"justification_correct":"Um business case é o melhor método para justificar um projeto ou iniciativa — inclui declaração do problema, estados atual e futuro desejados, recursos necessários, requisitos e critérios de sucesso. (CISM Review Manual, ISACA)","justification_wrong":"Plano de projeto documenta a execução, não justifica a necessidade; matriz de riscos não justifica a estratégia; SWOT não é usado para justificar estratégias — o business case é o instrumento correto."},
    {"num":4,"text":"Qual é o principal benefício de uma função de arquitetura de segurança em uma organização distribuída de grande porte?","tag":"Arquitetura de Segurança","options":["A. Maior satisfação dos colaboradores de engenharia","B. Melhores resultados em avaliações de vulnerabilidades","C. Maior consistência no uso de ferramentas e configurações","D. Menor custo de operações de segurança"],"correct":2,"justification_correct":"O principal benefício da arquitetura de segurança é a consistência na abordagem em todas as instâncias da organização. Por exemplo, uma arquitetura de referência para controle de acesso garantiria que SAML 2.0 fosse usado para SSO em todas as unidades de negócio. (CISM Review Manual, ISACA)","justification_wrong":"Satisfação de engenheiros é efeito colateral; avaliações de vulnerabilidades podem melhorar mas não é o benefício principal; custos podem até aumentar com consistência — a consistência de configurações é o benefício central."},
    {"num":5,"text":"Uma organização identificou que sua política de segurança é amplamente aspiracional. Qual é o maior risco dessa situação?","tag":"Política de Segurança","options":["A. Confusão entre os usuários finais sobre o que é permitido","B. Aparência de que a organização não controla suas práticas de segurança","C. Aumento de multas regulatórias por não conformidade","D. Vulnerabilidades não mitigadas por falta de orientação"],"correct":1,"justification_correct":"Uma política amplamente aspiracional significa que a organização está publicamente comprometida com práticas que não segue — em processos legais relacionados à segurança, isso cria aparência de falta de controle e pode ser usado contra a organização. (CISM Review Manual, ISACA)","justification_wrong":"Confusão, multas e vulnerabilidades são consequências possíveis mas secundárias — a exposição jurídica pela aparência de falta de controle é o risco mais significativo."},
]

def add_to_quiz(quiz_path, new_questions):
    if not quiz_path.exists():
        return False, 0
    data = json.loads(quiz_path.read_text(encoding="utf-8"))
    existing = data.get("questions", [])
    if len(existing) >= 50:
        return False, len(existing)
    next_num = len(existing) + 1
    for i, q in enumerate(new_questions):
        q["num"] = next_num + i
    existing.extend(new_questions)
    data["questions"] = existing[:50]
    quiz_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try: nums.append(int(f.stem.split("_")[1]))
        except: pass
    return max(nums) + 1 if nums else 1

# Fecha incident_management/quiz_001
path_inc = Path("static/quizzes/cism/incident_management/quiz_001_pt.json")
ok, total = add_to_quiz(path_inc, q_incident)
if ok:
    print(f"OK - {len(q_incident)} questoes adicionadas ao incident_management/quiz_001_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total >= 50 else f" (faltam {50-total})"))

# Inicia governance/quiz_004
dir_gov = Path("static/quizzes/cism/info_security_governance")
num4 = get_next_num(dir_gov)
out4 = {"cert_id":"cism","domain_id":"info_security_governance","quiz_num":num4,"domain_name":"Information Security Governance","cert_name":"CISM","lang":"pt","questions":q_gov4}
path4 = dir_gov / f"quiz_{num4:03d}_pt.json"
path4.write_text(json.dumps(out4, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(q_gov4)} questoes salvas em {path4}")
print(f"AVISO - quiz incompleto: {len(q_gov4)}/50.")
