#!/usr/bin/env python3
"""
CISM BATCH 2 - Estrategia e Governanca de Seguranca
15 questoes adaptadas de material bibliografico
Dominio: info_security_governance
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"Quais são os elementos do Modelo de Negócio para Segurança da Informação (BMIS — Business Model for Information Security)?","tag":"BMIS","options":["A. Cultura, governança, arquitetura, emergência, habilitação e suporte, fatores humanos","B. Pessoas, processos, tecnologia","C. Organização, pessoas, processos, tecnologia","D. Financeiro, cliente, processos internos, inovação e aprendizado"],"correct":2,"justification_correct":"O BMIS da ISACA é composto por quatro elementos: Organização, Pessoas, Processos e Tecnologia. As Interconexões Dinâmicas (DIs) são: Cultura, Governança, Arquitetura, Emergência, Habilitação e Suporte, e Fatores Humanos. (CISM Review Manual, ISACA)","justification_wrong":"A opção A descreve as Interconexões Dinâmicas, não os elementos; B é o modelo clássico PPT sem o elemento Organização; D é o Balanced Scorecard — nenhum corresponde ao BMIS."},
    {"num":2,"text":"A melhor definição de estratégia de segurança da informação é:","tag":"Estratégia","options":["A. O objetivo a ser alcançado por um plano de ação","B. O plano para alcançar um objetivo definido","C. O plano para garantir o alinhamento com o negócio","D. O plano para reduzir os riscos ao nível mínimo"],"correct":1,"justification_correct":"Uma estratégia é o 'como' — o plano para alcançar um objetivo. O objetivo é o 'o quê' que a organização deseja alcançar. Estratégia sem objetivo é execução sem direção. (CISM Review Manual, ISACA)","justification_wrong":"A inverte a relação entre objetivo e plano; C e D são objetivos possíveis, não a definição de estratégia — estratégia é o plano, não o destino."},
    {"num":3,"text":"Um estrategista de segurança analisa a política de segurança da organização para entender seu estado atual. O que a política revela ao estrategista?","tag":"Política de Segurança","options":["A. O nível de comprometimento da gestão com a segurança","B. O nível de conformidade regulatória da organização","C. O nível de maturidade da organização","D. Nenhuma dessas informações de forma confiável"],"correct":3,"justification_correct":"Por si só, a política de segurança oferece poucas informações sobre as práticas reais. Uma política é apenas um conjunto de declarações de intenção — sem examinar processos, registros de negócio e entrevistar pessoal, não é possível concluir nada sobre conformidade, comprometimento ou maturidade real. (CISM Review Manual, ISACA)","justification_wrong":"Comprometimento, conformidade e maturidade exigem análise de evidências operacionais — a política isolada não é indicador confiável de nenhum desses aspectos."},
    {"num":4,"text":"Um estrategista examina vários processos de negócio e constata que seus níveis de maturidade variam de Repetível a Otimizado. Qual é o melhor estado futuro para esses processos?","tag":"Maturidade CMMI","options":["A. Todos os processos devem ser elevados ao nível Repetível","B. Todos os processos devem ser elevados ao nível Otimizado","C. Não há informações suficientes para determinar os estados futuros desejados","D. Os processos em nível Repetível devem ser elevados ao nível Definido"],"correct":2,"justification_correct":"Não existe regra que determine que todos os processos devam estar no mesmo nível. O nível adequado depende do apetite ao risco, do nível de risco associado e de outras considerações estratégicas — informações não disponíveis neste cenário. (CISM Review Manual, ISACA)","justification_wrong":"Elevar todos ao mesmo nível ignora o contexto de risco de cada processo; definir o futuro sem informações de risco e apetite é precipitado."},
    {"num":5,"text":"Um estrategista busca melhorar o programa de segurança em uma organização com cultura forte mas informal. Qual é a melhor abordagem?","tag":"Cultura Organizacional","options":["A. Conduzir grupos focais para discutir possíveis abordagens de mudança cultural","B. Implantar controles detectivos para identificar funcionários que violam políticas","C. Implementar treinamento de conscientização que enfatize os novos comportamentos exigidos","D. Bloquear o acesso dos usuários até que concordem em ser conformes"],"correct":0,"justification_correct":"A cultura organizacional é poderosa e reflete como as pessoas pensam e trabalham. A melhor abordagem é compreender a cultura e trabalhar com as pessoas para introduzir uma cultura de segurança de forma colaborativa — grupos focais são o mecanismo adequado para isso. (CISM Review Manual, ISACA)","justification_wrong":"Punições e bloqueios podem gerar ressentimento e resistência; treinamento impositivo sem compreensão cultural tende a ser ineficaz — a abordagem colaborativa é mais sustentável."},
    {"num":6,"text":"Um estrategista recém-contratado em uma rede varejista com margens de lucro estreitas descobre que a organização carece de várias capacidades de segurança importantes. Qual é a melhor estratégia?","tag":"Estratégia de Risco","options":["A. Insistir que a gestão aprove programa agressivo de melhoria imediata","B. Desenvolver registro de riscos destacando todos os riscos identificados","C. Recomendar que os maiores riscos sejam simplesmente evitados","D. Desenvolver estratégia baseada em risco que implemente mudanças gradualmente ao longo do tempo"],"correct":3,"justification_correct":"Um estrategista precisa entender a capacidade financeira da organização para reduzir riscos. Com margens estreitas, um plano agressivo e caro é inviável — a estratégia gradual baseada em risco respeita as restrições financeiras enquanto prioriza as melhorias mais críticas. (CISM Review Manual, ISACA)","justification_wrong":"Programa agressivo é inviável com margens estreitas; registro de riscos é ferramenta de comunicação, não de mudança; evitar riscos pode significar abandonar operações que geram receita."},
    {"num":7,"text":"A governança de segurança da informação está mais diretamente relacionada a qual dos seguintes elementos?","tag":"Governança","options":["A. Políticas de segurança da informação","B. Políticas de tecnologia da informação","C. Estratégia de segurança da informação","D. Remuneração dos executivos de segurança"],"correct":2,"justification_correct":"A governança de segurança é o mecanismo pelo qual a estratégia de segurança é estabelecida, controlada e monitorada. Decisões estratégicas de longo prazo são tomadas no contexto da governança de segurança. (CISM Review Manual, ISACA)","justification_wrong":"Políticas de segurança e de TI são instrumentos operacionais; remuneração executiva é questão de RH — a governança é fundamentalmente sobre estabelecer e monitorar a estratégia."},
    {"num":8,"text":"Qual deve ser a relação entre o registro de riscos do ERM (Enterprise Risk Management) e o registro de riscos cibernéticos?","tag":"ERM e Risco Cibernético","options":["A. Os riscos cibernéticos devem influenciar os riscos do ERM, mas não o contrário","B. Os riscos do ERM devem influenciar os riscos cibernéticos, mas não o contrário","C. Os registros de ERM e de riscos cibernéticos devem se influenciar bidirecionalmente","D. Os registros de ERM e de riscos cibernéticos não devem ter relação entre si"],"correct":2,"justification_correct":"Os registros de ERM e de riscos cibernéticos devem influenciar-se mutuamente. Por exemplo, riscos crônicos no registro cibernético devem motivar a criação de entradas no registro de ERM, e contextos de risco empresarial devem orientar as prioridades de risco cibernético. (CISM Review Manual, ISACA)","justification_wrong":"A relação unidirecional subestima a interdependência entre risco empresarial e cibernético; a ausência de relação seria uma falha grave de governança de riscos."},
    {"num":9,"text":"O principal fator que influencia a seleção de um framework de controles de segurança é:","tag":"Frameworks de Controle","options":["A. O setor de atuação da organização (vertical de indústria)","B. O nível atual de maturidade dos processos","C. O tamanho da organização","D. O nível de conformidade regulatória existente"],"correct":0,"justification_correct":"O setor de atuação é o fator mais relevante na seleção do framework. Uma organização de saúde provavelmente adotará HIPAA; um varejista, PCI DSS; uma organização governamental, NIST 800-53 — o setor determina as obrigações regulatórias e os riscos específicos. (CISM Review Manual, ISACA)","justification_wrong":"Maturidade, tamanho e conformidade são fatores secundários — o setor define as obrigações legais, regulatórias e os requisitos específicos que determinam o framework mais adequado."},
    {"num":10,"text":"Como parte da análise do estado atual, um estrategista examina os padrões (standards) de segurança da organização. O que os padrões revelam?","tag":"Maturidade Organizacional","options":["A. O nível de comprometimento da gestão com a segurança","B. O nível de conformidade regulatória da organização","C. O nível de maturidade da organização","D. Nenhuma dessas informações de forma confiável"],"correct":2,"justification_correct":"A presença de padrões (standards) de segurança indica uma organização com nível de maturidade mais elevado do que aquelas que não os possuem — padrões documentados evidenciam processos mais estruturados e sistemáticos. (CISM Review Manual, ISACA)","justification_wrong":"Comprometimento e conformidade não podem ser inferidos apenas da existência de padrões; ao contrário das políticas, os padrões indicam maturidade pela especificidade técnica que contêm."},
    {"num":11,"text":"Durante análise de registros de negócio, o gestor de segurança constata que a organização não possui registro de incidentes de segurança. Que conclusão pode ser tirada?","tag":"Capacidade de Detecção","options":["A. A organização não possui capacidade de detectar e responder a incidentes de segurança","B. A organização ainda não sofreu nenhum incidente de segurança","C. A organização está registrando incidentes em seu registro de riscos","D. A organização possui controles preventivos e detectivos eficazes"],"correct":0,"justification_correct":"A ausência de registro de incidentes indica provavelmente falta de capacidade de detecção e resposta. Não é razoável assumir que não houve incidentes — incidentes menores ocorrem regularmente; e controles eficazes não eliminam todos os incidentes. (CISM Review Manual, ISACA)","justification_wrong":"A ausência de registro não prova ausência de incidentes; registro no ERM é improvável para incidentes operacionais; controles eficazes não implicam ausência de registro."},
    {"num":12,"text":"Um estrategista constata que um processo de negócio é executado de forma consistente pelos colaboradores, mas não existe documentação escrita do processo. Qual é o nível de maturidade desse processo?","tag":"Maturidade CMMI","options":["A. Inicial (Initial)","B. Repetível (Repeatable)","C. Definido (Defined)","D. Gerenciado (Managed)"],"correct":1,"justification_correct":"Um processo executado de forma consistente mas sem documentação formal é classificado como Repetível (nível 2 do CMMI) — existe padronização informal baseada na prática, mas sem a formalização documental que caracteriza o nível Definido. (CISM Review Manual, ISACA)","justification_wrong":"Inicial é ad hoc e imprevisível; Definido exige documentação formal; Gerenciado exige métricas de controle — apenas Repetível descreve consistência sem documentação."},
    {"num":13,"text":"Um estrategista descobre que a área de TI não controla o uso e a aquisição de software nos endpoints da organização. O que essa situação indica?","tag":"Controles de Endpoint","options":["A. Ausência de solução EDR nos endpoints","B. Ausência de solução XDR nos endpoints","C. Ausência de capacidade de whitelisting de aplicações","D. A política de uso aceitável não aborda software não autorizado"],"correct":2,"justification_correct":"A ausência de controle sobre instalação e uso de software indica falta de application whitelisting — mecanismo que restringe a execução apenas de aplicações autorizadas. Isso também implica que usuários finais provavelmente têm privilégios de administrador local. (CISM Review Manual, ISACA)","justification_wrong":"EDR e XDR são ferramentas de detecção de ameaças, não de controle de inventário de software; a política de uso aceitável é um controle administrativo que não substitui o controle técnico."},
    {"num":14,"text":"Uma organização que usa PCI DSS como framework de controles conclui, em avaliação de risco, que controles adicionais presentes na ISO/IEC 27001 devem ser implementados. Qual é o melhor curso de ação?","tag":"Frameworks de Controle","options":["A. Adotar a ISO/IEC 27001 como novo framework de controles","B. Manter o PCI DSS e atualizar apenas a documentação de processos","C. Adicionar os controles necessários ao framework de controles existente","D. Adotar o NIST 800-53 como novo framework de controles"],"correct":2,"justification_correct":"Quando novos controles são necessários, a organização deve incorporá-los ao framework existente. Não é necessário adotar um novo framework inteiro quando apenas alguns controles precisam ser adicionados — isso preserva o investimento e evita retrabalho. (CISM Review Manual, ISACA)","justification_wrong":"Adotar um novo framework inteiro é desproporcional para adicionar poucos controles; atualizar apenas a documentação não implementa os controles necessários."},
    {"num":15,"text":"Qual é o propósito de uma análise de lacunas (gap analysis) no contexto do desenvolvimento de estratégia de segurança?","tag":"Gap Analysis","options":["A. Identificar necessidades de melhoria em processos, sistemas, políticas e controles","B. Identificar sistemas e ativos vulneráveis a ataques","C. Identificar políticas ambíguas que necessitam de revisão","D. Identificar controles ineficazes que devem ser substituídos"],"correct":0,"justification_correct":"No contexto de desenvolvimento de estratégia, a gap analysis identifica as lacunas entre o estado atual e o estado futuro desejado em sistemas, processos, políticas e controles — habilitando o estrategista a desenvolver planos para fechar cada lacuna. (CISM Review Manual, ISACA)","justification_wrong":"Vulnerabilidades de sistemas são objeto de avaliação de vulnerabilidades; políticas ambíguas são tratadas em revisão de políticas; controles ineficazes são identificados em testes de controle — a gap analysis é mais abrangente e estratégica."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/cism/info_security_governance")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "cism",
    "domain_id": "info_security_governance",
    "quiz_num": num1,
    "domain_name": "Information Security Governance",
    "cert_name": "CISM",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (CISM Estrategia) salvas em {path1}")
print(f"AVISO - quiz incompleto: {len(questions)}/50 questoes. Complete com mais material.")
