#!/usr/bin/env python3
"""
CFE BATCH 6
Q51-75: Fraud Investigation (metodologia, provas, entrevistas, análise forense)
Q76-100: Prevention & Deterrence (triângulo, controles, ética, cultura)
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# ── Q51-75: Fraud Investigation ───────────────────────────────────────────────
fraud_investigation = [
    {"num":4,"text":"Durante exame de fraude em folha de pagamento, um examinador júnior obtém confissão verbal do suspeito logo na reunião inicial. Qual etapa crítica da metodologia foi provavelmente ignorada?","tag":"Metodologia","options":["A. Documentar as provas físicas antes de qualquer entrevista","B. Avaliar a predicação e planejar a investigação","C. Obter autorização formal do conselho de administração","D. Notificar as autoridades policiais antes de iniciar"],"correct":1,"justification_correct":"Saltar para processo acusatório sem primeiro estabelecer predicação (base razoável de suspeita) e criar plano estruturado compromete a objetividade e a defensabilidade legal da investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Documentar provas, autorização do conselho e notificação policial são etapas relevantes em contextos específicos — mas a predicação é o pré-requisito fundamental antes de qualquer ação investigativa."},
    {"num":5,"text":"Por que é crucial que um exame de fraude siga metodologia estruturada, avançando sistematicamente pelas suas fases?","tag":"Metodologia","options":["A. Para garantir que o processo é objetivo e legalmente defensável, preservando a integridade das provas","B. Para cumprir os prazos contratuais estabelecidos com o cliente","C. Para reduzir o custo total da investigação","D. Para satisfazer os requisitos formais da certificação CFE"],"correct":0,"justification_correct":"A natureza sistemática da metodologia garante que cada etapa se baseia logicamente na anterior, preservando a integridade das provas e resistindo a contestações legais em tribunal. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Prazos, custos e requisitos de certificação são considerações secundárias — a objetividade e a defensabilidade legal são os fundamentos da metodologia estruturada."},
    {"num":6,"text":"Uma denúncia anônima alega que um gestor está submetendo despesas fraudulentas. De acordo com os princípios da predicação, qual é o próximo passo imediato?","tag":"Predicação","options":["A. Avaliar a denúncia e buscar informações corroborativas para determinar se existe base razoável para investigação","B. Iniciar imediatamente a investigação para não perder provas","C. Reportar às autoridades policiais para investigação criminal","D. Entrevistar o gestor denunciado para obter sua versão"],"correct":0,"justification_correct":"A predicação exige estabelecer base razoável de crença de que fraude pode ter ocorrido antes de lançar investigação em grande escala — avaliar e corroborar a denúncia é o passo correto. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Iniciar imediatamente sem predicação é prematuro; reportar à polícia antes de avaliar é precipitado; entrevistar o suspeito antes de ter base razoável compromete a investigação."},
    {"num":7,"text":"Um examinador é criticado por conduzir uma 'expedição de pesca' (fishing expedition). Isso provavelmente significa que faltou qual elemento essencial à investigação?","tag":"Predicação e Escopo","options":["A. Predicação suficiente e escopo claramente definido","B. Autorização formal da alta gestão","C. Participação de advogado durante as entrevistas","D. Ferramentas de análise de dados adequadas"],"correct":0,"justification_correct":"Uma 'expedição de pesca' descreve busca desfocada por irregularidades sem base razoável (predicação) ou objetivos e limites claros (escopo) — os dois elementos fundamentais ausentes. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Autorização gerencial, presença de advogado e ferramentas de análise são aspectos complementares — a ausência de predicação e escopo é o problema que caracteriza a expedição de pesca."},
    {"num":8,"text":"Em investigação sobre subornos pagos a responsável de compras, um examinador obtém declaração assinada de fornecedor admitindo os pagamentos. Que tipo de prova é essa declaração?","tag":"Tipos de Prova","options":["A. Prova testemunhal","B. Prova documental","C. Prova física","D. Prova digital"],"correct":0,"justification_correct":"Declarações e entrevistas constituem prova testemunhal — relatos formais fornecidos por indivíduos sobre fatos de seu conhecimento. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Prova documental são registros escritos; física são objetos tangíveis; digital são dados eletrônicos — declarações formais assinadas são classificadas como prova testemunhal."},
    {"num":9,"text":"Uma ordem de compra alterada em papel e uma série de e-mails no servidor discutindo a alteração. Como seriam categorizadas essas duas provas, respectivamente?","tag":"Tipos de Prova","options":["A. Prova testemunhal e prova documental","B. Prova física e prova digital","C. Prova direta e prova circunstancial","D. Prova primária e prova secundária"],"correct":1,"justification_correct":"A ordem de compra alterada em papel é um item tangível (prova física); os e-mails existem em formato eletrônico (prova digital) — categorização fundamental na forense digital. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Testemunhal é relato de pessoas; direta/circunstancial refere-se ao tipo de inferência necessária; primária/secundária não é classificação padrão CFE — física e digital são as categorias corretas."},
    {"num":10,"text":"Um examinador precisa compreender o processo padrão para aprovar faturas no departamento de contas a pagar. Que técnica seria mais apropriada com os funcionários do departamento?","tag":"Entrevistas","options":["A. Interrogatório estruturado para identificar irregularidades","B. Confrontação baseada em provas documentais","C. Entrevista informativa para coletar informações gerais","D. Análise comportamental com avaliação de indicadores de engano"],"correct":2,"justification_correct":"A entrevista é um processo não acusatório usado para reunir informações gerais — exatamente o objetivo quando se busca compreender processos e procedimentos normais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Interrogatório é acusatório e inadequado para obter informações sobre processos; confrontação e análise comportamental são técnicas para suspeitos, não para levantamento de informações."},
    {"num":11,"text":"Em que ponto de um exame de fraude é apropriado que um examinador faça a transição de entrevista para interrogatório?","tag":"Entrevistas vs Interrogatório","options":["A. Após coletar provas suficientes para acreditar que o indivíduo está envolvido na conduta ilícita","B. Quando o entrevistado demonstra nervosismo ou evita o contato visual","C. Após a conclusão de todas as entrevistas com outros funcionários","D. Quando o entrevistado contradiz informações previamente obtidas"],"correct":0,"justification_correct":"O interrogatório é processo acusatório que só deve ser iniciado quando existem provas suficientes para justificar a abordagem confrontacional — não antes. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Nervosismo é prova circunstancial fraca; a sequência com outros funcionários não é determinante; contradições isoladas requerem investigação adicional antes do interrogatório."},
    {"num":12,"text":"Um CFE avalia a declaração de um suspeito. Qual é o método mais confiável para detectar engano?","tag":"Detecção de Engano","options":["A. Observar sinais físicos como evitar o contato visual e linguagem corporal","B. Avaliar se a história permanece consistente e lógica quando confrontada com provas","C. Aplicar teste de polígrafo para verificar os sinais fisiológicos","D. Comparar o tom de voz com o padrão habitual do entrevistado"],"correct":1,"justification_correct":"O engano é mais bem detectado analisando o conteúdo da história, sua consistência ao longo do tempo e como se sustenta em comparação com provas corroborativas — não por indicadores físicos isolados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Linguagem corporal, polígrafo e tom de voz são indicadores não confiáveis isoladamente — a consistência lógica da narrativa confrontada com provas é o método mais sólido."},
    {"num":13,"text":"Durante questionamento sobre transações específicas, um funcionário normalmente calmo torna-se defensivo e dá respostas vagas. O que pode o examinador concluir?","tag":"Análise Comportamental","options":["A. O funcionário é definitivamente culpado pelas irregularidades investigadas","B. O funcionário está nervoso por estar sendo investigado, o que é natural","C. A mudança de comportamento não tem relevância investigativa","D. A mudança é um indicador que justifica questionamento mais focado e coleta de provas nessa área"],"correct":3,"justification_correct":"Desvios no comportamento basal ajudam o examinador a focar em áreas de preocupação específicas para aprofundamento baseado em provas — não constitui prova, mas orienta a investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Culpa não pode ser inferida de comportamento; nervosismo pode ter múltiplas causas; mudanças comportamentais têm relevância como orientadores, não como provas definitivas."},
    {"num":14,"text":"Por que depender de uma única pista comportamental como nervosismo é má prática na detecção de engano?","tag":"Detecção de Engano","options":["A. Porque nervosismo indica sempre culpa em contextos investigativos","B. Porque o código de ética da ACFE proíbe avaliações comportamentais","C. Porque tais comportamentos exigem formação especializada em psicologia","D. Porque esses comportamentos podem ser causados pelo stress da entrevista, mesmo em pessoas sinceras"],"correct":3,"justification_correct":"O engano não é a única causa de stress ou nervosismo — uma pessoa sincera pode ficar ansiosa ao ser questionada em investigação formal, tornando o indicador isolado não confiável. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Nervosismo não indica culpa automaticamente; o código de ética não proíbe avaliações comportamentais; formação especializada é útil mas não é a razão para não depender de um único indicador."},
    {"num":15,"text":"Para garantir que uma declaração escrita seja legalmente defensável, qual é o elemento mais crítico?","tag":"Declarações","options":["A. A declaração ser redigida pelo próprio examinador para garantir precisão técnica","B. A declaração ser gravada em vídeo durante sua produção","C. A declaração ser revisada pelo conselho jurídico antes de ser assinada","D. A declaração ser voluntária, revista pelo declarante quanto à sua precisão e assinada por ele"],"correct":3,"justification_correct":"Voluntariedade, revisão pelo próprio declarante e assinatura confirmam que a declaração é o relato preciso e próprio do sujeito — os três elementos que a tornam legalmente defensável. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Redigida pelo examinador comprometeria a autoria; gravação em vídeo é prática complementar; revisão jurídica é recomendável mas não o elemento mais crítico."},
    {"num":16,"text":"Um examinador suspeita que fornecedor recém-aprovado é empresa fantasma usada para fraude. Que tipo de registro público seria mais útil para identificar os verdadeiros proprietários?","tag":"Registros Públicos","options":["A. Registros de imóveis e propriedades","B. Registros tributários e declarações fiscais","C. Registros corporativos (Junta Comercial/Conservatória do Registro Comercial)","D. Registros bancários e extratos financeiros"],"correct":2,"justification_correct":"Os registros corporativos contêm informações sobre formação, diretores, sócios e propriedade de empresas — fonte primária para identificar os verdadeiros controladores de uma entidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Imóveis identificam propriedades; registros tributários têm acesso restrito; registros bancários requerem ordem judicial — os registros corporativos são a fonte pública mais direta para identificar proprietários."},
    {"num":17,"text":"Uma investigação sobre riqueza inexplicável de um diretor usa registros públicos para descobrir propriedades de alto valor adquiridas recentemente. Essa informação viria de qual fonte?","tag":"Registros Públicos","options":["A. Registros corporativos da Junta Comercial","B. Registros tributários da Receita Federal","C. Registros de processos judiciais","D. Registros prediais (cartórios de imóveis)"],"correct":3,"justification_correct":"Os registros prediais mantidos pelo governo rastreiam especificamente a propriedade, o valor e a transferência de bens imóveis — fonte primária para investigar aquisições de propriedades. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Registros corporativos identificam empresas; registros tributários têm acesso restrito; processos judiciais são fontes diferentes — os registros prediais são específicos para imóveis."},
    {"num":18,"text":"Fundos roubados foram movidos através de múltiplas contas bancárias em nomes diferentes antes de serem usados para comprar um bem de luxo. Esse processo de criar camadas para ocultar a origem dos fundos é conhecido como:","tag":"Lavagem de Dinheiro","options":["A. Estratificação (Layering)","B. Colocação (Placement)","C. Integração (Integration)","D. Smurfing (Estruturação)"],"correct":0,"justification_correct":"A estratificação é a fase da lavagem de dinheiro onde transações complexas são usadas para obscurecer o rastro de auditoria e cortar as ligações ao crime original — movimentação por múltiplas contas é o mecanismo clássico. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Colocação é a introdução dos fundos no sistema financeiro; integração é o retorno ao circuito legítimo; estruturação é técnica específica de dividir transações — a movimentação por múltiplas contas é estratificação."},
    {"num":19,"text":"Qual é o principal objetivo do rastreamento de transações financeiras ilícitas em uma investigação de fraude?","tag":"Rastreamento Financeiro","options":["A. Quantificar o valor exato dos recursos desviados para fins de restituição","B. Identificar todas as contas bancárias usadas pelo perpetrador","C. Cumprir requisitos legais de due diligence investigativa","D. Reconstruir o caminho completo dos fundos desde a vítima até seu destino final"],"correct":3,"justification_correct":"O rastreamento segue o dinheiro para mostrar como foi desviado, ocultado e, em última análise, utilizado — construindo a narrativa completa do esquema fraudulento. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Quantificação e identificação de contas são resultados do rastreamento; due diligence é requisito complementar — o objetivo central é reconstruir o percurso completo dos fundos."},
    {"num":20,"text":"Um examinador observa depósitos em dinheiro de uma empresa ligeiramente abaixo do limite de declaração obrigatória, feitos em agências diferentes no mesmo dia. Esse padrão é indicador clássico de qual técnica?","tag":"Lavagem de Dinheiro","options":["A. Colocação (Placement) inicial de fundos ilícitos","B. Integração de fundos em ativos legítimos","C. Estratificação por múltiplas contas","D. Estruturação (Structuring/Smurfing)"],"correct":3,"justification_correct":"A estruturação (smurfing) envolve a divisão intencional de grandes transações em valores menores para fugir aos limites automáticos de reporte — padrão de depósitos abaixo do limiar em múltiplas agências. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Colocação é a entrada dos fundos no sistema; integração é o retorno ao circuito legítimo; estratificação usa múltiplas contas mas não especificamente para ficar abaixo de limites de reporte."},
    {"num":21,"text":"Ao revisar cheques cancelados da conta de uma empresa, um examinador descobre que vários cheques pagáveis a um funcionário foram endossados e depositados em sua conta pessoal. Isso é considerado que tipo de prova?","tag":"Provas Documentais","options":["A. Prova circunstancial que requer corroboração adicional","B. Prova testemunhal do banco sobre as transações","C. Prova indireta que precisa de inferência para estabelecer culpa","D. Prova objetiva que liga o funcionário diretamente aos fundos da empresa"],"correct":3,"justification_correct":"Registros bancários como cheques cancelados fornecem rastro de auditoria claro e factual que liga uma pessoa específica a uma transação específica — prova objetiva de alta qualidade. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Os cheques cancelados são provas diretas e objetivas, não circunstanciais ou indiretas — estabelecem o fato (depósito na conta do funcionário) sem necessidade de inferência."},
    {"num":22,"text":"Um CFE aplica a Lei de Benford a um grande conjunto de dados de pagamentos e encontra desvio significativo da frequência esperada dos dígitos iniciais. O que isso sugere?","tag":"Análise de Dados","options":["A. Os dados estão corretos pois variações são estatisticamente normais","B. Os dados podem conter números fabricados ou manipulados, justificando investigação mais aprofundada","C. O sistema contábil apresenta erro técnico que distorce os dados","D. Os pagamentos foram feitos a fornecedores de países com sistemas monetários diferentes"],"correct":1,"justification_correct":"A Lei de Benford descreve a frequência esperada dos dígitos iniciais em dados de ocorrência natural — desvios graves indicam que os dados podem ser artificiais ou ter sido manipulados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Variações estatísticas normais não geram desvios 'significativos'; erros técnicos e diferenças monetárias são explicações menos prováveis — desvios na Lei de Benford são red flag para manipulação de dados."},
    {"num":23,"text":"Um examinador observa que as despesas de viagem de uma empresa aumentaram 200% num ano, enquanto as receitas cresceram apenas 5%. Esse é um exemplo de que técnica de investigação?","tag":"Análise Financeira","options":["A. Análise de estratificação de dados","B. Análise de tendências e índices","C. Análise de correlação de variáveis independentes","D. Análise da Lei de Benford aplicada a despesas"],"correct":1,"justification_correct":"A comparação de dados financeiros ao longo do tempo e em relação a outros indicadores é análise de tendências e índices — técnica fundamental para identificar padrões incomuns que merecem investigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Estratificação é técnica de lavagem; correlação de variáveis e Benford são técnicas distintas — a comparação temporal de indicadores relativos é especificamente análise de tendências."},
    {"num":24,"text":"Ao apreender um computador como parte de uma investigação de fraude, qual é o procedimento padrão para garantir a integridade e admissibilidade da prova digital?","tag":"Forense Digital","options":["A. Copiar apenas os arquivos relevantes identificados para o caso","B. Analisar o computador diretamente para preservar o estado original","C. Enviar o computador original ao laboratório forense sem cópias","D. Criar cópia forense (imagem) do disco rígido e analisar a cópia"],"correct":3,"justification_correct":"A imagem forense preserva a prova original em estado íntegro, prevenindo alegações de adulteração e garantindo solidez forense — análise é sempre feita na cópia, nunca no original. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Copiar apenas arquivos relevantes pode perder evidências ocultas; analisar o original pode alterar metadados; enviar sem cópia não preserva o estado original — a imagem forense é o padrão."},
    {"num":25,"text":"Os papéis de trabalho de uma investigação devem ser completos, objetivos e claros. Qual é a principal razão para esse elevado padrão de documentação?","tag":"Documentação","options":["A. Cumprir os requisitos formais de arquivamento da ACFE","B. Permitir a cobrança precisa de honorários ao cliente","C. Proteger o examinador de responsabilidade civil futura","D. Permitir que outro examinador qualificado reconstrua a investigação e defenda as conclusões"],"correct":3,"justification_correct":"Os papéis de trabalho são o registro permanente da investigação — devem ser claros o suficiente para que um terceiro entenda e verifique o trabalho realizado e as conclusões alcançadas. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Requisitos da ACFE, honorários e proteção individual são considerações secundárias — o objetivo central é garantir que as conclusões sejam verificáveis e defensáveis por outros profissionais."},
]

# Ajusta numeração sequencial
for i, q in enumerate(fraud_investigation):
    q["num"] = i + 1

# ── Q76-100: Prevention & Deterrence ──────────────────────────────────────────
prevention = [
    {"num":1,"text":"Qual elemento o modelo do 'Diamante da Fraude' adiciona aos três componentes do Triângulo da Fraude?","tag":"Diamante da Fraude","options":["A. Racionalização aprofundada","B. Capacidade (Capability)","C. Oportunidade sistêmica","D. Motivação financeira"],"correct":1,"justification_correct":"O Diamante da Fraude, desenvolvido por David Wolfe e Dana Hermanson, adiciona 'capacidade' — as competências, autoridade e confiança necessárias para cometer a fraude com sucesso. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Racionalização e oportunidade já fazem parte do Triângulo; motivação financeira é componente da 'pressão' — apenas a capacidade é o elemento adicionado pelo Diamante."},
    {"num":2,"text":"De acordo com as classificações da ACFE, qual tipo de fraude ocupacional é o mais comum, mas tipicamente causa as menores perdas financeiras por incidente?","tag":"Categorias ACFE","options":["A. Fraude em demonstrações financeiras","B. Corrupção e pagamento de subornos","C. Fraude cibernética e invasão de sistemas","D. Apropriação indevida de ativos"],"correct":3,"justification_correct":"A apropriação indevida de ativos — skimming, cash larceny, fraude em folha — ocorre com maior frequência, mas geralmente envolve montantes menores por caso. (ACFE Report to the Nations 2024)","justification_wrong":"Fraude em demonstrações financeiras é menos frequente mas causa maiores perdas; corrupção e fraude cibernética têm incidência inferior à apropriação de ativos."},
    {"num":3,"text":"Qual é o principal objetivo dos controles internos dentro de um programa de prevenção de fraudes?","tag":"Controles Internos","options":["A. Detectar fraudes já ocorridas para possibilitar a recuperação de perdas","B. Garantir a conformidade com normas contábeis internacionais","C. Fornecer evidências suficientes para processos criminais","D. Reduzir a oportunidade de um indivíduo cometer e ocultar fraudes"],"correct":3,"justification_correct":"Os controles internos são concebidos primariamente como dissuasores — dificultam que uma pessoa cometa fraude sem ser notada, removendo o elemento 'oportunidade' do Triângulo da Fraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Detecção de fraudes, conformidade contábil e evidências para processos são objetivos complementares — o propósito primário dos controles é prevenir a oportunidade."},
    {"num":4,"text":"Um funcionário é responsável por criar novas contas de fornecedores, aprovar faturas e agendar pagamentos. Esse cenário descreve falha significativa em qual princípio de controle?","tag":"Segregação de Funções","options":["A. Segregação de funções","B. Princípio do menor privilégio","C. Autorização dupla de transações","D. Controle de acesso baseado em função"],"correct":0,"justification_correct":"A segregação de funções exige que nenhum indivíduo controle todas as fases de uma transação — autorização, execução, registro e custódia — para prevenir fraudes. Controlar as três etapas (criação, aprovação e pagamento) viola esse princípio. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Menor privilégio, autorização dupla e RBAC são controles relacionados — mas a concentração de todas as fases em uma pessoa é especificamente a violação da segregação de funções."},
    {"num":5,"text":"Qual é o papel principal do conselho de administração na dissuasão de fraudes, em distinção do papel da gestão?","tag":"Governança","options":["A. Implementar políticas e procedimentos de controle interno","B. Fornecer supervisão independente aos programas antifraude e avaliações de risco da gestão","C. Conduzir investigações internas quando há suspeita de fraude","D. Treinar funcionários sobre os procedimentos de denúncia"],"correct":1,"justification_correct":"O papel do conselho é de governança e supervisão independente — garantir que a gestão tem sistemas eficazes em vigor e responsabilizá-la pelos resultados, não implementar diretamente os controles. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Implementar políticas, conduzir investigações e treinar funcionários são responsabilidades da gestão — o conselho exerce supervisão independente sobre esses processos."},
    {"num":6,"text":"Como a implementação de monitoramento contínuo com análise de dados atua principalmente como dissuasor da fraude?","tag":"Monitoramento Contínuo","options":["A. Aumentando o risco percebido pelo funcionário de ser detectado","B. Reduzindo a pressão financeira sobre os funcionários vulneráveis","C. Eliminando a racionalização ao tornar as regras mais claras","D. Criando evidências que facilitam processos criminais"],"correct":0,"justification_correct":"Saber que transações estão sendo constantemente escrutinadas por sistemas automatizados aumenta a percepção de risco de detecção — dissuasor poderoso que age sobre o elemento 'oportunidade'. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Pressão financeira, racionalização e facilitação de processos são objetivos complementares — o mecanismo primário de dissuasão é o aumento do risco percebido de detecção."},
    {"num":7,"text":"Um gestor sob intensa pressão para atingir meta de lucro irrealista detecta fraqueza no processo de revisão de lançamentos no diário. Esse cenário ilustra a interação de quais dois elementos do Triângulo da Fraude?","tag":"Triângulo da Fraude","options":["A. Racionalização e capacidade","B. Oportunidade e racionalização","C. Pressão e racionalização","D. Pressão e oportunidade"],"correct":3,"justification_correct":"A meta irrealista cria a pressão (motivação para agir), e o controle fraco fornece a oportunidade (ausência de obstáculo) — os dois elementos do triângulo presentes nesse cenário. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Racionalização seria a justificativa interna; capacidade seria a habilidade técnica — o cenário descreve especificamente pressão (meta) e oportunidade (controle fraco)."},
    {"num":8,"text":"Um contabilista experiente começou a ter estilo de vida incompatível com seu salário, fica defensivo quando questionado sobre seu trabalho e recusa-se a tirar férias há mais de dois anos. Essa situação deve ser vista como:","tag":"Red Flags","options":["A. Padrão de red flags comportamentais que aumenta o risco avaliado de fraude","B. Evidência conclusiva de que o funcionário está cometendo fraude","C. Situação pessoal sem relevância para a avaliação de riscos da organização","D. Sinal de esgotamento profissional que requer suporte de RH"],"correct":0,"justification_correct":"Nenhum comportamento isolado é prova, mas a combinação de múltiplos red flags sugere que elementos do Triângulo da Fraude podem estar presentes — justificando avaliação de risco mais aprofundada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Não é evidência conclusiva; tem relevância para a avaliação de riscos; esgotamento profissional pode coexistir mas não explica os múltiplos indicadores — o padrão de red flags deve ser avaliado."},
    {"num":9,"text":"Um alto executivo justifica a manipulação dos relatórios trimestrais alegando que é necessário para evitar demissões e proteger a reputação da empresa. Essa justificativa alinha-se com qual conceito da psicologia do crime de colarinho branco?","tag":"Psicologia da Fraude","options":["A. Triângulo da Fraude — elemento de pressão","B. Neutralização cognitiva da responsabilidade","C. Desengajamento moral (Moral disengagement)","D. Racionalização defensiva pós-fato"],"correct":2,"justification_correct":"O desengajamento moral permite que o indivíduo veja suas ações antiéticas como servindo a um propósito moral mais elevado — justificando comportamentos que sabe estarem errados por uma causa aparentemente nobre. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Pressão é fator motivacional; neutralização cognitiva é conceito relacionado mas menos específico; racionalização pós-fato é distinto do desengajamento moral que ocorre durante o ato."},
    {"num":10,"text":"Qual é o indicador mais útil para medir a eficácia da cultura ética de uma organização e a disposição dos funcionários para reportar problemas?","tag":"Cultura Ética","options":["A. O número e a natureza das denúncias recebidas pelo canal de denúncias","B. O resultado das avaliações de satisfação dos funcionários","C. O número de treinamentos de ética realizados no ano","D. A frequência das auditorias internas conduzidas"],"correct":0,"justification_correct":"Um canal de denúncias ativo com fluxo constante de denúncias substanciais indica que os funcionários confiam no sistema e se sentem capacitados para reportar preocupações — indicador direto de cultura ética. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Satisfação, número de treinamentos e frequência de auditorias são métricas de processo — o volume e qualidade das denúncias medem diretamente a confiança na cultura de integridade."},
    {"num":11,"text":"Qual dos seguintes melhor exemplifica um forte 'tom no topo' (tone at the top)?","tag":"Tone at the Top","options":["A. O CEO envia comunicado anual sobre a importância da ética","B. O CEO segue consistentemente os mesmos procedimentos de despesas exigidos de todos os funcionários","C. O CEO participa de treinamento de ética uma vez por ano","D. O CEO publica declaração de missão ética no site da empresa"],"correct":1,"justification_correct":"O comportamento consistente do CEO — seguindo as mesmas regras que todos — demonstra que a liderança não está acima das normas, reforçando a responsabilização e dando exemplo ético poderoso. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Comunicados, participação simbólica em treinamentos e declarações publicadas são ações de comunicação — o tone at the top é definido pelo comportamento diário consistente da liderança."},
    {"num":12,"text":"A fase inicial de uma metodologia estruturada de avaliação de risco de fraude foca-se em:","tag":"Avaliação de Risco","options":["A. Implementar controles para mitigar os riscos identificados","B. Testar a efetividade dos controles existentes","C. Quantificar as perdas potenciais por categoria de fraude","D. Identificar onde e como a fraude pode ocorrer dentro dos processos"],"correct":3,"justification_correct":"O passo fundamental é compreender o panorama da fraude potencial — os riscos inerentes — antes de considerar controles ou respostas de mitigação. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Implementar controles, testar efetividade e quantificar perdas são etapas subsequentes — a fase inicial deve mapear onde e como a fraude pode ocorrer."},
    {"num":13,"text":"Qual dos seguintes é considerado um componente essencial de um programa antifraude abrangente?","tag":"Programa Antifraude","options":["A. Contratação de auditores externos especializados em fraude","B. Código de conduta claro, treinamento para funcionários e mecanismo de denúncia confidencial","C. Sistema de vigilância eletrônica de todos os espaços de trabalho","D. Política de tolerância zero com demissão imediata para qualquer irregularidade"],"correct":1,"justification_correct":"Esses três elementos funcionam em conjunto: código de conduta define expectativas, treinamento cria consciência e o mecanismo de denúncia proporciona via segura para reportar — base de qualquer programa antifraude. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Auditores externos, vigilância eletrônica e tolerância zero são elementos complementares — o código, treinamento e canal de denúncia são os componentes essenciais fundamentais."},
    {"num":14,"text":"Qual é a característica mais crítica que um sistema de denúncias deve ter para encorajar o reporte?","tag":"Canal de Denúncias","options":["A. Processo de investigação rápido com resposta em 48 horas","B. Recompensas financeiras para denúncias que resultem em condenações","C. Acesso disponível 24 horas por dia e sete dias por semana","D. Garantia de anonimato e proteção contra qualquer forma de retaliação"],"correct":3,"justification_correct":"O medo de represálias é o maior dissuasor para o reporte. Assegurar aos denunciantes que a identidade será protegida e que não serão punidos é essencial para a efetividade do canal. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Rapidez, recompensas e disponibilidade são características importantes mas secundárias — a proteção contra retaliação e o anonimato são os fatores determinantes para a disposição de reportar."},
    {"num":15,"text":"O conceito de 'slippery slope' (declive gradual) no crime de colarinho branco sugere que grandes fraudes começam frequentemente com:","tag":"Psicologia da Fraude","options":["A. Grandes oportunidades financeiras que surgem repentinamente","B. Pequenos desvios às regras, aparentemente menores, que são facilmente racionalizados","C. Pressão financeira extrema que força uma decisão desesperada","D. Ausência de controles internos que cria oportunidade imediata"],"correct":1,"justification_correct":"Os perpetradores começam frequentemente com um pequeno ato que conseguem justificar internamente, que depois escala gradualmente à medida que ficam insensíveis à conduta inadequada. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Grandes oportunidades, pressão extrema e ausência de controles podem ser gatilhos, mas o slippery slope descreve especificamente a escalada gradual a partir de pequenos desvios iniciais."},
    {"num":16,"text":"Um CFE descobre provas de fraude significativa pela gestão, mas é instruído pelo cliente para parar a investigação e reportar que não foram encontrados problemas. O que o código de ética da ACFE exige?","tag":"Ética Profissional","options":["A. Encerrar a investigação conforme instruído pelo cliente pagante","B. Reportar o caso às autoridades criminais imediatamente","C. Reportar as descobertas de forma verdadeira e recusar-se a emitir relatório enganador","D. Solicitar orientação do conselho jurídico antes de decidir"],"correct":2,"justification_correct":"O código de ética da ACFE exige que os CFEs relatem as descobertas de forma verídica e não sejam parte de nenhuma atividade ilegal ou imprópria — independentemente das instruções do cliente. (ACFE Code of Professional Standards)","justification_wrong":"Encerrar por instrução do cliente violaria o código; reportar imediatamente à polícia pode ser adequado mas não é o primeiro requisito; o código exige veracidade no relatório como obrigação primária."},
    {"num":17,"text":"Embora a fraude em demonstrações financeiras seja o tipo menos comum, é frequentemente o foco de reguladores e auditores porque:","tag":"Impacto da Fraude","options":["A. É a mais fácil de detectar pelos auditores externos","B. Afeta principalmente empresas de pequeno porte","C. Causa as maiores perdas financeiras e destrói a confiança dos investidores","D. É a única categoria que envolve a alta gestão"],"correct":2,"justification_correct":"O impacto da fraude em demonstrações financeiras é frequentemente catastrófico — levando ao colapso de empresas, perdas significativas para investidores e erosão da confiança nos mercados de capitais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"É difícil de detectar; afeta organizações de todos os portes; corrupção também envolve a gestão — o foco regulatório decorre das maiores perdas e do impacto sistêmico."},
    {"num":18,"text":"Uma organização onde executivos 'punem os mensageiros' que trazem más notícias tende a ver aumento em qual elemento do Triângulo da Fraude?","tag":"Cultura Organizacional","options":["A. Oportunidade, por redução da supervisão efetiva","B. Racionalização, pois funcionários justificam esconder problemas","C. Pressão, por criar ambiente de trabalho hostil","D. Capacidade, por selecionar funcionários menos qualificados"],"correct":1,"justification_correct":"Quando relatórios honestos são punidos, os funcionários racionalizam facilmente o ato de esconder problemas — acreditando que é necessário para a sobrevivência na organização. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Oportunidade, pressão e capacidade podem ser afetados indiretamente, mas a cultura de punir mensageiros impacta diretamente o elemento racionalização ao validar o comportamento de ocultar informações."},
    {"num":19,"text":"Para cumprir o código de ética profissional da ACFE, um examinador deve evitar conflitos de interesse para garantir a manutenção de qual princípio fundamental?","tag":"Ética Profissional","options":["A. Confidencialidade das informações do cliente","B. Competência técnica na condução das investigações","C. Integridade nos relatórios e comunicações","D. Objetividade na análise das provas e conclusões"],"correct":3,"justification_correct":"Conflitos de interesse prejudicam a capacidade do examinador de ser imparcial — comprometendo a objetividade, que é o princípio fundamental que garante a validade das conclusões investigativas. (ACFE Code of Professional Standards)","justification_wrong":"Confidencialidade, competência e integridade são princípios igualmente importantes, mas conflitos de interesse afetam diretamente a objetividade — a capacidade de analisar sem viés."},
    {"num":20,"text":"Qual afirmação distingue com precisão o papel de supervisão do conselho da responsabilidade da gestão na prevenção de fraudes?","tag":"Governança","options":["A. O conselho é responsável por implementar controles; a gestão por supervisionar sua aplicação","B. A gestão implementa políticas; o conselho garante que são adequadas e eficazes","C. Ambos compartilham igualmente a responsabilidade por todos os aspectos do programa antifraude","D. O conselho responde por fraudes externas; a gestão por fraudes internas"],"correct":1,"justification_correct":"A gestão projeta e opera a estrutura de prevenção; o conselho exerce governança e supervisão independente — verificando que os sistemas da gestão são adequados e responsabilizando-a pelos resultados. (CFE Fraud Examiners Manual 2024)","justification_wrong":"O conselho não implementa controles diretamente; não há divisão por tipo de fraude — a distinção fundamental é implementação (gestão) versus supervisão independente (conselho)."},
    {"num":21,"text":"Qual dos seguintes é um exemplo de esquema de corrupção?","tag":"Corrupção","options":["A. Funcionário que desvia dinheiro antes de registrá-lo no sistema","B. Contabilista que capitaliza despesas indevidamente para inflar lucros","C. Funcionário que cria empresa fantasma para emitir faturas falsas","D. Gestor de compras que aceita pagamento de fornecedor em troca de adjudicação de contrato"],"correct":3,"justification_correct":"O gestor de compras aceitando pagamento em troca de contrato representa suborno — forma clássica de corrupção onde um funcionário abusa de sua posição para ganho pessoal. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Desvio antes do registro é skimming; capitalização indevida é fraude contábil; empresa fantasma é esquema de fornecedor fictício — apenas o aceite de pagamento em troca de contrato é corrupção."},
    {"num":22,"text":"Uma avaliação de risco de fraude conclui identificando o risco residual. Esse termo refere-se ao risco que:","tag":"Gestão de Risco","options":["A. Foi identificado mas ainda não foi avaliado quanto ao impacto","B. Representa ameaças externas não controláveis pela organização","C. Foi transferido para terceiros por meio de seguros ou contratos","D. Permanece após a gestão ter implementado controles de mitigação"],"correct":3,"justification_correct":"Risco residual é o nível de exposição que permanece após a aplicação dos controles de mitigação — calculado como risco inerente menos a eficácia dos controles implementados. (ISO 31000:2018; CFE Fraud Examiners Manual 2024)","justification_wrong":"Risco não avaliado, riscos externos e riscos transferidos são categorias distintas — risco residual é especificamente o que permanece após os controles terem sido aplicados."},
    {"num":23,"text":"Um programa antifraude que confia exclusivamente em controles internos e ignora a cultura ética é falho porque:","tag":"Programa Antifraude","options":["A. Controles internos são insuficientes sem tecnologia de monitoramento","B. Uma cultura ética fraca pode fomentar a racionalização e o conluio para contornar os controles","C. Reguladores exigem evidências documentadas de programas de ética formal","D. Controles internos sem ética geram custos operacionais excessivos"],"correct":1,"justification_correct":"Quando o comportamento antiético é tolerado pela liderança, os funcionários justificam irregularidades e podem colaborar para contornar os controles — a cultura ética é o complemento indispensável dos controles formais. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Tecnologia, requisitos regulatórios e custos são considerações secundárias — a cultura ética é fundamental porque afeta diretamente a disposição de respeitar ou contornar os controles."},
    {"num":24,"text":"Qual técnica de investigação seria mais eficaz para identificar padrões incomuns em grandes volumes de dados de transações financeiras?","tag":"Análise de Dados","options":["A. Revisão manual de documentos de suporte de cada transação","B. Entrevistas com os responsáveis por cada categoria de transação","C. Análise de dados com ferramentas de mineração e detecção de anomalias","D. Revisão por amostragem estatística das transações de maior valor"],"correct":2,"justification_correct":"Ferramentas de análise de dados permitem examinar grandes volumes de transações, aplicar testes como a Lei de Benford, identificar duplicidades e detectar padrões anômalos inacessíveis por revisão manual. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Revisão manual, entrevistas e amostragem são técnicas válidas mas limitadas em escala — a análise de dados é a mais eficaz para grandes volumes com múltiplos tipos de irregularidades potenciais."},
    {"num":25,"text":"Qual abordagem de treinamento em ética seria mais eficaz para reduzir a racionalização como fator de risco de fraude?","tag":"Treinamento","options":["A. Treinamento anual obrigatório sobre o código de conduta","B. Distribuição de material escrito sobre as políticas de ética","C. Discussão de casos reais com dilemas éticos e consequências","D. Assinatura anual de declaração de compromisso com a ética"],"correct":2,"justification_correct":"A discussão de casos reais com dilemas éticos e consequências é mais eficaz porque confronta os funcionários com as racionalizações típicas, mostrando como mecanismos psicológicos de justificação levam a más decisões. (CFE Fraud Examiners Manual 2024)","justification_wrong":"Treinamento anual, material escrito e declarações de compromisso são práticas de conformidade — a discussão de casos reais aborda diretamente os mecanismos de racionalização."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

# Injeta Fraud Investigation
dir1 = Path("static/quizzes/cfe/fraud_investigation")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {"cert_id":"cfe","domain_id":"fraud_investigation","quiz_num":num1,"domain_name":"Fraud Investigation","cert_name":"CFE / ACFE","lang":"pt","questions":fraud_investigation}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(fraud_investigation)} questoes (Fraud Investigation) salvas em {path1}")

# Injeta Prevention & Deterrence
dir2 = Path("static/quizzes/cfe/prevention_deterrence")
dir2.mkdir(parents=True, exist_ok=True)
num2 = get_next_num(dir2)
out2 = {"cert_id":"cfe","domain_id":"prevention_deterrence","quiz_num":num2,"domain_name":"Fraud Prevention & Deterrence","cert_name":"CFE / ACFE","lang":"pt","questions":prevention}
path2 = dir2 / f"quiz_{num2:03d}_pt.json"
path2.write_text(json.dumps(out2, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(prevention)} questoes (Prevention & Deterrence) salvas em {path2}")
