#!/usr/bin/env python3
"""
CISM BATCH 6 - Controles, Frameworks, Zero Trust e Conscientizacao
15 questoes - adiciona ao quiz_003 (governance) e quiz_001 (risk)
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

# 10 questoes para info_security_governance/quiz_003 (precisa de 20 mais)
q_governance = [
    {"num":31,"text":"O fator mais importante na seleção de um framework de controles é:","tag":"Frameworks de Controle","options":["A. Maturidade organizacional atual","B. Relevância para o setor de atuação da organização","C. Tolerância ao risco da organização","D. Apetite ao risco da organização"],"correct":1,"justification_correct":"Organizações que selecionam um framework de controles como ponto de partida devem escolher aquele alinhado ao seu setor. Por exemplo, uma organização de saúde pode começar com HIPAA, enquanto um fabricante global provavelmente escolheria a ISO/IEC 27001. (CISM Review Manual, ISACA)","justification_wrong":"Maturidade, tolerância e apetite ao risco são considerações secundárias — o setor determina as obrigações regulatórias e os riscos específicos que guiam a seleção do framework."},
    {"num":32,"text":"O processo do ciclo de vida que influencia os controles ao longo do tempo é conhecido como:","tag":"Ciclo de Vida de Controles","options":["A. Gestão de riscos de terceiros","B. Auditoria externa","C. Gestão de riscos","D. Auditoria interna"],"correct":2,"justification_correct":"O ciclo de vida da gestão de riscos terá, ao longo do tempo, a maior influência sobre os controles de uma organização. Novos riscos descobertos podem ser tratados por meio da criação de novos controles. (CISM Review Manual, ISACA)","justification_wrong":"Auditorias e gestão de terceiros são atividades específicas — a gestão de riscos é o processo contínuo que direciona a evolução dos controles ao longo do ciclo de vida organizacional."},
    {"num":33,"text":"A principal razão pela qual controles preventivos são preferidos em relação a controles detectivos é:","tag":"Tipos de Controles","options":["A. Controles preventivos impedem que eventos indesejados ocorram","B. Controles preventivos são menos custosos de implementar","C. Controles preventivos são menos custosos de auditar","D. Controles detectivos são, por definição, ineficazes"],"correct":0,"justification_correct":"Controles preventivos são preferidos porque impedem que eventos indesejados ocorram — quando disponíveis e viáveis. Controles detectivos, por outro lado, não impedem eventos, apenas os identificam após ocorrerem. (CISM Review Manual, ISACA)","justification_wrong":"Custo e facilidade de auditoria não são as razões primárias; controles detectivos são eficazes para identificação — a preferência preventiva decorre da capacidade de impedir o evento."},
    {"num":34,"text":"Para proteger-se de ransomware, qual é a melhor abordagem de proteção de dados?","tag":"Proteção contra Ransomware","options":["A. Varrer periodicamente o ambiente em busca de malware","B. Replicar dados para armazenamento em nuvem","C. Replicar dados para sistema de armazenamento secundário","D. Fazer backup dos dados em mídia offline"],"correct":3,"justification_correct":"O backup em mídia offline é a melhor proteção contra ransomware — que tipicamente ataca armazenamentos de dados ativos e replicações. A mídia offline não está acessível pela rede durante o ataque. (CISM Review Manual, ISACA)","justification_wrong":"Varredura de malware é controle detectivo; replicação em nuvem e armazenamento secundário podem ser afetados pelo ransomware se conectados à rede — apenas mídia offline garante isolamento."},
    {"num":35,"text":"A melhor definição de controles gerais de computação (General Computing Controls / GCCs) é:","tag":"Controles Gerais","options":["A. Controles gerais em natureza e implementados em todos os sistemas","B. Salvaguardas básicas exigidas pela Lei Sarbanes-Oxley","C. Políticas aplicáveis a todos os sistemas e aplicações","D. Controles que precisam ser auditados anualmente"],"correct":0,"justification_correct":"Controles gerais de computação (GCCs), também conhecidos como ITGCs, são controles gerais em natureza e aplicados na maioria ou em todos os sistemas e aplicações de informação. (CISM Review Manual, ISACA)","justification_wrong":"SOX define requisitos específicos; políticas são documentos, não controles; frequência de auditoria não define GCCs — a abrangência geral sobre todos os sistemas é a característica definidora."},
    {"num":36,"text":"Qual é a melhor razão para adotar um framework de controles padrão?","tag":"Frameworks de Controle","options":["A. Controles podem ser implementados sem avaliações de risco demoradas","B. Auditorias podem começar mais cedo","C. Resultados de auditoria serão mais favoráveis","D. A organização será considerada mais progressista"],"correct":0,"justification_correct":"Uma organização que adota um framework padrão pode implementar controles imediatamente. Sem um framework padrão, avaliações de risco demoradas seriam necessárias para identificar áreas de risco antes do desenvolvimento de controles. (CISM Review Manual, ISACA)","justification_wrong":"Início antecipado de auditorias, resultados favoráveis e percepção de progressismo são benefícios secundários — a agilidade na implementação de controles é a razão primária."},
    {"num":37,"text":"Todas as afirmações sobre a ISO/IEC 27002 são corretas, EXCETO:","tag":"ISO 27002","options":["A. A ISO/IEC 27002 pode ser cruzada com o NIST SP 800-53","B. A ISO/IEC 27002 é um padrão internacional reconhecido","C. A ISO/IEC 27002 está disponível gratuitamente","D. Cópias da ISO/IEC 27002 precisam ser adquiridas"],"correct":2,"justification_correct":"A ISO/IEC 27002, assim como outros padrões ISO, não está disponível gratuitamente — deve ser adquirida por usuários individuais ou com licença de site. Esta é a principal distinção em relação aos padrões NIST, que são gratuitos. (CISM Review Manual, ISACA)","justification_wrong":"ISO 27002 pode ser cruzada com NIST 800-53, é padrão internacional reconhecido e requer aquisição — apenas a afirmação de disponibilidade gratuita é incorreta."},
    {"num":38,"text":"Qual das seguintes afirmações descreve corretamente o vínculo entre gestão de riscos e controles?","tag":"Risco e Controles","options":["A. O tratamento de riscos às vezes requer a criação de um novo controle","B. Controles definem o escopo das avaliações de risco","C. Controles definem o escopo da gestão de riscos","D. Não há vínculo entre gestão de riscos e controles"],"correct":0,"justification_correct":"No ciclo de vida da gestão de riscos, avaliações de risco identificam riscos e, no tratamento, o curso de ação acordado pode ser a criação de um novo controle para mitigar o risco identificado. (CISM Review Manual, ISACA)","justification_wrong":"Controles não definem o escopo de risco — é o contrário; há vínculo direto entre riscos e controles; controles são resposta aos riscos, não definidores de seu escopo."},
    {"num":39,"text":"Qual organização é o órgão governante do padrão PCI DSS?","tag":"Organismos de Governança","options":["A. ISO","B. NIST","C. PCI Security Standards Council","D. VISA e MasterCard"],"correct":2,"justification_correct":"O PCI Security Standards Council, um consórcio das principais bandeiras de cartão de crédito (VISA, MasterCard, American Express, Discover e JCB), é o órgão governante do PCI DSS e padrões relacionados como PA DSS. (CISM Review Manual, ISACA)","justification_wrong":"ISO publica normas de segurança da informação; NIST publica padrões do governo americano; VISA e MasterCard são membros fundadores do council, não o council em si."},
    {"num":40,"text":"A filosofia de sistema e proteção de dados que depende de avaliação contínua é conhecida como:","tag":"Zero Trust","options":["A. Prevenção de perda de dados","B. Confiar mas verificar","C. Confiança transitiva","D. Zero Trust"],"correct":3,"justification_correct":"Zero Trust (ZT) é a filosofia que foca na proteção de sistemas e dados onde a confiança não é concedida implicitamente — deve ser continuamente avaliada em todas as camadas e contextos de acesso. (CISM Review Manual, ISACA; NIST SP 800-207)","justification_wrong":"DLP é ferramenta de proteção; 'confiar mas verificar' é o modelo tradicional que o ZT substitui; confiança transitiva é o modelo de federação de identidades — Zero Trust é a filosofia de avaliação contínua."},
]

# 5 questoes para info_risk_management/quiz_001 (precisa de 14 mais)
q_risk = [
    {"num":37,"text":"Uma revisão do acesso de usuários a sistemas específicos de informação é mais bem conhecida como:","tag":"Revisão de Acesso","options":["A. Uma auditoria","B. Uma revisão de atividade","C. Uma recertificação","D. Um controle corretivo"],"correct":1,"justification_correct":"Uma revisão de atividade é um estudo do acesso de usuários a aplicações ou sistemas individuais para determinar se estão acessando adequadamente — usuários que não acessam são candidatos à remoção de acesso. (CISM Review Manual, ISACA)","justification_wrong":"Auditoria é exame mais amplo e formal; recertificação é processo de renovação de certificações; controle corretivo corrige problemas — a revisão de acesso a sistemas específicos é uma revisão de atividade."},
    {"num":38,"text":"Um departamento de segurança enviou questionário e solicitou evidências ao proprietário de um controle. Essa atividade é mais bem conhecida como:","tag":"Avaliação de Controles","options":["A. Autoavaliação de controle","B. Auditoria","C. Revisão","D. Investigação"],"correct":0,"justification_correct":"Em uma autoavaliação de controle (CSA), o proprietário do controle é solicitado a responder perguntas sobre o controle e fornecer evidências como procedimentos escritos e registros — diferente de uma auditoria conduzida por terceiro independente. (CISM Review Manual, ISACA)","justification_wrong":"Auditoria é conduzida por terceiro independente; revisão e investigação têm escopos distintos — responder questionário e fornecer evidências como proprietário do controle é autoavaliação."},
    {"num":39,"text":"A prática mais recomendada para o treinamento de conscientização em segurança é:","tag":"Conscientização em Segurança","options":["A. Treinamento apenas no momento da contratação","B. Treinamento no momento da contratação e anualmente a partir de então","C. Treinamento anual para todos os colaboradores","D. Leituras e materiais de referência"],"correct":1,"justification_correct":"A melhor prática de treinamento de conscientização consiste em treinar no momento da contratação e anualmente após isso — garantindo que novos colaboradores sejam treinados nos protocolos e expectativas, com reforços periódicos sobre novos controles e ameaças. (CISM Review Manual, ISACA)","justification_wrong":"Treinamento apenas na contratação não mantém a conscientização; apenas anual perde a oportunidade do onboarding; leituras isoladas são insuficientes — a combinação de onboarding e renovação anual é a prática ideal."},
    {"num":40,"text":"Um gestor de segurança de clínica de saúde está implementando controles HIPAA e PCI DSS. Qual abordagem deve ser adotada?","tag":"Múltiplos Frameworks","options":["A. Escolher HIPAA ou PCI DSS e usar seus controles para proteger tanto ePHI quanto dados de cartão","B. Aplicar controles HIPAA e PCI DSS individualmente por meio de avaliações de risco","C. Definir a aplicabilidade de HIPAA e PCI DSS às partes do negócio onde ePHI e dados de cartão são usados","D. Aplicar HIPAA e PCI DSS a toda a organização"],"correct":2,"justification_correct":"A melhor abordagem em ambiente híbrido é definir o escopo de aplicabilidade: controles HIPAA para sistemas que processam ePHI e controles PCI DSS para sistemas que processam dados de cartão. (CISM Review Manual, ISACA)","justification_wrong":"Escolher apenas um framework ignora obrigações do outro; avaliações individuais por risco são válidas mas menos eficientes; aplicar ambos a toda a organização é excessivo e custoso."},
    {"num":41,"text":"Qual solução é mais adequada para o controle: 'Salvaguardas impedem que usuários finais visitem sites perigosos'?","tag":"Controles Técnicos","options":["A. Cloud Access Security Broker (CASB)","B. Filtro de conteúdo web","C. Rede Privada Virtual (VPN)","D. Antimalware"],"correct":1,"justification_correct":"Um filtro de conteúdo web é a solução mais adequada para impedir que usuários finais acessem sites perigosos — filtra o tráfego web com base em categorias e reputação de URLs. (CISM Review Manual, ISACA)","justification_wrong":"CASB controla acesso a aplicações em nuvem; VPN criptografa o tráfego sem filtrar destinos; antimalware detecta ameaças no endpoint — apenas o filtro web controla especificamente o acesso a sites."},
]

def add_to_quiz(quiz_path, new_questions):
    if not quiz_path.exists():
        return False, 0
    data = json.loads(quiz_path.read_text(encoding="utf-8"))
    existing = data.get("questions", [])
    if len(existing) >= 50:
        return False, len(existing)
    next_num = len(existing) + 1
    for i, q in enumerate(new_questions):
        q["num"] = next_num + i
    existing.extend(new_questions)
    data["questions"] = existing[:50]
    quiz_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return True, len(data["questions"])

# Adiciona ao quiz_003 de governance
path_gov = Path("static/quizzes/cism/info_security_governance/quiz_003_pt.json")
ok, total = add_to_quiz(path_gov, q_governance)
if ok:
    print(f"OK - {len(q_governance)} questoes adicionadas ao governance/quiz_003_pt")
    print(f"Total: {total}/50" + (" - COMPLETO!" if total >= 50 else f" (faltam {50-total})"))

# Adiciona ao quiz_001 de risk management
path_risk = Path("static/quizzes/cism/info_risk_management/quiz_001_pt.json")
ok2, total2 = add_to_quiz(path_risk, q_risk)
if ok2:
    print(f"OK - {len(q_risk)} questoes adicionadas ao risk_management/quiz_001_pt")
    print(f"Total: {total2}/50" + (" - COMPLETO!" if total2 >= 50 else f" (faltam {50-total2})"))
