#!/usr/bin/env python3
"""
CISM - GOVERNANÇA DE SEGURANÇA DA INFORMAÇÃO
25 questoes de nivel senior adaptadas
Dominio: info_security_governance
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"Qual das alternativas descreve melhor o conceito de governança de segurança da informação?","tag":"Governança","options":["A. Conjunto de políticas de segurança da informação documentadas","B. Políticas de segurança combinadas com auditorias de sua efetividade","C. Controle, pela gestão, dos processos de segurança da informação","D. Comparação de métricas com organizações similares do setor"],"correct":2,"justification_correct":"A ISACA define governança como o conjunto de processos que avalia necessidades das partes interessadas, estabelece direção por meio de priorização e tomada de decisão, e monitora desempenho e conformidade. Políticas e auditorias são apenas componentes, não a governança em si. (CISM Review Manual, ISACA)","justification_wrong":"Políticas isoladas e auditorias são componentes da governança; benchmarking não é elemento central de um programa de governança — governança é o controle gerencial abrangente dos processos de segurança."},
    {"num":2,"text":"No processo de gestão de riscos, quem é a pessoa mais adequada para tomar a decisão de tratamento do risco?","tag":"Decisão de Risco","options":["A. Chief Risk Officer (CRO)","B. Chief Information Officer (CIO)","C. Dono do processo de negócio associado ao risco","D. Chief Information Security Officer (CISO)"],"correct":2,"justification_correct":"A decisão de tratamento de risco é uma decisão de negócio e deve ser tomada por quem é responsável pela função de negócio associada. CRO, CIO e CISO devem facilitar o processo, não decidir em nome dos donos de processo. (CISM Review Manual, ISACA)","justification_wrong":"CRO, CIO e CISO devem facilitar discussões sobre tratamento de riscos, mas não devem tomar decisões de risco em nome dos donos de processo de negócio."},
    {"num":3,"text":"A responsabilidade final pelo programa de cibersegurança de uma organização recai sobre qual instância?","tag":"Responsabilidade Final","options":["A. O conselho de administração","B. O diretor executivo (CEO)","C. O diretor de tecnologia da informação (CIO)","D. O diretor de segurança da informação (CISO)"],"correct":0,"justification_correct":"A responsabilidade final por tudo em uma organização — incluindo o programa de cibersegurança — recai sobre o conselho de administração, conforme definido em diversas leis e regulamentações, especialmente para empresas de capital aberto. (CISM Review Manual, ISACA)","justification_wrong":"CEO, CIO e CISO têm responsabilidades operacionais importantes, mas a responsabilidade final e fiduciária pertence ao conselho de administração."},
    {"num":4,"text":"Em uma empresa pública dos EUA, para qual instância o CISO geralmente reporta o estado do programa de cibersegurança?","tag":"Reporte ao Conselho","options":["A. À Treadway Commission","B. Aos auditores externos independentes","C. À Securities and Exchange Commission (SEC)","D. Ao comitê de auditoria do conselho de administração"],"correct":3,"justification_correct":"Na maioria das empresas de capital aberto nos EUA, o CISO reporta o estado do programa de cibersegurança ao comitê de auditoria do conselho de administração, que tem responsabilidade fiduciária sobre controles e riscos. (CISM Review Manual, ISACA)","justification_wrong":"A Treadway Commission não recebe relatórios; auditores externos e SEC recebem relatórios financeiros específicos — o reporte de cibersegurança é direcionado ao comitê de auditoria do conselho."},
    {"num":5,"text":"Um novo CISO está construindo um programa de cibersegurança e precisa garantir colaboração entre líderes de negócio e chefes de departamento. Qual estrutura deve ser formada e gerida pelo CISO?","tag":"Estruturas de Governança","options":["A. Um comitê de riscos do conselho de administração","B. Um comitê diretor de cibersegurança","C. Um comitê de auditoria do conselho de administração","D. Uma política de segurança alinhada ao negócio"],"correct":1,"justification_correct":"Um comitê diretor de cibersegurança, composto por executivos seniores e líderes de unidades de negócio, promove colaboração e permite discussões estratégicas sobre risco cibernético quando adequadamente conduzido pelo CISO. (CISM Review Manual, ISACA)","justification_wrong":"Comitê de riscos e comitê de auditoria do conselho não são criados pelo CISO; política de segurança, embora importante, não cria colaboração executiva estruturada."},
    {"num":6,"text":"Qual é o melhor grupo para tomar decisões de tratamento de riscos cibernéticos em uma organização?","tag":"Tomada de Decisão","options":["A. O CISO de forma unilateral","B. O comitê de auditoria do conselho de administração","C. O comitê diretor de cibersegurança","D. O CRO de forma unilateral"],"correct":2,"justification_correct":"O comitê diretor de cibersegurança, com executivos seniores e líderes de negócio, promove decisões colaborativas e aumenta a adesão dos stakeholders — decisões unilaterais do CISO ou CRO geram menor engajamento dos líderes de negócio. (CISM Review Manual, ISACA)","justification_wrong":"Decisões unilaterais do CISO e CRO reduzem a adesão; comitês de auditoria raramente se envolvem diretamente em decisões de tratamento de risco operacional."},
    {"num":7,"text":"Quem é a parte mais adequada para conduzir revisões de acesso a sistemas que suportam atividades de negócio?","tag":"Revisão de Acesso","options":["A. Gerentes diretos dos usuários","B. Gerente de segurança da informação","C. Equipe de service desk de TI","D. Chefe do departamento de negócio responsável pela atividade"],"correct":3,"justification_correct":"Os responsáveis pelas atividades de negócio são quem melhor conhece quem deve ter acesso e em que nível — TI e gestores de segurança raramente possuem conhecimento operacional suficiente para tomar decisões de qualidade sobre acesso. (CISM Review Manual, ISACA)","justification_wrong":"Gestores de usuários, segurança e service desk têm conhecimento técnico mas limitado sobre operações de negócio; o chefe do departamento tem visão completa das necessidades operacionais."},
    {"num":8,"text":"Quem é a parte mais adequada para tomar decisões sobre o propósito e a funcionalidade das aplicações de negócio?","tag":"Propriedade de Aplicações","options":["A. Chefe do departamento de negócio","B. Analista de negócios de TI","C. Desenvolvedor da aplicação","D. Usuário final da aplicação"],"correct":0,"justification_correct":"O chefe do departamento é responsável pela continuidade e sucesso das operações — sendo a parte mais adequada para definir o comportamento e as funcionalidades das aplicações que suportam esses processos. (CISM Review Manual, ISACA)","justification_wrong":"Analistas de TI facilitam discussões; desenvolvedores conhecem a tecnologia mas não as operações; usuários finais geralmente não são responsáveis pelas decisões estratégicas da unidade."},
    {"num":9,"text":"Qual das alternativas apresenta a melhor definição de responsabilidade custodial?","tag":"Custódia de Ativos","options":["A. Um custodiante protege ativos com base nos seus próprios interesses","B. Um custodiante protege ativos com base nos interesses definidos pelo cliente","C. Um custodiante toma decisões com base em seus próprios interesses","D. Um custodiante toma decisões com base nos interesses definidos pelo cliente"],"correct":3,"justification_correct":"Um custodiante (como o departamento de TI) toma decisões sobre design e operação de sistemas com base nas necessidades dos clientes internos — não em seus próprios interesses. A responsabilidade custodial abrange decisões amplas, não apenas proteção. (CISM Review Manual, ISACA)","justification_wrong":"Agir com base nos próprios interesses viola o papel custodial; proteger é apenas parte das responsabilidades — a definição completa envolve tomar decisões baseadas nos interesses do cliente."},
    {"num":10,"text":"Qual é o principal risco quando a área de TI atua como custodiante para donos de processos de negócio?","tag":"Risco de Custódia","options":["A. TI pode não ter interesse suficiente para cuidar adequadamente das aplicações","B. TI pode não ter equipe suficiente para gerenciar todas as aplicações","C. TI pode ter conhecimento insuficiente das operações de negócio para tomar boas decisões","D. Departamentos de negócio podem restringir o acesso da TI às aplicações"],"correct":2,"justification_correct":"Profissionais de TI tendem a focar na tecnologia, não nas operações de negócio — frequentemente fazem suposições sobre necessidades dos clientes sem compreender adequadamente o que os usuários precisam para suas atividades. (CISM Review Manual, ISACA)","justification_wrong":"Falta de interesse, equipe insuficiente e restrição de acesso não representam o risco primário — o risco central é a tomada de decisões inadequadas por falta de conhecimento operacional de negócio."},
    {"num":11,"text":"Uma organização busca contratar um executivo que desenvolverá um programa de gestão abrangendo ameaças, vulnerabilidades e controles para proteger sistemas E instalações físicas. Qual é o título mais adequado?","tag":"Papéis Executivos","options":["A. CSO (Chief Security Officer)","B. CRO (Chief Risk Officer)","C. CISO (Chief Information Security Officer)","D. CIRO (Chief Information Risk Officer)"],"correct":1,"justification_correct":"O CRO é responsável por gerir riscos de múltiplos tipos de ativos — incluindo ativos de informação, físicos e questões de segurança no ambiente de trabalho — sendo o mais adequado para um escopo abrangente. (CISM Review Manual, ISACA)","justification_wrong":"CSO foca em implementar controles de proteção; CISO foca em ativos de informação; CIRO foca em risco de ativos de informação — apenas o CRO abrange múltiplos tipos de ativos incluindo propriedades e instalações."},
    {"num":12,"text":"Uma organização busca contratar um executivo responsável por garantir conformidade com leis de coleta, uso e proteção de informações pessoalmente identificáveis (PII). Qual título é mais adequado?","tag":"Papéis Executivos","options":["A. CSO (Chief Security Officer)","B. CIRO (Chief Information Risk Officer)","C. CISO (Chief Information Security Officer)","D. CPO (Chief Privacy Officer)"],"correct":3,"justification_correct":"O CPO (Chief Privacy Officer) é o executivo responsável por garantir que políticas, práticas e sistemas da organização assegurem a coleta, uso e proteção corretos de PII — função específica de privacidade distinta das de segurança e risco. (CISM Review Manual, ISACA)","justification_wrong":"CSO, CIRO e CISO geralmente não são responsáveis por atividades de privacidade relacionadas à coleta e uso de PII — essa é a função específica do CPO."},
    {"num":13,"text":"Uma empresa precisa definir títulos adequados: o primeiro profissional é responsável pelos fluxos de dados entre sistemas; o segundo pela saúde e gestão dos sistemas que armazenam informações. Quais títulos são mais apropriados?","tag":"Papéis de TI","options":["A. Arquiteto de sistemas e administrador de banco de dados","B. Arquiteto de dados e cientista de dados","C. Cientista de dados e administrador de banco de dados","D. Arquiteto de dados e administrador de banco de dados"],"correct":3,"justification_correct":"Arquiteto de dados é responsável pelos relacionamentos e fluxos de dados entre sistemas. Administrador de banco de dados (DBA) é responsável pela manutenção e saúde dos sistemas de gerenciamento de banco de dados (SGBDs). (CISM Review Manual, ISACA)","justification_wrong":"Arquiteto de sistemas foca na infraestrutura; cientista de dados foca em análise e modelagem — para fluxos de dados e gestão de SGBDs, os títulos corretos são arquiteto de dados e DBA."},
    {"num":14,"text":"Qual é a principal distinção entre um engenheiro de rede e um engenheiro de telecomunicações?","tag":"Papéis de TI","options":["A. Engenheiro de rede foca em redes internas; engenheiro de telecomunicações foca em redes externas de operadoras","B. Engenheiro de rede foca em redes externas; engenheiro de telecomunicações foca em redes internas","C. Engenheiro de rede foca em protocolos da camada 3 acima; engenheiro de telecomunicações nas camadas 1 e 2","D. Não há distinção — ambos cobrem todos os aspectos das redes organizacionais"],"correct":0,"justification_correct":"O engenheiro de rede foca em redes e meios internos (cabeamento, Wi-Fi). O engenheiro de telecomunicações foca em redes externas de operadoras (MPLS, fibra escura) e serviços como telefonia e videoconferência. (CISM Review Manual, ISACA)","justification_wrong":"As definições da opção B estão invertidas; a distinção não se baseia estritamente em camadas de protocolo; existe clara distinção entre os dois papéis."},
    {"num":15,"text":"Uma empresa pública dos EUA está redesenhando controles de revisão de acesso. Qual é o melhor papel para a auditoria interna nesse esforço?","tag":"Auditoria Interna","options":["A. Desenvolver os procedimentos de revisão de acesso","B. Projetar os controles de revisão de acesso","C. Fornecer feedback sobre o design dos controles desenvolvidos por terceiros","D. Desenvolver controles e procedimentos de forma integrada"],"correct":2,"justification_correct":"A auditoria interna não deve projetar ou implementar controles que possa ser solicitada a auditar posteriormente — isso comprometeria sua independência. Sua função é fornecer feedback sobre controles desenvolvidos por outros. (IIA Standards; CISM Review Manual)","justification_wrong":"Desenvolver procedimentos, projetar controles e criar documentação coloca a auditoria interna na posição de auditar seu próprio trabalho — violando o princípio fundamental de independência da auditoria."},
    {"num":16,"text":"Engenheiros que projetam e gerenciam sistemas de informação podem desempenhar papel no monitoramento desses sistemas? Qual é a posição mais adequada?","tag":"Segregação de Funções","options":["A. Não — configura conflito de interesses incompatível com as funções","B. Sim — esses profissionais são mais familiarizados com os alertas e os procedimentos de resposta","C. Não — não estarão familiarizados com os procedimentos de resposta a incidentes","D. Não — não têm permissão de acesso a ambientes de produção"],"correct":1,"justification_correct":"Quem projeta e gerencia sistemas tem maior familiaridade com a natureza dos alertas e com os procedimentos de resposta — posição privilegiada para entender anomalias e agir adequadamente. (CISM Review Manual, ISACA)","justification_wrong":"Não há conflito de interesses entre design, gerenciamento e monitoramento; quem gerencia sistemas necessariamente conhece os procedimentos de resposta e tem acesso a ambientes de produção."},
    {"num":17,"text":"A declaração 'Migração completa do sistema principal para a versão mais recente do software do fornecedor' é um exemplo de qual tipo de declaração?","tag":"Planejamento Estratégico","options":["A. Declaração de missão (Mission statement)","B. Declaração de visão (Vision statement)","C. Declaração de propósito (Purpose statement)","D. Declaração de objetivo (Objective statement)"],"correct":3,"justification_correct":"A declaração é específica, mensurável e orientada a resultado — características de um objetivo estratégico. Missão e visão são declarações de propósito amplas e duradouras, não metas específicas. (CISM Review Manual, ISACA)","justification_wrong":"Missão descreve o propósito permanente da organização; visão descreve o estado futuro desejado de forma ampla; propósito é abstrato demais — a especificidade da declaração caracteriza um objetivo."},
    {"num":18,"text":"Um CISO deseja criar uma declaração de missão para seu grupo de segurança. Qual é a melhor abordagem inicial?","tag":"Missão de Segurança","options":["A. Começar com a declaração de missão da organização","B. Começar com a avaliação de desempenho mais recente do CISO","C. Começar com os resultados da avaliação de risco mais recente","D. Começar com o registro de riscos em aberto"],"correct":0,"justification_correct":"Alinhar a missão da equipe de segurança à missão da organização garante que a função de segurança suporte os objetivos estratégicos do negócio — fundamento do alinhamento estratégico. (CISM Review Manual, ISACA)","justification_wrong":"Avaliação de desempenho, resultados de risco e registro de riscos são insumos operacionais — a missão deve derivar do propósito organizacional mais amplo, não de avaliações táticas."},
    {"num":19,"text":"Em uma empresa pública dos EUA, a auditoria interna concentra esforços em aplicações 'financeiramente relevantes' e sua infraestrutura de TI. Que conclusão um CISO experiente pode tirar disso?","tag":"Auditoria e SOX","options":["A. As auditorias em sistemas de TI subjacentes são atividades de valor agregado","B. O escopo da auditoria interna é muito restrito e deve incluir todos os sistemas de TI","C. O escopo da auditoria interna não tem valor para o CISO","D. O escopo das atividades de auditoria é o esperado para uma empresa pública nos EUA"],"correct":3,"justification_correct":"Em empresas públicas nos EUA, a auditoria interna é obrigada pela Lei Sarbanes-Oxley (SOX) a auditar processos financeiramente relevantes e sua infraestrutura de TI para garantir integridade dos relatórios financeiros aos acionistas. (SOX 2002; CISM Review Manual)","justification_wrong":"O escopo não é restrito demais — é o mandato legal da SOX; e tem valor para o CISO, pois fornece garantias sobre sistemas críticos que suportam processos financeiros."},
    {"num":20,"text":"Qual é o propósito principal das métricas em um programa de segurança da informação?","tag":"Métricas de Segurança","options":["A. Medir o desempenho e a eficácia dos controles de segurança","B. Medir a probabilidade de um ataque à organização","C. Prever a probabilidade de ataques futuros","D. Prever o método de ataque mais provável"],"correct":0,"justification_correct":"As métricas medem o desempenho e a eficácia dos controles de segurança, fornecendo evidências objetivas de que o programa funciona conforme planejado e identificando áreas de melhoria. (CISM Review Manual, ISACA; ISO/IEC 27004)","justification_wrong":"Probabilidade de ataques e previsão de métodos são funções de inteligência de ameaças — as métricas medem a efetividade dos controles existentes, não eventos externos futuros."},
    {"num":21,"text":"Qual é a utilidade de um processo de Gestão de Riscos de Terceiros (TPRM) para um CISO desenvolvendo estratégia de segurança de longo prazo?","tag":"TPRM","options":["A. Fornece informações sobre as capacidades de segurança de provedores de serviços críticos","B. Fornece informações sobre o processo de compras da organização","C. Fornece lista completa de todos os provedores de serviços utilizados","D. Não agrega valor ao CISO por se preocupar apenas com processos de negócio"],"correct":0,"justification_correct":"Um programa de TPRM eficaz captura e documenta informações detalhadas sobre controles de segurança de provedores terceirizados, permitindo ao CISO compreender o cenário de riscos associado à proteção de dados e capacidades críticas. (CISM Review Manual, ISACA)","justification_wrong":"TPRM vai além de listas de fornecedores e processos de compras — seu valor estratégico está na avaliação das capacidades de segurança de terceiros que acessam dados e sistemas críticos."},
    {"num":22,"text":"Um líder de segurança desenvolveu uma descrição detalhada do estado futuro desejado da organização de segurança. O que deve fazer ANTES de desenvolver a estratégia para alcançá-lo?","tag":"Desenvolvimento de Estratégia","options":["A. Realizar auditoria dos controles existentes para entender sua eficácia","B. Entender o estado atual e realizar gap analysis para identificar as lacunas","C. Realizar avaliação de risco para identificar armadilhas na estratégia","D. Encomendar teste de penetração para identificar vulnerabilidades desconhecidas"],"correct":1,"justification_correct":"Para desenvolver uma estratégia, é necessário: (1) definir o estado futuro desejado, (2) entender o estado atual, (3) identificar as lacunas entre os dois. A estratégia consiste no trabalho para fechar essas lacunas. (CISM Review Manual, ISACA)","justification_wrong":"Auditoria, avaliação de risco e testes de penetração são ferramentas úteis, mas secundárias — sem entender o estado atual e as lacunas, não é possível desenvolver uma estratégia eficaz."},
    {"num":23,"text":"Um líder de segurança pesquisa documentos do programa atual. Qual dos seguintes documentos forneceria o MENOR valor nessa análise?","tag":"Documentação do Programa","options":["A. Estatuto do programa de segurança (Security program charter)","B. Descrições de cargos da equipe de segurança","C. Política de segurança da informação","D. Atas de reunião do comitê diretor de cibersegurança"],"correct":1,"justification_correct":"Descrições de cargos oferecem a menor utilidade analítica porque atividades reais frequentemente divergem das descrições escritas, e descrevem expectativas de um momento passado — não o estado atual real do programa. (CISM Review Manual, ISACA)","justification_wrong":"Estatuto, política e atas de reunião refletem a intenção, direção e decisões reais do programa — fontes de valor significativamente maior que descrições de cargos."},
    {"num":24,"text":"Um líder de segurança deseja formalizar o programa de segurança da informação na organização. Qual é o melhor primeiro passo?","tag":"Formalização do Programa","options":["A. Criar site de intranet de segurança da informação","B. Lançar boletim informativo de segurança da informação","C. Desenvolver política de segurança da informação","D. Desenvolver estatuto (charter) do programa de segurança da informação"],"correct":3,"justification_correct":"O estatuto do programa define missão, visão, papéis e responsabilidades, e o engajamento com stakeholders internos e externos — sendo o documento fundacional que legitima e formaliza o programa antes de qualquer outra iniciativa. (CISM Review Manual, ISACA)","justification_wrong":"Site de intranet e boletins são canais de comunicação; a política de segurança é importante mas deriva do estatuto — o estatuto é o documento fundacional que deve existir primeiro."},
    {"num":25,"text":"Um líder de segurança avaliou a maturidade das capacidades com o modelo CMMI e obteve média 3.2. O que deve fazer a seguir?","tag":"Maturidade CMMI","options":["A. Comparar os níveis atuais com os desejados e desenvolver estratégia para atingi-los","B. Determinar etapas para elevar todos os processos ao nível 5","C. Identificar processos de menor maturidade e elevá-los ao nível dos demais","D. Realizar análise de causa raiz para determinar por que a maturidade caiu a esse nível"],"correct":0,"justification_correct":"A melhor abordagem é comparar os níveis atuais com os níveis de maturidade desejados, identificar as lacunas e desenvolver estratégia para fechá-las — não elevar tudo ao máximo nem focar apenas nos menores. (CMMI Institute; CISM Review Manual, ISACA)","justification_wrong":"Elevar todos ao nível 5 pode não ser necessário ou viável; focar apenas nos menores ignora o alinhamento estratégico; análise de causa raiz é inadequada pois 3.2 pode ser o nível esperado."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/cism/info_security_governance")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "cism",
    "domain_id": "info_security_governance",
    "quiz_num": num1,
    "domain_name": "Information Security Governance",
    "cert_name": "CISM",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (CISM Governança) salvas em {path1}")
