#!/usr/bin/env python3
"""
ISO 27001 LEAD IMPLEMENTER - FUNDAMENTOS
40 questoes de nivel fundamental adaptadas
Dominio: fundamentals_isms
Execute em: C:\\NEXOR\\nexor_quiz\\
"""
import json
from pathlib import Path

questions = [
    {"num":1,"text":"Qual é a relação correta entre dado e informação no contexto da segurança da informação?","tag":"Conceitos Fundamentais","options":["A. Dado é informação estruturada e processada","B. Informação é o significado e o valor atribuído a um conjunto de dados","C. Dado e informação são termos intercambiáveis e equivalentes","D. Informação é a forma bruta e não processada do dado"],"correct":1,"justification_correct":"A informação resulta da atribuição de significado, contexto e valor a dados brutos — distinção fundamental na ISO 27000:2018, que define informação como dados dotados de relevância e propósito. (ISO/IEC 27000:2018)","justification_wrong":"Dado é a forma bruta; informação é o dado com significado atribuído. Os termos não são intercambiáveis na terminologia da norma."},
    {"num":2,"text":"Para determinar o valor de dados organizacionais visando contratação de seguro, qual fator NÃO é relevante?","tag":"Valor da Informação","options":["A. O conteúdo intrínseco do dado","B. A facilidade de recuperação em caso de perda, incompletude ou incorreção","C. A cor ou formato visual utilizado na apresentação do dado","D. A importância dos processos de negócio que utilizam o dado"],"correct":2,"justification_correct":"Cor e formato visual são atributos estéticos sem impacto sobre o valor estratégico, operacional ou de conformidade do dado para a organização. O valor é determinado pelo conteúdo, recuperabilidade e criticidade para os processos. (ISO/IEC 27001:2022)","justification_wrong":"Conteúdo, recuperabilidade e criticidade para processos são fatores diretamente relevantes para determinar o valor do dado organizacional."},
    {"num":3,"text":"Um hacker obtém acesso a um servidor e consegue visualizar um arquivo contendo números de cartões de crédito. Qual princípio do triângulo CIA foi violado?","tag":"Triângulo CIA","options":["A. Disponibilidade","B. Confidencialidade","C. Integridade","D. Autenticidade"],"correct":1,"justification_correct":"A confidencialidade foi violada — dados foram acessados por entidade não autorizada, expondo informações sensíveis a terceiros sem permissão. (ISO/IEC 27000:2018, Cláusula 3.10)","justification_wrong":"Disponibilidade refere-se ao acesso legítimo; integridade à ausência de alterações não autorizadas; o acesso indevido sem modificação viola exclusivamente a confidencialidade."},
    {"num":4,"text":"Documentos impressos são frequentemente deixados na impressora de rede do corredor. Qual consequência isso tem para a confiabilidade da informação?","tag":"Confidencialidade Física","options":["A. A integridade da informação não é mais garantida","B. A disponibilidade da informação não é mais garantida","C. A confidencialidade da informação não é mais garantida","D. A autenticidade da informação não é mais garantida"],"correct":2,"justification_correct":"Documentos deixados em local acessível a pessoas não autorizadas violam a confidencialidade, pois qualquer pessoa no corredor pode acessar informações que deveriam ser restritas. (ISO/IEC 27002:2022, Controle 7.7 — Política de mesa limpa)","justification_wrong":"Integridade seria afetada por alterações; disponibilidade por impossibilidade de acesso; o problema aqui é o acesso físico não controlado a informações restritas."},
    {"num":5,"text":"Uma análise de riscos bem realizada possui quatro objetivos principais. Qual NÃO é um deles?","tag":"Análise de Riscos","options":["A. Identificar os ativos e seus valores","B. Implementar diretamente as contramedidas durante a análise","C. Estabelecer equilíbrio entre custos de incidente e custos de medidas de segurança","D. Determinar vulnerabilidades e ameaças relevantes"],"correct":1,"justification_correct":"A análise de riscos identifica, avalia e prioriza riscos — a implementação de contramedidas é etapa subsequente do tratamento de riscos, não objetivo da análise em si. (ISO/IEC 27005:2022)","justification_wrong":"Identificar ativos, estabelecer equilíbrio custo-benefício e determinar vulnerabilidades são objetivos legítimos da análise de riscos conforme ISO 27005."},
    {"num":6,"text":"Como se denomina um evento possível que pode ter efeito prejudicial sobre a confiabilidade da informação?","tag":"Terminologia de Risco","options":["A. Dependência","B. Ameaça","C. Vulnerabilidade","D. Risco"],"correct":1,"justification_correct":"Ameaça é definida como causa potencial de um incidente indesejado que pode resultar em dano a um sistema ou organização — conforme ISO 27000:2018, Cláusula 3.74. (ISO/IEC 27000:2018)","justification_wrong":"Vulnerabilidade é fraqueza que pode ser explorada; risco é a combinação de probabilidade e impacto; dependência é relação entre componentes — nenhum é o evento em si."},
    {"num":7,"text":"Qual é o propósito central do gerenciamento de riscos em segurança da informação?","tag":"Gestão de Riscos","options":["A. Determinar com precisão a probabilidade estatística de cada risco ocorrer","B. Calcular o valor exato do dano causado por incidentes de segurança","C. Mapear todas as ameaças às quais os recursos de TI estão expostos","D. Implementar medidas para reduzir os riscos a um nível aceitável pela organização"],"correct":3,"justification_correct":"O gerenciamento de riscos visa tratar os riscos identificados mediante controles que os reduzam a um nível aceitável conforme o apetite ao risco da organização. (ISO/IEC 27005:2022, Cláusula 5)","justification_wrong":"Probabilidade, dano exato e mapeamento de ameaças são atividades da avaliação de riscos, não o propósito central do gerenciamento."},
    {"num":8,"text":"O que caracteriza uma análise qualitativa de riscos?","tag":"Tipos de Análise","options":["A. Segue cálculo preciso de probabilidade estatística para calcular perdas exatas","B. É baseada em cenários e situações, produzindo visão subjetiva das possibilidades","C. Utiliza exclusivamente dados históricos quantificados de incidentes anteriores","D. Requer ferramentas automatizadas para processamento de grandes volumes de dados"],"correct":1,"justification_correct":"A análise qualitativa de riscos baseia-se em julgamento, cenários e escalas descritivas (alto/médio/baixo) em vez de valores numéricos precisos — abordagem comum quando dados estatísticos são insuficientes. (ISO/IEC 27005:2022)","justification_wrong":"Cálculo preciso e dados históricos quantificados caracterizam a análise quantitativa; ferramentas automatizadas são auxiliares, não definidoras da abordagem qualitativa."},
    {"num":9,"text":"Após incêndio em filial de seguradora, o servidor foi destruído e as fitas de backup derreteram. Qual é um exemplo de dano INDIRETO causado pelo incêndio?","tag":"Tipos de Dano","options":["A. Fitas de backup derretidas pelo calor","B. Sistemas de computador queimados diretamente","C. Documentos consumidos pelo fogo","D. Danos causados pela água dos extintores de incêndio"],"correct":3,"justification_correct":"Danos causados pela água dos extintores são consequência indireta do combate ao incêndio, não do fogo em si — exemplificando dano colateral. Fitas, servidores e documentos são danos diretos do incêndio. (CFE Fraud Examiners Manual / ISO 22301:2019)","justification_wrong":"Fitas, servidores e documentos são danos diretos causados pelo calor e pelo fogo — não são consequências indiretas do evento."},
    {"num":10,"text":"Uma empresa decide adotar medidas apenas para grandes riscos, aceitando os pequenos sem ação. Como se denomina essa estratégia de risco?","tag":"Estratégias de Risco","options":["A. Aceitação do risco","B. Evitar o risco","C. Neutralizar o risco","D. Transferir o risco"],"correct":0,"justification_correct":"A aceitação do risco é a decisão consciente de não tomar ação sobre determinados riscos, geralmente os de menor impacto ou probabilidade, conforme o apetite ao risco da organização. (ISO/IEC 27005:2022, Cláusula 8.6)","justification_wrong":"Evitar elimina a atividade que gera o risco; neutralizar implementa controles; transferir repassa o risco a terceiros — nenhum descreve a aceitação consciente de riscos menores."},
    {"num":11,"text":"Qual dos seguintes é um exemplo de ameaça de origem humana?","tag":"Tipos de Ameaça","options":["A. Pen drive infectado introduzido na rede por um colaborador","B. Acúmulo excessivo de poeira na sala de servidores","C. Variação de tensão causando falha parcial no fornecimento elétrico","D. Falha de hardware por desgaste natural dos componentes"],"correct":0,"justification_correct":"A introdução de pen drive infectado é ação humana — intencional ou não — que configura ameaça de origem humana. Poeira, variação de tensão e desgaste são ameaças de origem ambiental ou técnica. (ISO/IEC 27005:2022)","justification_wrong":"Poeira, variações elétricas e desgaste de hardware são ameaças de origem não humana — ambiental ou técnica."},
    {"num":12,"text":"Qual dos seguintes é um exemplo de ameaça de origem humana?","tag":"Tipos de Ameaça","options":["A. Descarga elétrica por raio","B. Incêndio de origem acidental","C. Phishing direcionado a colaboradores","D. Inundação por fenômeno climático"],"correct":2,"justification_correct":"O phishing é ataque deliberadamente conduzido por agentes humanos maliciosos para obter credenciais ou dados — ameaça tipicamente humana e intencional. (ISO/IEC 27002:2022, Controle 6.3)","justification_wrong":"Raio, incêndio acidental e inundação são ameaças de origem natural ou ambiental, não de origem humana."},
    {"num":13,"text":"Um colaborador recebe ligação de alguém alegando ser da central de atendimento e solicitando sua senha. Que tipo de ameaça é essa?","tag":"Engenharia Social","options":["A. Ameaça de origem natural","B. Ameaça de origem organizacional","C. Engenharia social","D. Ameaça de origem técnica"],"correct":2,"justification_correct":"A engenharia social manipula pessoas para revelar informações confidenciais ou realizar ações que comprometam a segurança — neste caso, via vishing (voice phishing). (ISO/IEC 27002:2022, Controle 6.3)","justification_wrong":"Ameaças naturais e técnicas não envolvem manipulação humana; ameaças organizacionais referem-se a falhas de processo — a manipulação psicológica caracteriza a engenharia social."},
    {"num":14,"text":"Após incêndio em filial de seguradora, o pessoal é transferido para filiais vizinhas para continuar o trabalho. Em que etapa do ciclo de incidentes se posiciona esse sistema de prontidão?","tag":"Ciclo de Incidentes","options":["A. Entre a ameaça e o incidente","B. Entre a recuperação e a ameaça","C. Entre o dano e a recuperação","D. Entre o incidente e o dano"],"correct":3,"justification_correct":"O sistema de prontidão — como transferência de pessoal para local alternativo — atua entre o incidente e o dano, limitando o impacto antes que ele se consolide. (ISO 22301:2019)","justification_wrong":"Entre ameaça e incidente atuam medidas preventivas; entre recuperação e ameaça atuam melhorias; entre dano e recuperação atuam medidas corretivas."},
    {"num":15,"text":"Entre os exemplos de ameaça à confiabilidade da informação, qual representa especificamente uma ameaça à integridade?","tag":"Integridade","options":["A. Cabo frouxo causando interrupção na conexão","B. Alteração acidental de dados por um colaborador","C. Uso pessoal não autorizado de dados organizacionais","D. Falsificação de identidade para acesso ao sistema"],"correct":1,"justification_correct":"A alteração acidental de dados compromete a integridade — a propriedade de que a informação não foi modificada de forma não autorizada ou não intencional. (ISO/IEC 27000:2018, Cláusula 3.37)","justification_wrong":"Cabo frouxo afeta disponibilidade; uso pessoal afeta confidencialidade; falsificação de identidade afeta autenticidade — apenas a alteração do dado compromete diretamente a integridade."},
    {"num":16,"text":"Um membro da equipe nega ter enviado uma mensagem específica. Qual aspecto da confiabilidade da informação está em risco?","tag":"Não-repúdio","options":["A. Disponibilidade","B. Não-repúdio (irrefutabilidade)","C. Integridade","D. Confidencialidade"],"correct":1,"justification_correct":"O não-repúdio garante que o autor de uma ação não possa negá-la posteriormente — sua ausência permite que remetentes neguem o envio de mensagens. (ISO/IEC 27000:2018, Cláusula 3.48)","justification_wrong":"Disponibilidade refere-se ao acesso; integridade à não alteração; confidencialidade ao acesso restrito — a negação de autoria compromete o não-repúdio."},
    {"num":17,"text":"Como é melhor descrito o propósito de uma política de segurança da informação?","tag":"Política de Segurança","options":["A. Documenta a análise de riscos e o processo de busca por contramedidas","B. Fornece orientação e apoio à gestão em matéria de segurança da informação","C. Detalha especificações técnicas de cada controle de segurança implementado","D. Fornece visão abrangente sobre ameaças e suas possíveis consequências"],"correct":1,"justification_correct":"A política de segurança da informação estabelece a direção e o comprometimento da organização com a segurança, fornecendo orientação estratégica à gestão — conforme Cláusula 5.2 da ISO 27001:2022. (ISO/IEC 27001:2022)","justification_wrong":"Análise de riscos e detalhamento técnico são documentos separados; o mapeamento de ameaças é parte da avaliação de riscos — a política fornece direcionamento estratégico."},
    {"num":18,"text":"Um incidente de segurança sobre servidor web é transferido para um colega com mais experiência técnica. Qual termo descreve essa transferência?","tag":"Escalamento de Incidentes","options":["A. Escalamento funcional","B. Escalamento hierárquico","C. Delegação operacional","D. Transferência de responsabilidade"],"correct":0,"justification_correct":"O escalamento funcional transfere o incidente para alguém com expertise técnica específica no mesmo nível hierárquico — diferentemente do escalamento hierárquico que envolve um nível superior de autoridade. (ISO/IEC 27035:2016)","justification_wrong":"Escalamento hierárquico envolve subir na cadeia de comando; delegação e transferência são termos genéricos que não capturam a especificidade técnica do escalamento funcional."},
    {"num":19,"text":"Um incidente de modificação não autorizada de dados de apólice é registrado na central de atendimento com data, hora, descrição e possíveis consequências. Qual informação crítica está FALTANDO?","tag":"Registro de Incidentes","options":["A. O nome da pessoa que relatou o incidente","B. O nome do pacote de software utilizado","C. O número identificador do PC envolvido","D. A lista de pessoas que foram informadas sobre o incidente"],"correct":0,"justification_correct":"O nome do relator é informação essencial para rastreabilidade, responsabilização e acompanhamento do incidente — sem ele, não é possível contactar a fonte para informações adicionais. (ISO/IEC 27035:2016)","justification_wrong":"Nome do software e número do PC são dados técnicos complementares; lista de informados é produzida após o registro — o nome do relator é o dado imediato mais crítico."},
    {"num":20,"text":"No ciclo do incidente, qual etapa ocorre imediatamente após o incidente?","tag":"Ciclo de Incidentes","options":["A. Ameaça","B. Dano","C. Recuperação","D. Prevenção"],"correct":1,"justification_correct":"O ciclo de incidentes segue a sequência: Ameaça → Incidente → Dano → Recuperação. Após o incidente, o dano se materializa como consequência direta. (ISO/IEC 27035:2016)","justification_wrong":"Ameaça precede o incidente; recuperação é posterior ao dano; prevenção atua antes da ameaça — o dano é a etapa imediatamente seguinte ao incidente."},
    {"num":21,"text":"Qual das seguintes é uma medida de segurança PREVENTIVA?","tag":"Tipos de Medidas","options":["A. Instalar sistema de registro que permite determinar alterações no sistema","B. Desligar todo o tráfego de internet após hacker obter acesso","C. Armazenar informações confidenciais em cofre com acesso restrito","D. Acionar equipe de resposta após detecção de incidente"],"correct":2,"justification_correct":"O cofre com acesso restrito impede o acesso não autorizado antes que qualquer incidente ocorra — medida preventiva que atua sobre a oportunidade. (ISO/IEC 27002:2022)","justification_wrong":"Sistema de registro é medida detectiva; desligar tráfego após o acesso é medida repressiva/corretiva; acionar equipe é medida reativa — nenhum é preventivo."},
    {"num":22,"text":"No caso de um incêndio, qual é um exemplo de medida REPRESSIVA?","tag":"Tipos de Medidas","options":["A. Contratar seguro contra incêndio antecipadamente","B. Extinguir o incêndio após detecção por sistema de alarme","C. Reparar os danos causados pelo incêndio após sua extinção","D. Instalar detectores de fumaça nas instalações"],"correct":1,"justification_correct":"Extinguir o incêndio é medida repressiva — atua durante o incidente para conter e minimizar os danos em andamento. (ISO 22301:2019)","justification_wrong":"Seguro e detectores são medidas preventivas/detectivas que atuam antes ou no início do incidente; reparar danos é medida corretiva que atua após o incidente."},
    {"num":23,"text":"Qual é o objetivo principal da classificação da informação em uma organização?","tag":"Classificação da Informação","options":["A. Criar manual sobre como lidar com dispositivos móveis","B. Aplicar etiquetas tornando a informação mais fácil de localizar","C. Estruturar a informação de acordo com sua sensibilidade e requisitos de proteção","D. Determinar o custo de armazenamento de cada categoria de informação"],"correct":2,"justification_correct":"A classificação estrutura a informação por nível de sensibilidade, determinando os controles de proteção adequados para cada categoria — conforme Controle A.5.12 da ISO/IEC 27002:2022. (ISO/IEC 27001:2022)","justification_wrong":"Dispositivos móveis, etiquetagem para localização e custos de armazenamento são objetivos distintos; a classificação visa determinar o nível de proteção necessário."},
    {"num":24,"text":"Quem está autorizado a alterar a classificação de um documento organizacional?","tag":"Propriedade da Informação","options":["A. O autor original do documento","B. O administrador responsável pelo armazenamento","C. O proprietário (dono) do documento","D. O gerente do departamento onde o documento foi criado"],"correct":2,"justification_correct":"O proprietário do ativo de informação é o responsável pela sua classificação e pela autorização de mudanças nessa classificação — conforme Controle A.5.9 e A.5.12 da ISO/IEC 27002:2022. (ISO/IEC 27001:2022)","justification_wrong":"Autor, administrador e gerente de departamento podem ter funções relacionadas, mas a autoridade para alterar a classificação pertence ao proprietário designado do ativo."},
    {"num":25,"text":"A sala de informática é protegida por leitor de dispositivo de acesso exclusivo ao departamento de gestão de sistemas. Que tipo de medida de segurança é essa?","tag":"Medidas de Segurança","options":["A. Medida de segurança corretiva","B. Medida de segurança física","C. Medida de segurança lógica","D. Medida de segurança repressiva"],"correct":1,"justification_correct":"O controle de acesso físico por dispositivo (cartão, token) é uma medida de segurança física que protege as instalações e o hardware contra acesso não autorizado. (ISO/IEC 27002:2022, Controle 7.2)","justification_wrong":"Medidas corretivas e repressivas atuam após incidentes; medidas lógicas atuam no nível de software e sistemas — o leitor físico de acesso é tipicamente uma medida física."},
    {"num":26,"text":"Em autenticação multifator forte, qual fator é verificado quando o usuário apresenta seu dispositivo de acesso (cartão ou token)?","tag":"Autenticação","options":["A. Algo que você é (biometria)","B. Algo que você possui (posse)","C. Algo que você sabe (conhecimento)","D. Algo que você faz (comportamento)"],"correct":1,"justification_correct":"O dispositivo de acesso representa o fator de posse — algo que o usuário possui fisicamente. Os três fatores clássicos da autenticação forte são: posse, conhecimento e inerência (biometria). (ISO/IEC 27002:2022, Controle 8.5)","justification_wrong":"Biometria é o fator 'algo que você é'; senha/PIN é 'algo que você sabe'; comportamento é fator adicional menos comum — o dispositivo físico representa a posse."},
    {"num":27,"text":"Na segurança física com zonas concêntricas de proteção (anéis de proteção), qual dos seguintes NÃO é um anel de proteção?","tag":"Segurança Física","options":["A. O prédio como perímetro","B. Um anel intermediário como área controlada","C. Um objeto ou ativo específico como alvo final","D. Um anel externo como perímetro ampliado"],"correct":2,"justification_correct":"Na abordagem de anéis de proteção, os anéis são zonas concêntricas (externo, intermediário, interno/prédio). O 'objeto' é o ativo protegido pelo conjunto dos anéis — não é ele próprio um anel de proteção. (ISO/IEC 27002:2022, Controle 7.1)","justification_wrong":"Prédio, anel intermediário e anel externo são exemplos legítimos de anéis de proteção na abordagem de segurança em camadas."},
    {"num":28,"text":"Que ameaça pode ocorrer como resultado da ausência de uma medida de segurança FÍSICA adequada?","tag":"Segurança Física","options":["A. Um usuário visualizar arquivos de outro usuário no sistema","B. Um servidor desligar por superaquecimento da sala","C. Um documento confidencial ser deixado acessível na impressora","D. Hackers acessarem livremente a rede de computadores remotamente"],"correct":1,"justification_correct":"O superaquecimento de servidores decorre da ausência de controles físicos de temperatura e climatização — medida física de proteção ambiental das instalações. (ISO/IEC 27002:2022, Controle 7.5)","justification_wrong":"Acesso a arquivos alheios e invasão remota são problemas lógicos; documento na impressora é problema de política/comportamento — o superaquecimento é consequência direta de falha física ambiental."},
    {"num":29,"text":"Qual das seguintes é uma medida de segurança TÉCNICA (lógica)?","tag":"Medidas Técnicas","options":["A. Alocar informações a um proprietário designado","B. Criptografia de arquivos e dados armazenados","C. Criar política definindo o que é permitido em e-mails","D. Armazenar senhas de administração em cofre físico"],"correct":1,"justification_correct":"A criptografia é uma medida técnica/lógica que protege os dados mediante transformação matemática, tornando-os ilegíveis sem a chave correspondente. (ISO/IEC 27002:2022, Controle 8.24)","justification_wrong":"Alocação de proprietário e criação de políticas são medidas organizacionais; cofre físico é medida física — apenas a criptografia é tipicamente classificada como medida técnica."},
    {"num":30,"text":"Backups do servidor central são mantidos na mesma sala trancada que o servidor. Qual risco isso representa?","tag":"Backup e Recuperação","options":["A. Dificuldade de recuperação rápida em caso de falha do servidor","B. Impossibilidade de restauração em caso de incêndio que destrua a sala","C. Ausência de responsável designado pelos backups","D. Acesso fácil de pessoas não autorizadas aos backups"],"correct":1,"justification_correct":"Manter backups no mesmo local do servidor os expõe aos mesmos riscos físicos — incêndio, inundação ou desastre pode destruir simultaneamente servidor e backups, inviabilizando a recuperação. (ISO/IEC 27002:2022, Controle 8.13)","justification_wrong":"Velocidade de recuperação não é afetada pelo local; responsabilidade e controle de acesso são questões distintas — o risco crítico é a perda simultânea de dados e backups no mesmo sinistro."},
    {"num":31,"text":"Que tipo de malware cria uma rede de computadores comprometidos controlada remotamente?","tag":"Malware","options":["A. Bomba lógica","B. Botnet (Storm Worm ou similar)","C. Cavalo de Troia (Trojan)","D. Spyware"],"correct":1,"justification_correct":"Botnets são redes de dispositivos infectados e controlados remotamente por um atacante (botmaster), usadas para ataques DDoS, spam e outras atividades maliciosas. (ISO/IEC 27002:2022, Controle 8.7)","justification_wrong":"Bomba lógica executa ação em condição específica; Trojan disfarça malware em software legítimo; spyware coleta informações — apenas o botnet cria rede de computadores comprometidos."},
    {"num":32,"text":"Uma estação de trabalho foi infectada via ataque de phishing direcionado. Qual ação é mais eficaz para PREVENIR tais incidentes no futuro?","tag":"Prevenção de Malware","options":["A. Implementar tecnologia MAC (Mandatory Access Control)","B. Iniciar programa de conscientização e treinamento em segurança","C. Atualizar regras de firewall de perímetro","D. Atualizar assinaturas do filtro de spam"],"correct":1,"justification_correct":"Phishing explora o fator humano — a conscientização é a contramedida mais eficaz, pois capacita os colaboradores a reconhecer e resistir a tentativas de engenharia social. (ISO/IEC 27002:2022, Controle 6.3)","justification_wrong":"MAC, firewall e filtros de spam são controles técnicos complementares que não eliminam a vulnerabilidade humana central explorada pelo phishing."},
    {"num":33,"text":"Informações confidenciais têm caído em mãos erradas por meio de laptops. Qual é o PRIMEIRO passo para propor medidas de segurança organizacionais?","tag":"Segurança de Dispositivos Móveis","options":["A. Formular política abrangente para mídia e dispositivos móveis","B. Designar pessoal de segurança da informação","C. Criptografar pen drives e discos rígidos de laptops imediatamente","D. Estabelecer política de controle de acesso ao sistema"],"correct":0,"justification_correct":"A política é o ponto de partida — ela define os requisitos, responsabilidades e controles necessários, orientando todas as demais medidas subsequentes. (ISO/IEC 27002:2022, Controle 6.7)","justification_wrong":"Designar pessoal, criptografar e controle de acesso são medidas específicas que devem ser guiadas por uma política prévia — implementar controles sem política cria lacunas e inconsistências."},
    {"num":34,"text":"Qual é o nome do sistema que garante a coerência e a gestão sistemática da segurança da informação em uma organização?","tag":"SGSI","options":["A. Sistema de Gestão de Segurança da Informação (SGSI / ISMS)","B. Rootkit de proteção corporativa","C. Regulamentos de segurança para informações governamentais classificadas","D. Sistema de Detecção de Intrusão (IDS)"],"correct":0,"justification_correct":"O SGSI (Information Security Management System — ISMS) é o conjunto de políticas, processos e controles que garante a gestão sistemática e coerente da segurança da informação. (ISO/IEC 27001:2022, Cláusula 4)","justification_wrong":"Rootkit é malware; regulamentos governamentais são normativos específicos; IDS é ferramenta de detecção — apenas o SGSI é o sistema de gestão abrangente."},
    {"num":35,"text":"Como se denomina o processo de verificar se a identidade de alguém é genuína e corresponde ao que foi declarado?","tag":"Controle de Acesso","options":["A. Autenticação","B. Autorização","C. Identificação","D. Auditoria"],"correct":0,"justification_correct":"Autenticação é o processo de verificar a identidade declarada — confirmar que o sujeito é quem afirma ser. Identificação é apenas declarar a identidade; autorização define o que o sujeito autenticado pode fazer. (ISO/IEC 27000:2018)","justification_wrong":"Identificação é declarar quem se é; autorização é definir permissões após autenticação; auditoria é registrar e revisar atividades — apenas autenticação verifica a identidade."},
    {"num":36,"text":"Por que é necessário manter um plano de recuperação de desastres atualizado e testá-lo regularmente?","tag":"Continuidade de Negócios","options":["A. Para ter sempre acesso a backups recentes localizados fora do escritório","B. Para lidar com falhas operacionais que ocorrem no dia a dia","C. Porque em caso de interrupção de grande escala, medidas e procedimentos desatualizados podem ser inadequados","D. Porque é requerido pela legislação de proteção de dados pessoais"],"correct":2,"justification_correct":"Planos desatualizados ou não testados podem falhar justamente quando mais necessários — ambientes mudam, pessoas saem, sistemas evoluem, tornando os testes regulares essenciais. (ISO 22301:2019, Cláusula 8.5)","justification_wrong":"Backups offsite e falhas diárias são aspectos parciais; legislação de proteção de dados não é a razão principal para testar planos de recuperação."},
    {"num":37,"text":"Com base em qual legislação uma pessoa pode solicitar acesso aos dados pessoais registrados sobre ela?","tag":"Legislação e Privacidade","options":["A. Legislação sobre registros públicos","B. Legislação de proteção de dados pessoais","C. Legislação de crimes computacionais","D. Legislação de informações governamentais (acesso público)"],"correct":1,"justification_correct":"A legislação de proteção de dados pessoais (como LGPD no Brasil ou GDPR na Europa) garante o direito do titular de acessar, corrigir e solicitar exclusão de seus dados. (LGPD — Lei 13.709/2018; GDPR — Regulamento UE 2016/679)","justification_wrong":"Registros públicos tratam de transparência governamental; crimes computacionais tratam de ilícitos digitais; acesso público trata de documentos governamentais — apenas a legislação de proteção de dados garante o direito de acesso pelo titular."},
    {"num":38,"text":"Qual das seguintes opções representa um ato legislativo ou regulatório que pode ser imposto a todas as organizações?","tag":"Normas e Legislação","options":["A. Direitos de propriedade intelectual","B. ISO/IEC 27001:2022","C. ISO/IEC 27002:2022","D. Legislação de proteção de dados pessoais"],"correct":3,"justification_correct":"A legislação de proteção de dados é de cumprimento obrigatório por força legal para todas as organizações que tratam dados pessoais. ISO 27001 e 27002 são normas voluntárias de certificação/boas práticas, não legislação compulsória. (LGPD; GDPR)","justification_wrong":"ISO 27001 e 27002 são normas voluntárias; direitos de propriedade intelectual são proteções legais específicas — apenas a legislação de dados pessoais é compulsória universalmente aplicável."},
    {"num":39,"text":"Funcionários utilizam o tempo de espera para enviar e-mails pessoais e navegar na internet. Como o uso de recursos tecnológicos pode ser MELHOR regulamentado do ponto de vista legal?","tag":"Política de Uso Aceitável","options":["A. Instalando aplicações que bloqueiam sites e filtram anexos de e-mail","B. Elaborando código de conduta estabelecendo direitos e obrigações de empregador e funcionários","C. Implementando regulamentos genéricos de privacidade","D. Instalando antivírus em todos os dispositivos"],"correct":1,"justification_correct":"Um código de conduta (política de uso aceitável) documenta as regras de uso, direitos e obrigações de ambas as partes — a base legal mais sólida para regular o uso de recursos tecnológicos. (ISO/IEC 27002:2022, Controle 5.10)","justification_wrong":"Bloqueios técnicos e antivírus são controles unilaterais sem base contratual; regulamentos genéricos de privacidade não endereçam especificamente o uso de recursos — o código de conduta cria a base jurídica necessária."},
    {"num":40,"text":"Em que condições um empregador está autorizado a verificar se os funcionários utilizam internet e e-mail corporativo para fins privados?","tag":"Monitoramento e Privacidade","options":["A. Se informar o funcionário após cada verificação realizada","B. Se os funcionários estiverem previamente cientes de que tal monitoramento pode ocorrer","C. Se houver firewall instalado na rede corporativa","D. Se o monitoramento for realizado apenas por auditores externos"],"correct":1,"justification_correct":"O monitoramento é legítimo quando os funcionários foram previamente informados e concordaram — requisito de transparência e consentimento presente tanto na LGPD quanto no GDPR e nas normas trabalhistas. (ISO/IEC 27002:2022, Controle 6.4; LGPD)","justification_wrong":"Informar após cada verificação é retroativo e insuficiente; firewall e auditores externos não são condições jurídicas para o monitoramento — a ciência prévia dos funcionários é o requisito central."},
]

def get_next_num(directory):
    existing = list(directory.glob("quiz_*_pt.json"))
    nums = []
    for f in existing:
        try:
            nums.append(int(f.stem.split("_")[1]))
        except:
            pass
    return max(nums) + 1 if nums else 1

dir1 = Path("static/quizzes/iso27001_li/fundamentals_isms")
dir1.mkdir(parents=True, exist_ok=True)
num1 = get_next_num(dir1)
out1 = {
    "cert_id": "iso27001_li",
    "domain_id": "fundamentals_isms",
    "quiz_num": num1,
    "domain_name": "Fundamentos e Gestão de ISMS",
    "cert_name": "ISO 27001 Lead Implementer",
    "lang": "pt",
    "questions": questions
}
path1 = dir1 / f"quiz_{num1:03d}_pt.json"
path1.write_text(json.dumps(out1, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"OK - {len(questions)} questoes (ISO 27001 LI Fundamentos) salvas em {path1}")
